### ISSUE TITLE
rasa forms in 3.x when slots are `from_text` differ behavior from 2.x

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10053]
I'm in the process of rewriting my 2.x form examples into 3.x. While working on [this example](https://github.com/RasaHQ/rasa-2.x-form-examples/tree/main/03-simple-form) I think I may have stumbled upon a bug. 

The goal of the form is to retrieve a first and last name by fetching the slots from text. There are no entities being detected here. 

## Old Domain.yml

Originally, this was the form definition. 

```yml
forms:
  name_form:
    first_name:
    - type: from_text
    last_name:
    - type: from_text

slots:
  first_name:
    type: text
    influence_conversation: true
  last_name:
    type: text
    influence_conversation: true
```

This is the new definition, per 3.0 specs.

```yml
slots:
  first_name:
    type: text
    influence_conversation: true
    mappings:
      - type: from_text
  last_name:
    type: text
    influence_conversation: true
    mappings:
      - type: from_text

forms:
  name_form:
    required_slots:
      - first_name
      - last_name
```

Everything else is kept the same, however. I've made no changes to the stories/rule or nlu files.

## Differences

I'm trying out both approaches inside of `rasa interactive` but the behavior seems inconsistent. 

### Rasa 2.x Behavior

```
Chat History

 #    Bot                                                       You        
───────────────────────────────────────────────────────────────────────────
 1    action_listen                                                        
───────────────────────────────────────────────────────────────────────────
 2                                                                   hello 
                                                        intent: greet 1.00 
───────────────────────────────────────────────────────────────────────────
 3    utter_greet 1.00                                                     
      Hey! How are you?                                                    
      action_listen 1.00                                                   
───────────────────────────────────────────────────────────────────────────
 4                                                  i want to give my name 
                                                intent: request_names 1.00 
───────────────────────────────────────────────────────────────────────────
 5    name_form 1.00                                                       
      active_loop{"name": "name_form"}                                     
      slot{"requested_slot": "first_name"}                                 
      What is your first name?                                             
      slot{"first_name": "vincent"}                                        
      slot{"requested_slot": "last_name"}                                  


Current slots: 
        first_name: vincent, last_name: None, requested_slot: last_name, session_started_metadata: None
```

It's able to pick up the slots just fine. No "bothering" about intents. 

### Rasa 3.x Behavior

This is different in 3.x. It now doesn't pick up the slots anymore. 

```
 #    Bot                                                       You        
───────────────────────────────────────────────────────────────────────────
 1    action_listen                                                        
───────────────────────────────────────────────────────────────────────────
 2                                                                   hello 
                                                        intent: greet 1.00 
───────────────────────────────────────────────────────────────────────────
 3    utter_greet 1.00                                                     
      Hey! How are you?                                                    
      action_listen 1.00                                                   
───────────────────────────────────────────────────────────────────────────
 4                                                  i want to give my name 
                                                intent: request_names 0.99 
───────────────────────────────────────────────────────────────────────────
 5    name_form 1.00                                                       
      active_loop{"name": "name_form"}                                     
      slot{"requested_slot": "first_name"}                                 
      What is your first name?                                             


Current slots: 
        first_name: None, last_name: None, requested_slot: first_name, session_started_metadata: None

------
? The bot wants to run 'action_listen', correct? Yes                                                                                              
? Your input -> vincent                                                                                                                           
? Your NLU model classified 'vincent' with intent 'deny' and there are no entities, is this correct? (Y/n)
```

This gives me the following chat history, even though the input is exactly the same. 

```
Chat History

 #    Bot                                                       You        
───────────────────────────────────────────────────────────────────────────
 1    action_listen                                                        
───────────────────────────────────────────────────────────────────────────
 2                                                                   hello 
                                                        intent: greet 1.00 
───────────────────────────────────────────────────────────────────────────
 3    utter_greet 1.00                                                     
      Hey! How are you?                                                    
      action_listen 1.00                                                   
───────────────────────────────────────────────────────────────────────────
 4                                                  i want to give my name 
                                                intent: request_names 0.99 
───────────────────────────────────────────────────────────────────────────
 5    name_form 1.00                                                       
      active_loop{"name": "name_form"}                                     
      slot{"requested_slot": "first_name"}                                 
      What is your first name?                                             


Current slots: 
        first_name: None, last_name: None, requested_slot: first_name, session_started_metadata: None
```

Note: the first name slot is now no longer set. 

This feels like an inconsistency, it may be related to the [stories](https://github.com/RasaHQ/rasa-2.x-form-examples/blob/main/03-simple-form/data/stories.yml) but if that's the case then we may need to be more explicit about that in migration documents.

**Comment by ancalita** [comment]
@koaning This definitely should be looked into further! At first glance I'd advise that `from_text` mappings used in existing forms should also have mapping conditions if you want the exact same behaviour as in 2.0. Otherwise the slot can be populated with any user message uttered at any point of the conversation regardless whether the form is active or not. Let me know if this works:
```
slots:
  first_name:
    type: text
    influence_conversation: true
    mappings:
      - type: from_text
         conditions:
         - active_loop: name_form
            requested_slot: first_name
  last_name:
    type: text
    influence_conversation: true
    mappings:
      - type: from_text
         conditions:
         - active_loop: name_form
            requested_slot: last_name
```
