### ISSUE TITLE
markers break on 3.0.0rc1

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10099]
I installed the 3.0 release candidate and I'm about to run my markets for the first time. I'm using the `rasa init` assistant and I have the following `markers.yml` file. 

```yaml
marker_mood_expressed:
  or:
    - intent: mood_unhappy
    - intent: mood_great
marker_cheer_up_worked:
  seq:
    - intent: mood_unhappy
    - action: utter_cheer_up
    - intent: affirm
marker_cheer_up_failed:
  seq:
    - intent: mood_unhappy
    - action: utter_cheer_up
    - intent: deny
marker_bot_challenged:
  at_least_once:
    - intent: bot_challenge
```

Next, I set up my environments file to use sqlite.

```
tracker_store:
   type: SQL
```

Next, I talk to the assistant a bit. I can confirm locally via datasette that the sqlite store now contains events. 

Then, I try running the markers feature and it seems to break. 

```
> rasa evaluate markers extracted_markers.csv all

InvalidMarkerConfig: Could not load marker marker_mood_expressed from /Users/vincent/Development/rasa-ini/markers.yml
```

Is this feature supported? Or can we not use SQLite here?
