### ISSUE TITLE
Predicted intent is always 'greet' for every message that doesn't exists in the training data

### ISSUE THREAD

**Issue by georak** [RasaHQ/rasa#10102]
### Rasa Open Source version

2.8.12

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

'greet' intent always return as the selected intent with confidence 1 when user types a message that doesn't exists in the training data.

nlu.yml
```yml
version: "2.0"
nlu:
  - intent: greet
    examples: |
      - γεια
      - γεια σας
      - καλησπέρα
      - καλημερα
      - kalispera
      - geia
      - geia sas
      - kalimera
      - hey
      - hello
      - hi
      - hello there
      - good morning
      - good evening
      - hey dude
      - goodmorning
      - goodevening
      - good afternoon
  - intent: affirm
    examples: |
      - yes
      - sure
```

domain.yml is the default
config.yml is the default + added FallbackClassifier with threshold 0.3

User input: "I am writting something"

predicted intent is always "greet"

![image](https://user-images.githubusercontent.com/3660446/140733318-648a5128-fcf6-4c75-bb67-d7a9fc2bce89.png)
