### ISSUE TITLE
global slot mappings: not_intent setting ignored

### ISSUE THREAD

**Issue by ka-bu** [RasaHQ/rasa#10129]
### Rasa Open Source version

3.0.0rc1

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

specified
```
slots:
  boolean_slot:
    type: bool
    mappings:
      - type: from_entity
        entity: boolean
        not_intent: affirm

entities:
  - boolean
 ```

and tagged some examples for boolean entities in training data, then ...
```
Hey! How are you?
Your input ->  yes this is a False   
....
2021-11-09 17:28:57 DEBUG    rasa.core.policies.rule_policy  - Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
[state 2] user intent: greet | previous action name: utter_greet
[state 3] user intent: affirm | user entities: ('boolean',) | previous action name: action_listen | slots: {'boolean_slot': (1.0, 0.0)}
[state 4] user intent: affirm | user entities: ('boolean',) | previous action name: action_unlikely_intent | slots: {'boolean_slot': (1.0, 0.0)}
[state 5] user intent: affirm | user entities: ('boolean',) | previous action name: utter_happy | slots: {'boolean_slot': (1.0, 0.0)}
```
Did not expect the slot to be set since the intent is detected as `affirm` and `not_intent: affirm` is specified.
