### ISSUE TITLE
Error messages given by `rasa evaluate markers` are sometimes not very specific

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#10125]
### Rasa Open Source version

3.0rc1

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

`rasa evaluate markers` shows an error message produced when incorrect operator, condition, or marker name but this error message is not always very specific.
For example, here is the `markers.yml`:

```
marker_mood:
 xxx:
   - intent_detected: mood_unhappys
   - intent_detected: mood_great
```

The operator here is incorrect, and when evaluating markers I see the following:
```
> rasa evaluate markers extracted_markers.csv all
InvalidMarkerConfig: Could not load marker marker_mood from /Users/alwx/Dev/rasa/demo-sm1/markers.yml
```
It makes sense but would be nice to have an error message telling why this marker can't be loaded.
