### ISSUE TITLE
Unclear error message when mitie model does not exist on path

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#10140]
When a model is provided for `MitieNLP` but doesn't exist on disk
e.g.
```yml
pipeline:
  - name: MitieNLP
    model: "data/total_word_feature_extractor.dat"
```
but no `"data/total_word_feature_extractor.dat"`

This is the error:
```
InvalidConfigException: The MITIE component 'MitieNLP' needs the configuration value for 'model'.Please take a look at the documentation in the pipeline section to get more info about this parameter.
```
 However this makes it seem like the parameter is not provided which is confusing. We should have a different message if the file does not exist.
