### ISSUE TITLE
Categorical slot accepts invalid values with `from_text` mapping type

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#10218]
Categorical slots with a list of allowed values should have all other values turned into the special `__other__` value. However, when I define a slot like this:
```yml
slots:
  slot_1:
    type: categorical
    mappings:
    - type: from_text
    values:
      - some
      - none
```
and include it in a form in an otherwise fresh `rasa init` project, upon `rasa train` and `rasa shell --debug` I can see that the slot gets filled with whatever user text is received -- instead of being filled with one of the allowed values or `__other__`.

It may be that this is a result of a conscious design decision. However, knowing categorical slots from 2.x, I was expecting them to work in 3.0 in the same way whether they're mapped as `from_text` or not.
