### ISSUE TITLE
`from_text` slots in form get filled too greedily

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#10219]
_While the optimal behaviour here is disputable, the observed behaviour simply differs between versions 2.8 and 3.0rc2._

Let's have the `rasa init` project with a form with two slots, each filled `from_text` (in 2.8, the mapping would be defined in the form):
```yml

slots:
  slot_1:
    type: categorical
    mappings:
    - type: from_text
    values:
      - some
      - none
  slot_2:
    type: bool
    mappings:
    - type: from_text
forms:
  my_form:
    required_slots:
        - slot_1
        - slot_2
```

Let's say that the form should start after `intent:greet`. So, when I say `hi`, the form starts. However, when that happens, both slots also get filled from that utterance and the form instantly exits! In 2.8, the form would ignore the form-initiating utterance and only fill the slot(s) after asking the user about them (`utter_ask_<slot_name>`).

On a similar note, what I also observe (which wasn't in 2.8) is that already filled slots get re-filled. What I mean is: Let's change the above situation such that the 2nd slot has a custom extractor that is a bit more picky and doesn't fill `slot_2` with `hi`. Then, that `hi` makes it into `slot_1` only and the bot asks the user about `slot_2`. Then, when a user provides a value which now fills `slot_2`, that value also fills `slot_1` which was already filled. In 2.8, `slot_1` would've kept its original value when already filled.

**Comment by ancalita** [comment]
@samsucik I've managed to fix these 2 issues you flagged: (1) `from_text` slots being filled with trigger user utterance leading to form deactivation (2) `from_text` slots being refilled when they should not be, by adding the `intent` parameter in the mappings, for example:

```
slots:
  slot_1:
    type: categorical
    mappings:
    - type: from_text
      intent: inform_slot_1
    values:
      - some
      - none
  slot_2:
    type: bool
    mappings:
    - type: from_text
      intent: inform_slot_2
```
To prevent users running in these tricky situations with `from_text`, I can do 2 things:
a) enforce the usage of `intent` parameter with `from_text` mapping during validation of slot mappings. If `from_text` mapping doesn't contain `intent` then an `InvalidDomain` exception gets raised.
b) clarify the need for this mandatory parameter in the docs.

Do you think this solution is good enough?

**Comment by ancalita** [comment]
@samsucik Alternatively, if enforcing `intent` parameter is too restrictive, this 2nd solution also works that needs to be added in the docs: Use mapping conditions that must have both `active_loop` and `requested_slot` keys:

```
slots:
  slot_1:
    type: categorical
    mappings:
    - type: from_text
      conditions:
        - active_loop: my_form
          requested_slot: slot_1
    values:
      - some
      - none
  slot_2:
    type: bool
    mappings:
    - type: from_text
      conditions:
        - active_loop: my_form
          requested_slot: slot_2
```
@melindaloubser1 Looping you in at Akela's advice to make sure we choose the best option here.
