### ISSUE TITLE
Dynamically added form slot is not being requested

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#10224]
_Most likely a result of #10219, but should be checked._

If I have 2 slots in a form (the 1st one mapped in the domain, the 2nd one added dynamically and with a custom mapping), the 2nd slot doesn't get correctly requested because the logic for conditionally adding the 2nd slots to `required_slots` behaves counter-intuitively.

**Example** (start with a `rasa init` project and make the following changes):

Add 2 slots and a form to the domain:
```yml
# responses for the form
  utter_ask_slot_1:
  - text: "Do you have some nice thoughts? (Answer `some` or `none` only.)"

  utter_ask_slot_2:
  - text: "Alright. And are you thoughts actually nice? Answer `yes` or `no` only."

slots:
  slot_1:
    type: categorical
    mappings:
    - type: from_text
      not_intent: greet
    values:
      - some
      - none
  slot_2:
    type: bool
    mappings:
    - type: custom
forms:
  my_form:
    required_slots:
        - slot_1

actions:
  - validate_my_form
```

Rules file to control the form:
```yml
version: "3.0"

rules:

- rule: Say goodbye anytime the user says goodbye
  steps:
  - intent: goodbye
  - action: utter_goodbye

- rule: Say 'I am a bot' anytime the user challenges
  steps:
  - intent: bot_challenge
  - action: utter_iamabot

- rule: Activate form
  steps:
  - intent: greet
  - action: my_form
  - active_loop: my_form

- rule: Submit form
  condition:
  - active_loop: my_form
  steps:
  - action: my_form
  - active_loop: null
  - slot_was_set:
    - requested_slot: null
  - action: utter_happy
```

Form validation action:
```python
from typing import Text, List, Any, Dict, Optional
from rasa_sdk import Tracker, FormValidationAction
from rasa_sdk.executor import CollectingDispatcher
from rasa_sdk.types import DomainDict

class ValidateMyForm(FormValidationAction):
    def name(self) -> Text:
        return "validate_my_form"

    async def required_slots(
        self,
        slots_mapped_in_domain: List[Text],
        dispatcher: "CollectingDispatcher",
        tracker: "Tracker",
        domain: "DomainDict",
    ) -> Optional[List[Text]]:
        additional_slots = ["slot_2"] if tracker.slots.get("slot_1") == "some" else []
        return additional_slots + slots_mapped_in_domain

    async def extract_slot_2(
        self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict
    ) -> Dict[Text, Any]:
        text_of_last_user_message = tracker.latest_message.get("text")
        if text_of_last_user_message in ["yes", "no"]:
            bool_val = text_of_last_user_message == "yes"
        else:
            bool_val = None
        return {} if bool_val is None else {"slot_2": bool_val}
```

When you talk to this bot (`rasa train; rasa shell --debug`), you say `hi`, which triggers the form. You say `some` which fills `slot_1` and `slot_2` gets dynamically requested. You say `yes` but `slot_2` doesn't get filled with `True`. Why? Because the custom extractor method for this slot doesn't run after your `yes`. This, in turn, is because `slot_1` gets filled with `yes` (the point of #10219) and so now `slot_2` is removed from `required_slots` based on the logic in your customised `required_slots()` -- this is the couter-intuitive behaviour. In order to make the form behave as expected (with respect to filling `slot_2`), you have to change your logic to:
```python
additional_slots = ["slot_2"] if tracker.slots.get("slot_1") in ["some", "yes"] else []
```
