### ISSUE TITLE
Non-requested `from_text` slots getting filled

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#10231]
_Potentially related to #10219._

Let's have a form with 2 `from_text` slots. Previously (2.x), only the requested slot would get filled from a user message. In 3.0, both slots get filled. I think @ancalita pointed out a solution [here](https://github.com/RasaHQ/rasa/issues/10053#issuecomment-957301046) but I wanted to make sure this regression is properly documented in its own issue here.

Example: Starting with a `rasa init` project, add a form with 2 slots to the domain:
```yml
# responses for the form
  utter_ask_slot_1:
  - text: "Do you have some nice thoughts? (Answer `some` or `none` only.)"

  utter_ask_slot_2:
  - text: "Alright. And are you thoughts actually nice? Answer `yes` or `no` only."
slots:
  slot_1:
    type: categorical
    mappings:
    - type: from_text
      not_intent: greet
    values:
      - some
      - none
  slot_2:
    type: bool
    mappings:
    - type: from_text
      not_intent: greet
forms:
  my_form:
    required_slots:
        - slot_1
        - slot_2
```
make these the bot's rules:
```yml
version: "3.0"
rules:
- rule: Say goodbye anytime the user says goodbye
  steps:
  - intent: goodbye
  - action: utter_goodbye

- rule: Say 'I am a bot' anytime the user challenges
  steps:
  - intent: bot_challenge
  - action: utter_iamabot

- rule: Activate form
  steps:
  - intent: greet
  - action: my_form
  - active_loop: my_form

- rule: Submit form
  condition:
  - active_loop: my_form
  steps:
  - action: my_form
  - active_loop: null
  - slot_was_set:
    - requested_slot: null
  - action: utter_happy
```
and run `rasa train; rasa shell --debug`. Greet the bot with `hi`, then say `some`. Both slots will be filled with `some` even though the requested slot was only `slot_1`.
