### ISSUE TITLE
Form automatically fills in all `from_text` slots in RC2

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10259]
I am working on a bot in RC2 where I'm supposed to give my name. 

```
> python -m rasa --version

Rasa Version      :         3.0.0rc2
Minimum Compatible Version: 3.0.0rc1
Rasa SDK Version  :         3.0.0rc1
Rasa X Version    :         None
Python Version    :         3.7.9
Operating System  :         Linux-5.11.0-7614-generic-x86_64-with-Pop-20.10-groovy
Python Path       :         /home/vincent/Development/rasa-3.x-form-examples/venv/bin/python
```

Here's a snippet of the domain file where the bot is having well. 

```yaml
forms:
  name_form:
    required_slots:
      - first_name
      - last_name

slots:
  first_name:
    type: text
    influence_conversation: true
    mappings:
      - type: from_text
        conditions:
         - active_loop: name_form
           requested_slot: first_name
  last_name:
    type: text
    influence_conversation: true
    mappings:
      - type: from_text
        conditions:
         - active_loop: name_form
           requested_slot: last_name
```

This form behaves well, here's a snippet for the behavior in `rasa shell`. 

```
Your input ->  hi there                                                                                                                                                                
Hey! How are you?

Your input ->  i want to tell you my name                                                                                                                                              
What is your first name?

Your input ->  vincent                                                                                                                                                                 
What is your last name?

Your input ->  warmerdarm                                                                                                                                                              
Ok. Thanks!
I will remember that your name is vincent warmerdarm!
```

So far so good. But let's now remove the conditions. 

```yaml
forms:
  name_form:
    required_slots:
      - first_name
      - last_name

slots:
  first_name:
    type: text
    influence_conversation: true
    mappings:
      - type: from_text
  last_name:
    type: text
    influence_conversation: true
    mappings:
      - type: from_text
```

Here's what `rasa shell` does now. 

```
Your input ->  i want to tell you my name                                                                                                                                              
Ok. Thanks!
I will remember that your name is i want to tell you my name i want to tell you my name!
```

This is a bit strange. The form has two slots but they both automatically get filled from a single utterance. I'd argue that this is a bit greedy, similar to the issue described [here](https://github.com/RasaHQ/rasa/issues/10219). What's going to be confusing to the end-user is that the two responses for asking the user is completely skipped too. 

```yaml
responses:
  utter_ask_first_name:
  - text: What is your first name?
  utter_ask_last_name:
  - text: What is your last name?
  utter_submit:
  - text: Ok. Thanks!
  utter_slots_values:
  - text: I will remember that your name is {first_name} {last_name}!
```

If anybody is interested in reproducing this issue, the project can be found [here](https://github.com/RasaHQ/rasa-3.x-form-examples/tree/main/05-validation).
