### ISSUE TITLE
`rasa data validate` warns about the form 'None' is used

### ISSUE THREAD

**Issue by JulianGerhard21** [RasaHQ/rasa#10392]
### Rasa Open Source version

3.0.0

### Rasa SDK version

3.0.0

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

Given the following `rule`: 

```
- rule: Deactivate troubleshooting form and end
  condition:
  - active_loop: troubleshooting_form
  steps:
  - action: troubleshooting_form
  - slot_was_set:
    - requested_slot: null
    - troubleshooting_type: 'na'
  - active_loop: null
  - action: action_persist_slot_data_in_lock_store
  - action: utter_fallbackcallback_list
  - action: action_restart
```

after executing `rasa data validate` the following warning occurs:

```
UserWarning: The form 'None' is used in the 'Deactivate troubleshooting form and end' block, b
ut it is not listed in the domain file. You should add it to your domain file!
  More info at https://rasa.com/docs/rasa/forms
Project validation completed with errors.
```

I am not sure why this happens since it only happens with this single rule while there are other rules working the same way for which no warning occurs. 

Training works fine so it might just be a simple thing to fix.
