### ISSUE TITLE
`num_threads` and `finetuning_epoch_fraction` CLI defaults overwrite user config

### ISSUE THREAD

**Issue by ka-bu** [RasaHQ/rasa#10409]
### Rasa Open Source version

3.0.0

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

In `default_recipe.py`,  `_extra_config_from_cli` will always return something for the `num_threads` (and for the finetuning fraction, if we're in finetuning mode) (because otherwise the [`cli_parameter[param]` call would fail](https://github.com/RasaHQ/rasa/blob/main/rasa/engine/recipes/default_recipe.py#L364)). If the user does not specify any CLI parameters then that something are the default (CLI) parameters which will then [overwrite the user settings](https://github.com/RasaHQ/rasa/blob/main/rasa/engine/recipes/default_recipe.py#L340):

To reproduce this, e.g. create a config with MITIE components and set the num_threads
```
pipeline:
- name: "MitieNLP"
  model: "<add-your-path-here>/total_word_feature_extractor.dat"
- name: "MitieTokenizer"
- name: "MitieFeaturizer"
- name: "MitieEntityExtractor"
- name: "MitieIntentClassifier"
  num_threads: 200000
```
and add a breakpoint to `_add_nlu_train_mode`

**Definition of done**
- [ ] Ensure that `num_threads` can be set
- [ ] Determine a way to test this properly
- [ ] Add a test
