### ISSUE TITLE
Issue with Spacy component with e2e storied

### ISSUE THREAD

**Issue by iovigi** [RasaHQ/rasa#10525]
### Rasa Open Source version

3.0

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.9

### What operating system are you using?

Windows

### What happened?

Hello, I am using Rasa 3.0\. I am trying to build a Rasa project with Spacy component in my pipeline, it is working fine in "normal" case, but when I try to train it with an end-to-end story, it is throwing "raise GraphSchemaValidationException( rasa.engine.exceptions.GraphSchemaValidationException: Your model uses a component 'SpacyNLP' which needs the param 'model' to be provided to its method 'process'. Please make sure that you registered your component correctly and that your model configuration is valid. See [https://rasa.com/docs/rasa/custom-graph-components](https://rasa.com/docs/rasa/custom-graph-components) for more information.". I have provided the model and installed it. My config is:

1.  The config recipe.

1.  [https://rasa.com/docs/rasa/model-configuration/](https://rasa.com/docs/rasa/model-configuration/)

recipe: default.v1

1.  Configuration for Rasa NLU.

1.  [https://rasa.com/docs/rasa/nlu/components/](https://rasa.com/docs/rasa/nlu/components/)

language: bg

pipeline:

1.  # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.

1.  # If you'd like to customize it, uncomment and adjust the pipeline.

1.  # See [https://rasa.com/docs/rasa/tuning-your-model](https://rasa.com/docs/rasa/tuning-your-model) for more information.

*   name: "SpacyNLP"

1.  language model to load

model: "bg_pipeline"

case_sensitive: False

*   name: SpacyTokenizer

*   name: SpacyEntityExtractor

*   name: SpacyFeaturizer

pooling: mean

*   name: RegexFeaturizer

*   name: LexicalSyntacticFeaturizer

*   name: CountVectorsFeaturizer

*   name: CountVectorsFeaturizer

analyzer: char_wb

min_ngram: 1

max_ngram: 4

*   name: DIETClassifier

epochs: 100

*   name: EntitySynonymMapper

*   name: ResponseSelector

epochs: 100

*   name: FallbackClassifier

threshold: 0.3

ambiguity_threshold: 0.1

1.  Configuration for Rasa Core.

1.  [https://rasa.com/docs/rasa/core/policies/](https://rasa.com/docs/rasa/core/policies/)

policies:

1.  # No configuration for policies was provided. The following default policies were used to train your model.

1.  # If you'd like to customize them, uncomment and adjust the policies.

1.  # See [https://rasa.com/docs/rasa/policies](https://rasa.com/docs/rasa/policies) for more information.

1.  * name: MemoizationPolicy
2.  * name: RulePolicy
3.  * name: UnexpecTEDIntentPolicy
4.  max_history: 5

1.  epochs: 100

1.  * name: TEDPolicy
2.  max_history: 5

1.  epochs: 100

1.  constrain_similarities: true

It is working with a normal story, the issue appears only with an end-to-end story. Please advice

### Command / Request

 _No response_ 

### Relevant log output

 _No response_ 

## Defnition of Done

*   [ ] Determine if the issue is a more general issue of the graph architecture or only specific to e2e

If it's e2e, then put this on deprio on the research board.

**Comment by sara-tagger** [comment]
Thanks for the issue, @koernerfelicia will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koernerfelicia** [comment]
Can confirm this. To reproduce on `examples/e2ebot`:

use config:

```
recipe: default.v1
language: en
pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
    case_sensitive: False
  - name: SpacyTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: SpacyEntityExtractor
  - name: DIETClassifier
    epochs: 200
policies:
- name: TEDPolicy
  epochs: 200
```


error message:

```
rasa.engine.exceptions.GraphSchemaValidationException: Your model uses a component 'SpacyNLP' which needs the param 'model' to be provided to its method 'process'. Please make sure that you registered your component correctly and and that your model configuration is valid.See https://rasa.com/docs/rasa/custom-graph-components for more information.
```

**Comment by koernerfelicia** [comment]
Training seems fine if you comment out the text from the stories like so:

```
....
- story: accepts suggestion, indirectly
  steps:
  - intent: greet
  - action: utter_greet
  - intent: search_restaurant
  - action: utter_suggest_cuisine
#  - user: "I can always go for sushi"
#  - action: utter_search_restaurants

- story: rejects suggestion, indirectly
  steps:
  - intent: search_restaurant
  - action: utter_suggest_cuisine
#  - user: "I had that yesterday"
#  - action: utter_suggest_cuisine
```

**Comment by CharlesSQ** [comment]
> Training seems fine if you comment out the text from the stories like so:
> 
> ```
> ....
> - story: accepts suggestion, indirectly
>   steps:
>   - intent: greet
>   - action: utter_greet
>   - intent: search_restaurant
>   - action: utter_suggest_cuisine
> #  - user: "I can always go for sushi"
> #  - action: utter_search_restaurants
> 
> - story: rejects suggestion, indirectly
>   steps:
>   - intent: search_restaurant
>   - action: utter_suggest_cuisine
> #  - user: "I had that yesterday"
> #  - action: utter_suggest_cuisine
> ```

Hello, I'm having the same issue but I need to use end-to-end stories because that's the main reason I'm moving to rasa 3

**Comment by koernerfelicia** [comment]
@CharlesSQ thanks for the input. That comment was just intended to support those who will investigate the bug, it's definitely not a fix or workaround! It's been routed to the relevant teams, and we'll be working on a fix once it's been triaged

**Comment by rgstephens** [comment]
I think this issue isn't confined to e2e.  I was able to duplicate this issue by doing:

- `rasa init`
- Add `SpacyEntityExtractor`
- `rasa train`

Does Spacy work with 3.x?

**Comment by koaning** [comment]
@rgstephens could you share the full `config.yml` file? I'm assuming that you've added a `SpacyNLP` object to your pipeline in order to get the `SpacyEntityExtractor` to work.

**Comment by koaning** [comment]
I was just able to run pipelines just fine with the spaCy tokenizer and featurizer. I did hit a minor developer experience bug, explained here: https://github.com/RasaHQ/rasa/issues/10814.

**Comment by koaning** [comment]
To confirm, this was the pipeline that I tried on `rasa init`. It trained just fine. 

```yaml
pipeline:
  - name: SpacyNLP
    model: en_core_web_md
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: SpacyEntityExtractor
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
```
