### ISSUE TITLE
Boolean error on Rasa Learning Center

### ISSUE THREAD

**Issue by jonra1993** [RasaHQ/rasa#10607]
### Rasa Open Source version

3.0.4

### Python version

3.7

### What operating system are you using?

OSX

### What happened?

This is not a bug but an error on the Rasa learning center website

https://learning.rasa.com/conversational-ai-with-rasa/slots/

![image](https://user-images.githubusercontent.com/23468720/147710607-8249ff9b-2a1f-493d-97a4-2fe4a5fe2d7d.png)

The correct way to create a boolean slot is in this way _type: bool_ I think it is important to correct this mistake to avoid confusion on new learners.

```
slots:
  authenticated:
    type: bool
    influence_conversation: true
```
