### ISSUE TITLE
Domain schema overrestricts `slots` options, making custom slots with custom keys invalid

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#10765]
### Rasa Open Source version

3.0.4

### What happened?

In 2.8.x, it was possible to have a custom slot definition that took an additional key e.g. 
```
slots:
  limit:
     type: custom.slots.LimitSlot
     limit: 1000
```
As long as the custom code could process all the keys listed, the domain would be valid.
In 3.0.4, the domain schema restricts the keys allowed per slot to specific ones, and makes this format invalid.

 i.e. running `rasa data validate` with a domain including this section gives the error below
```
slots:
  limit:
    type: custom.slots.LimitSlot
    limit: 1000
    mappings:
    - type: from_entity
      entity: limit
```

### Command / Request

```shell
rasa data validate
```

### Relevant log output

```shell
YamlValidationException: Failed to validate '/Users/melinda/rasa_bots/moodbot/domain.yml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
  in /Users/melinda/rasa_bots/moodbot/domain.yml:26:
      Key 'limit' was not defined. Path: '/slots/limit'
```

See the [2.x domain schema](https://github.com/RasaHQ/rasa/blob/a215ae5ef54bed0c62e25331866f97f6f2845df7/rasa/shared/utils/schemas/domain.yml#L43-L45) vs. the [3.x domain schema](https://github.com/RasaHQ/rasa/blob/e6d07d93a689c595efcd13cd03e145fef23c87d2/rasa/shared/utils/schemas/domain.yml#L43-L103)
