### ISSUE TITLE
Allow global `influence_conversation` per entity instead of per intent

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#10852]
### What problem are you trying to solve?

Depending on the use case, it can be that only certain **entities** should influence the conversation ever, as opposed to entities influencing the conversation only for certain **intents**.
In this situation, it is unwieldy to specify entities to ignore/use for every intent. It is also easy to accidentally leave out an ignored entity for some intent, leading to unintended behaviour.

e.g. let's say entities `fox, goat, hare, ibex, jaguar, ` should always be ignored, but the others are used for some intents. That means you'll have to list up to half of all the entities for each intent to get the right result:
```
entities:
- apple
- bear
- canoe
- digit
- eel
- fox
- goat
- hare
- ibex
- jaguar

intents:
- greet: 
   use_entities: 
   - apple
   - bear
   - canoe
   - digit
   - eel
- bye:
   ignore_entities:
  - fox
  - goat
  - hare
  - ibex
  - jaguar
```

In a real use case, there could be dozens of entities and intents, leading to it being very hard to read over the list of intents without getting lost in the lists of entities.

### What's your suggested solution?

Add a global `influence_conversation` flag under each entity (similarly as for slots), which adds the entity to all `ignore_entities` lists for all intents when `false`. 
Let it default to `true` to maintain current behaviour.
The flags `ignore_entities` and `use_entities` continue to work as before, but specifying `use_entity` with an entity that is `influence_conversation: false` should error out. 

E.g.
```
entities:
- apple
- bear
- canoe
- digit
- eel
- fox:
   influence_conversation: false 
- goat
   influence_conversation: false 
- hare
  influence_conversation: false 
- ibex
  influence_conversation: false 
- jaguar
  influence_conversation: false 

intents:
- greet
- bye
```

### Is anything blocking this from being implemented? (if relevant)

No.

### Definition of Done

- [ ] flag added
- [ ] previous default behaviour not changed
- [ ] throw error when illogical combinations are specified
- [ ] add/update tests
- [ ] update documentation
