### ISSUE TITLE
Slot Mappings: custom validation action doesn't validate the slot when the slot is extracted by a different custom action

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#10886]
**Problem description**:
I tried testing to see if extracting a slot via a custom action inheriting from sdk `Action` class, then validating this extraction with a custom action inheriting from sdk `ValidationAction` works.

While the extraction works fine, the validation code doesn't seem to run, because the debug log shows the slot being set with the unvalidated value.

`actions.py` code:

```
from typing import Any, Text, Dict, List

from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
from rasa_sdk.forms import ValidationAction
from rasa_sdk.events import SlotSet


class SlotExtraction(Action):
    def name(self) -> Text:
        return "extract_residential_status"

    async def run(
            self, dispatcher, tracker: Tracker, domain: Dict[Text, Any],
    ) -> List[Dict[Text, Any]]:
        latest_intent = tracker.get_intent_of_latest_message()

        if latest_intent == "indicate_permanent_residence":
            return [SlotSet("residential_status", "resident")]
        elif latest_intent == "indicate_temporary_residence":
            return [SlotSet("residential_status", "tourist")]
        else:
            return []


class TestValidation(ValidationAction):
    @staticmethod
    def residence_db() -> List[Text]:
        """DB of supported residential statuses."""
        return ["resident", "tourist"]

    async def validate_residential_status(
            self, slot_value: Any, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict
    ) -> Dict[Text, Any]:
        if slot_value in self.residence_db():
            return {"residential_status": slot_value.upper()}
        else:
            return {"residential_status": None}

```

The domain file includes:
```
  residential_status:
    type: categorical
    influence_conversation: false
    values:
      - resident
      - tourist
      - non-visitor
    mappings:
    - type: custom
      action: extract_residential_status

actions:
- action_validate_slot_mappings
- extract_residential_status
```

`nlu.yml` includes the checked intents:
```
- intent: indicate_permanent_residence
  examples: |
    - I am a citizen here.
    - I'm a permanent resident.
    - I live here.

- intent: indicate_temporary_residence
  examples: |
    - I don't live here.
    - I'm only visiting temporarily.
    - On vacation.
```

**Definition of Done**:
- [ ] validate if this method of slot filling via 2 different custom actions should work
- [ ] investigate and fix
- [ ] update docs that this method works as well
