### ISSUE TITLE
`rasa visualize` does not show entities and slots relevant for the stories

### ISSUE THREAD

**Issue by raoulvm** [RasaHQ/rasa#10941]
### What problem are you trying to solve?

For our dialog designers to have a visual tool to look at and debug complex stories, they need to see where stories are identical and where they are different.
As stories may differ **by intents with entities** and also **by slots** being extracted or provided by **custom actions** it is very important for us to show also entities and SlotSet events in the visualization.

### What's your suggested solution?

Intents: instead of showing some sample user utterance from the training data, show the intent name together with entities, like `user_intent(entity1, entity2)`

**SlotSet events** should be shown comparably to actions, for the simple reason that the current solution does only support one intent in a row.

Have a look into #10932 for a working example (Python 3.8 only so far). 

### Examples (if relevant)

```yaml
stories:
  story: story1
  steps: 
     - intent: some_intent
       entities:
          - supper
     - action: utter_supper

  story: story2
  steps: 
     - intent: some_intent
       entities:
          - lunch
     - action: utter_lunch
```

### Is anything blocking this from being implemented? (if relevant)

NO. 
Working example provided.
Only little changes required.

### Definition of Done

Entities are shown together with intents, slot set events are shown in the visualization to explain connections.
