### ISSUE TITLE
Interest in expanding conditional response variations?

### ISSUE THREAD

**Issue by willstott101** [RasaHQ/rasa#10958]
### What problem are you trying to solve?

I'm trying to build some responses using detailed information from spaCy ideally without needing to resort to re-inventing a bunch of wheels in my own actions. Such a situation is a question like:

> "Do you speak french?"

In my opinion the intent here is to ask if I can speak a language - and all similar questions should share the same intent. Having training data for every single language in the world is unnecessary and already covered by spaCy's language models.

That being said I want to respond differently depending on the language being asked about. I'm using spaCy in a custom action to insert applicable information to slots. It then feels natural to use conditional responses to decide what to say.

In this simple example the following would be sufficient:
```yaml
    - condition:
        - type: slot
          name: LANGUAGE
          value: null
      text: I can only speak English.
    - condition:
        - type: slot
          name: LANGUAGE
          value: ... ??????
      text: I don't know {LANGUAGE} yet, sorry about that.
```

### What's your suggested solution?

Introduce some alternatives to the `value` key in condition responses.

`value_in: [possible, values]`
`value_not: null`
`value_not_in:  [impossible, values]`

### Is anything blocking this from being implemented? (if relevant)

This seems trivial to implement having looked at `response.py` and I'm curious if you would consider it in-scope. Alternatively a fully-generic condition system would suite me too, similar to: #10538

### Definition of Done

An expansion of the conditional response options, or a rationale for not expanding the API.
