### ISSUE TITLE
Handle unexpected intents from Telegram

### ISSUE THREAD

**Issue by digitalWestie** [RasaHQ/rasa#11021]
### What problem are you trying to solve?

Rasa (2.8.12) throws a ValueError when the user sends an intent message that’s not listed in the domain on Telegram. As there's no reply to telegram, telegram keeps trying to send the error-causing message. The result is the conversation remains blocked and can't continue.

I first came across this error as I connected rasa to telegram, and sent a ‘/start’ command which I didn’t have in my domain. We can add '/start' to the domain, and handle it, but this does not cover any other '/' messages sent by the user. 

I've documented the issue further in the forum: https://forum.rasa.com/t/how-to-handle-receiving-intents-not-listed-in-the-domain/52099

### What's your suggested solution?

In channel credentials yml provide a list of approved '/' message intents. Any other messages beginning with '/' character are stripped of '/' at the beginning and handled as normal text message by the NLU.

Example credentials:

```
telegram:
  access_token: "490161424:AAGlRxinBRtKGb21_rlOEMtDFZMXBl6EC0o"
  verify: "your_bot"
  webhook_url: "https://your_url.com/webhooks/telegram/webhook"
  allowed_slash_intents:
   - start
   - restart
   - inform
   - deny
   - affirm
   - greet
```

See pull request for possible implementation https://github.com/digitalWestie/rasa/pull/1

Another option would be to query the domain to get a list of available intents. 

### Is anything blocking this from being implemented? (if relevant)

Don't think so

### Definition of Done

A Telegram user sends a slash command that is not listed in the domain. Rasa responds without failing.
