### ISSUE TITLE
Make it possible to define intents as list in `intent` param of `from_intent` mapping

### ISSUE THREAD

**Issue by artemsnegirev** [RasaHQ/rasa#11206]
### What problem are you trying to solve?

I need to create the same slot mapping for several intents, i can't enumerate intents in one mapping and have to define same mapping for each intent

```yml
mappings:
- type: from_intent
  intent: intent_A
  value: my_value
- type: from_intent
  intent: intent_B
  value: my_value
- type: from_intent
  intent: intent_C
  value: my_value
```

### What's your suggested solution?

I want to define intent list instead of several mappings

```yml
mappings:
- type: from_intent
  intent: 
  - intent_A
  - intent_B
  - intent_C
  value: my_value
```
