### ISSUE TITLE
Bad indentation in rasa X 0.42.x documentation

### ISSUE THREAD

**Issue by Aymoelle** [RasaHQ/rasa#11371]
### Rasa Open Source version

3.2.2

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

In the Postgres Database Storage section of this page : https://legacy-docs-rasa-x.rasa.com/docs/rasa-x/0.42.x/installation-and-setup/install/docker-compose/#docker-compose-manual-install

The docker docker-compose.override.yml is badly indented and it should be like this :
```yml
version: "3.4"
services:
   db:
      volumes:
         - db-volume:/bitnami/postgresql
volumes:
   db-volume:
      name: db-volume
```
it is also the case for other versions like 1.0.x for example
