### ISSUE TITLE
Test stories entity issue doesn't report failed entity value

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#11385]
### Rasa Open Source version

3.2.1

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Given a test story that expects entity extraction:

```yml
- story: Entity WAWM F M
  steps:
  - user: |
      play [WAWM]{"entity": "station_callsign"} F M
    intent: listen_station_live
  - action: utter_listen_station_callsign
  - action: action_play_station_callsign
```

If the entity extraction fails, provides only general output:

```log
WrongPredictionException: NLU model predicted a wrong intent or entities. Failed Story: 

version: "3.1"
stories:
- story: Entity WAWM F M
  steps:
  - intent: listen_station_live
    entities:
    - station_callsign: WAWM
```

If there is an intent failure, the output will indicate the predicted intent but with an entity failure it doesn't show which entity failed and the predicted entity value.

If you look at the output in `failed_test_stories.yml` it shows the story but **no error**:

```yml
version: "3.1"
stories:
- story: Entity w b u r (./tests/test_stories.yml)
  steps:
  - intent: listen_station_live
    entities:
    - station_callsign: w b u r
  - slot_was_set:
    - station_callsign: w b u r
  - slot_was_set:
    - station_callsign: w b u r
  - action: utter_listen_station_callsign
  - action: action_play_station_callsign
```

### Command / Request

```shell
rasa test
```
