### ISSUE TITLE
Is ner_duckling removed in component_classes in latest rasa-nlu  0.14.3 ? 

### ISSUE THREAD

**Issue by balumatta** [RasaHQ/rasa#1684]
**Rasa NLU version**:0.14.3

**Operating system** (windows, osx, ...): Ubuntu

**Content of model configuration file**:
```yml
pipeline:
  - name: "tokenizer_whitespace"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "ner_duckling_http"
  - name: "intent_featurizer_count_vectors"
  - name: "intent_classifier_tensorflow_embedding"

```

**Issue**:
ner_duckling does not seem to work, instead if I change the ner_duckling to ner_duckling_http, it works. I checked in registry component classes of both 0.14.3 and 0.13.7. Component classes had DucklingExtractor in older version but not the latest has only DucklingHTTPExtractor. Has it been really removed?
