### ISSUE TITLE
Configure tracker store in configuration file

### ISSUE THREAD

**Issue by tdzienniak** [RasaHQ/rasa#2506]
**Feature request:**

Add configuration for tracker store to `domain.yml` or other configuration file. Something like this:

```yaml
tacker_store:
  mongo:
     host: http://localhost:27017
     db: rasa
     user: user
     password: pass
     collection: conversations
```

Then this information can be used to configure tracker store while running Rasa with `run.py`.
