### ISSUE TITLE
Use elements in domain.yml

### ISSUE THREAD

**Issue by FellowNico** [RasaHQ/rasa#2679]
**Rasa Core version**:
0.11.12
**Python version**: 
3.6.6
**Operating system** (windows, osx, ...):
windows
**Issue**:
Hello guys,

When creating my domain.yml I was wondering if it were possible to use elements or rich response other 
than buttons or image.
I managed to use elements in a custom action but I can't figure out a way to do it inside the domain.yml.

Thank you

**Content of actions file**
```
element1 = \
{
  "title": "Un nouveau compte ?",
  "image_url": "https://upload.wikimedia.org/wikipedia/fr/0/09/Orange_Bank_2017.png",
  "subtitle": "We have the right hat for everyone.",
  "default_action": {
    "type": "web_url",
    "url": "https://www.orangebank.fr/portalserver/espace-client/souscription-compte",
    "webview_height_ratio": "tall"
  },
  "buttons": [
    {
      "title": "Consulter mon solde",
      "payload": "/get_balance{'user': '{user}'}"
    },
    {
      "title": "Connaître mon id",
      "payload": "/get_id{'user': '{user}'}"
    }
  ]
}

(further in the code)
dispatcher.utter_custom_message(element1)
```
This is working as expected but the same dict converted into yaml doesn't work when putting it in the domaim.yml

**Content of domain file** (if used & relevant):
```
entities:
  - user
  - amount

slots:
  user:
    type: text

intents:
  - spend_money
  - greet
  - get_infos
  - get_id
  - get_balance
  - tell_name
  - good_bye

actions:
  - action_spend_money
  - action_good_bye
  - action_handle_invalid_name
  - action_tell_name
  - utter_get_infos
  - utter_nice_to_meet
  - action_greet
  - action_get_balance
  - action_get_id

templates:
  utter_get_infos:
  - text: "Okay {user}, que veux-tu faire maintenant ?"
    buttons:
    - title: "Consulter mon solde"
      payload: "/get_balance{'user': '{user}'}"
    - title: "Connaître mon id"
      payload: "/get_id{'user': '{user}'}"
  utter_nice_to_meet:
    - elements:
        title: "Enchanté {user}, que souhaites-tu faire ?"
        image_url: "https://petersfancybrownhats.com/company_image.png"
        subtitle: "We have the right hat for everyone."
        default_action:
          type: "web_url"
          url: "https://petersfancybrownhats.com/view?item=103"
          webview_height_ratio: "tall"
        buttons:
        - title: "Consulter mon solde"
          payload: "/get_balance{'user': '{user}'}"
        - title: "Connaître mon id"
          payload: "/get_id{'user': '{user}'}"
```
