### ISSUE TITLE
 tracker issue

### ISSUE THREAD

**Issue by oldmonkABA** [RasaHQ/rasa#3087]
**Rasa Core version**: 0.13.3

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**:

I downloaded and installed the latest rasa_core version from github since it has implemented the SQL tracker.
The contents of my endpoints.yml file is as follows:

**Content of domain file** (if used & relevant):
```yaml
tracker_store:
    type: SQL
    dialect: "postgresql"
    url: "localhost"
    db: "rasa.db"
    username:  My_db_username
    password:  My_db_password
```
When I run python -m rasa_core.run --core models/dialogue/ -u models/nlu/default/hospnlu/ --endpoints endpoints.yml --credentials credentials.yml

I am getting the following error :
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "venv_bm/lib/python3.6/site-packages/rasa_core/run.py", line 247, in <module>
    None, _endpoints.tracker_store, _broker)
  File "venv_bm/lib/python3.6/site-packages/rasa_core/tracker_store.py", line 28, in find_tracker_store
    if store is None or store.type is None:
AttributeError: 'EndpointConfig' object has no attribute 'type'
