### ISSUE TITLE
rasa core server is displaying TypeError: from_intent() got an unexpected keyword argument 'entity'

### ISSUE THREAD

**Issue by tchax3742** [RasaHQ/rasa#3181]
**Rasa version**: 0.14.5

**Python version**: 3.6.4

**Operating system** (windows, osx, ...): Linux Ubuntu

**Issue**:
there seems to be an error in slot mappings because rasa core server displays the following
![Screenshot from 2019-03-30 14-21-58](https://user-images.githubusercontent.com/46517278/55276262-a4b2e580-52fa-11e9-975f-dd7146fc91ba.png)

**Content of  slot mappings section (actions.py)**:
``` 
 def slot_mappings(self):
        # type: () -> Dict[Text: Union[Dict, List[Dict]]]
       # A dictionary to map required slots to
        #    - an extracted entity
        #    - intent: value pairs
          #  - a whole message
         #   or a list of them, where a first match will be picked

        return {"size": self.from_entity(entity="size",
                                          not_intent="chitchat"),
                "pizzatype": self.from_entity(entity="pizzatype",
                                               not_intent="chitchat"),
                "ask_toppings": [self.from_entity(entity="toppings"),
                                    self.from_intent(intent='affirm',
                                                     value=True),
                                    self.from_intent(intent='deny',
                                                     value=False)],
                "toppings": self.from_intent(entity="toppings",
                                              not_intent="chitchat"),
                "num_pizza": [self.from_entity(entity="num_pizza",
                                               intent=["inform",
                                                        "order_pizza"]),
                              self.from_entity(entity="number")],
                "feedback": [self.from_entity(entity="feedback"),
                             self.from_text()]}

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml


       intents:
       # add your intents
       - greet
       - thanks
       - toppings_deny
       - stop
       - toppings_affirm
       - inform
       - what_is_pizza_cost
       - order_pizza
       - chitchat:
          use_entities: false
      
       entities:
       - size
       - pizzatype
       - toppings
       - num_pizza
       - number
       - feedback
      
       slots:
        size:
         type: text
         auto_fill: false
        pizzatype:
         type: text
         auto_fill: false
        ask_toppings:
         type: text
         auto_fill: false
        toppings:
         type: text
         auto_fill: false
        num_pizza:
         type: text
         auto_fill: false
        feedback:
         type: text
        requested_slot:
         type: unfeaturized
      
       templates:
        utter_greet:
        - "Hey there, welcome to Tatenda's pizzabot, how can I help you"
        utter_thank:
        - "You're welcome!"
        utter_ask_size:
        - "We have small, medium, large and extra large pizzas. Which one do you want?"
        utter_ask_pizzatype:
        - "We have BBQ, Hawaiian, Bacon Cheeseburger, and Buffalo chicken pizzas, which one do you want"
        utter_ask_toppings:
        - "Do you want any toppings?"
        utter_ask_num_pizza:
        - "How many pizzas do you want"
        utter_toppings:
        - "We have mushrooms, onions, bacon, green peppers and sausage toppings, which would you like?"
        utter_affirm:
        - "thanks for the details.your order is being processed"
        utter_default: 
        - "sorry, i couldnt understand you.please retry"
        utter_ask_feedback:
        - text: "please give your feedback on your experience so far"
        utter_slots_values:
        - text: "You have ordered the following pizza:

             - size: {size}

             - pizzatype: {pizzatype}

             - num_pizza: {num_pizza}

             - toppings: {toppings}

             - feedback: {feedback}"
       utter_submit:
       - text: "submit"
       utter_chitchat:
       - text: "chitchat"
       utter_ask_continue:
       - text: "do you want to continue?"
       utter_wrong_size:
       - text: "We do not have that size, please try again"
       utter_wrong_pizzatype:
       - text: "We do not have that type of pizza, please choose from Hawaiian, buffalo chicken, Magherita and BBQ"
       utter_wrong_num_pizza:
       - text: "number of people should be a positive integer e.g 3, 4, please try again"
       utter_wrong_toppings1:
       - text: "Please answer with yes/no"
       utter_wrong_toppings2:
       - text: "Those toppings are currently unavailable, please choose from  mushrooms, onions, bacon, green peppers and sausage toppings "
       action_default_fallback:
       - text: "Sorry, I do not understand"

       actions:
       # all the utter actions from the templates, plus any custom actions
       
       - utter_ask_size
       - utter_ask_pizzatype
       - utter_ask_toppings
       - utter_toppings
       - utter_ask_num_pizza
       - utter_ask_continue
       - utter_chitchat
       - utter_greet
       - utter_thank
       - utter_slots_values
       
       forms:
       - pizza_form
      

```
