### ISSUE TITLE
Feature request: Reusing components in pipeline

### ISSUE THREAD

**Issue by Mangirdas** [RasaHQ/rasa#3223]
**Rasa version**:
0.14.3

**Python version**: 
3.6

**Issue**:
I want to re-use same component with different configs.
Model persistance is incorrect. It saves two components, but params are the same. First components params are used for both components.

My current solution is multiple class definitions extending same class - does not look good.
```
class CustomComponent_1(CustomComponent)
class CustomComponent_2(CustomComponent)
...
```

Suggestions on solutions? 
Is it hard to support this in RASA pipelines? Anything in pipeline?
I might contribute if this would be useful for more people in the community.

Please see example below.

**Content of configuration file (config.yml)**:
```yaml
pipeline:
- name: "ner_duckling_http"
  dimensions: ["time"]
  locale: "en_EN"
  timezone: "utc"
- name: "ner_duckling_http"
  dimensions: ["duration"]
  locale: "en_EN"
  timezone: "utc"
```

**Content of metadata.json file**:
```json
"language": "en",
"pipeline": [
    {
        "dimensions": [
            **"time"**
        ],
        "url": null,
        "locale": "en_EN",
        "timezone": "utc",
        "name": "ner_duckling_http",
        "class": "rasa_nlu.extractors.duckling_http_extractor.DucklingHTTPExtractor"
    },
    {
        "dimensions": [
            **"time"**
        ],
        "url": null,
        "locale": "en_EN",
        "timezone": "utc",
        "name": "ner_duckling_http",
        "class": "rasa_nlu.extractors.duckling_http_extractor.DucklingHTTPExtractor"
    }
```
