### ISSUE TITLE
Why is there local path being added to the generated intent_featurizer_count_vectors.pkl

### ISSUE THREAD

**Issue by libindavis** [RasaHQ/rasa#3258]
**Rasa version**:
"0.14.0a1"
**Python version**: 
Python 3.5.6

**Operating system** (windows, osx, ...):
Linux

**Issue**:
I am using tensorflow and CounVector to featurize the input text.   
But when I run my model in a Docker container,  it would try to access my local file of /home/<my_local_path>/rasa_nlu/rasa_nlu/featurizers/count_vectors_featurizer.py, other than the related file in the docker which is /app/rasa_nlu_chatbot/rasa_nlu/rasa_nlu/featurizers/count_vectors_featurizer.py.  And it leads to some strange error message like: 

    File "/usr/local/lib/python3.5/site-packages/sklearn/feature_extraction/text.py", line 266, in <lambda>
        tokenize(preprocess(self.decode(doc))), stop_words)
      File "/home/<my_local_path>/rasa_nlu/rasa_nlu/featurizers/count_vectors_featurizer.py", line 140, in _tokenizer

    NameError: name 'T' is not defined

After some debugging,  I found that  in the generated intent_featurizer_count_vectors.pkl,  there is a string of my local path /home/<my_local_path>/rasa_nlu/rasa_nlu/featurizers/count_vectors_featurizer.py. 

**My question is,  why  is the model in the docker trying to acces my local path ?  Why is a local path in the generated model?**   How can I change the local path to the docker path in the pickle? 

**Content of configuration file (config.yml)**:
```yml
    language: "en"
    pipeline:
        - name: "nlp_spacy"
        - name: "tokenizer_spacy"
        - name: "intent_featurizer_count_vectors"
          stop_words: ['how','what','hows','is','the','whats']
          min_df: 0.0
          max_df: 1.0
          min_ngram: 1
          max_ngram: 2
        - name: "intent_entity_featurizer_regex"
        - name: "ner_crf"
          BILOU_flag: true
          features: [["low",'title'],
               ["bias", "low", "title","pos",'pattern','prefix5','prefix2', 'suffix5', 'suffix3'],
               ["low", "title"]]
        - name: "ner_duckling_http"
          url: "http://tegra-infra-nlp-vm-dev-01:8000"
          dimensions: ["time", "number", "duration", "ordinal"]
          locale: "en_US"
          timezone: "US/Pacific"
        - name: "ner_synonyms"
        - name: "intent_classifier_tensorflow_embedding"
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```
