### ISSUE TITLE
How to create UI for buttons added in rasa chatbot using angular

### ISSUE THREAD

**Issue by cs-2007** [RasaHQ/rasa#3273]
**Rasa Core Version **: 0.13.7

**Python version**: 3.6

**Operating system** : Windows 10

**Issue**: 
I have added the button in templates of domain.yml file in rasa core. But those buttons are appearing as text in UI part. So can any one help me out with demo code how to convert those text into clickable button in UI to make my chatbot more interactive.

**Content of configuration file (config.yml)**:
```yml
pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```

**Content of domain file (domain.yml)** (if used & relevant):
```yml

utter_book_appointment:
    - text: "Tell the timing for appointment"
      buttons:
      - title: "Morning"
        payload: '/Visit_Time{"AppointmentTime": "Morning"}'
      - title: "Afternoon"
        payload: '/Visit_Time{"AppointmentTime": "Afternoon"}'
      - title: "Evening"
        payload: '/Visit_Time{"AppointmentTime": "Evening"}'
```
