### ISSUE TITLE
NLU correctly extracts intent, does not pass to slot via story

### ISSUE THREAD

**Issue by Zylatis** [RasaHQ/rasa#3279]
**Rasa version**: 
Core: 0.13.7
Core-sdk: 0.13.0
NLU: 0.14.6

**Python version**:  3.6

**Operating system**:  Ubuntu 16.04

**Issue**: NLU correctly identifying intent, not passing to slot via story

**Content of configuration file (config.yml)**:
```yml
language: "en"
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
- name: "ner_duckling_http"
  url:  "http://0.0.0.0:8000"
  dimensions: ["time"]
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
  - greet
  - goodbye
  - get_quote_withinfo
  - get_quote
  - modify_booking
  - thanks
  - inform_city
  - inform_date
  - check_status

actions:
- utter_greet
- utter_goodbye
- utter_welcome
- utter_get_quote
- utter_slot_values
- utter_submit
- utter_ask_source # should this not be included by default, will i be overriding shit?
- utter_changebook
- utter_check_status

entities:
  - source
  - destination
  - day
  - month
  - year
  - time_day
  - new_day
  - new_month
  - date
  - city
  - time

slots:
  source:
    type: unfeaturized
    auto_fill: false
  destination:
    type: unfeaturized
    auto_fill: false
  date:
    type: unfeaturized
    auto_fill: false
  day:
    type: unfeaturized
    auto_fill: false
  month:
    type: unfeaturized
    auto_fill: false
  year:
    type: unfeaturized
    auto_fill: false
  time_day:
    type: unfeaturized
    auto_fill: false

templates:
  utter_greet:
  - text: "Hello! How can I help?"
  - text: "Hiya!"
  utter_goodbye:
  - text: "Goodbye!"
  utter_ask_source:
    - text: "Where are you shipping from?"
  utter_ask_destination:
    - text: "Where are you shipping to?"
  utter_ask_date:
  - text: "When do you want your items to ship from {source}?"
  utter_welcome:
    - text: "You're welcome!"
    - text: "No worries :)"
  utter_get_quote:
    - text: "Okay, lets get a quote going"
  utter_changebook:
    - text: "Okay, let me grab that booking for you"
  utter_slot_values:
    - text: "I am going to run a quote search using the following parameters:\n
            - source: {source}\n
            - destination: {destination}\n
            - date: {day} of {month}\n
            - time: {time_day}"
  utter_submit:
    - text: "All done!"
  utter_default:
    - text: "Totes soz, I don't understand what you mean there, can you rephrase please?"
  utter_ask_month:
    - text: "What day of {year}"
  utter_ask_day:
    - text: "What day of {month}"
  utter_ask_time_day:
    - text: "What time on {day}"

forms:
  - booking_form
```

**Content of stories.md
```md
## new_quote2
* greet
  - utter_greet
* get_quote{"source":"perth"}
  - utter_get_quote
  - booking_form
  - form{"name": "booking_form"}
  - form{"name": null}
  - utter_slot_values
* goodbye
  - utter_goodbye
```

I am trying to make a fairly standard variation of the form bot which will make bookings. If the user writes 'make booking' and starts the form then everything works fine. However, I would like to be able to extract information from the very first sentence before an intent has been classified (i.e. before a form is used). It seems this is done via slot filling directly in the stories but i cannot get it to work. In the attached image it shows that NLU is correctly pulling the source city (though admittedly low confidence but that's fine) but the form is still asking for it.

 I have tried several variations (i.e. putting the slot filling part in the story after the form is activated) but nothing seems to work, what am i missing?

Thanks!
![nluform](https://user-images.githubusercontent.com/1456631/56335676-c9ef9100-61e0-11e9-9968-d62bf48f7ee0.png)
