### ISSUE TITLE
No data in mongo with MongoTrackerStore

### ISSUE THREAD

**Issue by HatuneMiku** [RasaHQ/rasa#3284]
**Rasa version**:
```
rasa-core                 0.13.8                   pypi_0    pypi
rasa-core-sdk             0.12.2                   pypi_0    pypi
rasa-nlu                  0.14.6                   pypi_0    pypi
```

**Python version**: 
```
python                    3.6.8                h9f7ef89_7    defaults
```
**Operating system** (windows, osx, ...):
```
Winodws 10 Pro 1809 
OS 17763.437
```
**Issue**:

I use  MongoTrackerStore, but I can find nothing in Mongodb, this is my config:

**Content of endpoints file (endpoints.yml)** :
```
action_endpoint:
  url: "http://localhost:5055/webhook"

nlu:
  url: "http://localhost:5000"
  token: mytoken
  token_name: token

tracker_store:
  type: mongod
  url: mongodb://localhost:27017
  db: rasa
  username: rasa
  password: rasa
  collection: conversations
  auth_source: rasa
```

The action server and nlu server work well, so I think the endpoints.yml file work well. But the mongodb is empty, mybe like #3262, but I'm not very sure. And the rasa core server with no error or warning.

Thanks!

**Comment by HatuneMiku** [comment]
I found why,   `rasa-core 0.13.8 ` the tracker store type should be **`store_type`** not **`type`**,  my fault.
that is the right config:

```
tracker_store:
  store_type: mongod
  url: mongodb://localhost:27017
  db: rasa
  username: rasa
  password: rasa
  collection: conversations
  auth_source: rasa
```
