### ISSUE TITLE
Failed to register package ‘actions.actions’

### ISSUE THREAD

**Issue by karanshah150696** [RasaHQ/rasa#3285]
**Rasa version**:
Rasa-core: 0.13.7,
Rasa-core-sdk: 0.12.2,
Rasa-nlu: 0.14.6. 
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
ubuntu 16.4 LTS
**Issue**:

> action_server_1 | 2019-04-19 09:31:35 INFO main - Starting action endpoint server...
> action_server_1 | 2019-04-19 09:31:35 ERROR rasa_core_sdk.executor - Failed to register package 'actions.actions'.
> action_server_1 | Traceback (most recent call last):
> action_server_1 | File "/app/rasa_core_sdk/executor.py", line 150, in register_package
> action_server_1 | self._import_submodules(package)
> action_server_1 | File "/app/rasa_core_sdk/executor.py", line 137, in _import_submodules
> action_server_1 | package = importlib.import_module(package)
> action_server_1 | File "/usr/local/lib/python3.6/importlib/init.py", line 126, in import_module
> action_server_1 | return _bootstrap._gcd_import(name[level:], package, level)
> action_server_1 | File "", line 994, in _gcd_import
> action_server_1 | File "", line 971, in _find_and_load
> action_server_1 | File "", line 953, in _find_and_load_unlocked
> action_server_1 | ModuleNotFoundError: No module named 'actions.actions'
> action_server_1 | 2019-04-19 09:31:35 INFO main - Action endpoint is up and running. on ('0.0.0.0', 5055)
> duckling_1 | no port specified, defaulting to port 8000
> duckling_1 | Listening on http://0.0.0.0:8000
> rasa_nlu_1 | Traceback (most recent call last):
> rasa_nlu_1 | File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> rasa_nlu_1 | "main", mod_spec)
> rasa_nlu_1 | File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
> rasa_nlu_1 | exec(code, run_globals)
> rasa_nlu_1 | File "/app/rasa/core/run.py", line 204, in 
> rasa_nlu_1 | "Calling rasa.core.run directly is "
> rasa_nlu_1 | RuntimeError: Calling rasa.core.run directly is no longer supported. Please use rasa shell instead.
> chatwithme_rasa_nlu_1 exited with code 1

**Content of configuration file (config.yml)**:
```
language: "en"

pipeline:
- name: "nlp_spacy"
  model: "en"
- name: "ner_spacy"
- name: "ner_ngrams"
  max_number_of_ngrams: 7
- name: "ner_duckling_http"
  url: "http://my_url"
  dimensions:
  - "NUMBER"
- name: "ner_crf"
  BILOU_flag: true
  features:
    # features for word before token
    - ["low", "title", "upper", "pos", "pos2"]
    # features of token itself
    - ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"]
    # features for word after the token we want to tag
    - ["low", "title", "upper", "pos", "pos2"]
  max_iterations: 50
  L1_c: 1
  L2_c: 1e-3
- name: "intent_classifier_sklearn"
  C: [1, 2, 5, 10, 20, 100]
  kernel: "linear"

```

**Content of domain file (domain.yml)** (if used & relevant):
```
action_factory: null
action_names:
- utter_greet
- utter_did_that_help
- utter_happy
- utter_goodbye
- utter_unclear
- utter_ask_picture
- action_retrieve_image
actions:
- utter_greet
- utter_did_that_help
- utter_happy
- utter_goodbye
- utter_unclear
- utter_ask_picture
- __main__.ApiAction
config:
  store_entities_as_slots: true
entities:
- group
intents:
- greet
- goodbye
- mood_affirm
- mood_deny
- mood_great
- mood_unhappy
- inform
slots:
  group:
    initial_value: null
    type: rasa_core.slots.TextSlot
templates:
  utter_ask_picture:
  - text: To cheer you up, I can show you a cute picture of a dog, cat or a bird.
      Which one do you choose?
  utter_did_that_help:
  - text: Did that help you?
  utter_goodbye:
  - text: Bye
  utter_greet:
  - text: Hey! How are you?
  utter_happy:
  - text: Great carry on!
  utter_unclear:
  - text: I am not sure what you are aiming for.
topics: []
```
**metadata.json**
```
{
    "language": "en",
    "pipeline": [
        {
            "model": "en",
            "case_sensitive": false,
            "name": "nlp_spacy",
            "class": "rasa_nlu.utils.spacy_utils.SpacyNLP"
        },
        {
            "name": "tokenizer_spacy",
            "class": "rasa_nlu.tokenizers.spacy_tokenizer.SpacyTokenizer"
        },
        {
            "BILOU_flag": true,
            "features": [
                [
                    "low",
                    "title",
                    "upper",
                    "pos",
                    "pos2"
                ],
                [
                    "bias",
                    "low",
                    "word3",
                    "word2",
                    "upper",
                    "title",
                    "digit",
                    "pos",
                    "pos2",
                    "pattern"
                ],
                [
                    "low",
                    "title",
                    "upper",
                    "pos",
                    "pos2"
                ]
            ],
            "max_iterations": 50,
            "L1_c": 1,
            "L2_c": 0.001,
            "name": "ner_crf",
            "classifier_file": "crf_model.pkl",
            "class": "rasa_nlu.extractors.crf_entity_extractor.CRFEntityExtractor"
        },
        {
            "name": "intent_featurizer_spacy",
            "class": "rasa_nlu.featurizers.spacy_featurizer.SpacyFeaturizer"
        },
        {
            "C": [
                1,
                2,
                5,
                10,
                20,
                100
            ],
            "kernels": [
                "linear"
            ],
            "max_cross_validation_folds": 5,
            "name": "intent_classifier_sklearn",
            "classifier_file": "intent_classifier_sklearn.pkl",
            "class": "rasa_nlu.classifiers.sklearn_intent_classifier.SklearnIntentClassifier"
        },
        {
            "name": "ner_synonyms",
            "synonyms_file": "entity_synonyms.json",
            "class": "rasa_nlu.extractors.entity_synonyms.EntitySynonymMapper"
        }
    ],
    "training_data": "training_data.json",
    "trained_at": "20180703-013012",
    "rasa_nlu_version": "0.14.0a8"
}
```

**Docker-Compose.yml**

```
version: '3.0'

services:
  rasa_core:
    image: rasa/rasa_core:latest
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./rasa-app-data/models/current/dialogue:/app/model"
    - "./rasa-app-data/config:/app/config"
    - "./rasa-app-data/project:/app/project"
    command:
    - start
    - -d
    - ./model
    - -c
    - rest
    - -u
    - current/nlu
    - --endpoints
    - config/endpoints.yml

  action_server:
    image: rasa/rasa_core_sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./rasa-app-data/actions:/app/actions"

  rasa_nlu:
    image: rasa/rasa_nlu:latest-full
    networks: ['rasa-network']
    ports:
    - "5000:5000"
    volumes:
    - "./rasa-app-data/models/:/app/projects"
    - "./rasa-app-data/logs:/app/logs"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

networks: {rasa-network: {}}

```
