### ISSUE TITLE
CORS error in docker

### ISSUE THREAD

**Issue by LoganDungeon** [RasaHQ/rasa#3314]
**Rasa version**: 0.14.6

**Python version**:  3.6

**Operating system**: Arch Linux (Debian in the Docker)

**Issue**: 
I want to build a simple bot and access it via a web front end. To achieve this I use docker to run rasa nlu, core and the website. I followed [the instructions](https://rasa.com/docs/nlu/docker/) on the rasa website.  
Now if I curl a post request to the bot, I get the desired response. But if I send it from the website I get a CORS Error. I am aware that there is a cors parameter when i start rasa over python. However I don't know where this parameter goes in the docker. I tried passing it to the docker-compose as a parameter or to my nlu_config but neither seem to work.  

Can someone explain to me where i can enable cors support in the docker?

**Content of docker-compose:**
```yml
version: '3.0'

services:
    rasa_core:
        image: rasa/rasa_core:latest
        ports:
            - 5005:5005
        volumes:
            - ./models/rasa_core:/app/models
            - ./config:/app/config
        command:
            - start
            - --core
            - models
            - -c
            - rest
            - --endpoints
            - config/endpoints.yml
            - -u
            - current/

    rasa_nlu:
        image: rasa/rasa_nlu:latest-spacy
        volumes:
            - ./models/rasa_nlu:/app/models
            - ./config:/app/config
        command:
            - start
            - --path
            - models
            - -c
            - config/nlu_config.yml

    action_server:
        image: rasa/rasa_core_sdk:latest
        volumes:
            - ./actions:/app/actions

    website:
        image: webserver-image:v1
        ports:
            - 80:80
        expose: 
            - 80
```

**Content of configuration file (nlu_config.yml)**:
```yml
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "intent_classifier_sklearn"

language: "en"

```
