### ISSUE TITLE
POST /jobs doesn't work

### ISSUE THREAD

**Issue by Djiwaye** [RasaHQ/rasa#3317]
**Rasa version**: image: rasa/rasa_core:latest (from docker-compose)

**Issue**:
When trying to train with /jobs, the core doesn't train. I'm sending the request with a rest client (see the body.json below) to POST localhost:5005/jobs
I don't know if that's related but I can see that the tmp path of saving (e.g. 2019-04-25 08:42:58 INFO     rasa.core.agent  - Persisted model to '/tmp/tmp2biusgln/core') doesn't match the tmp directories in the container ('tmp2biusgln' doesn't exist).

config.yml
```yaml
language: en
pipeline: supervised_embeddings
policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: MappingPolicy
```

domain.yml
```yaml
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```

nlu.md
```md
## intent:greet
- hey
- hello
- hi
- good morning
- good evening
- hey there

## intent:goodbye
- bye
- goodbye
- see you around
- see you later

## intent:mood_affirm
- yes
- indeed
- of course
- that sounds good
- correct

## intent:mood_deny
- no
- never
- I don't think so
- don't like that
- no way
- not really

## intent:mood_great
- perfect
- very good
- great
- amazing
- wonderful
- I am feeling very good
- I am great
- I'm good

## intent:mood_unhappy
- sad
- very sad
- unhappy
- bad
- very bad
- awful
- terrible
- not very good
- extremely sad
- so sad
```

stories.md
```md
## happy path
* greet
  - utter_greet
* mood_great
  - utter_happy
  - action_restart

## sad path 1
* greet
  - utter_greet
* mood_unhappy
  - utter_cheer_up
  - utter_did_that_help
* mood_affirm
  - utter_happy
  - action_restart

## sad path 2
* greet
  - utter_greet
* mood_unhappy
  - utter_cheer_up
  - utter_did_that_help
* mood_deny
  - utter_goodbye
  - action_restart

## say goodbye
* goodbye
  - utter_goodbye
  - action_restart
```

body.json
```json
{
  "config": "language: en\npipeline: supervised_embeddings\npolicies:\n  - name: KerasPolicy\n    epochs: 100\n    max_history: 5\n  - name: FallbackPolicy\n    fallback_action_name: 'action_default_fallback'\n  - name: MemoizationPolicy\n    max_history: 5\n  - name: FormPolicy\n  - name: MappingPolicy\n",
  "domain" : "intents:\n  - greet\n  - goodbye\n  - mood_affirm\n  - mood_deny\n  - mood_great\n  - mood_unhappy\n\nactions:\n - utter_greet\n - utter_cheer_up\n - utter_did_that_help\n - utter_happy\n - utter_goodbye\n\ntemplates:\n  utter_greet:\n  - text: \"Hey! How are you?\"\n\n  utter_cheer_up:\n  - text: \"Here is something to cheer you up:\"\n    image: \"https://i.imgur.com/nGF1K8f.jpg\"\n\n  utter_did_that_help:\n  - text: \"Did that help you?\"\n\n  utter_happy:\n  - text: \"Great carry on!\"\n\n  utter_goodbye:\n  - text: \"Bye\"\n",
  "nlu" : "## intent:greet\n - hey\n - hello\n - hi\n - good morning\n - good evening\n - hey there\n\n## intent:goodbye\n - bye\n - goodbye\n - see you around\n - see you later\n\n## intent:mood_affirm\n - yes\n - indeed\n - of course\n - that sounds good\n - correct\n\n## intent:mood_deny\n - no\n - never\n - I don't think so\n - don't like that\n - no way\n - not really\n\n## intent:mood_great\n - perfect\n - very good\n - great\n - amazing\n - wonderful\n - I am feeling very good\n - I am great\n - I'm good\n\n## intent:mood_unhappy\n - sad\n - very sad\n - unhappy\n - bad\n - very bad\n - awful\n - terrible\n - not very good\n - extremely sad\n - so sad\n",
  "stories" : "## happy path\n* greet\n  - utter_greet\n* mood_great\n  - utter_happy\n  - action_restart\n\n## sad path 1\n* greet\n  - utter_greet\n* mood_unhappy\n  - utter_cheer_up\n  - utter_did_that_help\n* mood_affirm\n  - utter_happy\n  - action_restart\n\n## sad path 2\n* greet\n  - utter_greet\n* mood_unhappy\n  - utter_cheer_up\n  - utter_did_that_help\n* mood_deny\n  - utter_goodbye\n  - action_restart\n\n## say goodbye\n* goodbye\n  - utter_goodbye\n  - action_restart\n",
  "force":true
}
```

rasa core server logs
```shell
Processed Story Blocks: 0it [00:00, ?it/s]
rasa_core_1      | 2019-04-25 08:28:33 WARNING  rasa.core.training.generator  - There is no starting story block in the training data. All your story blocks start with some checkpoint. There should be at least one story block that starts without any checkpoint.
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa.core.policies.ensemble  - Skipped training, because there are no training samples.
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa.core.agent  - Persisted model to '/tmp/tmpdcq99jh0/core'
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.training_data.training_data  - Training data stats:
rasa_core_1      |      - intent examples: 0 (0 distinct intents)
rasa_core_1      |      - Found intents:
rasa_core_1      |      - entity examples: 0 (0 distinct entities)
rasa_core_1      |      - found entities:
rasa_core_1      |
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Starting to train component WhitespaceTokenizer
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Finished training component.
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Starting to train component RegexFeaturizer
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Finished training component.
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Starting to train component CRFEntityExtractor
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Finished training component.
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Starting to train component EntitySynonymMapper
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Finished training component.
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Starting to train component CountVectorsFeaturizer
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Finished training component.
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Starting to train component EmbeddingIntentClassifier
rasa_core_1      | 2019-04-25 08:28:33 ERROR    rasa_nlu.classifiers.embedding_intent_classifier  - Can not train an intent classifier. Need at least 2 different classes. Skipping training of intent classifier.
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Finished training component.
rasa_core_1      | 2019-04-25 08:28:33 INFO     rasa_nlu.model  - Successfully saved model into '/tmp/tmpdcq99jh0/nlu'
```
