### ISSUE TITLE
POST /model doesn't work

### ISSUE THREAD

**Issue by Djiwaye** [RasaHQ/rasa#3320]
**Rasa version**: image: rasa/rasa_core:latest (from docker-compose)

**Issue**: When trying to push a model to POST /model endpoint, I get a 500 Internal Server Error. I use Content-Type: multipart/form-data as header and an attribute "model" which is a trained model as ZIP (with command python -m rasa train core [...]).

**Content of configuration file (config.yml)**:
```yml
language: en
pipeline: supervised_embeddings
policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: MappingPolicy
```

**rasa_core_1 server logs**:
```shell
rasa_core_1      | 2019-04-25 14:09:08 INFO     rasa.core.server  - Received new model through REST interface.
rasa_core_1      | [2019-04-25 14:09:08 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://localhost:5005/model'
rasa_core_1      | Traceback (most recent call last):
rasa_core_1      |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 750, in handle_request
rasa_core_1      |     response = await response
rasa_core_1      |   File "/app/rasa/core/server.py", line 148, in decorated
rasa_core_1      |     result = await result
rasa_core_1      |   File "/app/rasa/core/server.py", line 543, in load_model
rasa_core_1      |     model_file.save(zipped_path.name)
rasa_core_1      | AttributeError: 'list' object has no attribute 'save'
rasa_core_1      | 2019-04-25 14:09:08 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5005/model'
rasa_core_1      | Traceback (most recent call last):
rasa_core_1      |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 750, in handle_request
rasa_core_1      |     response = await response
rasa_core_1      |   File "/app/rasa/core/server.py", line 148, in decorated
rasa_core_1      |     result = await result
rasa_core_1      |   File "/app/rasa/core/server.py", line 543, in load_model
rasa_core_1      |     model_file.save(zipped_path.name)
rasa_core_1      | AttributeError: 'list' object has no attribute 'save'
```
