### ISSUE TITLE
httptools build fail while pip installing requirements.txt

### ISSUE THREAD

**Issue by mohit-sym** [RasaHQ/rasa#3323]
**Rasa version**: 0.13.1

**Python version**:  3.6.8

**Operating system** (windows, osx, ...): osx

**Issue**: [httptools does not build while installing requirements for rasa_nlu](https://stackoverflow.com/questions/55855529/how-to-build-httptools-to-setup-rasa-nlu)
`$ pip install -r requirements.txt`

> Building wheel for httptools (setup.py) ... error ERROR: Complete output from command /Users/mohit/anaconda3/envs/condapy36/bin/python -u -c 'import setuptools, tokenize;file='"'"'/private/var/folders/9t/0qgpwgy906z_sww71dnkgkr80000gn/T/pip-install-7hmlhuo6/httptools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/9t/0qgpwgy906z_sww71dnkgkr80000gn/T/pip-wheel-u02mzs5m --python-tag cp36: ERROR: running bdist_wheel
> 
> error: command 'gcc' failed with exit status 1
> ---------------------------------------- ERROR: Failed building wheel for httptools Running setup.py clean for httptools Building wheel for ujson (setup.py) ... error

`$ pip install -e .`

> Obtaining file:///Users/mohit/work/research/NLP/Rasa/rasa_nlu ERROR: Error installing 'file:///Users/mohit/work/research/NLP/Rasa/rasa_nlu': editable mode is not supported for pyproject.toml-style projects. pip is processing this project as pyproject.toml-style because it has a pyproject.toml file. Since the project has a setup.py and the pyproject.toml has no "build-backend" key for the "build_system" value, you may pass --no-use-pep517 to opt out of pyproject.toml-style processing. See PEP 517 for details on pyproject.toml-style projects.

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
- greet
- goodbye
- thanks
- deny
- joke
- name


entities:
- name


slots:
  name:
    type: text


actions:
- utter_name
- utter_thanks
- utter_greet
- utter_goodbye
- action_joke


templates:
  utter_name:
  - text: "Hey there! Tell me your name."

  utter_greet:
  - text: "Nice to you meet you {name}. How can I help?"

  utter_goodbye:
  - text: "Talk to you later!"
  
  utter_thanks:
  - text: "My pleasure."
  

```
