### ISSUE TITLE
Always returning fallback response when using MongoTrackerStore

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa#3336]
**Rasa version**: Rasa master version

**Python version**:  Python 3.6.7

**Operating system** (windows, osx, ...):
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Issue**:
Once the bot sends a fallback response, all the following requests are responded with the fallback action only until we clear the mongo collection which is used for tracker.

Steps:

- Add MongoTrackerStore as the tracker_store in endpoints.yml
- Add an intent with some sample user inputs
- Train the agent
- Run rasa and actions
- Check the user input from slack. The bot will provide the correct response for all the user inputs.
- Try another user input, which should not be similar to the trained data. So that the bot should respond with the message written in fallback action. This is expected behaviour.
- Now, try with some trained user inputs (or may be you can try with even simple greet message). Now the bot will again respond with the fallback action message. Here after, all the subsequent requests (user inputs from slack, even if we use the same trained samples) will be replied with the fallback action message only.
- Now, go to mongo and drop the stored collection.
- Try with the greet / trained samples. The bot will start responding correctly.

**Content of endpoints file (endpoints.yml)**:
```yml
action_endpoint:
  url: http://localhost:5055/webhook

core_endpoint:
  url: http://localhost:5005

tracker_store:
  store_type: mongod
  url: mongodb://localhost:27017
  db: conversations
```
