### ISSUE TITLE
Why does the memory usage increases rapidly when I sent a request the first time?

### ISSUE THREAD

**Issue by Miopas** [RasaHQ/rasa#3345]
**Rasa version**:
(The following are docker images I use.)
rasa core: rasa/rasa_core:latest
rasa nlu: rasa/rasa_nlu:latest-spacy

**Python version**: 
Python 3.7.3

**Operating system** (windows, osx, ...):
MaxOS 10.14.3

**Issue**:
Hi,
I followed the steps in the official docs of [this page](https://rasa.com/docs/core/docker_walkthrough/) and found the memory usage increases rapidly when I sent a request to the service the first time. The followings are the screenshots of the memory usage.

When I started the service by run `docker-compose up`, the memory usage looked like:
![image](https://user-images.githubusercontent.com/10841135/56937710-cb9a4c80-6b30-11e9-9cba-cd11c699249b.png)

Then I sent a message by running 
```
curl --request POST   --url http://localhost:5005/webhooks/rest/webhook   --header 'content-type: application/json'   --data '{
    "message": "hello"
  }'
```
The memory usage looked like:
![image](https://user-images.githubusercontent.com/10841135/56937761-1a47e680-6b31-11e9-9214-6cfe240d4419.png)

The pictures shows that the memory usage of `rasa_nlu` increased from 50.6 M to 886.6 M.

Another strange thing is that when I sent the same message the second time, the answer was empty. Here is the screenshot:
![image](https://user-images.githubusercontent.com/10841135/56937893-aeb24900-6b31-11e9-9fb5-76eb6f707e54.png)

I tried to block some components in the pipeline and restart the service and test again. But the memory usage kept the same. I have read some source code in `rasa/nlu` but I still can't figure out the reason. Could anyone helps me with the issue？

**Content of configuration file (config.yml)**:
**Here is `docker-compose.yml`**
```yml
version: '3.0'

services:
  rasa_core:
    image: rasa/rasa_core:latest
    ports:
      - 5005:5005
    volumes:
      - ./models/rasa_core:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - current/
  rasa_nlu:
    image: rasa/rasa_nlu:latest-spacy
    volumes:
      - ./models/rasa_nlu:/app/models
      - ./config:/app/config
    command:
      - start
      - --path
      - models
      - -c
      - config/nlu_config.yml
  action_server:
    image: rasa/rasa_core_sdk:latest
    volumes:
      - ./actions:/app/actions
```
**Here is the `nlu_config.yml`**
```
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "intent_classifier_sklearn"
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
  - greet
  - mood_happy
  - mood_unhappy
  - goodbye

actions:
  - utter_greet
  - utter_happy
  - action_joke
  - utter_goodbye

templates:
  utter_greet:
    - text: "Hi, how is it going?"
  utter_happy:
    - text: "Great, carry on!"
  action_joke:
    - text: "Don't be sad. Keep smiling!"
  utter_goodbye:
    - text: "Goodbye!"
```

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @Miopas,

Seems to be expected behaviour to me - the increased usage occurs upon the first message because spaCy's language model has to be held in memory to begin parsing messages.

As for blank messages upon the second response, I suspect this is because the bot wants to [fallback](https://rasa.com/docs/core/fallbacks/), but you haven't written a template for `utter_default` in your domain file.  Try writing one out and then let me know if that solves it.

**Comment by Miopas** [comment]
Hi @MetcalfeTom,

I try to add two lines in `domain.yml` like the following and the second response is still blank.
```
intents:
  - greet
  - mood_happy
  - mood_unhappy
  - goodbye

actions:
  - utter_greet
  - utter_happy
  - action_joke
  - utter_goodbye
  - utter_default

templates:
  utter_greet:
    - text: "Hi, how is it going?"
  utter_happy:
    - text: "Great, carry on!"
  action_joke:
    - text: "Don't be sad. Keep smiling!"
  utter_goodbye:
    - text: "Goodbye!"
  utter_default:
    - text: "This is a default message."
```

But I find that there is some fixed paths in  `data/stories.md`. When I follow the path, the second response is not blank.

here is the `stories.md`:
```
## happy_path
* greet
  - utter_greet
* mood_happy
  - utter_happy
* goodbye
  - utter_goodbye

## sad_path
* greet
  - utter_greet
* mood_unhappy
  - action_joke
* goodbye
  - utter_goodbye
```

here is my test result:
```shell
gyt@work:~ [Sun 08:26:30]
$ curl --request POST   --url http://localhost:5005/webhooks/rest/webhook   --header 'content-type: application/json'   --data '{
    "message": "hello"
  }'
[{"recipient_id":"default","text":"Hi, how is it going?"}]

gyt@work:~ [Sun 08:32:23]
$ curl --request POST   --url http://localhost:5005/webhooks/rest/webhook   --header 'content-type: application/json'   --data '{
    "message": "very good"
  }'
[{"recipient_id":"default","text":"Great, carry on!"}]

gyt@work:~ [Sun 08:33:42]
$ curl --request POST   --url http://localhost:5005/webhooks/rest/webhook   --header 'content-type: application/json'   --data '{
    "message": "very sad"
  }'
[]

gyt@work:~ [Sun 08:33:59]
$ curl --request POST   --url http://localhost:5005/webhooks/rest/webhook   --header 'content-type: application/json'   --data '{
    "message": "bye"
  }'
[{"recipient_id":"default","text":"Goodbye!"}]
```

Does that mean that if I don't follow the path, the rasa core won't return the response even if it could parse the input?
