### ISSUE TITLE
Mapping Policy crashes

### ISSUE THREAD

**Issue by tahamr83** [RasaHQ/rasa#3348]
**Rasa version**:
14.0
**Python version**: 
3.7.3
**Operating system** (windows, osx, ...):
MacOS
**Issue**:
Mapping policy crashes when the intent triggers the corresponding action. 
AttributeError: 'latest_action' object has no attribute 'name' line 77 in `mapping_policy.py`.
I believe it's probably a naming issue . Changing the line 77 to `assert latest_action.action_name==action` fixed issues internally. But had to resort to an older version in production.

**Content of configuration file (config.yml)**:
```yml
policies:
  - name: KerasPolicy
    epochs: 60
    max_history: 5
  - name: FallbackPolicy
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 4
  - name: FormPolicy
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
- ask_is_machine: {triggers: action_utter_i_am_machine}
```
