### ISSUE TITLE
Inserting default parameters into the config messes up the component variable order

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#3362]
If we train models with missing config values, we insert them from the defaults and write a new config file, however `ruamel.yaml.dump()` writes YAML files in alphabetical order, which makes the configs look wrong because `name` isn't necessarily first.  The file still loads as usual.
```yaml
language: en
pipeline:
- name: tokenizer_whitespace
- name: ner_crf
- name: intent_featurizer_count_vectors
- epochs: 200
  name: intent_classifier_tensorflow_embedding
- dimensions:
  - time
  - number
  - amount-of-money
  - distance
  locale: en
  name: ner_duckling_http
  timezone: Europe/Berlin
  url: http://localhost:8000
```
