### ISSUE TITLE
rasa: error: unrecognized arguments: --data data/nlu.md

### ISSUE THREAD

**Issue by tpacker** [RasaHQ/rasa#3367]
**Rasa version**:  current master branch, 1.0.0a3 and 1.0.0a2 and possibly earlier

**Python version**:  Python 3.6.8 :: Anaconda, Inc.

**Operating system** (windows, osx, ...):  Windows 10 Enterprise

**Issue**:  

I get the following error when I run the example in the Rasa online documentation:  

https://rasa.com/docs/get_started_step2/

```
C:\Users\xxxxxxxx\AppData\Local\Continuum\anaconda3\envs\rasa\python.exe C:/Dev/Rasa/rasa/rasa train nlu -c config/nlu_config.yml --data data/nlu.md -o models --verbose
usage: rasa [-h] [--version]
            {init,run,shell,train,interactive,test,show,data,x} ...
rasa: error: unrecognized arguments: --data data/nlu.md

Process finished with exit code 2
```

I get the same error when I run it in a Jupyter notebook or in PyCharm IDE.  I have tried to search the source code and debug it myself, but I'm not quite familiar enough with the project code to find it.  I have also done a quick search in the branch (master) to see if this command line argument has been changed since the version in the documentation, but I don't see anything there.  

**Content of configuration file (config.yml)**:
Unedited
```yml
language: en

pipeline: supervised_embeddings

policies:
  - name: KerasPolicy
    epochs: 200
    batch_size: 50
    max_training_samples: 300
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if used & relevant):
Unedited
```yaml
allowempty: True
mapping:
  intents:
    type: "seq"
    sequence:
    - type: "map"
      mapping:
        use_entities:
          type: "bool"
      allowempty: True
    - type: "str"
  entities:
    type: "seq"
    sequence:
    - type: "str"
  actions:
    type: "seq"
    sequence:
    - type: "str"
      required: True
  templates:
    type: "map"
    allowempty: True
  slots:
    type: "map"
    allowempty: True
  forms:
    type: "seq"
    sequence:
    - type: "str"
    allowempty: True
```
