### ISSUE TITLE
Interactive learning chat history is not showing correctly. (rasa-core==0.14.1)

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa#3391]
**Rasa version**:
rasa-core==0.14.1
rasa-core-sdk==0.13.1
rasa-nlu==0.15.0

**Python version**:  Python 3.6.7

**Operating system** (windows, osx, ...):
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Issue**: Interactive learning chat history is not showing correctly. Please find the chat log below , when creating a new intent.

```
? Your input -> This is test intent                                                                                                                   
? Your NLU model classified 'This is test intent' with intent 'stop' and there are no entities, is this correct?  No                                  
? What intent is it?  <create_new_intent>                                                                                                             
? Please type the intent name request_test_intent                                                                                                     
? Please mark the entities using [value](type) notation This is test intent                                                                           
------
Chat History

b' #    \x1b[94mBot      \x1b[39m                                \x1b[91mYou       \x1b[39m \n\x1b(0qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq\x1b(B\n 1    \x1b[96maction_listen\x1b[39m                                       \n\x1b(0qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq\x1b(B\n 2                                    \x1b[91mThis is test intent\x1b[39m \n                         intent: request_test_intent 1.00 '


Current slots: 
	test_slot: None, requested_slot: None

------
? The bot wants to run 'utter_unclear', correct?  (Y/n)
```

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline:
- name: "nlp_spacy"                   # loads the spacy language model
- name: "tokenizer_spacy"             # splits the sentence into tokens
- name: "ner_crf"                   # uses the pretrained spacy NER model
- name: "intent_featurizer_spacy"     # transform the sentence into a vector representation
- name: "intent_classifier_sklearn"   # uses the vector representation to classify using SVM
- name: "ner_synonyms"                # trains the synonyms
```
