### ISSUE TITLE
Configuring Rasa Core model policies

### ISSUE THREAD

**Issue by karan3194** [RasaHQ/rasa#3413]
**Rasa version**: 0.14.6

**Python version**: 0.13.8

**Operating system** (windows, osx, ...): Linux 18.04.1 LTS

**Issue**: I am building a chatbot using the Rasa Stack. While I've implemented NLU part , I'm having a few issues while building the Rasa model. One is that I'm unsure of where to put in the policy configurations, which we could do it earlier inside the agent.train() function. I understand it has been migrated but I'm not sure if i need to place it inside Core's config.yml file or not. I have place the configuration parameters inside config.yml now but the dont seem to work as I'm unable to change the number of epochs from default (100) to any other value.
Also, I'm not able to achieve high accuracy (around 60%, screenshot attached 
![rasa-core](https://user-images.githubusercontent.com/50234516/57435420-000db700-725b-11e9-8c04-8461d0e011df.png)
)while training the Rasa Core component. Is it due to stories/domain not being properly built? I have uploaded my config and story files for reference, and also a screenshot of the model getting trained. Would appreciate some guidance on what area I need to improve to get higher accuracy.

**Content of configuration file (config.yml)**:
```yml

language: "en"

pipeline:
- name: "nlp_spacy"                   # loads the spacy language model
- name: "tokenizer_spacy"             # splits the sentence into tokens
- name: "ner_crf"                     # uses the pretrained spacy NER model
- name: "intent_featurizer_spacy"     # transform the sentence into a vector representation
- name: "intent_classifier_sklearn"   # uses the vector representation to classify using SVM
- name: "ner_synonyms"                # trains the synonyms
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
policies:
  - name: KerasPolicy
    epochs: 200
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: MappingPolicy

intents:
- greeting
- flight
- inform
- affirmation
- deny

entities:
- location 
- date

slots:
   from:
        type: text
   to:
      type: text
   date:
        type: text

actions:
- utter_greeting
- utter_boarding
- utter_destination
- utter_date
- utter_confirm
- utter_check_another_one
- utter_thanks
- utter_unclear
- action_save_origin
- action_save_destination
- action_save_date
- action_get_flight
- action_slot_reset

templates:  
  utter_greeting:
  - text: "hello!"

  utter_boarding:
  - text: "We'll help you find the latest flight schedule. First, please provide your origin airport code?" 
  
  utter_destination:
  - text: "And the destination airport code?"
  
  utter_date:
  - text: "What is the date for your travel(in dd-mm-yyyy)?"
  
  utter_confirm:
  - text: "I will be making inquiry for flight from {from} to {to} on {date}. Is that correct?"
  
  utter_check_another_one:
  - text: "Do you want to make another inquiry?"
  
  utter_thanks:
  - text: "Thanks for contacting us. Have a good day!"
  
  utter_unclear:
  - text: "I am not sure what you are aiming for.Kindly try it again"
  
```
**Stories.md  **

## fallback
- utter_unclear

## Story 1
* flight
    - utter_boarding
* inform{"location": "BOM"}
    - action_save_origin
    - slot{"from": "BOM"}
    - utter_destination
* inform{"location": "DEL"}
    - action_save_destination
    - slot{"to": "DEL"}
    - utter_date
* inform{"date": "20-01-2019"}
    - action_save_date
    - slot{"date": "20-01-2019"}
    - utter_confirm
* affirmation
    - action_get_flight
	- utter_check_another_one
* deny
	- utter_thanks
	- action_restart

## Stry 2-multiple steps
* flight
    - utter_boarding
* inform{"location": "CCU"}
    - action_save_origin
    - slot{"from": "CCU"}
    - utter_destination
* inform{"location": "BLR"}
    - action_save_destination
    - slot{"to": "BLR"}
    - utter_date
* inform{"date": "03-02-2019"}
    - slot{"date": "03-02-2019"}
    - action_save_date
    - slot{"date": "03-02-2019"}
    - utter_confirm
* affirmation
    - action_get_flight
    - utter_check_another_one
* affirmation
	- action_slot_reset
	- reset_slots
    - utter_boarding
* inform{"location": "BOM"}
    - action_save_origin
    - slot{"from": "BOM"}
    - utter_destination
* inform{"location": "DEL"}
    - action_save_destination
    - slot{"to": "DEL"}
    - utter_date
* inform{"date": "10-02-2019"}
    - slot{"date": "10-02-2019"}
    - action_save_date
    - slot{"date": "10-02-2019"}
    - utter_confirm
* affirmation
    - action_get_flight
    - utter_check_another_one
* deny
    - utter_thanks
    - action_restart
