### ISSUE TITLE
Connect Rasa chatbot to Telegram (or any other channel)

### ISSUE THREAD

**Issue by tLabruna** [RasaHQ/rasa#3420]
**Rasa version**: 
rasa                          1.0.0a5   /mnt/d/Users/Tiz/Documents/rasa/rasa_nlu
rasa-core                     0.14.1
rasa-core-sdk                 1.0.0a1
rasa-nlu                      0.15.0
rasabaster                    0.7.18

**Python version**:  3.6.7

**Operating system** (windows, osx, ...): windows 10 running Ubuntu Bash

**Issue**: 

I created my chatbot thanks to Rasa and now I would like to make it available for everyone to talk with. I thought it was nice to have it on Telegram, so I tried to follow the instructions given [here](https://rasa.com/docs/core/connectors/#telegram-setup)

However, I’ve not been able to understand what I should specify as webhook URL. I have my own web-server, but what specific file should I insert instead of this: webhook_url: “your_url.com/webhooks/telegram/webhook” ?

By the way, I don’t need to use Telegram, any other way would work, I’m just looking for an easy way to make the bot public.

**Content of configuration file (config.yml)**:
```yml

language: "en"
pipeline: "spacy_sklearn"

<!---pipeline: supervised_embeddings-->

policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
```
