### ISSUE TITLE
Kindly help me to with proper config file for source and destination extraction

### ISSUE THREAD

**Issue by prashant334** [RasaHQ/rasa#3431]
@akelad @RasaHQ

**Rasa  NLU version**: 0.15.0 
**Rasa core version** : 0.14.3 

**Python version**: 3.7

**Operating system** (windows, osx, ...): windows

**Issue**: I want to extract entities like Source and Destination from string like "Show me trains from Rajkot to Ahmedabad on 31st may" . Kindly help me with CONFIG.YML file. I am also attaching my training data. 

I am annotating after "from" as source and after  "to" as destination.
digits similar to 3rd ,4th and 13th...etc   as "date" and "may", "june"....etc as month.

IT EXTRACTS MONTH AND DATE PROPERLY USING CRFENTITYEXTRACTOR BUT FOR SOURCE AND DESTINATION IT IS NOT WORKING.

Kindly help me with proper config.yml file

**Content of configuration file (config.yml)**:
```yml


language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

[data.txt](https://github.com/RasaHQ/rasa/files/3166510/data.txt)
