### ISSUE TITLE
TypeError: Object of type UserUttered is not JSON serializable

### ISSUE THREAD

**Issue by mirfan899** [RasaHQ/rasa#3442]
**Rasa version**:
0.15.0
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Osx
**Issue**:
UserUttered is being executed and throws an error `TypeError: Object of type UserUttered is not JSON serializable`
Here is my custom action code
```python
from rasa_core.events import UserUttered

class ActionNextQuestion(Action):
    def name(self):
        return "action_next_question"

    def run(self, dispatcher, tracker, domain):
        print("running action_next_question")
        return [UserUttered(text="/recipe", intent={'name': 'recipe', 'confidence': 1.0})]
```
**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
slots:
  Y:
    type: text
  N:
    type: text
  rearrange_answers:
    type: list
  rearrange_answer_1:
    type: unfeaturized
  rearrange_answer_2:
    type: unfeaturized
  rearrange_answer_3:
    type: unfeaturized
  rearrange_answer_4:
    type: unfeaturized
  rearrange_answer_5:
    type: unfeaturized
  rearrange_question_1:
    type: unfeaturized
  rearrange_question_2:
    type: unfeaturized
  rearrange_question_3:
    type: unfeaturized
  rearrange_question_4:
    type: unfeaturized
  rearrange_question_5:
    type: unfeaturized

  recipe_answer_1:
    type: text
  recipe_answer_2:
    type: text
  recipe_answer_3:
    type: text
  recipe_answer_4:
    type: text
  recipe_answer_5:
    type: categorical
    values:
    - We need to ask mother for help
    - We need to add some Soy Sauce
    - We need to cook the Fish Sashimi for 50 minutes
    - We need to wash our hands before touching the rice

entities:
- Y
- N
- rearrange_answer_1
- rearrange_answer_2
- rearrange_answer_3
- rearrange_answer_4
- rearrange_answer_5
- rearrange_question_1
- rearrange_question_2
- rearrange_question_3
- rearrange_question_4
- rearrange_question_5

intents:
- rearrange.detail
- rearrange.question
- rearrange.answer
- intent.choice
- recipe.detail
- recipe.question
- recipe.answer
- greet

templates:
  utter_greet:
  - text: "I'm fine, thanks"
  utter_rearrange_question_detail:
  - text: "Holly is playing a game. Read the words and rearrange the words in correct order."
  utter_rearrange_question:
  - text: "Do you know what a sentence structure is? (Yes / No)"
  utter_ask_rearrange_question_1:
  - text: "Enough / , / vegetables / cereals / we / eat / should / and /"
  utter_ask_rearrange_question_2:
  - text: "likes / his job / to sleep / , / he / because / plenty of time / has / he"
  utter_ask_rearrange_question_3:
  - text: "works / he / very / needs / , / to be / careful / on a plane / because / he"
  utter_ask_rearrange_question_4:
  - text: "give / , / is / fruit / because / you / vitamins / it  / and / vegetables"
  utter_ask_rearrange_question_5:
  - text: "famous / , / photos / she / beautiful / takes / of / people"
  utter_rearrange_structure:
  - text: "A basic sentence structure is as follow"
    image: "https://imgur.com/oaLXpFU"
  utter_recipe_question_detail:
  - text: "Holly is reading an article in a magazine. Read the article."
    image: "https://imgur.com/9drXUtG"
  utter_recipe_question:
  - text: "Do you know what 'extracting information' means? (Yes / No)"
  utter_recipe_question_1:
  - text: "Holly is reading a . . ."
actions:
- utter_greet
- utter_rearrange_question
- utter_rearrange_question_detail
- utter_show_rearrange_detail
- utter_rearrange_structure
- utter_ask_rearrange_question_1
- utter_ask_rearrange_question_2
- utter_ask_rearrange_question_3
- utter_ask_rearrange_question_4
- utter_ask_rearrange_question_5
- utter_recipe_question_detail
- utter_recipe_question
- utter_recipe_question_1
- action_check_answer
- action_next_question
- action_slot_reset
- action_slot_set
- action_restart


policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 15
  - name: FallbackPolicy
    nlu_threshold: 0.7
    core_threshold: 0.7
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 15
  - name: FormPolicy
```
