### ISSUE TITLE
Unable to run formbot

### ISSUE THREAD

**Issue by oldmonkABA** [RasaHQ/rasa#3444]
**Rasa version**:0.15 (latest github download)

**Python version**: 3.6.7

**Operating system** (windows, osx, ...):  Ubuntu 16.04.5 LTS

**Issue**:
I downloaded and installed the latest code from rasa repo. I was trying to run the formbot example.
I am able to run
1. make train
2. make run-core

However when i run 

make run-actions

I get the following error:

Traceback (most recent call last):
  File "/home/sfrplindia1/Work/SantaFe/Raghuram/chatbots/venv_rasa_14/bin/rasa", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "/home/sfrplindia1/Work/SantaFe/Raghuram/chatbots/rasa/rasa/__main__.py", line 68, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/sfrplindia1/Work/SantaFe/Raghuram/chatbots/rasa/rasa/cli/run.py", line 67, in run_actions
    import rasa_core_sdk.endpoint as sdk
  File "/home/sfrplindia1/Work/SantaFe/Raghuram/chatbots/venv_rasa_14/lib/python3.6/site-packages/rasa_core_sdk/endpoint.py", line 11, in <module>
    from flask import Flask, jsonify, request
  File "/home/sfrplindia1/Work/SantaFe/Raghuram/chatbots/venv_rasa_14/lib/python3.6/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/home/sfrplindia1/Work/SantaFe/Raghuram/chatbots/venv_rasa_14/lib/python3.6/site-packages/flask/app.py", line 25, in <module>
    from . import cli, json
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
EOFError: EOF read where object expected
Makefile:21: recipe for target 'run-actions' failed
make[1]: *** [run-actions] Error 1

**Content of configuration file (config.yml)**:
```yml
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: EmbeddingIntentClassifier
  - name: DucklingHTTPExtractor
    url: http://localhost:8000
    dimensions:
      - number

policies:
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: FormPolicy
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```
