### ISSUE TITLE
Rasa stops at nlp_spacy

### ISSUE THREAD

**Issue by Chatzimina** [RasaHQ/rasa#3460]
Rasa version: 0.14.6
Python version: 3.6.7
Operating system: Ubuntu 18.04 LTS
config.yml:

```
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "ner_duckling_http"
  url: "http://localhost:8000"
  dimensions: ["amount-of-money", "distance", "duration", "email", "number", "ordinal", "phone-number", "quantity", "temperature", "time", "unit", "unit-of-duration", "url", "volume"]
  locale: "en_EN"
  timezone: "Europe/Athens"
policies:
  - name: KerasPolicy
    epochs: 50
    max_history: 6
  - name: MemoizationPolicy
    max_history: 6
  - name: FallbackPolicy
    nlu_threshold: 0.8
    core_threshold: 0.3
  - name: FormPolicy
```

I am able to use train interactive but when I try to run this command : 
      
       python3 -m rasa_utils.bot -d models/dialogue -u models/current/nlu --debug --port 8890 --endpoint endpoints.yml

Also if I try to run it through this python code:

        from rasa_core.channels.socketio import SocketIOInput
        from rasa_core.agent import Agent
        from rasa_core.interpreter import RasaNLUInterpreter
        from rasa_core.utils import EndpointConfig
        import logging
        import os

        logging.basicConfig(level="DEBUG")
        nlu_interpreter = RasaNLUInterpreter('models/current/nlu')
        action_endpoint = EndpointConfig(url="http://localhost:8005/webhook")
        agent = Agent.load('models/dialogue', interpreter = nlu_interpreter, action_endpoint = 
        action_endpoint)

        input_channel = SocketIOInput(

           user_message_evt="user_uttered",

           bot_message_evt="bot_uttered",

           namespace=None
         )

        s = agent.handle_channels([input_channel], 8890, serve_forever=True)

it stops at rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
It was working until yesterday and the only change I did was to add a picture in an utterance. I removed the picture and it still doesn't work. I have also deleted contents of folder "models".
I cannot also find something in the logs. I don't know where to look.

Thank you
