### ISSUE TITLE
ImportError: cannot import name 'interactive'

### ISSUE THREAD

**Issue by meghnasmhs** [RasaHQ/rasa#3481]
**Rasa version**:rasa core-0.14.4 (updated from 0.8.2), rasa nlu-0.15.0

**Python version**: 3.6.6

**Operating system** (windows, osx, ...): windows 10, core i7 processor

**Issue**:running python train_interactive.py gives this error: 
C:\Python36\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train_interactive.py", line 12, in <module>
    from rasa_core.train import interactive
ImportError: cannot import name 'interactive'

**Content of configuration file (config.yml)**:
```yml
{
  "pipeline":"spacy_sklearn",
  "path":"./models/nlu",
  "data":"./data/data.json"
}

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
slots:
  location:
    type: text


intents:
 - greet
 - goodbye
 - inform


entities:
 - location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_location:
    - 'In what location?'


actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - action_weather

```
After I updated rasa_core, my nlu_model is not compiling as well.
