### ISSUE TITLE
Not getting answers for all questions.

### ISSUE THREAD

**Issue by sushilr007** [RasaHQ/rasa#3530]
**Rasa version**: 0.13.7

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): windows 10

**Issue**: I have created a bot for a website which will fetch data from the database on a few questions for that I have assigned 4 to 5 questions to each intent but it is not giving an answer for all questions.
Example: Me: Why should I get less salary ?
Bot: "Data from database"

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline: spacy_sklearn

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
- greet
- goodbye
- thanks
- deny
- joke
- name
- PF_UAN_Number
- Update_Bank_Account
- Update_Mobile_Number
- Update_Aadhar_card
- Update_PAN
- Update_Name
- form_16
- Permanent_ID_Card
- Promotion_letter
- Maternity_Leave_Benefits
- previous_PF_number
- reason_No_Salary
- Update_Date_of_Birth
- Experience_Relieving_letter
- Offer_letter
- Less_salary
- Leave_Policy



entities:
- name


slots:
  name:
    type: unfeaturized


actions:
- utter_name
- utter_thanks
- utter_greet
- utter_goodbye
- action_db


templates:
  utter_name:
  - text: "Hey there! Tell me your Employee-ID"
  - text: "Hello! please tell me your Employee-ID"

  utter_greet:
  - text: "Nice to you meet you {name}. How can I help?"

  utter_goodbye:
  - text: "Talk to you later!"
  - text: "See you again!"
  - text: "Have nice day!"
  - text: "Nice to meet you."

  utter_thanks:
  - text: "You are most welcome."
  - text: "It is my pleasure"

```

**nlu_data.md**:
```
## intent:Less_salary
- I have received less salary ,how could this happen?
- How could I get less salary ,how could this happen?
- What is the reason behind less salary?
- Is there any reason for receiving less salary?
- Why should I get less salary ?

## intent:Leave_Policy
- What is the Leave Policy?
- How about Leave policy?
- Do you know about leave policy?
- Can you explain leave policy?
- Explain leave policy?

## intent:greet
- Hi
- Hey
- hi there
- hello is anybody there
- hello robot

## intent:thanks
- Thanks
- Thank you
- Thank you so much
- Thanks bot
- Thanks for that
- cheers
- cheers bro
- ok thanks!
- perfect thank you
- thanks a bunch for everything


## intent:affirm
- yes
- yes sure
- absolutely

## intent:name
- My employee id is [123](name)
- I am [456](name)
- I'm [789](name)  <!--- Square brackets contain the value of entity while the text in parentheses is a a label of the entity -->
- My emp id is [1468Y](name)
- It's [227845](name)
- Usually people call me [Amy](name)
- My company name is [334764TYU](name)
- You can call me [Sam](name)
- Please call me [Linda](name)
- emp id is  [335785](name)
- I am [Richard](name)
- I'm [Tracy](name)
- Employee id is [SSERT567](name)
- I am [Philipp](name)
- I am [Charlie](name)
- I am [Charlie](name)
- I am [Ben](name)
- Call me [Susan](name)


```
**stories.md**:
```
## story_joke_15
* Less_salary
 - action_db

## story_joke_16
* Leave_Policy
 - action_db       

## story_joke_00
* greet
 - utter_name
* name{"name":"Lucy"} <!--- User response with an entity. In this case it represents user message 'My name is Lucy.' -->
 - utter_greet
* PF_UAN_Number
 - action_db
* thanks
 - utter_thanks
* goodbye
 - utter_goodbye
```
