### ISSUE TITLE
Slots not populating in Rasa X

### ISSUE THREAD

**Issue by anishrav** [RasaHQ/rasa#3546]
**Rasa version**: Rasa 1.0.0

**Python version**: Python 3.7.3

**Operating system** (windows, osx, ...): OS X 10.14.4

**Issue**:
Slots are not populating properly in Rasa X's interactive learning mode. I have a slot called 'name' from the original domain.yml that's provided on `rasa init` and although there's a slot populated in the story that's created, it still says 'No slots' underneath Slots.  

**Content of configuration file (config.yml)**:
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
%YAML 1.1
---
actions:
- utter_greet
- action_spent_timeframe
- utter_goodbye
- utter_date_info
- action_spent_since
- utter_thanks
- utter_name
entities:
- name
- budget_action
- time_unit
- time_count
- end_date
- start_date
intents:
- greet
- spent_timeframe
- name
- date_info
- spent_since
- thanks
- goodbye
- deny
slots:
  end_date:
    type: text
  name:
    type: text
  start_date:
    type: text
  time_count:
    type: text
  time_unit:
    type: categorical
    values:
    - day
    - week
    - month
    - year
templates:
  utter_date_info:
  - text: Sure, what are the start and end dates? Here's an example date April 14
      2015
  utter_goodbye:
  - text: Talk to you later!
  utter_greet:
  - text: Nice to you meet you {name}. How can I help?
  utter_name:
  - text: Hey there! Tell me your name.
  utter_thanks:
  - text: My pleasure.

```
