### ISSUE TITLE
Rasa core action server taking long and entire system become slow 

### ISSUE THREAD

**Issue by siddheshjain** [RasaHQ/rasa#3559]
rasa                          1.0.0rc8  /home/skj/rasachat/rasa_nlu
rasa-core                     0.14.4    
rasa-core-sdk                 0.14.0    
rasa-demo                     1.1       /home/skj/sara/rasa-demo   
rasa-nlu                      0.15.0    
rasa-sdk                      1.0.0rc4  

**Rasa version**:

**Python version**: 
3.6
**Operating system** (windows, osx, ...):

**Issue**:
my action server.py code deals with large excel file >75mb. Action server works well for small files. But takes longer for large files and after 7-8 min whole system gets slowed down and finally become unresponsive... pls help 

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline: tensorflow_embedding
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
action_endpoint:
  url: http://localhost:5055/webhook

#nlg:
# url: http://localhost:5056/nlg

core_endpoint:
  url: http://localhost:5055
```
