### ISSUE TITLE
rasa x with own data failing

### ISSUE THREAD

**Issue by bamba518** [RasaHQ/rasa#3563]
**Rasa version**:
Rasa X
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Ubuntu 16.04
**Issue**:
I trained a model using rasa with my own data, it works fine for all the http and command line interface. I wanted to try the rasa x GUI. The rasa X gui works with the standard data from rasa init, but when i try to do my own data with rasa x I get a sqlite3.IntegrityError UNIQUE constraint failed: domain_intent.id, domain_intent.intent

**Content of configuration file (config.yml)**:
```yml
standard default
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by erohmensing** [comment]
Can you post your domain file intents? Sounds like you might have duplicate entries under your `intents:` in your domain.

**Comment by bamba518** [comment]
I am doing a bilingual bot, and using whitespace tokenzier with tensorflow
```
intents:
  - greet: {triggers: utter_greet}
  - weather
  - weather_French
  - chitchat: {triggers: utter_chitchat}
  - questions: {triggers: utter_qa}
  - chitchat_French: {triggers: utter_chitchat_French}
  - questions_French: {triggers: utter_qa_French}
```
