### ISSUE TITLE
Example code on api/jupyter-notebooks fails to run properly

### ISSUE THREAD

**Issue by ravikrcs** [RasaHQ/rasa#3579]
**Rasa version**: 1.0.1

**Python version**:  3.6.8

**Operating system** (windows, osx, ...): windows

**Issue**:
config = "config.yml"
training_files = "data/"
domain = "domain.yml"
output = "models/"

import rasa
model_path = rasa.train(domain, config, [training_files], output)

RuntimeError: This event loop is already running

**Content of configuration file (config.yml)**:
```yml

```# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy


**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```
