### ISSUE TITLE
Rasa X quick installation ansible playbook syntax error

### ISSUE THREAD

**Issue by ftsamis** [RasaHQ/rasa#3585]
**Rasa Χ version**: 0.19.0

**Python version**: 2.7

**Operating system**: Ubuntu Linux 18.04.02 LTS

**Issue**: In step 2 of the [quick installation](https://rasa.com/docs/rasa-x/0.19.0/deploy/#quick-installation) guide there is a [shell script](https://storage.googleapis.com/rasa-x-releases/stable/install.sh) which fetches and executes the Ansible playbook from https://storage.googleapis.com/rasa-x-releases/stable/rasa_x_playbook.yml.

In this playbook lines 57 through 62 are over-indented by one level, generating a syntax error and failing the ansible-playbook execution:

Original:
```
  - name: Create the directory for the database persistence
      file:
        path: /etc/rasa/db
        state: directory
        mode: 0750
        owner: 1001
        group: root
``` 

Should be:
```
  - name: Create the directory for the database persistence
    file:
      path: /etc/rasa/db
      state: directory
      mode: 0750
      owner: 1001
      group: root
```
