### ISSUE TITLE
rasa run --enable-api without model

### ISSUE THREAD

**Issue by neumann-d** [RasaHQ/rasa#3588]
**Rasa version**: 1.0.1

**Python version**: Python 3.6.8

**Operating system** (windows, osx, ...): Linux/Docker

**Issue**: When executing `rasa run --enable-api ` without any model passed as argument or provided in the default models directory, the programm shows the following error message and exits:
```
No model found. Train a model before running the server using `rasa train`.
```
In my use case, I only want to start rasa without an initial model, because I want to train models using the http api `http://localhost:5005/model/train` and later load a trained model with `http://localhost:5005/model`. Would be nice to be able to start the rasa http server without any model.

My workaround for now is to check at first, if there exists a model in the `models` directory and run `rasa init` if there is no model existing. After that I can run `rasa run --enable-api`.

**Content of configuration file (config.yml)**:
```yml
                    language: "de"
                    pipeline:
                    - name: "WhitespaceTokenizer"
                    - name: "CRFEntityExtractor"
                    - name: "EntitySynonymMapper"
                    - name: "CountVectorsFeaturizer"
                    - name: "EmbeddingIntentClassifier"
```
