### ISSUE TITLE
Deploy to a Server

### ISSUE THREAD

**Issue by nkane2898** [RasaHQ/rasa#3591]
**Rasa version**:
Rasa-X 0.19.0

**Python version**: 
Python 2.7.15rc1

**Operating system** (windows, osx, ...):
Ubuntu 18.04

**Issue**:

When trying to setup Rasa X on an ubuntu 18.04 server. The ansible playbook failed to run. This is due to a formatting issue in rasa_x_playbook.yml. Updating the following section:
```
  - name: Create the directory for the database persistence
      file:
        path: /etc/rasa/db
        state: directory
        mode: 0750
        owner: 1001
        group: root
```
To the following resolved the issue.
```
  - name: Create the directory for the database persistence
    file:
        path: /etc/rasa/db
        state: directory
        mode: 0750
        owner: 1001
        group: root
```
**Content of configuration file (config.yml)**:
```yml
N/A
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
N/A
```
