### ISSUE TITLE
custom actions are lost events

### ISSUE THREAD

**Issue by rishi454** [RasaHQ/rasa#3594]
**Rasa version**:0.14

**Python version**: 3.6.8

**Operating system** (windows 10):

**Issue**:
Encountered an exception while running action 'action_listen'. Bot will continue, but the events of the action are lost. Make sure to fix the exception in your custom code.

**Content of action file (actions.py)**:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

#from rasa_core_sdk import Action
#from rasa_core_sdk.events import SlotSet
#from rasa_core.action import Action
#from rasa_core.events import SlotSet

from rasa_sdk import Action
from rasa_sdk.events import SlotSet

class ProductDetails(Action):
	def name(self):
		return ('action_pdetails')

	def run(self, dispatcher, tracker, domain):
			curl = ("http://localhost:5000/webhook/sms/demosendsms/")
			pro = tracker.get_slot("pdetail")
			current = curl.get(q=pro)
			details= current['pdetail']
			response = """The Product Details are {}""".format(details)
			dispatcher.utter_message(response)
			return [SlotSet('pdetail', pro)]
		
```

**Content of domain file (domain.yml)** (if used & relevant):
```
slots:
  pname:
   type: text
   
 plist:
   type: text

 pdetail:
   type: text

 order_number:
   type: text
   
 deny:
   type: text
   
 bestp:
   type: text
 
 sellp:
   type: text

 
entities:
 - order
 - pname
 - pdetails
 - plist
 - product
 - quantity
 - price
 - idproof
 - stock
 - outstock
 - confirm
 - time
 - order_id
 - bestp
 - sellp
 - toffer
 - doffer
 
intents:
  - greet
  - action_listen
  - action_restart
  - can_help
  - ask_product
  - product_name
  - ask_product_name
  - ask_product_nvalue
  - order
  - deny
  - affirm
  - need_quantity_value
  - product_details
  - product_list
  - product_price
  - order_confirm
  - today_offers
  - discount_offers
  - thanks
  - product_in_stock
  - order_details
  - order_time 
  - outstock
  - idproof
  - out_of_scope
  - goodbye
  - suggest_best_product
  - most_selling_product
  - product_help
  - order_modify
  - order_cancel
  
actions:
 - utter_greet
 - utter_help
 - utter_can_help
 - utter_ask_product
 - utter_ask_price
 - utter_ask_quantity
 - utter_affirm
 - utter_goodbye
 - utter_order_confirm
 - utter_total_price
 - utter_order_id
 - utter_thanks
 - utter_id_proof
 - utter_product_price
 - utter_product_details
 - utter_product_list
 - utter_any_thing_else
 - utter_order_ready_time
 - utter_default
 - action_listen
 - action_restart
 - action_pdetails
 - utter_suggest_best_product
 - utter_today_offer_list
 - utter_discount_offers
 - utter_product_stock
 - utter_product_outstock
 - utter_product_help
 - utter_order_modify
 - utter_order_cancel
 
templates:
 utter_greet:
   - text: "Hey there! "
   - text: "Hi "
   - text: "Hey"
   - text: "Hello!"
   
 utter_can_help:
   - text: "I’ll be happy to help you with the Product Booking, Product list with their Details, Discounts, and your related queries"
   
 utter_product_help:
   - text: "I’ll be happy to help you with the Product Booking, Product list with their Details, Discounts, and your related queries"

```
@amn41 @sheldon @fungiboletus @phoet @ryanmcdonough @bderenzi @akelad
