### ISSUE TITLE
Why cannot rasa core detect the intents?

### ISSUE THREAD

**Issue by CathyWang53** [RasaHQ/rasa#3596]
**Rasa version**: rasa-0.15.0a1; rasa-nlu-0.15.0; rasa-core-0.14.4; rasa-core-sdk-0.14.0

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): CentOS 7.6.1810

**Issue**: 
Hi everyone,
I meet with an issue about rasa core...It's very wired.

I installed rasa.core through "pip install rasa.core" and trained the core model through "python -m rasa.core.train -d domain.yml -s stories.md -o models/dialogue". 
Then, I ran the core model by typing "python -m rasa.core.run -d models/dialogue". (using no nlu model)

However, when I tried to contact with rasa core model using parameters, most intents cannot get any reply. In most cases, only '/goodbye' works, and sometimes, the '/greet' works, too.  But when I type in other intents, nothing seems to happen. 

There are some warnings about Tensorflow or rasa.core, but seems to have no affections.

My stories and domain files are showed below. I tried to search but I can't find anyone who meet with the same problem with me. I just followed the popular tutorials and it was very easy, but it failed here and I cannot find the solution. It makes me so upset....

Can anyone give me some suggestions? Thanks a lot!

**Content of domain file (domain.yml)** :
```
intents:
 - greet
 - goodbye
 - affirm
 - deny
 - food
 - restaurant_search

entities:
 - food

templates:
  utter_greet:
    - "Hello"
  utter_goodbye:
    - "Bye"
  utter_eat_query:
    - "How's dinner?"
  utter_eat_what:
    - "What did you eat?"
  utter_eat:
    - "How about go to the dinner now?"
  utter_eat_healthy:
    - "How about eat salad?"
  utter_appraise:
    - "Good."

actions:
  - utter_default
  - utter_greet
  - utter_goodbye
  - utter_eat_query
  - utter_eat
  - utter_eat_what
  - utter_eat_healthy
  - utter_appraise
```

**Content of story file (stories.md)** :
```
## story_1
* greet
 - utter_eat_query
* affirm
 - utter_eat_what
* food 
 - utter_eat_healthy
* affirm
 - utter_appraise
* goodbye
 - utter_goodbye

## story_2
* greet
 - utter_eat_query
* affirm 
 - utter_eat_what
* food
 - utter_appraise
* goodbye
 - utter_goodbye

## story_3
* greet
 - utter_greet
* restaurant_search
 - utter_eat_query
 
## say_hello
* greet
 - utter_greet

## say_goodbye
* goodbye
 - utter_goodbye
```
