### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5005 ssl:None [Connection refused]

### ISSUE THREAD

**Issue by harunkelesoglu** [RasaHQ/rasa#3606]
**Rasa version**: 1.0.1

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): macOS

**Issue**:  I get this error when i enter the mongo tracker store `aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5005 ssl:None [Connection refused]`

**Content of configuration file (config.yml)**:
```yml
language: en
pipeline: supervised_embeddings
timezone: "Europe/Istanbul"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy
```

**Content of domain file (endpoints.yml)** 
```yaml
tracker_store:
   type: mongod
   url: mongodb://myaddress:port/?ssl=true
   db: mydb
   username: user
   password: pass
```
Additional rasa is working on my localhost.

console output:
<img width="1195" alt="Screen Shot 2019-05-27 at 15 35 54" src="https://user-images.githubusercontent.com/9349762/58420130-3b024e00-8095-11e9-8d37-8fd68950bbc8.png">
