### ISSUE TITLE
Rasa X startup delay

### ISSUE THREAD

**Issue by psds01** [RasaHQ/rasa#3611]
**Rasa version**: 1.0.1

**Python version**: Python 3.6.8 |Anaconda 

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:

```
n_stories = 3 (stories.md)
n_intents ~= thousand (nlu.md)
```
plus some regex features

With `rasa train`, it takes only `40 seconds` to train both `nlu` and `core` and the resulting model size is 12 MB. But when I run `rasa x`, it takes `more than 2 minutes` to load the UI. As this is happening, a file named `rasa.db-journal` gets created and deleted at least a hundred times. 
sizes:
```
rasa.db = 1.6 MB
tracker.db = 1.6kB
model.tar.gz = 12.1 MB
```

**Content of configuration file (config.yml)**:
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings
  - epochs : 10

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
    epochs : 1000
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
actions:
 - action_bot_do_0
 - action_bot_do_1
 - action_bot_do_2
 - action_bot_do_3
 - action_bot_do_4
 - action_bot_do_5
 - action_bot_do_6
 - action_bot_do_7
 - action_bot_do_8
 - action_bot_do_9
 - action_bot_do_10
 - action_bot_do_11
 - action_bot_do_12
 - action_bot_do_13
 - action_bot_do_14
 - action_bot_do_15
 - action_bot_do_16
 - action_bot_do_17
 - action_bot_do_18
 - action_bot_do_19
 - action_bot_do_20
 - action_bot_do_21
 - action_bot_do_22
 - action_bot_do_23
 - action_bot_do_24
 - action_bot_do_25
 - action_bot_do_26
 - action_bot_do_27
 - action_bot_do_28
 - action_bot_do_29
 - action_bot_do_30
 - action_bot_do_31
 - action_bot_do_32
 - action_bot_do_33
 - action_bot_do_34
 - action_bot_do_35

slots:
  is_a:
    type: categorical
    values:
      - true
      - false
  is_b:
    type: categorical
    values:
      - true
      - false
  is_c:
    type: categorical
    values:
      - true
      - false
  is_d:
    type: categorical
    values:
      - true
      - false
  is_e:
    type: categorical
    values:
      - true
      - false
  is_f:
    type: categorical
    values:
      - true
      - false
  g:
    type : text
  h:
    type : text
  i:
    type : text
  j:
    type : text
  k:
    type : text
  l:
    type : text
  m:
    type : text
  n:
    type: text
  o:
    type: text

entities:
- is_a
 - is_b
 - is_c
 - is_d
 - is_e
 - is_f
 - g
 - h
 - i
 - j
 - k
 - l
 - m
 - n
 - o

intents:
 - intent_a
 - intent_b
 - intent_c
 - intent_d
 - intent_e
 - intent_f
 - intent_g
 - intent_h
 - intent_i
 - intent_j
 - intent_k
 - intent_l
 - intent_m
 - intent_n
 - intent_o
 - intent_p

```

It may be due to `rasa.db-journal` getting created and deleted a lot of times but I am not exactly sure what's causing that. Any ideas why this might be happening? 
Thanks,
