### ISSUE TITLE
Overlapping bot answers in Rasa X

### ISSUE THREAD

**Issue by nicola1M** [RasaHQ/rasa#3618]
**Rasa version**: Rasa 1.0.1

**Python version**: Python 3.6.8 : Anaconda

**Operating system** (windows, osx, ...): windows 10

**Browser:** Google Chrome Version 74.0.3729.169 (Offizieller Build) (64-Bit)

Hello,

I'm having some issue with Rasa X.

After sending 2 utters one after the other, the messages overlap and can not be read properly.

<img width="586" alt="Unbenannt" src="https://user-images.githubusercontent.com/51114505/58465009-178fdf80-8137-11e9-8e0b-e31630bdf481.PNG">

**Content of domain file (domain.yml) (if used & relevant)**:
```
utter_greet:
  - text: Large text, large text, Large text, large text,Large text, large text,Large
      text, large text,Large text, large text,Large text, large text,Large text, large
      text,Large text, large text,Large text, large text,Large text, large text,Large
      text, large text,Large text, large text,Large text, large text,
  utter_profile:
  - buttons:
    - payload: '/affirm{"has_profile": true}'
      title: Ja
    - payload: '/deny{"has_profile": false}'
      title: Nein
    text: Hast du bereits einen Account?
```

**Content of story file (domain.yml) (if used & relevant)**
```
## Generated Story -5132019411761668121
* greet
    - utter_greet
    - utter_profile
* affirm{"has_profile": true}
```
