### ISSUE TITLE
AttributeError: 'function' object has no attribute 'train_dialogue_model'

### ISSUE THREAD

**Issue by tiwo19** [RasaHQ/rasa#3627]
**Python version**: = python3.7

rasa-core                         0.14.4
rasa-core-sdk                  0.14.0
rasa-nlu                           0.15.0

Windows 10
**Issue**:
I get this error when i run python train_online.py
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-05-28 18:37:01 WARNING  tensorflow  - From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./models/nlu/default/college_bot\component_5_EmbeddingIntentClassifier.ckpt
2019-05-28 18:37:01 INFO     tensorflow  - Restoring parameters from ./models/nlu/default/college_bot\component_5_EmbeddingIntentClassifier.ckpt
Traceback (most recent call last):
  File "train_online.py", line 32, in <module>
    agent = train_agent(interpreter)
  File "train_online.py", line 16, in train_agent
    return train.train_dialogue_model(domain_file="college_bot_domain.yml",
AttributeError: 'function' object has no attribute 'train_dialogue_model'

**Content of configuration file (config.yml)**:
language: "en"

pipeline: "tensorflow_embedding"

training_data,
            augmentation_factor=50,
            epochs=500,
            batch_size=10,
            validation_split=0.2  ```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
slots:
  group:
    type: text

intents:
 - greeting
 - get_jabu
 


entities:
 - product
 - jabuinfo

templates:
  utter_greet:
    - "Hello! What can I do for you?"
  utter_JABU:
   - "The Joseph Ayo Babalola University (JABU) is a private Nigerian university located in Ikeji-Arakeji in Osun State, established by the Christ Apostolic Church (CAC) Worldwide. The university is named after the first Spiritual leader of Christ Apostolic Church, Joseph Ayo Babalola (1904–1959); it is located at the place where he was called by God to slay the Ogobungo ogre in 1928. Joseph Ayo Babalola University is a fully residential institution. The university offers courses in the following colleges; Agricultural Sciences, Environmental Sciences, Humanities, Law, Management Sciences, Natural Sciences and Social Sciences. Due to its Christian foundations, male and female in the school are enjoined to adopt an extremely modest mode of dressing while on campus"
actions:
 - utter_greet
 - utter_JABU

```yaml

```
