### ISSUE TITLE
Rasa 1.0 ImportError: cannot import name 'EndpointConfig' from 'rasa_core.utils'

### ISSUE THREAD

**Issue by karthikbalu** [RasaHQ/rasa#3629]
**Rasa version**:
rasa                    1.0.1 

**Python version**: 
Python 3.7.3

**Operating system** (windows, osx, ...):
OSX

**Issue**:
ImportError: cannot import name 'EndpointConfig' from 'rasa_core.utils'

After upgrading to rasa version 1.0,
How can we train using python agent

```python
from rasa_core.utils import EndpointConfig
core_endpoint_config = EndpointConfig(url='http://localhost:5055/webhook')

agent = Agent(domain_file, policies=[MemoizationPolicy(), KerasPolicy(), fallback], action_endpoint = core_endpoint_config, interpreter=interpreter)
#agent = Agent.load(current_project_path+"/models")`
```

**Content of configuration file (config.yml)**:
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
- greet
- goodbye
- thanks
- deny
- joke
- name


entities:
- name


slots:
  name:
    type: text


actions:
- utter_name
- utter_thanks
- utter_greet
- utter_goodbye
- action_joke
- utter_unclear

templates:
  utter_name:
  - text: "Hey there! Tell me your name."

  utter_greet:
  - text: "Nice to you meet you {name}. How can I help?"

  utter_goodbye:
  - text: "Talk to you later!"
  
  utter_thanks:
  - text: "My pleasure."

  utter_unclear:
  - text: "Sorry, I dont know"
  

```
