### ISSUE TITLE
Entity extraction (using Duckling) not working when changing the order of the sentence

### ISSUE THREAD

**Issue by danielhomsa** [RasaHQ/rasa#3643]
**Rasa version**: 0.13.5

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): macOS Mojave

**Issue**:
I am trying to extract some entity of the 'time' type using duckling, it is working with sentences like: 
"Find me 2 artists born in Vienna between 1700 and 1800"
But if I change the sentence to:
"Find me 2 artists born between 1700 and 1800 in Vienna"
the duckling extractor won't recognize the 'time' entity and will completely skip it. And as I said before, it works when having the date in the end of the sentence. I added the training data to identify it, but it just doesn't get extracted.

Is there a way to fix this?

**Content of configuration file (config.yml)**:
```yml
language: "en"
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_duckling_http"
  url: http://localhost:8000
  dimensions: ["time", "number"]
  locale: 'en_US'
  timezone: "Europe/Paris"
- name: "ner_crf"
- name: "ner_spacy"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
```
