### ISSUE TITLE
HTTP 404 in versioned environment

### ISSUE THREAD

**Issue by naj44692** [RasaHQ/rasa#3646]
**Rasa version**: 1.0

**Python version**: 3.6.1

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
Hi,

I was able to run Rasa great locally. There is a requirement for me to deploy to a versioned environment (i.e. example.com/virtualassistantserver/v1), and when I have the additional route (/virtualassistantserver/v1) I get 404 responses.

i.e. Error: Requested URL /virtualassistantserver/v1/webhooks/rest/webhook not found

I tried against a non-versioned deployment (just the base uri) and everything worked fine. So it seems like the router is not properly parsing the uri and therefore not resolving to the endpoint.

Is there a configuration that I am missing for the routing to work correctly?

Thanks

**Content of configuration file (config.yml)**:
```yml
language: en
pipeline:
- name: tokenizer_whitespace
- name: intent_entity_featurizer_regex
- features:
  - - prefix5
    - prefix2
    - suffix3
    - suffix2
    - title
    - upper
  - - bias
    - upper
    - title
    - digit
    - pattern
  - - prefix5
    - prefix2
    - suffix3
    - suffix2
    - title
    - upper
  name: ner_crf
- name: ner_synonyms
- name: intent_featurizer_count_vectors
- intent_split_symbol: +
  intent_tokenization_flag: true
  name: intent_classifier_tensorflow_embedding
policies:
- epochs: 100
  max_history: 5
  name: KerasPolicy
- core_threshold: 0.6
  fallback_action_name: action_default_fallback
  name: FallbackPolicy
  nlu_threshold: 0.6
- max_history: 5
  name: MemoizationPolicy
- name: FormPolicy

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```
