### ISSUE TITLE
Training data generator hangs in Interactive Learning

### ISSUE THREAD

**Issue by tahamr83** [RasaHQ/rasa#3648]
**Rasa version**:
1.0.2
**Python version**: 
3.6.6
**Operating system** (windows, osx, ...):
MacOS
**Issue**:
So the issue I am facing while migrating to Rasa 1.0.x is that during interactive learning 
`training.load_data()` runs indefinitely. This was seemingly not an issue in previous rasa version, since I have been using the interactive learning feature a lot (RASA 0.14.x and 0.15.x). My stories are using checkpoints. But the checkpointing isn't complex. Each story starts with only one common checkpoint. But on the other hand I do have a lot of OR statements in my story. Why is this happening? Also regular story training doesn't hang. It does complete in a reasonable time. 

**Content of configuration file (config.yml)**:
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en_core_web_md
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
- name: "DucklingHTTPExtractor"
  url: http://0.0.0.0:8000
  
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: FormPolicy
    priority: 7
  - name: FallbackPolicy
    fallback_action_name: 'action_custom_fallback'
    priority: 6
  - name: MappingPolicy
    priority: 3
  - name: MemoizationPolicy
    max_history: 5
    priority: 2
  - name: KerasPolicy
    epochs: 300
    max_history: 3
    priority: 1

```
