### ISSUE TITLE
Rasa-X Is not able to find conversations

### ISSUE THREAD

**Issue by ayushmaang** [RasaHQ/rasa#3663]
**Rasa version**: 1.0.2

**Rasa-X Version**: 0.19

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): Mac OS 10.14.5

**Issue**:
When I try to use rasa-x, it seems that it doesn't detect any of my conversations or the database itself. I'm getting the pop up that says: "It seems you're new here! ..."

The rasa.db file is in the same directory as my other files. I have tried to do an absolute path to the rasa.db file but then sqlite gives me the following error: 

sqlalchemy.exc.ArgumentError: Invalid SQLite URL: sqlite:////Users/ayushmaanganotra/newRasa/rasa.db
Valid SQLite URL forms are:
 sqlite:///:memory: (or, sqlite://)
 sqlite:///relative/path/to/file.db
 sqlite:////absolute/path/to/file.db
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited

**Content of configuration file (config.yml)**:
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: pretrained_embeddings_spacy

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

```

**Content of endpoints file (endpoints.yml)** (if used & relevant):
```yaml
tracker_store:
    type: SQL
    dialect: "sqlite"  # the dialect used to interact with the db
    url: ""  # (optional) host of the sql db
    db: "rasa.db"  # path to your db
    username:  # username used for authentication
    password:  # password used for authentication
```
