### ISSUE TITLE
rasa_core.train. train_dialog_model

### ISSUE THREAD

**Issue by Sonia2016** [RasaHQ/rasa#3682]
**Rasa version**:
rasa-core==0.11.1
rasa-core-sdk==0.11.0
rasa-nlu==0.13.8
rasa-sdk==1.0.0

**Python version**:
Python 3.6.5 :: Anaconda, Inc.

**Operating system** (windows, osx, ...):
Mac OS 10.14.0
**Issue**:
I am trying to work on realtime learning of chatbot so I was using _rasa-core.train.train_dialog_model_ but it shows me ` module 'rasa_core.train' has no attribute 'train_dialog_model'`

**Error (including full traceback)**:
AttributeError                            Traceback (most recent call last)
<ipython-input-10-3158e5f9d7fb> in <module>()
      3     nlu_model_path = "./models/nlu/default/horoscopebot"
      4     interpreter = NaturalLanguageInterpreter.create(nlu_model_path)
----> 5     agent = train_agent(interpreter)
      6     online.serve_agent(agent)

<ipython-input-9-0f70797e16e8> in train_agent(interpreter)
      1 def train_agent(interpreter):
----> 2     return train.train_dialog_model(domain_file="horoscope_domain.yml",
      3                                       stories_file="data/stories.md",
      4                                       output_path="models/dialog",
      5                                       nlu_model_path=interpreter,

AttributeError: module 'rasa_core.train' has no attribute 'train_dialog_model'

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

{
  "pipeline":"tensorflow_embedding",
  "path":"./models/nlu",
  "data":"./data/data.json"
}
```

**Content of domain file (domain.yml)** (if relevant):
```yml

%YAML 1.1
---
actions:
- utter_greet
- utter_ask_horoscope_sign
- utter_ask_dob
- utter_subscribe
- get_todays_horoscope
- subscribe_user
config:
  store_entities_as_slots: true
entities:
- horoscope_sign
- DD
- MM
- subscribe
- dob_intent
intents:
- greeting:
    use_entities: true
- get_horoscope:
    use_entities: true
- subscription:
    use_entities: true
- dob_intent:
    use_entities: true
slots:
  DD:
    initial_value: null
    type: rasa_core.slots.TextSlot
  MM:
    initial_value: null
    type: rasa_core.slots.TextSlot
  horoscope_sign:
    initial_value: null
    type: rasa_core.slots.TextSlot
  subscribe:
    initial_value: null
    type: rasa_core.slots.BooleanSlot
templates:
  utter_ask_dob:
  - text: What is your DOB in DD-MM format?
  utter_ask_horoscope_sign:
  - text: What is your horoscope sign?
  utter_greet:
  - text: Hello! How are you doing today?
  utter_subscribe:
  - text: Do you want to subscribe for daily updates?

```
