### ISSUE TITLE
Request URL Your URL didn't respond with the value of the challenge parameter.

### ISSUE THREAD

**Issue by tiwo19** [RasaHQ/rasa#3690]
**Rasa version**:
rasa-core                          0.14.4
rasa-core-sdk                      0.14.0
rasa-nlu                           0.15.0

**Python version**:
python 3.7

**Operating system** (windows, osx, ...):
windows10
**Issue**:
When i try to integrate my rasa bot to slack , I try to do Event Subscriptions  it does not work.
so i try to view the log using  heroku logs --tail
i get this message. Any help?

**Error (including full traceback)**:
```
019-06-04T00:11:49.465060+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/webhooks/slack/webhook" host=jabu1234.herokuapp.com request_id=a66010d7-1918-4c52-aad9-e72bee75d540 fwd="34.204.52.96" dyno= connect= service= status=503 bytes= protocol=https
```

**Command or request that led to error**:
```
when i try to enable event in slack api it give me this error

Request URL Your URL didn't respond with the value of the challenge parameter.
https://jabu1234.herokuapp.com/webhooks/slack/webhook
        

```

**Content of configuration file (config.yml)** (if relevant):
```language: "en"

pipeline: "tensorflow_embedding"
training_data,
            augmentation_factor=50,
            epochs=500,
            batch_size=10,
            validation_split=0.2

```

**Content of domain file (domain.yml)** (if relevant):
```yml
slots:
  group:
    type: text

intents:
 - greeting
 - get_jabu
 


entities:
 - product
 - jabuinfo

templates:
  utter_greet:
    - "Hello! What can I do for you?"
  utter_JABU:
   - "The Joseph Ayo Babalola University (JABU) is a private Nigerian university located in Ikeji-Arakeji in Osun State, established by the Christ Apostolic Church (CAC) Worldwide. The university is named after the first Spiritual leader of Christ Apostolic Church, Joseph Ayo Babalola (1904–1959); it is located at the place where he was called by God to slay the Ogobungo ogre in 1928. Joseph Ayo Babalola University is a fully residential institution. The university offers courses in the following colleges; Agricultural Sciences, Environmental Sciences, Humanities, Law, Management Sciences, Natural Sciences and Social Sciences. Due to its Christian foundations, male and female in the school are enjoined to adopt an extremely modest mode of dressing while on campus"
actions:
 - utter_greet
 - utter_JABU


```
![Capture](https://user-images.githubusercontent.com/30261634/58842582-d92e7f00-8666-11e9-94ae-8e1c7b66c551.PNG)
Screen shot of my log 
![g](https://user-images.githubusercontent.com/30261634/58842517-979dd400-8666-11e9-8d37-f62da1f820bf.PNG)
Screenshot of my slack event sub
