### ISSUE TITLE
Unable to `/restart` Rasa X UI conversations when trained with EmbeddingPolicy

### ISSUE THREAD

**Issue by psds01** [RasaHQ/rasa#3720]
**Rasa version**:1.0.1

**Rasa X version** (if used & relevant):

**Python version**: Python 3.6.8 |Anaconda

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
When I train the core+nlu with `rasa train` and start rasa X with `rasa x`. I am unable to restart the conversation with `/restart`. The error message says : 
```rasa.core.featurizers  - Feature 'intent_restart' could not be found in feature map```

**Error (including full traceback)**:
```
 WARNING  rasa.core.featurizers  - Feature 'intent_restart' could not be found in feature map.
```
Followed by : 
```
rasa.core.processor  - Circuit breaker tripped. Stopped predicting more actions for sender 'me'
```

**Command or request that led to error**:
Playing with Rasa X UI. 
If I input `/restart`, the default `action_restart` is not invoked.

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: EmbeddingPolicy
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment]
Hm, this wouldn't really be `EmbeddingPolicy` specific. Can you please fill out the issue template?

**Comment by psds01** [comment]
@akelad updated. Any help will be appreciated.

**Comment by akelad** [comment]
what's in your domain file?

**Comment by psds01** [comment]
Essentially this : 
```yml
slots
  a
  type: text
  b
  type : text

entities:
 - a
 - b

intents:
 - p
 - q

actions:
 - r
 - s
```
