### ISSUE TITLE
Template could not be saved since domain id is None.

### ISSUE THREAD

**Issue by ddombrowsky** [RasaHQ/rasa#3723]
**Rasa version**:

rasa --version
Rasa 1.0.0
 (from docker)

**Rasa X version** (if used & relevant):

Installed `rasa/rasa-x:stable` from docker.

**Python version**:

python3 --version
Python 3.6.8

**Operating system** (windows, osx, ...):

linux 64 bit
Linux 154c7240445c 4.4.0-1083-aws #93-Ubuntu SMP Wed May 8 16:08:41 UTC 2019 x86_64 GNU/Linux

**Issue**:

1. Open web UI
2. Go to "responses"
3. enter something

ERROR: in the logs ->
```
rasa-x_1           | Template could not be saved since domain id is None.
```
And nothing is saved.

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline: supervised_embeddings 
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

```
