### ISSUE TITLE
Lookup tables

### ISSUE THREAD

**Issue by ice2tricky** [RasaHQ/rasa#3734]
**Rasa version**:
v1.06
**Rasa X version** (if used & relevant):

**Python version**:
3.7.3
**Operating system** (windows, osx, ...):
Windows
**Issue**:

Lookup tables don't work with big entities. Only when my training examples are simple, it will recognize the simple entities. I don't want to overfit my model with 500 times the same sentence but with a different entity. So I'm guessing that the lookup tables don't match exacts, what I need in my case

This is my intent.
 
## intent:asset_exist
- Is [Akira](asset_name) an asset?
- Does [MPI Subnational New](asset_name) exists?
- Is this [Particle Board](asset_name) an asset?
- can you confirm [mpi_subnational_old.csv > Sub-national region](asset_name) is an asset?
- Is there an asset called [Outlook Freestanding Table level 1](asset_name)?
- Can you check if [TS 200 Series Laterals](asset_name) is an asset?
- Can you find this [asset_name](asset_name) asset?

my assets file
[assets.txt](https://github.com/RasaHQ/rasa/files/3266068/assets.txt)

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline: supervised_embeddings
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: FormPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
