### ISSUE TITLE
Datepicker template gives error

### ISSUE THREAD

**Issue by agrawal-mohit** [RasaHQ/rasa#3745]
Rasa 1.0.2
Using the custom datepicker component like this :

```
utter_ql:
  - custom:
      blocks:
      - type: section
        text:
          text: 'Can you tell me the start date and end date?'
          type: mrkdwn
        accessory:
          type: datepicker
          initial_date: '2019-05-21'
          placeholder:
            type: plain_text
            text: Select a date
```

I get this error :

![Screenshot 2019-06-09 at 8 51 06 PM](https://user-images.githubusercontent.com/1859165/59185112-42455380-8b8d-11e9-8195-37e88f9323f0.png)

How do i make this work? 

Thanks!
