### ISSUE TITLE
Unicode Encode Error When Training

### ISSUE THREAD

**Issue by TestCandidate** [RasaHQ/rasa#3747]
When I try to train arabic text with entities, I get the following error:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-5: ordinal not in range(128)

**Using version 1.0.6**

**My data file:** 
`{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "مرحبا",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "صباح الخير",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "مساء الخير",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "سيدى العزيز",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "ابحث عن مطعم مكسيكي في الشمال",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 13,
            "end": 19,
            "value": "مكسيكي",
            "entity": "مطبخ"
          },
		  {
            "start": 23,
            "end": 29,
            "value": "الشمال",
            "entity": "موقع"
          }
        ]
      }
    ]
  }
}`

**My config.yml file:**
```
language: ar
pipeline: supervised_embeddings

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```
