### ISSUE TITLE
image tag is not working  properly in domain file

### ISSUE THREAD

**Issue by sushilr007** [RasaHQ/rasa#3755]
**rasa-core**:                          0.14.5
**rasa-core-sdk**:                      0.14.0
**rasa-nlu**:                           0.15.1

**Python version**:

**Operating system** (windows, osx, ...): win 10

**Issue**:  It is giving me output as URL only in postman and on my website not showing image
**Output:** ```
[
    {
        "recipient_id": "385",
        "text": "Image here:"
    },
    {
        "image": "https://i.imgur.com/nGF1K8f.jpg",
        "recipient_id": "385"
    }
]```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "en"

pipeline: supervised_embeddings

```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
- visiting_card
actions:
 - utter_visiting_card

  utter_visiting_card:
  - text: "Image here:"
    image:  "https://i.imgur.com/nGF1K8f.jpg"
```
