### ISSUE TITLE
triggers keyword lost in IL domain export

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3766]
before IL: 
```
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great:
      use_entities: false
  - mood_unhappy
  - random:
      triggers: utter_random
```

after IL:
```
intents:
- greet
- random
- affirm
- mood_unhappy
- goodbye
- deny
- mood_great:
    use_entities: false
```
