### ISSUE TITLE
Rasa X Docker Domain Templates

### ISSUE THREAD

**Issue by nkane2898** [RasaHQ/rasa#3798]
**Rasa version**:

1.1.1

**Rasa X version** (if used & relevant):

0.19.1

**Python version**:

3.6.8

**Operating system** (windows, osx, ...):

Ubuntu 18.04.2 running docker 18.09.6, build 481bc77

**Issue**:

When trying to save the domain.yml file to my rasa x server deployment after following the Quick Installation section of this guide http://rasa.com/docs/rasa-x/deploy/, the templates section will not save. I am trying to save it using Rasa X UI. The same domain file works when I  run rasa x locally on my computer.

**Error (including full traceback)**:
```
No error but the save and discard are greyed out and I see a caution icon when I hover over them until I refresh the page.
```

**Command or request that led to error**:
```
Paste contents of domain.yml into the Training > Domain section of the Rasa X UI and hit Save changes.
```

**Content of configuration file (config.yml)** (if relevant):
```yml

pipeline: supervised_embeddings
language: en
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.4
  core_threshold: 0.45
  fallback_action_name: action_default_fallback

```

**Content of domain file (domain.yml)** (if relevant):
```yml

intents:
  - affirm
  - associative_symptoms
  - deny
  - general_fever
  - goodbye
  - greet
  - mood_great
  - mood_unhappy
  - number_of_bananas
  - onset
  - palliative
  - provoke
  - quality
  - radiate
  - ros_abdominal_appetite_changes
  - ros_abdominal_belching
  - ros_abdominal_bloating
  - ros_abdominal_bowel_habits_general
  - ros_abdominal_defecation_pain
  - ros_abdominal_dysphagia
  - ros_abdominal_emesis
  - ros_abdominal_heartburn
  - ros_abdominal_hematochezia
  - ros_abdominal_melena
  - ros_abdominal_nausea
  - ros_abdominal_odynophagia
  - ros_abdominal_pain
  - ros_abdominal_stool_caliber_changes
  - ros_abdominal_stool_color_changes
  - ros_abdominal_stool_size_changes
  - ros_breast_discomfort
  - ros_breast_lumps
  - ros_breast_nipple_discharge
  - ros_breast_pain
  - ros_cardiac_chest_discomfort
  - ros_cardiac_chest_pain
  - ros_cardiac_chest_pressure
  - ros_cardiac_orthopnea
  - ros_cardiac_palpitations
  - ros_ears_discharge
  - ros_ears_discharge_color
  - ros_ears_earaches
  - ros_ears_earaches_specific
  - ros_ears_hearing_changes
  - ros_ears_tinnitus
  - ros_ears_vertigo
  - ros_eyes_contacts
  - ros_eyes_discharge
  - ros_eyes_flashing_lights
  - ros_eyes_glasses
  - ros_eyes_pain
  - ros_eyes_redness
  - ros_eyes_specks
  - ros_eyes_spots
  - ros_eyes_vision_changes
  - ros_general_chills
  - ros_general_fatigue
  - ros_general_night_sweats
  - ros_general_unintentional_wt_gain
  - ros_general_unintentional_wt_loss
  - ros_head
  - ros_lymph_enlargement
  - ros_lymph_tenderness
  - ros_neck_lumps
  - ros_neck_pain
  - ros_neck_stiffness
  - ros_nose_discharge
  - ros_nose_discharge_color
  - ros_nose_epistaxis
  - ros_nose_sense_of_smell
  - ros_nose_sinus_pressure
  - ros_nose_stuffiness
  - ros_peripheral_vascular_arm edema
  - ros_peripheral_vascular_claudication
  - ros_peripheral_vascular_feet_edema
  - ros_peripheral_vascular_fingers_color_change
  - ros_peripheral_vascular_leg edema
  - ros_peripheral_vascular_toes_color_change
  - ros_peripheral_vascular_vericose_veins
  - ros_pulmonary_cough
  - ros_pulmonary_cough-productive
  - ros_pulmonary_cough-productive_color
  - ros_pulmonary_hemoptysis
  - ros_pulmonary_hemoptysis_amount
  - ros_pulmonary_pleuritic_pain
  - ros_pulmonary_sob
  - ros_pulmonary_wheezing
  - ros_pulmonary_wheezing_trigger
  - ros_skin_Itching
  - ros_skin_bruises
  - ros_skin_dryness
  - ros_skin_hair_changes
  - ros_skin_lump
  - ros_skin_moles_changes
  - ros_skin_moles_color_changes
  - ros_skin_nails_changes
  - ros_skin_rashes
  - ros_skin_sores
  - ros_throat_dental_exam_last
  - ros_throat_dry_mouth
  - ros_throat_hoarseness
  - ros_throat_soreness
  - ros_throat_teeth_condition
  - severity
  - timing
  - verify_age
  - verify_allergies_environment
  - verify_allergies_food
  - verify_allergies_med
  - verify_brother_age
  - verify_brother_gen
  - verify_cc
  - verify_childhood_illness
  - verify_chronic_conditions
  - verify_comfortable
  - verify_dob
  - verify_famhx_brother_deceased_age
  - verify_famhx_dad_age
  - verify_famhx_dad_alive
  - verify_famhx_dad_deceased_age
  - verify_famhx_dad_gen
  - verify_famhx_mom_age
  - verify_famhx_mom_alive
  - verify_famhx_mom_deceased_age
  - verify_famhx_mom_gen
  - verify_famhx_permission
  - verify_famhx_sister_deceased
  - verify_gender_born
  - verify_gender_current
  - verify_hospitalizations
  - verify_hospitalizations_los
  - verify_hospitalizations_reason
  - verify_hospitalizations_time_since
  - verify_injury
  - verify_medications_dose
  - verify_medications_form
  - verify_medications_frequency
  - verify_medications_otc
  - verify_medications_prescribed
  - verify_medications_purpose
  - verify_medications_route
  - verify_medications_supplements
  - verify_name
  - verify_preferred_pronoun
  - verify_safety_car
  - verify_safety_sun_eyes
  - verify_safety_sun_skin
  - verify_sexual_preference
  - verify_sexual_protection
  - verify_siblings
  - verify_sister_age
  - verify_sister_gen
  - verify_soc_caffeine
  - verify_soc_caffeine_amount
  - verify_soc_diet
  - verify_soc_drug_length
  - verify_soc_drug_needle
  - verify_soc_drug_needle_clean
  - verify_soc_drug_smoke
  - verify_soc_drug_snort
  - verify_soc_drugs_type
  - verify_soc_drugs_verify
  - verify_soc_edu
  - verify_soc_etoh_quantity
  - verify_soc_etoh_type
  - verify_soc_etoh_verify
  - verify_soc_exercise
  - verify_soc_fun
  - verify_soc_home
  - verify_soc_home_safe
  - verify_soc_insurance
  - verify_soc_job
  - verify_soc_sleep
  - verify_soc_support
  - verify_soc_tobacco
  - verify_soc_tobacco_chew
  - verify_soc_tobacco_length
  - verify_soc_tobacco_smoke
  - verify_soc_tobacco_smoke_ppd
  - verify_soc_travel
  - verify_soc_travel_location
  - verify_soc_travel_time
  - verify_surgeries
  - verify_vaccines_specific_flu
  - verify_vaccines_specific_tetanus
  - verify_vaccines_up_to_date
  - verify_verify_okay_to_start
templates:
  utter_greet:
    - text: Hey! How are you?
  utter_happy:
    - text: Great carry on!
  utter_goodbye:
    - text: Bye
  utter_age:
    - text: '29'
  utter_be_name:
    - text: Kyle Wodak
  utter_be_cc:
    - text: I can't breathe and I feel really sick
  utter_be_dob:
    - text: 1/16/1990
  utter_be_comfortable:
    - text: 'I''m okay where I am I guess, but Iv''e been better'
  utter_be_onset:
    - text: About 2 days ago
  utter_be_palliating:
    - text: >-
        When I sit down and take a break I guess, but it seems to be getting
        worse
  utter_be_prov:
    - text: >-
        Seems everyday it gets worse. Just moving around in general just makes
        me exhausted and I can't breathe
  utter_absolute_yes:
    - text: Absolutely
    - text: 'Oh yes, definitely'
    - text: Yes!
  utter_be_quality:
    - text: I don't really know how to answer that. I feel like I am going to die
  utter_be_severity:
    - text: >-
        Bad enough that I had to call of work today and I can barely go about a
        normal day at the house
  utter_be_timing:
    - text: >-
        Keeps getting worse, but more so when I was lifting things at work or
        walking up and down the stairs
  utter_be_asocsym:
    - text: 'Yeah. I have noticed some Fever, Night sweats, and headache'
  utter_be_meds:
    - text: I'm not taking any
  utter_be_pmhhosp:
    - text: 'Yeah, I sprained my ankle like 10 years ago playing basketball'
  utter_be_immunizations:
    - text: I think I'm up to day with everything. Work makes me get all the shots
  utter_be_famhxgen:
    - text: Yes what about them?
  utter_be_fammomge:
    - text: Shes 65
  utter_be_famhhmother:
    - text: >-
        She smokes a lot. Im not sure what health problems she has, but I know
        she takes meds for depression
  utter_be_famhxdadgen:
    - text: I don't know my dad. He left me when I was little...
  utter_be_brothergen:
    - text: >-
        My little brother is the man. I don't think he has any medical problems
        besides being a knuckle head
  utter_be_socjob:
    - text: I work with my bud who does contracting for drywalling houses
  utter_be_socedu:
    - text: I finished High School and didn't have the money for college
  utter_be_sochomesafe:
    - text: Yeah home is safe
  utter_be_sochome:
    - text: >-
        I live with my mom. They want me to move out, but I have no where to go
        right now
  utter_be_socsup:
    - text: >-
        Other than my parents not really. My friends would help me out, but are
        not too reliable
  utter_be_socdiet:
    - text: >-
        My moms boyfriend cooks pretty good. I think I eat healthy. Lots of
        chicken, steak, and veggies
  utter_be_socexercise:
    - text: >-
        I workout sometimes. I used to all the time when I played sports in
        school, but not much int he past 10 years
  utter_be_socfun:
    - text: 'I like to hangout with my friends, watch basketball, and just chill'
  utter_be_socetoh:
    - text: I'm not much of a drinker. Every now and then I have like a beer
  utter_be_soctobac:
    - text: 'Yeah, I smoke a pack a day'
  utter_be_soctoblength:
    - text: Probably like 10 years now. I started in High School
  utter_be_socdrugsnervous:
    - text: Uhmmm.. No...... If I tell you will I get in trouble?
  utter_be_soocdrugsopen:
    - text: I mess around with some stuff with my buds
  utter_be_socdrugswhat:
    - text: I have been using heroin
  utter_be_socdruglength:
    - text: >-
        For the past 4 months, but that can't be it because this just started
        two days ago
  utter_be_socdrugneedle:
    - text: I only share with my friends
  utter_be_socdrugother:
    - text: 'Just marijuana a couple times a week, but that''s all'
  utter_be_soccaf:
    - text: Monster every now and then to help me stay awake when I work
  utter_be_soctrav:
    - text: Nah. My family is pretty poor we don't have money to travel
  utter_be_socsleep:
    - text: I sleep in most days. Maybe like 10-11 hours a night
  utter_be_safety:
    - text: I wear a seat belt
  utter_be_sexual:
    - text: >-
        I've been with a couple chicks at my friends house. They were from out
        of town, so I don't know much about them
  utter_be_gendercurrent:
    - text: I am a male
  utter_be_genderborn:
    - text: I was born a male
  utter_be_preferredpronoun:
    - text: 'I go by he, him, his'
  utter_general_no:
    - text: 'No'
    - text: Nope
    - text: Nah
  utter_absolute_no:
    - text: Absolutely not
    - text: 'Oh no, definitely not'
    - text: 'No'
  utter_general_unsure:
    - text: I'm not sure
    - text: I haven't really noticed
  utter_general_thinking:
    - text: Uhmm
    - text: Uhhh...
    - text: Let me think
  utter_general_yes:
    - text: 'Yes'
    - text: Yup
    - text: Yeah
  utter_default:
    - text: I'm having trouble understanding what you are saying
    - text: Can you repeat that question differently?
    - text: I'm not sure what you are asking
actions:
  - action_random_banana
  - utter_absolute_no
  - utter_absolute_yes
  - utter_age
  - utter_be_asocsym
  - utter_be_brothergen
  - utter_be_cc
  - utter_be_comfortable
  - utter_be_dob
  - utter_be_famhxdadgen
  - utter_be_famhxgen
  - utter_be_fammomge
  - utter_be_genderborn
  - utter_be_gendercurrent
  - utter_be_immunizations
  - utter_be_meds
  - utter_be_name
  - utter_be_onset
  - utter_be_palliating
  - utter_be_preferredpronoun
  - utter_be_prov
  - utter_be_quality
  - utter_be_safety
  - utter_be_severity
  - utter_be_sexual
  - utter_be_soccaf
  - utter_be_socdiet
  - utter_be_socdrugneedle
  - utter_be_socdrugother
  - utter_be_socdrugsnervous
  - utter_be_socdrugswhat
  - utter_be_socedu
  - utter_be_socetoh
  - utter_be_socexercise
  - utter_be_socfun
  - utter_be_sochome
  - utter_be_sochomesafe
  - utter_be_socjob
  - utter_be_socsleep
  - utter_be_socsup
  - utter_be_soctobac
  - utter_be_soctoblength
  - utter_be_soctrav
  - utter_be_timing
  - utter_default
  - utter_general_no
  - utter_general_thinking
  - utter_general_unsure
  - utter_general_yes
  - utter_goodbye
  - utter_greet
  - utter_happy

```
