### ISSUE TITLE
Socket channel does not return json messages

### ISSUE THREAD

**Issue by Elysium13** [RasaHQ/rasa#3823]
**Rasa version**: 1.1.3

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): WSL Ubuntu 16.04

**Issue**: Attempting to send custom json response over socket channel returns null instead.

**Steps to recreate**: 
1. Initialize a new rasa project.
2. Update the templates in domain with custom json.
3. Update the credentials file allowing socket channel.
4. Send message 'hi' over socket connection. (I'm using [Rasa-Webchat](https://github.com/mrbot-ai/rasa-webchat) as the interface

**Content of credentials file (credentials.yml)**:
```yml
# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/

rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials


#facebook:
#  verify: "<verify>"
#  secret: "<your secret>"
#  page-access-token: "<your page access token>"

#slack:
#  slack_token: "<your slack token>"
#  slack_channel: "<the slack channel>"

socketio:
 user_message_evt: user_uttered
 bot_message_evt: bot_uttered
 session_persistence: false

rasa:
  url: "http://localhost:5002/api"

```

**Content of domain file (domain.yml)**:
```yml
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - custom:
      text: "Hey! How are you?"
      something: "wrong"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"

```

The above configuration runs successfully under rasa shell
![alt text](https://i.ibb.co/Gvc4KHT/rasa-shell.jpg "Rasa Shell Success")

**Comment by erohmensing** [comment]
> returns null instead.

what do you mean by returns null?

The point of custom json payloads is to be able to send json API calls to your output channel, so it's channel specific. Therefore your json payload has to be in a format that socket will accept. In the case of socketio, it sends your paylod to the [emit function](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/asyncio_server.py#L78) of the async socketIO server. If your parameters don't match up to what socket is expecting, it probably won't take the request. 

What are you trying to achieve with your custom json?

**Comment by CathyWang53** [comment]
Hi, I met a similar problem to you. 
I am trying to use HTTP API with Java language from my computer to call my Rasa server. However, for the GET request, it seems to work well, **but for the POST request, rasa response with nothing**. 
I also used the rasa initial project. I am pretty sure that my JSON is in the correct format and URL is also correct. 
Waiting for a solution...

**Comment by erohmensing** [comment]
Hi @CathyWang53, that is a very different issue from this one about the socket connector. Please create a post on our [forum](forum.rasa.com) about your question.

**Comment by Elysium13** [comment]
Hi @erohmensing ,
Thanks for your response.

By seeing the image attached for the shell output in the OP. Could you point out what is wrong with json being returned. 

Correct me if I am wrong. My understanding for a custom json response for a socket connection is that I can send any data as long as it is in proper json format and it is upto the chat interface on the frontend to handle how to interpret that data. 

To add more perspective, let's take an utter_ask template requesting a specific type of data. The custom json could contain something like:
```json
{
    "input_type": "date",
    "text": "For which date?"
}
```
The chat interface on the front would be responsible for deciding what to do with the data other than default text. 

Hope that clarifies my use case.

**Comment by Elysium13** [comment]
I also went ahead and did a bit of debugging on my own.

Reference: [/rasa/core/channels/socketio.py line 99](https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/socketio.py)

I can confirm that the socketio channel method for custom json contains my intended output in ```json_message``` however the AsyncServer emit does not receive any data.

However, changing :
```python
 await self.sio.emit(self.bot_message_evt, **json_message)
```
 to
```python
 await self.sio.emit(self.bot_message_evt, json_message)
```
solves the issue for me.

I'm not aware of what  ```**json_message``` achieves.

Hope that helps.

**Comment by Elysium13** [comment]
I did a bit of debugging on my own and following are my findings:

1. The json output as shown in the shell response is available under ```json_message``` for rasa's socketio channel method for sending custom json. Reference: [socketio.py line-92](https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/socketio.py)
2. This however does not get transferred to asyncio server's emit method. Reference: [asyncio_server.py line-78](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/asyncio_server.py#L78)
3. Inferring from the above 2 methods - asyncio expects a keyword ```data``` for emitting response, which does not exist. Hence, I updated the domain template to:
```yml
templates:
  utter_greet:
  - custom:
      data:
        text: "Hey! How are you?"
        something: "wrong"
```
This now correctly populates in response.

**Conclusion**: The custom template should be enclosed under the key ```data``` for custom json response.

Having an example for the same would have been helpful. Personally I feel the ```data``` key is redundant for a custom json output in socket channel and could have been abstracted from the user.

Please feel free to close this issue.
