### ISSUE TITLE
Rasa X not loading conversations

### ISSUE THREAD

**Issue by tpacker** [RasaHQ/rasa#3839]
**Rasa version**:  Rasa 1.0.7

**Rasa X version** (if used & relevant):  0.19.0

**Python version**:  3.7.3

**Operating system** (windows, osx, ...):  Windows 10 Enterprise

**Issue**:  

I have a recently installed rasa 1.0.  It has the "cheer-up" demo bot with very little modification except that I used Rasa X to add a couple more stories for training.  When I start Rasa X and switch to Conversations, it hangs with a message "loading messages" and "0 conversations".  

I have looked at this issue:  https://github.com/RasaHQ/rasa/issues/3663

I don't have anything in my endpoints, but running Rasa X the first time, it did create rasa.db and tracker.db files.  

Also, what is the correct way to terminate `rasa run` or `rasa x`?  When I do Ctrl+X in the Command Prompt on windows, it hangs and will not close.  

Also, are these the most recent versions of Rasa components?  I have tried upgrading using `pip install rasa-x --extra-index-url https://pypi.rasa.com/simple` and a few other ways, but it always says it is up to date.  

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```
rasa x
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```
