### ISSUE TITLE
domain entity featurization dump format

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3842]
Reading a domain with
```
intents:
  - intent1:
    use_entities: False
```

currently leads to a dump format (if domain is persisted) which is a bit confusing

```
intents:
- intent1:
  use_entities: []
  ignore_entities: []
```

Ric also said:
> I'm not sure because in the docs and examples we give use_entities: None or use_entities: False. So I think to preserve that syntax we should dump use_entities: False in the case of an empty list. but that too is a rasa code change

We should check if we adapt the docs / code.
