### ISSUE TITLE
Rasa X: Annotate - Correct intent: intents missing from dropdown

### ISSUE THREAD

**Issue by snbuchholz** [RasaHQ/rasa#3845]
**Rasa version**: 1.1.3

**Rasa X version** (if used & relevant): 0.19.2

**Python version**: 3.6.0

**Operating system** (windows, osx, ...): macOS

**Issue**:

It seems that the "Correct intent" dropdown in Rasa X's "Talk to your bot" and "Conversations" tab is not populated from domain.yml but from the conversations in Rasa X so far. I noticed this with the conversations migrated from my tracker store but then managed to reproduce the problem with the example bot that comes with Rasa.
I created the example bot with "rasa init" and started "rasa x", went to the "Talk to your bot" tab and started a conversation. After my second utterance, I selected that utterance and checked the content of the "Correct intent" dropdown:
<img width="1428" alt="rasa example1" src="https://user-images.githubusercontent.com/2370438/59920812-aa185b80-9423-11e9-86dd-4349f455bc40.png">

It only showed "mood_unhappy" and "greet", the two intents used in the conversation so far. 
I continued the conversation and later there were four intents in the dropdown:
<img width="1428" alt="rasa example3" src="https://user-images.githubusercontent.com/2370438/59920836-ba303b00-9423-11e9-8a85-913dd21dea25.png">

At some point I also reloaded the page. The conversation was still there but the "Correct intent" dropdown was now completely empty:
<img width="1426" alt="rasa example2" src="https://user-images.githubusercontent.com/2370438/59920867-cddba180-9423-11e9-98d7-12ecaadae52e.png">

PS: I also see the issue described in https://github.com/RasaHQ/rasa/issues/3839

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```
rasa x
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
- affirm
- deny
- goodbye
- greet
- mood_great
- mood_unhappy
templates:
  utter_greet:
  - text: Hey! How are you?
  utter_cheer_up:
  - text: 'Here is something to cheer you up:'
    image: https://i.imgur.com/nGF1K8f.jpg
  utter_did_that_help:
  - text: Did that help you?
  utter_happy:
  - text: Great carry on!
  utter_goodbye:
  - text: Bye
actions:
- utter_cheer_up
- utter_did_that_help
- utter_goodbye
- utter_greet
- utter_happy
```
