### ISSUE TITLE
RASA shell stuck on incoming quick reply

### ISSUE THREAD

**Issue by cowjen01** [RasaHQ/rasa#3856]
**Rasa version**:
Rasa 1.1.3
**Python version**:
Python 3.7.3
**Operating system** (windows, osx, ...):
osx Mojave
**Issue**:
I use external NLG app to generate response based on tracker store data. On greeting intent I return quick replies buttons in http response. After that RASA shell stuck and stopped responding.

I suggest to create same functionality both for quick replies and classic buttons so we could test the components locally without starting API server. I found a possible place for fix on [this line](https://github.com/RasaHQ/rasa/blob/ad66510dbebf7888602a87f2be2428b7090ae878/rasa/core/channels/console.py#L52).

**Command or request that led to error**:
NLG server log:
```
[NLGController] debug: Incoming message from RASA.
[RedisController] debug: Updating a collection "USER_default".
[NLGController] debug: {"text":"Hello, I'm chatbot 🙂 How are you?","quick_replies":[{"title":"Great","payload":"/onboardingStep1"},{"title":"Fine","payload":"/onboardingStep1"},{"title":"Awesome","payload":"/onboardingStep1"}]}
```
Terminal log:
```
➜  rasa-chatbot git:(master) rasa shell
2019-06-24 11:35:58 INFO     root  - Starting Rasa Core server on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit):
Your input ->  hello
```
... now stuck and waiting.
**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline: supervised_embeddings
policies:
  - name: MemoizationPolicy
    max_history: 1
  - name: KerasPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - greeting: {
    triggers: utter_onboarding_greeting
  }
  - onboardingStep1: {
    triggers: utter_onboarding_step_1
  }

actions:
- utter_onboarding_greeting
- utter_onboarding_step_1

slots:
  answer:
    type: unfeaturized
    initial_value: "yes"
```
