### ISSUE TITLE
NameError: Cannot access action 'utter_default', as that name is not a registered action for this domain.

### ISSUE THREAD

**Issue by adu013** [RasaHQ/rasa#3858]
I've followed tutorial http://www.rasa.com/docs/rasa/user-guide/rasa-tutorial/

Issue:

```
NameError: Cannot access action 'utter_default', as that name is not a registered action for this domain. Available actions are: 
	 - action_listen
	 - action_restart
	 - action_default_fallback
	 - action_deactivate_form
	 - action_revert_fallback_events
	 - action_default_ask_affirmation
	 - action_default_ask_rephrase
	 - action_back
	 - utter_cheer_up
	 - utter_did_that_help
	 - utter_goodbye
	 - utter_greet
	 - utter_happy
```
domain.yml

```
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```
