### ISSUE TITLE
Custom tracker store not found

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#3867]
**Rasa version**: 1.1.3

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Docker on OSX

**Issue**:

I and another user cannot get custom tracker store working as reported on the forum [here](https://forum.rasa.com/t/tracker-store-not-found/11408). My custom tracker has been working fine in prior versions of Rasa but not under 1.0.

**Error (including full traceback)**:
```
WARNING  rasa.core.tracker_store  - Store type 'f.Ff' not found. Using InMemoryTrackerStore instead
```

**Command or request that led to error**:
```
asa run --enable-api --model /app/data/models --endpoints /app/data/endpoints_local.yml --credentials /app/data/credentials.yml --port 5005 --log-file /app/data/logs/rasa_core.log --debug
```

**Content of configuration file (endpoints.yml)** (if relevant):

```yml
action_endpoint:
  url: "http://action:5055/webhook"
tracker_store:
    store_type: trackerArango.ArangoTrackerStore
    db: kyc-chatbot
    url: http://arango:8529
nlu:
  url: http://nlu:5000
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "en"

pipeline: supervised_embeddings
policies:
  - name: KerasPolicy
    epochs: 200
    max_history: 1
  - name: MemoizationPolicy
    max_history: 1
  - name: FallbackPolicy
    nlu_threshold: 0.59
  - name: FormPolicy
```

**Comment by wochinge** [comment]
Thanks for raising this issue, @samwill get back to you about it soon.

**Comment by akelad** [comment]
Not sure who you meant to tag there tobias :D 
@rgstephens is it possible this issue is related to your problem? https://github.com/RasaHQ/rasa/issues/3748

**Comment by wochinge** [comment]
Updated it :-D

**Comment by rgstephens** [comment]
I reviewed #3748. Maybe it's possible that PYTHONPATH now needs to be set in for 1.0 that was not a requirement before?  I will give this a try.

**Comment by akelad** [comment]
yeah your assumption is correct there, we're looking into avoiding having to set the PYTHONPATH. 

Do you have an __init__.py in your directory?

**Comment by rgstephens** [comment]
No, it's worked before with no `__init__.py`.  Tried adding one and it made no difference.

We have two of us that can't get this to work.  @thom in the [post](https://forum.rasa.com/t/tracker-store-not-found/11408) had a nice short example. Can we get a 3rd person to try this out real quick?

```yml
tracker_store:
  store_type: f.Ff
  url: localhost
```

f.py:
```
from rasa.core.tracker_store import TrackerStore

class Ff(TrackerStore):

def __init__(self, url, domain):
    print("OUI")
```
