### ISSUE TITLE
Rasa X UI problems

### ISSUE THREAD

**Issue by TatianaParshina** [RasaHQ/rasa#3879]
**Rasa version**:
rasa==1.1.4

**Rasa X version** (if used & relevant):
rasa-x==0.19.2

**Python version**:
Python 3.6.8

**Operating system** (windows, osx, ...):
Windows 8

**Issue**:
Rasa X UI doesn't display response if it has more then 2 lines in the Google Chrome browser using Talk Mode

 
![rasa_x_ui](https://user-images.githubusercontent.com/42603622/60206946-798a5480-985d-11e9-8ad2-5861a611da05.png)

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline: supervised_embeddings

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.5
    core_threshold: 0.5
    fallback_core_action_name: "action_default_fallback"
    fallback_nlu_action_name: "action_default_fallback"
    deny_suggestion_intent_name: "out_of_scope"  
```
