### ISSUE TITLE
Using using pyMongo srv tracker with latest Rasa docker image

### ISSUE THREAD

**Issue by argideritzalpea** [RasaHQ/rasa#3971]
Using latest rasa/rasa:latest-full docker image and getting the following error. Shouldn't the dnspython module come standard in the docker image? Or is this due to something else?:
```rasa_1           | 2019-07-10 04:06:20 INFO     root  - Starting Rasa Core server on http://localhost:5200
rasa_1           | 2019-07-10 04:06:20.650678: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
rasa_1           | 2019-07-10 04:06:21.221940: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
rasa_1           | 2019-07-10 04:06:21.277310: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x556f569865c0 executing computations on platform Host. Devices:
rasa_1           | 2019-07-10 04:06:21.277484: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
rasa_1           | [2019-07-10 04:06:22 +0000] [1] [ERROR] Experienced exception while trying to serve
rasa_1           | Traceback (most recent call last):
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
rasa_1           |     serve(**server_settings)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
rasa_1           |     trigger_events(before_start, loop)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
rasa_1           |     loop.run_until_complete(result)
rasa_1           |   File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 176, in load_agent_on_start
rasa_1           |     None, endpoints.tracker_store, _broker
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/tracker_store.py", line 38, in find_tracker_store
rasa_1           |     domain=domain, host=store.url, event_broker=event_broker, **store.kwargs
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/tracker_store.py", line 205, in __init__
rasa_1           |     connect=False,
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 524, in __init__
rasa_1           |     res = uri_parser.parse_uri(entity, port, warn=True)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/pymongo/uri_parser.py", line 318, in parse_uri
rasa_1           |     raise ConfigurationError('The "dnspython" module must be '
rasa_1           | pymongo.errors.ConfigurationError: The "dnspython" module must be installed to use mongodb+srv:// URIs
```
**Content of endpoints file (endpoints.yml)**
```
action_endpoint:
  url: "http://localhost:5200/webhooks/twilio/webhook"

  tracker_store:
    store_type: mongod
    url: mongodb+srv://(etc.etc.etc.)
    db: [REDACTED]
    username: [REDACTED]
    password: [REDACTED]
```

relevant part of Docker-compose.yml:
```
version: '3.0'
  
services:
  rasa:
    image: rasa/rasa:latest-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - ./:/app
            #- "./models:/app/models"
            #- "./data:/app/data"
      #- "./rasa:/usr/local/lib/python3.6/site-packages/rasa"
    command: run --enable-api --model models --p 5200 --connector twilio --credentials credentials.yml --endpoints endpoints-twilio.yml
```
