### ISSUE TITLE
Dialogue shows warning and freezes after adding the Duckling pipeline.

### ISSUE THREAD

**Issue by tushar-semwal** [RasaHQ/rasa#3996]
**Rasa version**: Rasa 1.1.5

**Rasa X version** (if used & relevant):

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): Ubuntu 18.04.2 LTS (Windows Subsystem for Linux)

**Issue**: After a `rasa init`, I just changed my config file and added the Duckling pipeline. Now when I run `rasa shell`, a warning message is popped and the dialogue freezes. Note: My Duckling server is running at 8000. I have already tested the Duckling part with my other chatbot and it works well.

**Error (including full traceback)**:
```
2019-07-12 11:33:28 INFO     root  - Starting Rasa Core server on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit):
Your input ->  hello
2019-07-12 11:33:31 WARNING  root  - Could not parse timestamp cd478070c50e4f499fe04697e3249982. Instead current UTC time will be passed to duckling. Error: invalid literal for int() with base 10: 'cd478070c50e4f499fe04697e3249982'
```

**Command or request that led to error**:
```
rasa shell
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: EmbeddingIntentClassifier
  epochs: 50
- name: DucklingHTTPExtractor
  url: http://0.0.0.0:8000
  dimensions:
  - time
  - number
- name: EntitySynonymMapper

policies:
- epochs: 50
  max_history: 6
  name: KerasPolicy
- max_history: 6
  name: AugmentedMemoizationPolicy
- core_threshold: 0.3
  name: TwoStageFallbackPolicy
  nlu_threshold: 0.8
- name: FormPolicy
- name: MappingPolicy


```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"

```
