### ISSUE TITLE
Template returns different slot values depending on required_slots order

### ISSUE THREAD

**Issue by IgNoRaNt23** [RasaHQ/rasa#3997]
**Rasa version**:
Rasa 1.1.5
**Python version**:
Python 3.6.8
**Operating system** (windows, osx, ...):
Ubuntu 18.04
**Issue**:
Similar to this issue 
https://github.com/RasaHQ/rasa/issues/2868

Encountered this bug and made a minimal example for convenience. I want to run a form and output the slot values at the end in the form's submit function. One of the slots is mapped from another entity (and processed in the real example). However, if the slot with the custom mapping is the last required slot the template returns None even though the slot is correctly set as you can see by the utter_message variant. This output is produced for example:

```
      Action: Slot A: apfel - Slot C: birne                                    
      Template:  Slot A: apfel - Slot C: None
```

However, when I change the order of requested slots in the requested_slot function, I get the expected output.
```
      Action: Slot A: apfel - Slot C: birne                                    
      Template:  Slot A: apfel - Slot C: birne
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy

```

**Content of domain file (domain.yml)** :
```yml
%YAML 1.1
---
actions:
- utter_slot_values
- utter_something
entities:
- slot_a
- slot_b
- slot_c
forms:
- bug_form
intents:
- answer_slot_a
- answer_slot_b
- show_bug
- kartoffel
slots:
  requested_slot:
    type: unfeaturized
  slot_a:
    type: text
  slot_c:
    type: text
templates:
  utter_ask_slot_a:
  - text: Enter a value for slot_a
  utter_ask_slot_c:
  - text: Enter a value for slot_c
  utter_slot_values:
  - text: 'Template:  Slot A: {slot_a} - Slot C: {slot_c}'
  utter_something:
  - text: Something
```
**Content of actions file (actions.py)** :
```py
# -*- coding: utf-8 -*-
from typing import Dict, Text, Any, List, Union

from rasa_sdk import Tracker
from rasa_sdk.forms import FormAction
from rasa_sdk.executor import CollectingDispatcher

class BugForm(FormAction):

    def name(self) -> Text:
        """Unique identifier of the form"""

        return "bug_form"

    @staticmethod
    def required_slots(tracker:Tracker) -> List[Text]:

        req_slots = ["slot_a","slot_c"] # gives None output for template
       #req_slots= ["slot_c","slot_a"] # gives expected output

        return req_slots

    def slot_mappings(self) -> Dict[Text, Union[Dict, List[Dict]]]:
       return {'slot_c': self.from_entity(entity="slot_b")} 

    def submit(self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict[Text, Any]) -> List[Dict]:
        """Define what the form has to do
            after all required slots are filled"""
        slot_list = []

        # utter submit template
        Slot_A = tracker.get_slot("slot_a")
        Slot_C = tracker.get_slot("slot_c")

        dispatcher.utter_message(f'Action: Slot A: {Slot_A} - Slot C: {Slot_C}')
        dispatcher.utter_template('utter_slot_values', tracker)

        return slot_list
```
