### ISSUE TITLE
rasa x removes "triggers" from intents in domain.yml

### ISSUE THREAD

**Issue by creadoit** [RasaHQ/rasa#4037]
Rasa version: 1.1.4

Rasa X version (docker): 0.19.5

Python version: Python 3.6.9

Operating system (windows, osx, ...): Linux/Docker

**Issue**:

Hi, working with Rasa X the intent "triggers" are removed in the `domain.yml`

**Content of domain file before opening/saving with rasa x**:

```yml
intents:
- affirm
- requirements:
    triggers: action_requirements
- requirements_age:
    triggers: action_apprenticeship_age
- start:
    triggers: action_start_date
```

**Content of domain file after opening/saving with rasa x**:

```yml
intents:
- affirm
- requirements
- requirements_age
- start
```

Even if I try to add the triggers back via the Rasa x UI, after saving all triggers are gone again.

Thanks for your help! :)
