### ISSUE TITLE
Cannot tun Custom actions while deploying with docker

### ISSUE THREAD

**Issue by talhashaikh5** [RasaHQ/rasa#4042]
## rasa.core.actions.action  - Failed to run custom action 'action_hello_world'. 
Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:None [Cannot assign requested address]

i am gaving above error while deploying my bot with docker. i coudnt understand what is happing please help me

## docker-compose.yml
```
version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run 
      - -m
      - models
      - --enable-api
      - --log-file
      - out.log
      - -p
      - '5005'
  action_server:
    image: rasa/rasa_core_sdk:latest
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
    command:
      - start
      - --actions
      - actions
```
![error1](https://user-images.githubusercontent.com/28058426/61477402-c8369480-a9ac-11e9-97cd-7a4a0b91c85f.png)

## actions.py
```
from typing import Any, Text, Dict, List

from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
import mysql.connector



class ActionHelloWorld(Action):

    def name(self) -> Text:
        return "action_hello_world"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:

        dispatcher.utter_message("Hello World!")

        return []

class ActionFetchSickLeaves(Action):

    def name(self) -> Text:
        return "action_fetch_sick"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        senderid = tracker.sender_id
        mydb = mysql.connector.connect(host="XXXX",user="XXXX",passwd="XXXX",database="XXXX")
        mycursor = mydb.cursor()
        mycursor.execute("SELECT sick FROM leaves where sender = {}".format(senderid))
        myresult = mycursor.fetchall()
        leaves = str(myresult[0][0])
        dispatcher.utter_message("Remaining Sick Leaves : {}".format(leaves))
        return []

```
