### ISSUE TITLE
In RegexFeaturizer the regex_string seems not suitable for chinese?

### ISSUE THREAD

**Issue by journey1986** [RasaHQ/rasa#4069]
**Rasa version**:
"1.1.2"
**Rasa X version** (if used & relevant):

**Python version**:
3.7.3
**Operating system** (windows, osx, ...):
windows
**Issue**:
In RegexFeaturizer the regex_string seems not suitable for chinese?

In the RegexFeaturizer

```python
 # regex matching elements with word boundaries on either side
        regex_string = "(?i)(\\b" + "\\b|\\b".join(elements_sanitized) + "\\b)"
        return regex_string
```

It seems the above code not suitable for chinese.
```python
# regex matching elements with word boundaries on either side
        regex_string = "(?i)(\\b" + "\\b|\\b".join(elements_sanitized) + "\\b)"
        if self.language == 'zh':
            regex_string = "(?i)(" + "|".join(elements_sanitized) + ")"
        return regex_string
```
test code:
```python
import re

elements_sanitized = ["南京", "北京", "上海"]
text = "买一张从南京到上海的火车票"
regex_string1 = "(?i)(\\b" + "\\b|\\b".join(elements_sanitized) + "\\b)"
print(regex_string1)
matches1 = re.finditer(regex_string1, text)
matches1 = list(matches1)
print("matches1 len is:%d" % len(matches1))

regex_string2 = "(?i)(" + "|".join(elements_sanitized) + ")"
print(regex_string2)
matches2 = re.finditer(regex_string2, text)
matches2 = list(matches2)
print("matches2 len is:%d" % len(matches2))
```

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by msamogh** [comment]
Thanks for raising this issue, @ricwo will get back to you about it soon.

**Comment by ricwo** [comment]
Hi @journey1986, I don't know if I understand you correctly, but it seems that for Chinese characters word boundaries are not defined by spaces? Is this always true?

**Comment by journey1986** [comment]
Hi @ricwo , yes, you are right.

**Comment by ricwo** [comment]
@journey1986 I believe you should be able to use the `JiebaTokenizer` (see [here](https://rasa.com/docs/rasa/nlu/components/#jiebatokenizer)). You'll have to make sure to define a pipeline with `- name: "JiebaTokenizer"` followed by `- name: "RegexFeaturizer"`. Let me know if that works!

**Comment by journey1986** [comment]
@ricwo   I used JiebaTokenizer and it is also not working.
Below is my config.yml

```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "zh"
pipeline:
- name: "JiebaTokenizer"
  dictionary_path: "jieba_dict"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
  token_pattern: (?u)\b\w+\b
- name: "EmbeddingIntentClassifier"
  num_neg: 1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
```
