### ISSUE TITLE
Can not config token_pattern for CountVectorsFeaturizer in config.yml?

### ISSUE THREAD

**Issue by journey1986** [RasaHQ/rasa#4078]
**Rasa version**:
1.1.2
**Rasa X version** (if used & relevant):

**Python version**:
3.7.3
**Operating system** (windows, osx, ...):

**Issue**:
In the config.yml I want to config token_pattern: r’(?u)\b\w+\b’ for chinese under CountVectorsFeaturizer Component. But it doesn’t work.

CountVectorsFeaturizer reads my configuration r’(?u)\b\w+\b’ as a normal string not a regex. and failed in train method and go into exception branch:
```python
try:
            # noinspection PyPep8Naming
            X = self.vectorizer.fit_transform(lem_exs).toarray()
        except ValueError:
            self.vectorizer = None (will come here)
            return
```

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "zh"
pipeline:
- name: "JiebaTokenizer"
  dictionary_path: "jieba_dict"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
  token_pattern: r'(?u)\b\w+\b'
- name: "EmbeddingIntentClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by msamogh** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon.

**Comment by psds01** [comment]
This is probably because of the `r` at the beginning of r'(?u)\b\w+\b'. Can you try without the `r` and see if the tokenization is correct. YAML might be parsing the "raw flag" `r` as a part the string.

**Comment by journey1986** [comment]
Hi @psds01, I have tried '(?u)\b\w+\b' and it is also not working.
Bcz, YAML will  read  '(?u)\b\w+\b' as string,and rasa will pass the string to CountVectorsFeaturizer.
So I think rasa need convert the configuration from string to Regex and pass the regex to CountVectorsFeaturizer .

**Comment by psds01** [comment]
If it is string and not a _raw_ string, you could add escape chars like `'(?u)\\b\\w+\\b'`. Not sure if it is a string.

Related question: Is this also true for the `regex_features` that we write in `nlu.md`? Do I need to manually escape there as well or adding the raw flag will do the job? @erohmensing

**Comment by erohmensing** [comment]
Hey there @journey1986. I'm looking into some tests for this `token_pattern`, specifically [this one](https://github.com/RasaHQ/rasa/blob/master/tests/nlu/base/test_featurizers.py#L268) that tests this exact pattern on Chinese data, and it doesn't look like there's an issue. Can you perhaps test what happens if you don't have a try/except and it throws the whole error? (or alternatively accept the error as e and print it)

**Comment by journey1986** [comment]
Hi @erohmensing @psds01 . when I use '(?u)\\b\\w+\\b' or  '(?u)\b\w+\b' in my config,yml。There is no error. But rasa can not predict **single  chinese character intent**.
I will show you all of my configuration:

config.yaml:
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "zh"
pipeline:
- name: "JiebaTokenizer"
  dictionary_path: "bdialogue/jieba_dict"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
  token_pattern: '(?u)\\b\\w+\\b'
- name: "EmbeddingIntentClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
```

nlu.md:
```md
## intent:goodbye
- 拜拜
- 再见
- 拜
- 退出
- 结束
- 回头见
- see you
- 没事了
- 88
- 886
- 3166
- 撒扬拉拉

## intent:greet
- 你好
- 您好
- Hello
- hello
- Hi
- hi
- 喂
- 在么
- 好啊
- 在吗
- 嗨
- 在

## intent:insult
- 真恶心
- 我贼，真垃圾
- 太垃圾了
- 你一点都不智能
- 智障
- 前言不搭后语
- 答案完全不搭界
- 呆子
- 笨蛋
- 蠢货
- 草泥马
- 日
- 操
- 我日
- 我草
- 我操
- 滚
- 傻逼
- SB
```
Then I trained rasa nlu model and test nlu. Below is my test results:
```txt
NLU model loaded. Type a message and press enter to parse it.
Next message:
在
2019-07-24 09:24:06 ERROR    rasa.nlu.featurizers.count_vectors_featurizer  - There is no trained CountVectorizer: component is either not trained or didn't receive enough training data
{
  "intent": {
    "name": null,
    "confidence": 0.0
  },
  "entities": [],
  "intent_ranking": [],
  "text": "\u5728"
}
```

but if I use r"(?u)\b\w+\b" directly in CountVectorsFeaturizer  instead of in yml.then it is ok.
I also show the correct senario:
config.yaml
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "zh"
pipeline:
- name: "JiebaTokenizer"
  dictionary_path: "bdialogue/jieba_dict"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
```
CountVectorsFeaturizer:
```python
  #"token_pattern": r"(?u)\b\w\w+\b",
        "token_pattern": r"(?u)\b\w+\b",
```
Then I trained rasa nlu model and test nlu agein. Below is my test results:
```txt
NLU model loaded. Type a message and press enter to parse it.
Next message:
在
{
  "intent": {
    "name": "greet",
    "confidence": 0.9605631232261658
  },
  "entities": [],
  "intent_ranking": [
    {
      "name": "greet",
      "confidence": 0.9605631232261658
    },
    {
      "name": "insult",
      "confidence": 0.0
    },
    {
      "name": "enter_data",
      "confidence": 0.0
    },
    {
      "name": "goodbye",
      "confidence": 0.0
    },
    {
      "name": "thank",
      "confidence": 0.0
    },
    {
      "name": "weather",
      "confidence": 0.0
    }
  ],
  "text": "\u5728"
}
```
Now  rasa can predict **single  chinese character intent.**
You also can try single  chinese character like  '嗨‘，’喂‘ to check whether rasa can predict the intent.
