### ISSUE TITLE
API Domain Call Issues

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4080]
The Rasa X domain related API calls have some issues:

* There should be a `DELETE` call as there is for the Stories & NLU Training data API calls
* The `PUT` appears to do nothing unless you specify the `store_templates=true` param. It should update the domain like the Stories & NLU calls do as it's default (without requiring a query param).
* The `PUT` call with `store_templates=true` updated `intents` and `actions` but not `templates`.

*There is no way to delete content from the domain via the API.*

**Rasa X version**: 0.19.5

**Comment by msamogh** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon.

**Comment by wochinge** [comment]
> There should be a DELETE call as there is for the Stories & NLU Training data API calls

What do you need the `DELETE` for? We didn't have the use case yet that we have to delete a domain. 

> The PUT appears to do nothing unless you specify the store_templates=true param

It does so, means `entities`, `intents` and so on should be updated. Do you have an example where this wasn't the case?

> The PUT call with store_templates=true updated intents and actions but not templates.

Mhm, how did your domain body look like? seems sth is wrong here.

By the way:
We are also adding new endpoints to manipulate actions in a domain in the next release 🎉

**Comment by rgstephens** [comment]
As discussed in this forum [thread](https://forum.rasa.com/t/reseting-stories-using-rasa-x-server-deployment-with-docker/12719), the use case is where we want to reset the content of an existing Rasa X instance.

If I start with a new Rasa X instance and I want to import existing NLU, Stories and domain. 

For the domain, there's no `POST` like there is for NLU & Stories. I use the `PUT` method on the following domain.yml and the following domain.yml.  The results are completely inconsistent but the status return is always 200. Sometimes it works and sometimes it doesn't. I confirm that my domain in the UI is empty. I've tried the `PUT` with `store_templates=true` and with no value. Mostly it is not working the more I test the API and review the domain in the UI.  I've probably run 10-15 tests of the `PUT` this morning with different `store_templates` options and domain files.

```
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great

actions:
- utter_greet
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"
  utter_did_that_help:
  - text: "Did that help you?"
  utter_happy:
  - text: "Great carry on!"
  utter_goodbye:
  - text: "Bye"
```

**Comment by rgstephens** [comment]
I've done some more testing with **templates**. I'm using `store_templates=true` and an updated domain from the one above. I've (1) replaced `utter_greet` with `utter_greet_greg`; and (2) removed `utter_goodbye` and get a status 200 from the `PUT`.

```
intents:
  - greet_greg
  - goodbye
  - mood_affirm
  - mood_deny

actions:
- utter_greet_greg
- utter_did_that_help
- utter_happy

templates:
  utter_greet_greg:
  - text: "Hey! How are you Greg?"
  utter_did_that_help:
  - text: "Did that help you?"
  utter_happy:
  - text: "Great carry on!"
```

As you can see from this screenshot of Responses, I see the following issues:

* Now two copies of `utter_happy` & `utter_did_that_help`
* `utter_greet` should be deleted but it still exists
* `utter_goodbye` should have been deleted

<img width="685" alt="Screen Shot 2019-07-23 at 8 51 13 AM" src="https://user-images.githubusercontent.com/846052/61727021-75036f80-ad27-11e9-9225-3ecad7d97611.png">

I see from some comments from #3798 that templates are really moving out of the domain and should be edited separately. Maybe there should be a separate set of calls for templates from the domain calls and just completely pull templates out of domain.
