### ISSUE TITLE
Sending messenger-like bot message in Rasa X generate error

### ISSUE THREAD

**Issue by RogersNtr** [RasaHQ/rasa#4093]
**Rasa version**: 1.1.4

**Rasa X version** (if used & relevant):1.0

**Python version**: 3.7

**Operating system** (windows, osx, ...): Linux Ubuntu

**Issue**:

```
> rasa.core.channels.channel - An exception occured while handling user message ‘yoo’. 
Traceback (most recent call last): 
File “$HOME/lib/python3.7/site-packages/rasa/core/channels/channel.py”, line 460, in receive text, collector, sender_id, input_channel=self.name() 
File “$HOME/lib/python3.7/site-packages/rasa/core/channels/channel.py”, line 75, in handler await app.agent.handle_message(*args, **kwargs) 
File “$HOME/lib/python3.7/site-packages/rasa/core/agent.py”, line 440, in handle_message return await processor.handle_message(message) 
File “$HOME/lib/python3.7/site-packages/rasa/core/processor.py”, line 84, in handle_message await self._predict_and_execute_next_action(message, tracker) 
File “$HOME/lib/python3.7/site-packages/rasa/core/processor.py”, line 350, in _predict_and_execute_next_action action, tracker, message.output_channel, self.nlg, policy, confidence 
File “$HOME/lib/python3.7/site-packages/rasa/core/processor.py”, line 461, in _run_action await self._send_bot_messages(events, tracker, output_channel) 
File “$HOME/lib/python3.7/site-packages/rasa/core/processor.py”, line 382, in _send_bot_messages await output_channel.send_response(tracker.sender_id, e.message()) 
File “$HOME/lib/python3.7/site-packages/rasa/core/channels/channel.py”, line 175, in send_response **message 
File “$HOME/lib/python3.7/site-packages/rasa/core/channels/channel.py”, line 251, in send_quick_replies await self.send_text_with_buttons(recipient_id, text, quick_replies, **kwargs) TypeError: send_text_with_buttons() got multiple values for argument ‘buttons’
```

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```
rasa x --enable-api -t <token_number>
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en,fr
pipeline: supervised_embeddings   #  pretrained_embeddings_spacy

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: FormPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
