### ISSUE TITLE
MappingPolicy is not usable in Rasa X

### ISSUE THREAD

**Issue by amaurymercier** [RasaHQ/rasa#4114]
Hello !
It seems I can't get the MappingPolicy to work in Rasa X.

**Rasa version**:  1.1.8

**Rasa X version** (if used & relevant):  0.19.5

**Python version**:  3.6.7

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: `MappingPolicy` configuration in `domain.yml` (e.g. setting `triggers: action_name` in the domain) is ignored by rasa-x (the attribute doesn't show up when looking up the domain, and isn't included in the trained model).

To reproduce :
```
- rasa init
- {add `triggers: test` to a new `test` intent}
- rasa x
- The triggers: test is not seen in rasa x when checking the domain, and isn't present in the model when trained.
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
- greet
- goodbye
- affirm
- deny
- mood_great
- mood_unhappy
- test:
    triggers: test
templates:
  utter_greet:
  - text: Hey! How are you?
  utter_cheer_up:
  - text: 'Here is something to cheer you up:'
    image: https://i.imgur.com/nGF1K8f.jpg
  utter_did_that_help:
  - text: Did that help you?
  utter_happy:
  - text: Great carry on!
  utter_goodbye:
  - text: Bye
actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye
- test
```
