### ISSUE TITLE
Client for conversation_id ‘me’ could not be found” 

### ISSUE THREAD

**Issue by harunkelesoglu** [RasaHQ/rasa#4146]
**Rasa version**:

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:

Hi, I deployed rasa x on server.I get the following error when I try to test in the talk section
```json
{ 
"version":"0.20.0",
"status":"failure",
"message":"Client for conversation_id 'me' could not be found",
"reason":"ClientNotFound",
"details":{},
"help":null,
"code":404
}
```
Screenshot:
![Screen Shot 2019-07-31 at 16 50 05](https://user-images.githubusercontent.com/9349762/62218086-77fc0100-b3b4-11e9-880c-06026294f894.png)

my endpoints.yml:
```yml
# This file contains the different endpoints your bot can use.

# Server where the models are pulled from.
# https://rasa.com/docs/rasa/user-guide/running-the-server/#fetching-models-from-a-server/

#models:
#  url: ${RASA_MODEL_SERVER}
#  token:${RASA_X_TOKEN}
#  wait_time_between_pulls:  ${RASA_MODEL_PULL_INTERVAL}   # [optional](default: 100)

# Server which runs your custom actions.
# https://rasa.com/docs/rasa/core/actions/#custom-actions/

action_endpoint:
 url: ${RASA_USER_APP}/webhook

# Tracker store which is used to store the conversations.
# By default the conversations are stored in memory.
# https://rasa.com/docs/rasa/api/tracker-stores/
tracker_store:
   type: sql
   dialect: "postgresql"
   url: ${DB_HOST}
   port: ${DB_PORT}
   username: ${DB_USER}
   password: ${DB_PASSWORD}
   db: ${DB_DATABASE}
   login_db: ${DB_LOGIN_DB}
#tracker_store:
#    type: redis
#    url: <host of the redis instance, e.g. localhost>
#    port: <port of your redis instance, usually 6379>
#    db: <number of your database within redis, e.g. 0>
#    password: <password used for authentication>

#tracker_store:
#    type: mongod
#    url: <url to your mongo instance, e.g. mongodb://localhost:27017>
#    db: <name of the db within your mongo instance, e.g. rasa>
#    username: <username used for authentication>
#    password: <password used for authentication>

# Event broker which all conversation events should be streamed to.
# https://rasa.com/docs/rasa/api/event-brokers/

event_broker:
  type: "pika"
  url: ${RABBITMQ_HOST}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  queue: queue
```
my credentials.yml
```yml
# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/

rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials


slack:
 slack_token: "mytoken"
 slack_channel: "#mychannel"

#socketio:
#  user_message_evt: <event name for user message>
#  bot_message_evt: <event name for but messages>
#  session_persistence: <true/false>

rasa:
  url: ${RASA_X_HOST}/api
```
my config.yml
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings
timezone: Europe/Istanbul

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.4
    core_threshold: 0.3
    fallback_action_name: action_default_fallback
```
