### ISSUE TITLE
action_listen action following the chitchat utterance

### ISSUE THREAD

**Issue by jianjunchang** [RasaHQ/rasa#4217]
**Rasa version**:
1.1.4
**Rasa X version** (if used & relevant):

**Python version**:
3.6.9
**Operating system** (windows, osx, ...):
osx
**Issue**:
There is a action_listen action following the chitchat utterance when i'm working with interactive learning, but i think it should not be there, see the screenshot bellow.(i have post a thread [here](https://forum.rasa.com/t/why-is-there-a-action-listen-action-following-the-chitchat-utterance/14118) )
![image](https://user-images.githubusercontent.com/6183488/62768169-dfa70000-bac8-11e9-9f63-eee380325786.png)

my actions.py
```
from typing import Any, Text, Dict, List, Union, Optional
from rasa_sdk import Tracker
from rasa_sdk.forms import FormAction
from rasa_sdk.executor import CollectingDispatcher


class RestaurantForm(FormAction):

    def name(self) -> Text:
        return "action_restaurant_form"
    
    @staticmethod
    def required_slots(tracker) -> List[Text]:
        
        return ["cuisine", "num_people", "outdoor_seating", "preferences", "feedback"]
    
    def slot_mappings(self) -> Dict[Text, Union[Dict, List[Dict]]]:
        return {
                "cuisine": [self.from_entity(entity="cuisine", not_intent=["chitchat+weather_good", "chitchat+weather_bad"])],
                "num_people": [
                    self.from_entity(entity="num_people", intent=["inform", "restaurant_search"]),
                    self.from_entity(entity="number")
                    ],
                "outdoor_seating": [
                    self.from_entity(entity="outdoor_seating", intent=["inform", "restaurant_search"]),
                    self.from_intent(value=True, intent="affirm"),
                    self.from_intent(value=False, intent="deny")
                    ],
                "preferences": [
                        self.from_intent(value="没有更多要求。", intent="deny"),
                        self.from_text(not_intent=["affirm", "chitchat+weather_good", "chitchat+weather_bad"])
                    ],
                "feedback": [
                    self.from_entity(entity="feedback", not_intent=["chitchat+weather_good", "chitchat+weather_bad"]),
                    self.from_text(not_intent=["chitchat+weather_good", "chitchat+weather_bad"])
                    ]
            }
        
    @staticmethod
    def cuisine_db() -> List[Text]:
        return [
            "中式", "中国",
            "法式", "法国",
            "希腊",
            "印度",
            "意大利", "意式",
            "墨西哥",
            ]

    @staticmethod
    def is_int(stringValue: Text) -> bool:
        try:
            print('converting {} to int'.format(stringValue))
            int(stringValue)
            return True
        except ValueError:
            return False
        
    def validate_cuisine(self, value: Text, dispatcher: CollectingDispatcher, tracker, domain) -> Optional[Text]:
        if value.lower() in RestaurantForm.cuisine_db():
            return { "cuisine": value }
        else:
            dispatcher.utter_template("utter_wrong_cuisine", tracker)
            return { "cuisine": None }
        
    def validate_num_people(self, value: Text, dispatcher: CollectingDispatcher, tracker, domain):
        if RestaurantForm.is_int(value) and int(value) > 0:
            return { "num_people": value }
        else:
            dispatcher.utter_template("utter_wrong_num_people", tracker)
            return { "num_people": None }
        
    def validate_outdoor_seating(self, value, dispatcher: CollectingDispatcher, tracker, domain):
        if isinstance(value, str):
            if "外边" in value:
                return { "outdoor_seating": True }
            elif "里边" in value:
                return { "outdoor_seating": False }
            else:
                dispatcher.utter_template("utter_wrong_outdoor_seating", tracker)
                return { "outdoor_seating": None }
        else:
            return { "outdoor_seating": value }
        
    def submit(self, dispatcher: CollectingDispatcher, tracker, domain) -> List[Dict]:
        dispatcher.utter_template("utter_submit", tracker)
        return []
```

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "zh"
pipeline: 
- name: "JiebaTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
  token_pattern: (?u)\b\w+\b
- name: "EmbeddingIntentClassifier"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 5
#  - name: KerasPolicy
#    epochs: 200
#    featurizer:
#    - name: MaxHistoryTrackerFeaturizer
#      max_history: 5
#      state_featurizer:
#        - name: BinarySingleStateFeaturizer
  - name: EmbeddingPolicy
    epochs: 20
    attn_shift_range: 5
    featurizer:
    - name: FullDialogueTrackerFeaturizer
      state_featurizer:
        - name: LabelTokenizerSingleStateFeaturizer
  - name: MappingPolicy
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.4
    core_threshold: 0.3
    fallback_action_name: "utter_default_fallback"

```

**Content of domain file (domain.yml)** (if relevant):
```yml
%YAML 1.1
---
actions:
- utter_ask_cuisine
- utter_ask_feedback
- utter_ask_num_people
- utter_ask_outdoor_seating
- utter_ask_preferences
- utter_blessing
- utter_default_fallback
- utter_goodbye
- utter_greet
- utter_noworries
- utter_slots_values
- utter_submit
- utter_weather_bad
- utter_weather_good
- utter_wrong_cuisine
- utter_wrong_num_people
- utter_wrong_outdoor_seating
entities:
- cuisine
- feedback
- num_people
- outdoor_seating
forms:
- action_restaurant_form
intents:
- greet
- deny
- inform
- affirm
- thankyou
- restaurant_search:
    ignore_entities: []
    use_entities: []
- chitchat+weather_good:
    ignore_entities: []
    use_entities: []
- chitchat+weather_bad:
    ignore_entities: []
    use_entities: []
- affirm+thankyou
- chitchat:
    ignore_entities: []
    use_entities: []
- deny+thankyou
- goodbye
- weather_bad:
    ignore_entities: []
    use_entities: []
- weather_good:
    ignore_entities: []
    use_entities: []
slots:
  cuisine:
    auto_fill: false
    type: unfeaturized
  feedback:
    auto_fill: false
    type: unfeaturized
  num_people:
    auto_fill: false
    type: unfeaturized
  outdoor_seating:
    auto_fill: false
    type: unfeaturized
  preferences:
    auto_fill: false
    type: unfeaturized
  requested_slot:
    type: unfeaturized
templates:
  utter_ask_cuisine:
  - text: 您想要哪种风味的餐厅？
  utter_ask_feedback:
  - text: 请您给出本次服务的评价！
  utter_ask_num_people:
  - text: 您准备多少人同时就餐？
  utter_ask_outdoor_seating:
  - text: 您喜欢露天餐位吗？
  utter_ask_preferences:
  - text: 还有哪些特别的要求吗？
  utter_blessing:
  - text: 祝您生活愉快！
  utter_default_fallback:
  - text: 抱歉，您说领域我不擅长 :(
  utter_goodbye:
  - text: 再见
  utter_greet:
  - text: 您好，我是订餐助手，请问您需要什么服务？
  utter_noworries:
  - text: 不客气！
  utter_slots_values:
  - text: 我将为您查询相关酒店，请您核对您的偏好：\n 风味：{cuisine}\n 人数：{num_people}\n 露天餐位：{outdoor_seating}\n
      其它要求：{preferences}\n 服务反馈：{feedback}
  utter_submit:
  - text: 好了
  utter_weather_bad:
  - text: 天气不好也要保持好心情，祝您愉快！
  utter_weather_good:
  - text: 天气好，心情就好，心情好有利于身体健康，祝您身体棒棒哒～
  utter_wrong_cuisine:
  - text: 抱歉，您选的风味无法提供，请换一种风味吧。
  utter_wrong_num_people:
  - text: 您说的人数我没看明白，请重新告诉我，谢谢。
  utter_wrong_outdoor_seating:
  - text: 抱歉，您是不是喜欢露天餐位我没看明白，请重新告诉我，谢谢。

```
