### ISSUE TITLE
Duckling is not working for entity extraction 

### ISSUE THREAD

**Issue by IKhushi** [RasaHQ/rasa#4228]
**Rasa version**: Rasa 1.1.8

**Rasa X version** (if used & relevant):

**Python version**: python3.6.7

**Operating system** (windows, osx, ...): linux

**Issue**: Duckling is not working for entity extraction
I've done testing is done using 
curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text="the first Tuesday of October"'
it will give o/p:  
[{"body":"the first Tuesday of October","start":1,"value":{"values":[{"value":"2019-10-01T00:00:00.000-07:00","grain":"day","type":"value"}],"value":"2019-10-01T00:00:00.000-07:00","grain":"day","type":"value"},"end":29,"dim":"time","latent":false}]
but when I will try it out in RASA than it produce empty entity , so how can I Implement it in my rasa code

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
pipeline: supervised_embeddings
  - name: rasa_addons.nlu.components.language_setter.LanguageSetter
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: EmbeddingIntentClassifier
  - BILOU_flag: true
    name: CRFEntityExtractor
    features:
      - [low, title, upper]
      - [low, bias, prefix5, prefix2, suffix5, suffix3, suffix2, upper, title, digit, pattern]
      - [low, title, upper]
  - name: rasa_addons.nlu.components.gazette.Gazette
  - name: EntitySynonymMapper
  - name: components.botfront.duckling_http_extractor.DucklingHTTPExtractor
    url: http://duckling:8000
    dimensions: 
    - "number"
    - "time"
    - "duration"  
    locale: en_US
    timezone: Europe/Berlin
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
