### ISSUE TITLE
Action default fallback - respond nothing

### ISSUE THREAD

**Issue by GraphGrailAi** [RasaHQ/rasa#4308]
According to https://forum.rasa.com/t/action-default-fallback-already-defined/629/7

In action server i see action_default_fallback is triggered
```
    I0822 18:59:21.712826 139684754990912 executor.py:173] Received request to run 'action_default_fallback'
    I0822 18:59:21.712929 139684754990912 executor.py:186] Successfully ran 'action_default_fallback'
```

But, in cmd test bot answer nothing, nevertheless i have utter_default in domain.yml and copied class ActionDefaultFallback(Action):  class to actions.py

```
2019-08-22 19:15:12 INFO     root  - Rasa Core server is up and running on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Your input ->  dfer rtrertretttrtrteee                                                          
127.0.0.1 - - [2019-08-22 19:15:17] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 122 0.205780
Your input ->       
```       

What is wrong?

policies.yml:
```
policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.5
    core_threshold: 0.5
    fallback_action_name: 'action_default_fallback'
```
