### ISSUE TITLE
DialogFlow import doesn't read language from given data

### ISSUE THREAD

**Issue by Cristianasp** [RasaHQ/rasa#4320]
**Rasa version**: Rasa 1.2.3

**Rasa X version** (if used & relevant):

**Python version**: Python 3.7.3

**Operating system** (windows, osx, ...): 
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch

**Issue**:
I am following the tutorial below:
https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/
That instructs the user to export the agent in Dialog Flow and them copy the agent to the data directory.
After that, run
$ rasa train nlu
Got error message : that there was no trrainning examples in the intent.
BUT what happens is the followin:
when you download an intent directly from the intent list, you download ONE file with all information. but when you make an export from configuration menu, there is actually TWO files, the intent and another one intent_user_says.
I am providing copies of the files attached.

**Error (including full traceback)**:
```
2019-08-23 12:34:58 WARNING  rasa.nlu.training_data.formats.dialogflow  - No training examples found for dialogflow file data/intents/888-faq-atendimento.
json!
No NLU data given. Please provide NLU data in order to train a Rasa NLU model using the '--nlu' argument.
```

**Command or request that led to error**:
```
rasa train nlu
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt
pipeline: supervised_embeddings
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
[Intent.zip](https://github.com/RasaHQ/rasa/files/3536119/Intent.zip)



```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
