### ISSUE TITLE
No agent loaded. To continue processing, a model of a trained agent needs to be loaded.

### ISSUE THREAD

**Issue by dhwanils95** [RasaHQ/rasa#4330]
**Rasa version**: 1.2.2
**Rasa X version** (if used & relevant): 0.20.1
**Python version**: 3.6
**Operating system** (windows, osx, ...): Ubuntu 18.04 and CentOS 7.6

**Issue**:
I tried a automated script install (the one from Rasa X - Deploy on Server Docs) on Ubuntu and a full manual deployment with custom rasa Action Server app. In both the case, whenever I try to use the interactive learning to start training. I get the following error:

**Error**:
```
rasa-x_1           | WARNING:rasax.community.api.blueprints.stack:Creating event for sender '32f4f91570044c1b898486d67fb3a7ab' failed. Error: 409, Conflict, body='b'{"version":"1.2.3","status":"failure","message":"No agent loaded. To continue processing, a model of a trained agent needs to be loaded.","reason":"Conflict","details":{},"help":"https:\\/\\/rasa.com\\/docs\\/rasa\\/user-guide\\/running-the-server\\/","code":409}''
No agent loaded. To continue processing, a model of a trained agent needs to be loaded.
rasa-worker_1      | 2019-08-26 13:00:03 DEBUG    rasa.core.agent  - Model server didn't find a model for our request. Probably no one did train a model for the project and tag combination yet.
rasa-worker_1      | 2019-08-26 13:00:03 DEBUG    rasa.core.agent  - No new model found at URL http://rasa-x:5002/api/projects/default/models/tags/production
rasa-production_1  | 2019-08-26 13:00:03 DEBUG    rasa.core.agent  - Model server didn't find a model for our request. Probably no one did train a model for the project and tag combination yet.
rasa-production_1  | 2019-08-26 13:00:03 DEBUG    rasa.core.agent  - No new model found at URL http://rasa-x:5002/api/projects/default/models/tags/production
```

**Command or request that led to error**:
```
Rasa X - Interactive Learning UI on fresh installation.
```

**Content of configuration file (config.yml)** (if relevant):
```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_core_action_name: "action_default_fallback"
    fallback_nlu_action_name: "action_default_fallback"
    deny_suggestion_intent_name: "out_of_scope"
```

**Content of domain file (domain.yml)** (if relevant):
```
intents:
- impact
- inform
- greet
entities:
- above_below
- operation
- period
templates:
...
slots:
...
```

**Comment by ricwo** [comment]
Hi @dhwanils95, did you train a model and tag it as `production`?

**Comment by dhwanils95** [comment]
Yes @ricwo, we have a trained model on the action server in .../action_server/models/models.tar.gz

The thing is I have dockerized our previous Rasa project and then replaced it in the docker-compose file as the "app" service. I'm guessing it should load the models and data/nlu.md, data/stories.md and all those files automatically right?

Please correct me if I'm wrong, since I'm just deploying I'm not still accustomed to the workflow in Rasa.

Thanks & regards.

**Comment by dhwanils95** [comment]
Hey @ricwo I found the issue. I had the model in place but it was not mounting onto the rasa-x container. I was refraining from default docker-compose you guys ship out but then I realized since I am using my own action server and the model lies in that directory which is not the root for this rasa-x project. I changed the following:

```
services:
  rasa-x:
    restart: always
    image: "rasa/rasa-x:${RASA_X_VERSION}"
    expose:
      - "5002"
    volumes:
      - ./models:/app/models
      - ./environments.yml:/app/enviro
```
**to** 
```
  rasa-x:
    restart: always
    image: "rasa/rasa-x:${RASA_X_VERSION}"
    expose:
      - "5002"
    volumes:
      - ${RASA_ACTIONS_SERVER}/models:/app/models
      - ./environments.yml:/app/environments.yml
      - ./logs:/logs
      - ./auth:/app/auth
```

So it was an issue on my part. Sorry for the inconvenience. 
Also, this is now loading the models but I still have the issue where my nlu.md and stories.md file are not loaded. Can you point me in the right direction to resolve that. I have these files i.e.
1. nlu.md
2. domain.yml

Thanks and regards!
