### ISSUE TITLE
How to use multiple intent classifier in Rasa nlu pipeline?

### ISSUE THREAD

**Issue by gongshaojie12** [RasaHQ/rasa#4336]
Hello everyone:
I want to use multiple intent classfier in rasa nlu pipeline,but not work,The following is my configuration file:

```
language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "KeywordIntentClassifier"
- name: "SklearnIntentClassifier"
- name: "DucklingHTTPExtractor"
  url: "http://localhost:8000"
  dimensions: ["time", "duration", "phone-number", "number", "amount-of-money", "distance"]

```

I added two intent classifiers ，KeywordIntentClassifier and SklearnIntentClassifier,
but KeywordIntentClassifier  not work,where is the problem？

I want to use both keyword and machine learning to identify the intent at the same time. First, the intent is identified by the keyword. If the keyword recognizes the intent, the result is returned. Otherwise, the intent is identified through machine learning.

How can I do it? Thanks a lot!
