### ISSUE TITLE
Actions do not work properly

### ISSUE THREAD

**Issue by nvlong198** [RasaHQ/rasa#4371]
**Rasa version**: 
rasa-core (0.14.4)
rasa-core-sdk (0.14.0)
rasa-nlu (0.15.1)
rasa-sdk (1.2.0)

**Python version**: Python 3.6.8

**Operating system** Ubuntu 18.04

**Issue**: My rasa bot understands the action, but It does not respond to the message ‘Hello world’ in the console output. I saw many struggling with this, hope you guys consider.
Here is my actions.py & whole project
https://github.com/nvlong198/Chatbot/blob/master/actions.py

**Error (including full traceback)**:
![image](https://user-images.githubusercontent.com/23328191/64117173-a8252e00-cdbe-11e9-878e-7c2247cb2346.png)

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_featurizer_spacy"
  - name: "intent_classifier_sklearn"
  - name: "ner_crf"
  - name: "ner_synonyms"
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
 - ask_weather
 - greet
....
actions:
 - utter_weather
 - action_get_weather
....

```
