### ISSUE TITLE
Multiple responses are not working with buttons

### ISSUE THREAD

**Issue by nicola1M** [RasaHQ/rasa#4415]
Hello,
when trying to use multiple responses with buttons, the buttons are not shown.
Don't know if this a bug or should be an feature request.

**Rasa version**: 1.2.3

**Python version**: 3.6.2

**Content of domain file (domain.yml)** (if relevant):
```yml
 utter_question:
  - text: Kann ich noch etwas für dich tun?
  - text: Gibt es noch etwas was ich für dich tun kann?
  - text: Gibt es sonst noch etwas?
  - text: Soll ich noch etwas für dich tun?
    buttons:
    - payload: '/affirm'
      title: Ja
    - payload: /deny
      title: Nein
```
