### ISSUE TITLE
Web chat unresponsive; API fine, other channels fine

### ISSUE THREAD

**Issue by tangochris** [RasaHQ/rasa#4479]
**Rasa version**: 1.3.2
**Rasa X version**: 0.21.0
**Operating system**: OSX. Tested in Chrome, Safari, and Firefox; same result.

**Issue**: "Talk to your bot" doesn't respond to anything; not even "Restart". Just a pulsing ellipsis appears. ("Interactive Learning" works just fine, but it uses different API calls). The API seems to be returning a result, but that result doesn't render to webchat. See short screencast to see the problem in action: https://www.dropbox.com/s/6ofz8gyn558gurk/screen%20recording%202019-09-17%20at%204.34.54%20pm.mov?dl=0

**Error**: There are no errors in the Chrome developers' console.

**Content of configuration file (config.yml)** (if relevant):
```
pipeline: supervised_embeddings
language: en
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```
intents:
  - greeting
  - insurance-car
  - insurance-home
  - insurance-business
templates:
  utter_greeting:
    - text: Hi there!
  utter_insurance-type:
    - text: What kind of insruance do you need?
  utter_start-car:
    - text: What kind of car?
  utter_start-business:
    - text: Is your business incorporated?
  utter_start-home:
    - text: What year was your house built?
  utter_start_car2:
    - text: 'Ooh, nice car!'
actions:
  - utter_insurance-type
  - utter_greeting
  - utter_start-car
  - utter_start-business
  - utter_start-home
  - utter_start_car2
```
