### ISSUE TITLE
Can't add channel to Rasa X responses

### ISSUE THREAD

**Issue by andrew-tangowork** [RasaHQ/rasa#4533]
**Rasa version**:
1.3.6

**Rasa X version** (if used & relevant):
0.21.1

**Python version**:
3.7.3

**Operating system** (windows, osx, ...):
Pop!_OS 19.04

**Issue**:
When editing a response template in Rasa X 0.21.1 the channel option does not save. 

Example of text added
```yml
text: Test of facebook channel
channel: "facebook"
buttons: 
  - title: test 1
    payload: test 1
```
I can confirm that the rest of the template saves correctly. I tried placing channel below buttons too, as well as not having facebook in quotes. 
Custom saves though.

```yml
text: Test of channels
channel: facebook
custom:
  buttons:
    - title: "Visit website"
      type: web_url
      url: exampleurl.com
      webview_height_ratio: full
```
this results in the following in the domain file.

```yml
utter_test_channel:
- text: Test of facebook
    custom:
      buttons:
      - title: Visit website
        type: web_url
        url: https://www.peopleslawschool.ca/hiring-someone
        webview_height_ratio: full

```

**Error (including full traceback)**:
```
No errors outputted in log or dev console
```

**Command or request that led to error**:
```
Save
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
