### ISSUE TITLE
DucklingHTTPExtractor is not properly piping in dimensions into requests

### ISSUE THREAD

**Issue by lhr0909** [RasaHQ/rasa#4558]
**Rasa version**: Rasa 1.3.2

**Rasa X version** (if used & relevant): N/A

**Python version**: Python 3.7.3

**Operating system** (windows, osx, ...): MacOS

**Issue**:

Relevant issue from duckling - https://github.com/facebook/duckling/issues/88

The problem is that the duckling HTTP extractor is merely filtering results rather than actually applying the dimensions into the request, causing recognition issues on Duckling's side. Even with `ordinal` filter, it will not properly return the ordinal parse result until we actually apply the `ordinal` filter to the Duckling server request.

**Error (including full traceback)**:
There is no error, just wrong result.

**Command or request that led to error**:
N/A

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
# pipeline: pretrained_embeddings_spacy
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
# this is a test result where I am overriding with my own implementation with dimensions pulled up (PR coming soon)
- name: "components.duckling_http_extractor.DucklingHTTPExtractor"
  # url of the running duckling server
  url: "http://localhost:8000"
  # dimensions to extract
  # dimensions: ["time", "number", "amount-of-money", "distance"]
  dimensions: ["ordinal"]
  # allows you to configure the locale, by default the language is
  # used
  locale: "en_US"
  # if not set the default timezone of Duckling is going to be used
  # needed to calculate dates from relative expressions like "tomorrow"
  # timezone: "Europe/Berlin"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
- name: "ResponseSelector"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
N/A
