### ISSUE TITLE
RASA API /model/parse and /conversations/<id>/messages get bad messages.

### ISSUE THREAD

**Issue by GuillaumeKoenigTncy** [RasaHQ/rasa#4570]
**Rasa version**: 1.3.6

**Python version**: 3.7

**Operating system** (windows, osx, ...): Ubuntu 18.04 

**Issue**:
For the needs of my project I have to create a bridge between the RASA API and the outside world. For this purpose I use a Flask server that uses the RASA API if necessary.

During the tests I used the resource /model/parse as shown below:
```
data = {
        "text": "Hello!",
        "message_id": "b2831e73-1407-4ba0-a861-0f30a42a42a2a5a",
        "text": "Hello!",
        "sender": "user"
}
print(data)
r = requests.post(url = "http://rasa:5005/model/parse", json = data, headers={{'Content-Type': "application/json'}) 
data = r.json()
return data, 200, {'Content-Type':'application/json; charset=utf-8' }
```
My API print : 
```
api_1            | {'text': 'Hello!', 'message_id': 'b2831e73-1407-4ba0-a861-0f30a42a2a5a', 'sender': 'user'}
```
It seems the message is correct. The endpoint is accessible and the format is normally correct. However, RASA's response adds a / to the text which causes :
```
{
  "entities": [], 
  "intent": {
    "Confidentiality": 1.0, 
    "name": "Hello!"
  }, 
  "intent_ranking": [
    {
      "Confidentiality": 1.0, 
      "name": "Hello!"
    }
  ], 
  "text": "/Hello!"
}
```
The intention seems forced because of the / and this with all the texts that can be given to the API. 
RASA log print : 
```
rasa_1           | 2019-10-07 10:43:17 DEBUG    rasa.core.processor  - Received user message 'Hello!' with intent '{'name': 'Hello!', 'confidence': 1.0}' and entities '[]'
rasa_1           | 2019-10-07 10:43:17 WARNING  rasa.core.processor  - Interpreter parsed an intent 'Hello!' that is not defined in the domain.
```

The problem is also present on the endpoint /conversations/<id>/messages.

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
Hi @GuillaumeKoenigTncy this looks like a custom response you defined:
```
{
  "entities": [], 
  "intent": {
    "Confidentiality": 1.0, 
    "name": "Hello!"
  }, 
  "intent_ranking": [
    {
      "Confidentiality": 1.0, 
      "name": "Hello!"
    }
  ], 
  "text": "/Hello!"
}
```
Can you share the code of what you're trying to implement?

**Comment by GuillaumeKoenigTncy** [comment]
In my API I have only that :
```
data = {
    "message_id": "b2831e73-1407-4ba0-a861-0f30a42a2a5a",
    "text": "Hello!",
}
print(data)
r = requests.post(url = "http://rasa:5005/model/parse", json = data, headers={'Content-Type': 'application/json'}) 
data = r.json()
return json.dumps(data), 200, {'Content-Type': 'application/json; charset=utf-8'}
```

Or this one for testing :
```
data = {
    "message":"i did some tennis",
    "sender": "3"
}
print(data)
r = requests.post(url = "http://rasa:5005/webhooks/rest/webhook", json = data, headers={'Content-Type': 'application/json'})
data = r.json()
loogger.info(data)
return json.dumps(data), 200, {'Content-Type': 'application/json; charset=utf-8'}
```

The problem is for with every message I sent using /parse or /webhook (with curl or with my python script previously presented), something add a / at the beginning of if. This is between my API call and the RASA API because when I print the content of data (in my script presented upper) I get the correct data without /. But when I get the response from RASA a / as been added and then the message is considered like an intent. 

Example :
I send to /model/parse : "how are you ?"
I get :
 ```
{
  "entities": [], 
  "intent": {
    "Confidentiality": 1.0, 
    "name": "how are you ?"
  }, 
  "intent_ranking": [
    {
      "Confidentiality": 1.0, 
      "name": "how are you ?"
    }
  ], 
  "text": "/how are you ?"
}
```

**Comment by akelad** [comment]
i mean the reason i ask about custom code is because "confidentiality" is not the syntax we have in our requests. The only thing I can think of here is that the model you have loaded up is a core only model. What's the name of the model you're passing ?

**Comment by GuillaumeKoenigTncy** [comment]
I have trained the NLU using this command in my Docker container :
``` rasa train nlu --config ${CONFIG_FILE} --out models/${PROJECT} --nlu ${TRAIN_DATA} --fixed-model-name nlu --verbose  ```

The variable CONFIG_FILE point to a file with that configuration : 
```
language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "SpacyEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
- name: "RegexFeaturizer"

- name: "DucklingHTTPExtractor"
  url: "http://duckling:8000"
  dimensions: ["time", "temperature", "number", "ordinal", "distance", "volume", "amount-of-money", "duration", "Duration", "Time"]
  locale: "en_GB"
  timezone: "Europe/Paris"

- name: "rasa_components.SA.SentimentAnalyzer"
- name: "rasa_components.RGX.RegexExtractor"
``` 

The variable project is used to store the trained model in a particular folder (we use many pipelines, so we have different models trained in the model folder, each of them in a particular subfolder). In this case, the subfolder name is ``` spacy_en_on_EN ```

The variable Training data is used to set the path for the training Data. Here ``` data/en_init_data_set_train.json ```

The result is a nlu.tar.gz file containing NLU training in /models/spacy_en_on_EN/nlu.tar.gz. Inside the nlu.tar.gz there is a fingerprint.json file and a nlu folder containing component_6_SklearnClassifier_classifier.pkl, component_6_SklearnClassifier_encoder.pkl, component_7_RegexFeaturizer.pkl and metadata.json which contain all the steps defined in my pipeline (I check it manually previously to see if the problem comes from the training).

The Core is trained using this command : 
``` rasa train core --stories data/stories.md --domain domain.yml --config policies.yml --out models/${PROJECT} --fixed-model-name core --verbose ``` 

Stories are correct (they worked before with the previous rasa version I used). The domain file is correct too but too big to be shared here. 

Policies file is here : 
```
policies:
  - name: KerasPolicy
    epochs: 10
    max_history: 8

  - name: MemoizationPolicy
    max_history: 8
  
  - name: FormPolicy
```

Like for the nlu, the variable project is used to store the trained model in a particular subfolder, in this case, the subfolder name is ``` spacy_en_on_EN ```

The result is a core.tar.gz file containing Core training in /models/spacy_en_on_EN/core.tar.gz. The file contain a fingerprint and a core folder that contain /policy_0_KerasPolicy, /policy_1_MemorizationPoliciy, /policy_2_FormPolicy, domain.json, domain.yml, metadata.json.

Both were last trained at 2019-10-04 with rasa 1.3.6.

To use rasa I use a docker-compose.yml file. Here is the service rasa :
```
  rasa:
    image: aliae-rasa:1.0.0
    command:
      - run
      - --m 
      -  models/spacy_en_on_EN/
      - --endpoints 
      - endpoints.yml
      - --credentials 
      - credentials.yml
      - --log-file
      - out.log
      - --enable-api
      - --cors
      - "*"
      - --debug
    networks:
      - default_network
    expose:
      - 5005
    labels:
      - traefik.enable=true
      - traefik.port=5005
      - traefik.frontend.rule=HostRegexp:rasa.{subdomain:.+}.nip.io
      - traefik.frontend.entryPoints=https
    depends_on:
      - postgres
      - actionserver
```

aliae-rasa:1.0.0 is the company image of rasa build with the following dockerfile :
```
FROM rasa/rasa:latest-full

# Add a custom system library
RUN apt-get update && \
    apt-get install -y git && \
    apt-get install -y nano

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
```

Models are trained in the docker container (linked to a local volume). 

When I run the docker-compose up command I have no errors nor warning. 
```
rasa_1          | 2019-10-09 08:51:29 DEBUG    rasa.core.utils  - Available web server routes: 
rasa_1          | /conversations/<conversation_id>/messages          POST                           add_message
rasa_1          | /conversations/<conversation_id>/tracker/events    POST                           append_events
rasa_1          | /webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
rasa_1          | /webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
rasa_1          | /webhooks/rest                                     GET                            custom_webhook_RestInput.health
rasa_1          | /webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
rasa_1          | /model/test/intents                                POST                           evaluate_intents
rasa_1          | /model/test/stories                                POST                           evaluate_stories
rasa_1          | /conversations/<conversation_id>/execute           POST                           execute_action
rasa_1          | /domain                                            GET                            get_domain
rasa_1          | /                                                  GET                            hello
rasa_1          | /model                                             PUT                            load_model
rasa_1          | /model/parse                                       POST                           parse
rasa_1          | /conversations/<conversation_id>/predict           POST                           predict
rasa_1          | /conversations/<conversation_id>/tracker/events    PUT                            replace_events
rasa_1          | /conversations/<conversation_id>/story             GET                            retrieve_story
rasa_1          | /conversations/<conversation_id>/tracker           GET                            retrieve_tracker
rasa_1          | /status                                            GET                            status
rasa_1          | /model/predict                                     POST                           tracker_predict
rasa_1          | /model/train                                       POST                           train
rasa_1          | /model                                             DELETE                         unload_model
rasa_1          | /version                                           GET                            version
rasa_1          | 2019-10-09 08:51:29 INFO     root  - Starting Rasa server on http://localhost:5005
rasa_1          | 2019-10-09 08:51:29 INFO     root  - Enabling coroutine debugging. Loop id 94065175478200.
rasa_1          | 2019-10-09 08:51:30 DEBUG    rasa.model  - Extracted model to '/tmp/tmpcde2u75s'.
rasa_1          | 2019-10-09 08:52:21 INFO     rasa.nlu.components  - Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
rasa_1          | 2019-10-09 08:52:21 DEBUG    rasa.core.tracker_store  - Connected to InMemoryTrackerStore.
rasa_1          | 2019-10-09 08:52:21 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
rasa_1          | 2019-10-09 08:52:22 DEBUG    rasa.model  - Extracted model to '/tmp/tmpeydlibnp'.
```

I can test the Core model and it works (in some case I have core actions based on intent so send a message using curl or previous python script with "/hello" make the right things).
