### ISSUE TITLE
Spacy Model Linkage Error when launching Rasa X

### ISSUE THREAD

**Issue by jimbudarz** [RasaHQ/rasa#4650]
**Rasa version**: Rasa 1.2.7

**Rasa X version** (if used & relevant): 0.20.2

**Python version**: Python 3.7.3

**Operating system** (windows, osx, ...): OSX

**Issue**: 

When launching rasa x I get the following error on Mac OS X:

    rasa.core.agent  - Could not load model due to Model 'en_core_web_md' is not a linked spaCy model.  Please download and/or link a spaCy model, e.g. by running:
    python -m spacy download en_core_web_md
    python -m spacy link en_core_web_md en.

Due to network restrictions, I have downloaded the model as a tarball and linked it as follows:
`python -m spacy link ../SPACY_en_Models/en_core_web_md-2.1.0.tar.gz en`

This appears to have worked, based on the following output:

    Linking successful
    ../SPACY_en_Models/en_core_web_md-2.1.0.tar.gz -->
    /Users/username/anaconda3/lib/python3.7/site-packages/spacy/data/en

    You can now load the model via spacy.load('en')

However, it still results in the original error.

**Error (including full traceback)**:
```
rasa.core.agent  - Could not load model due to Model 'en_core_web_md' is not a linked spaCy model.  Please download and/or link a spaCy model, e.g. by running:
    python -m spacy download en_core_web_md
    python -m spacy link en_core_web_md en.
```

**Command or request that led to error**:
```
rasa x
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by amn41** [comment]
thanks for raising @jimbudarz - can you please share your config file? Can you try changing the `language` param from `en` to `en_core_web_md` ?

**Comment by jimbudarz** [comment]
Thanks @amn41 . Heres are the contents of the config file:

```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language:  en_core_web_md
pipeline: pretrained_embeddings_spacy

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy`
```
