### ISSUE TITLE
Except list slot type all the slots are converted to a single value

### ISSUE THREAD

**Issue by DivyashaAgrawal** [RasaHQ/rasa#4660]
**Rasa version**: latest

**Python version**: 3.6

**Operating system** (windows, osx, ...): windows

**Issue**:

All the slot types apart from list type slot get converted to a single value

**Content of domain file (domain.yml)** (if relevant):
```yml
entities:
 - cities
slot:
 cities:
  type: unfeaturized
```
Input: `/inform{"cities": ["new york", "paris"]}`
Current Output: `slot{"cities": "paris"}`
Expected Output: `slot{"cities": ["new york", "paris"]}`
