### ISSUE TITLE
"Received an action call without an action" - Custom Actions, POST Request

### ISSUE THREAD

**Issue by aejaex** [RasaHQ/rasa#4728]
**Rasa version**: 1.4.3

**Python version**: 3.7

**Operating system** (windows, osx, ...): Mac OS X High Sierra

**Issue**: Custom Action via POST Request not working

**Error (including full traceback)**: I have set up a custom action and defined it in my domain.yml, and also set up the endpoint in endpoint.yml at "http://localhost:5055/webhook", however, when I call the post request I get a 200 response but there is no output by the bot and I get a warning that "Received an action call without an action". If I call the action just by conversing with the bot it works well, the message is dispatched.
```

2019-11-05 19:14:14 WARNING  rasa_sdk.endpoint  - You are using an old version of rasa which might not be compatible with this version of rasa_sdk (1.4.0).
To ensure compatibility use the same version for both, modulo the last number, i.e. using version A.B.x the numbers A and B should be identical for both rasa and rasa_sdk.
2019-11-05 19:14:14 WARNING  rasa_sdk.executor  - Received an action call without an action.
127.0.0.1 - - [2019-11-05 19:14:14] "POST /webhook HTTP/1.1" 200 144 0.005133

```

**Content of configuration file (config.yml)** (if relevant):
```yml

language: en
pipeline: supervised_embeddings
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy

```

**Content of domain file (domain.yml)** (if relevant):
```yml

intents:
- greet
- goodbye
- affirm
- deny
- mood_great
- mood_unhappy
- bot_challenge
- bored
- joke


templates:
  utter_greet:
  - text: Hey! How are you?
  utter_cheer_up:
  - text: 'Here is something to cheer you up:'
    image: https://i.imgur.com/nGF1K8f.jpg
  utter_did_that_help:
  - text: Did that help you?
  utter_happy:
  - text: Great, carry on!
  utter_goodbye:
  - text: Bye
  utter_iamabot:
  - text: I am a bot, powered by Rasa.
  utter_joke:
  - text: Would you like to hear a joke?
  utter_onejoke:
  - text: There was once a person talking to a bot.
  utter_nojoke:
  - text: Alright, suit yourself.
  
  
actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye
- utter_iamabot
- utter_joke
- utter_onejoke
- utter_nojoke
- action_main

```

ACTION.PY

from rasa_sdk import Action
from rasa_sdk.events import SlotSet
from datetime import datetime
from crontab import CronTab
import schedule
import timE

class ActionMain(Action):
    
    def name(self):
        return "action_main"
    
    
    def run(self, dispatcher, tracker, domain):
        
        dispatcher.utter_message("Our chatbot is live")

        return []

     

POST REQUEST:

import requests
import json

url = 'http://localhost:5055/webhook'

#url = "http://localhost:5055/conversations/default/execute"

headers = {'Content-type': 'application/json'}

dx = json.dumps({"name": "action_main"})

requests.post(url, data=dx, headers=headers)

Please help me, I am not being able to call my custom action when running via post. Thanks.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Hi there @aejaex. From your code, it looks like you're posting to `/webhook`, not `/conversations/default/execute`. The latter is the correct endpoint for the external actions, can you confirm which you're using when you're getting the "received an action... " warning?

Also, what channel are you using to test this functionality?

**Comment by aejaex** [comment]
Hello @erohmensing, I tried using "/conversations/default/execute", however I get a 404 error in my terminal when I post to it. My full URL for POST requests is: 

http://localhost:5055/conversations/default/execute

and I have defined the same in my endpoints.yml file as well....

This is my POST request code:

/////////////////////////////
import requests
import json

url = "http://localhost:5055/conversations/default/execute"

headers = {'Content-type': 'application/json'}

dx = json.dumps({"name": "action_hello_world"})

requests.post(url, json={"name": "action_hello_world"}, headers=headers)

/////////////////////////////


Please help...

**Comment by erohmensing** [comment]
What command are you using to run your server? In order to use the /conversations/default/execute endpoint, you have to enable the api with the `--enable-api` flag.

**Comment by aejaex** [comment]
Hi @erohmensing , I have run my shell using the enable-api flag, using: "rasa shell --enable-api". The shell works fine, I can have my conversation. Then I run "rasa run actions" and activate my action server. However, I am still not able to call my actions through the API - I keep getting a 404 error.

My terminal output:
"POST /conversations/default/execute HTTP/1.1" 404 341 0.001052

My URL endpoint:
"http://localhost:5055/conversations/default/execute"

Please help...

**Comment by erohmensing** [comment]
Ah, I see the problem, I think. `POST /conversations/default/execute` is part of the Rasa API, not the rasa sdk (actions server) API. so you should be posting to 
```
"http://localhost:5005/conversations/default/execute"
```
instead of 
```
"http://localhost:5055/conversations/default/execute"
```
Didn't catch that in the initial code.

**Comment by aejaex** [comment]
@erohmensing Just tried that Ella - I don't get a response from the server when I change it to localhost:5005...

So just to add some details - 

1) I am running the rasa shell to test my bot, using "rasa shell" in my terminal. My shell activates on localhost:5005.

2) I run my actions using "rasa run actions" - My action server activates on localhost:5055.

Do I need to enable something in the credentials or any other file?

My credentials.yml looks like this:

```
# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/

rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials


#facebook:
#  verify: "<verify>"
#  secret: "<your secret>"
#  page-access-token: "<your page access token>"

#slack:
#  slack_token: "<your slack token>"
#  slack_channel: "<the slack channel>"

#socketio:
#  user_message_evt: <event name for user message>
#  bot_message_evt: <event name for but messages>
#  session_persistence: <true/false>

#mattermost:
#  url: "https://<mattermost instance>/api/v4"
#  team: "<mattermost team>"
#  user: "<bot username>"
#  pw: "<bot token>"
#  webhook_url: "<callback URL>"

rasa:
  url: "http://localhost:5002/api"
```

And my config.yml looks like:

```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: pretrained_embeddings_spacy

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.1
    ambiguity_threshold: 0.01
    core_threshold: 0.3
    fallback_action_name: "fallback_action"
```

My POST request file looks like:

```
import requests
import json

#url = 'http://localhost:5055/webhook'

url = "http://localhost:5005/conversations/default/execute"

headers = {'Content-type': 'application/json'}

dx = json.dumps({"name": "fallback_action"})

requests.post(url, data=dx, headers=headers)

```

And my endpoints.yml looks like:

```
# This file contains the different endpoints your bot can use.

# Server where the models are pulled from.
# https://rasa.com/docs/rasa/user-guide/running-the-server/#fetching-models-from-a-server/

#models:
#  url: http://my-server.com/models/default_core@latest
#  wait_time_between_pulls:  10   # [optional](default: 100)

# Server which runs your custom actions.
# https://rasa.com/docs/rasa/core/actions/#custom-actions/

action_endpoint:
  url: "http://localhost:5055/webhook"

# Tracker store which is used to store the conversations.
# By default the conversations are stored in memory.
# https://rasa.com/docs/rasa/api/tracker-stores/

#tracker_store:
#    type: redis
#    url: <host of the redis instance, e.g. localhost>
#    port: <port of your redis instance, usually 6379>
#    db: <number of your database within redis, e.g. 0>
#    password: <password used for authentication>
#    use_ssl: <whether or not the communication is encrypted, default false>

#tracker_store:
#    type: mongod
#    url: <url to your mongo instance, e.g. mongodb://localhost:27017>
#    db: <name of the db within your mongo instance, e.g. rasa>
#    username: <username used for authentication>
#    password: <password used for authentication>

# Event broker which all conversation events should be streamed to.
# https://rasa.com/docs/rasa/api/event-brokers/

#event_broker:
#  url: localhost
#  username: username
#  password: password
#  queue: queue
```


Again thanking you for your prompt response ! I have had good success using rasa for my chatbot's intelligence, but I now need to get it out of the terminal and into a production environment so needing this to work !
