### ISSUE TITLE
Spacy model won't train. Freezes at "[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers."

### ISSUE THREAD

**Issue by mroyce1** [RasaHQ/rasa#4730]
Hi,

when using spacy, rasa won't train the NLU model. It preoceeds until `[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.` and then just stays like this forever.
I tried several operating systems and python versions, but the problem persists. I don't think it's an issue of "giving it more time". I think it just freezes.

While I do have a lot of training data, supervised embeddings work just fine (and I would expect this to be slower). There is a thread about this issue on rasa forums which was however never resolved: https://forum.rasa.com/t/can-not-train-rasa-nlu-with-spacy-models/11374/3

**Rasa version**: 
rasa==1.4.3
rasa-nlu==0.14.3
rasa-sdk==1.4.0
(also happens with older versions)

**Python version**:
3.6.8
(also happens with 3.7)

**Operating system** (windows, osx, ...):
Both Windows 10 and Ubuntu 18.04

**Issue**:
Rasa won't train the NLU model when using spacy. It proceed's until

`Fitting 2 folds for each of 6 candidates, totalling 12 fits`
`[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.`

and then just stays like this forever. I left it like this for 12+ hours and nothing happened.
This happens with both `en_core_web_sm` and `en_core_web_md`

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "en"
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
  lowercase: true
- name: "SklearnIntentClassifier"
timezone: "Europe/Berlin"
case_sensitive: false

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: "KerasPolicy"
    featurizer:
    - name: "MaxHistoryTrackerFeaturizer"
      max_history: 5
      state_featurizer:
        - name: "LabelTokenizerSingleStateFeaturizer"
  - name: "MemoizationPolicy"
    max_history: 5
  - name: MappingPolicy
  - name: FormPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.75
    core_threshold: 0.45
    fallback_action_name: "action_default_ask_rephrase"
```
