### ISSUE TITLE
Text, image, and buttons response only return text and image

### ISSUE THREAD

**Issue by haydarai** [RasaHQ/rasa#4790]
**Rasa version**: 1.4.3

**Python version**: 3.7.4

**Operating system** (windows, osx, ...): OSX

**Issue**:
I am trying to return text, image, and buttons at the same time. But every time I check it using `rasa shell`, it only returns text and image. The buttons will show up if I remove the image entry, is this behavior expected?

**Content of domain file (domain.yml)** (if relevant):
```yml
utter_info:
  - text: "You may visit our page for the latest updates on our events."
    image: "https://..."
    buttons:
    - title: "Take survey"
      payload: '/request{"survey_name": "survey_name"}'
```
