### ISSUE TITLE
Rasa X not showing image when given local path (showing "broken image" icon instead)

### ISSUE THREAD

**Issue by snbuchholz** [RasaHQ/rasa#4958]
**Rasa version**: 1.5.

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.23.3

**Python version**: 3.7.1

**Operating system** (windows, osx, ...): OSX

**Issue**: I want my bot to show pictures that are generated on the fly by a custom action and use Rasa X for letting test users interact with the bot. The custom action stores the picture in a local path. However, while Rasa X does show pictures when given a URL (like with moodbot's tiger cub image), it only displays the "broken image" icon when given a local path to a picture. To reproduce this issue in a minimal way, simply take Rasa's moodbot and replace the value of the image attribute in 
```
  utter_cheer_up:
  - text: 'Here is something to cheer you up:'
    image: https://i.imgur.com/nGF1K8f.jpg
``` 
with a local path to the same image (after downloading it to there).
The screenshot shows the resulting conversation in Rasa X:
![rasax_screenshot](https://user-images.githubusercontent.com/2370438/70704179-66632800-1cc9-11ea-9f6d-781de6266f8c.png)

PS: It works when using the Webex Teams channel, so it seems to be a Rasa X rather than a Rasa issue.

There are some related questions on the forum [1](https://forum.rasa.com/t/not-able-to-use-local-images/14964/5), [2](https://forum.rasa.com/t/how-to-output-a-graph-in-the-chat/6919/3), but I could not find a bug report about it.

**Error (including full traceback)**:
No error message, just "broken image" icon

**Command or request that led to error**:
Conversation with bot in Rasa X

**Content of configuration file (config.yml)** (if relevant):
not relevant

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
- greet
- goodbye
- affirm
- deny
- mood_great
- mood_unhappy
- bot_challenge
templates:
  utter_greet:
  - text: Hey! How are you?
  utter_cheer_up:
  - text: 'Here is something to cheer you up:'
    image: file:///Users/s.buchholz/venv_my-rasa_new/nlp-rasa-code/init/tiger.jpg
  utter_did_that_help:
  - text: Did that help you?
  utter_happy:
  - text: Great, carry on!
  utter_goodbye:
  - text: Bye
  utter_iamabot:
  - text: I am a bot, powered by Rasa.
actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye
- utter_iamabot
```

PS: I followed [this forum post](https://forum.rasa.com/t/how-to-output-a-graph-in-the-chat/6919/3) for the syntax for a local path. Have tried variations (without file:// prefix, with quotation marks, just relative path) as well but did not make a difference.
