### ISSUE TITLE
Intent recognition is not happning properly.

### ISSUE THREAD

**Issue by sushilr007** [RasaHQ/rasa#4986]
**Rasa version**: 1.2.7

**Rasa SDK version** (if used & relevant): 

**Rasa X version** (if used & relevant):

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): Win 10

**Issue**:  I am giving input as "kids friendly" expected answer is "kids are playing" but its always recognizing the action_default_fallback. Confidence for kids play in "0.8".

**Error (including full traceback)**:
```

```

**Command or request that led to error**: 
```

```

**Content of configuration file (config.yml)** (if relevant): 
```yml
language: "en"
pipeline:
- name: "WhitespaceTokenizer"
- name: "CountVectorsFeaturizer"
  token_pattern: '(?u)\b\w+\b'
  max_ngram: 2
- name: "RegexFeaturizer"
- name: "EmbeddingIntentClassifier"

policies:
  - name: "KerasPolicy"
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 5
      state_featurizer:
        - name: BinarySingleStateFeaturizer
    epochs: 500
    batch_size: 100
    validation_split: 0.2
  - name: "MemoizationPolicy"
    max_history: 5
  - name: "FallbackPolicy"
    nlu_threshold: 0.5
    core_threshold: 0.2
    fallback_action_name: "action_default_fallback"
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
- kids_friendly

templates:
  utter_kids_friendly: 
  - text: "kids are playing"

actions:
- utter_kids_friendly

```
