### ISSUE TITLE
Cannot run docker-compose up or deploy to AWS EB - Permission denied at pip install stage

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#5058]
**Rasa version**: `rasa:1.6.1-spacy-en`

**Rasa SDK version** (if used & relevant): `1.6.1`

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu / 

**Issue**:
I am updating from Rasa 1.3.3 to Rasa 1.6.1. When trying to run `docker-compose up` locally or when deploying to AWS Elastic Beanstalk (on multi-container instances), I get permission errors when packages are installed within the container (see error below). 

**Error (including full traceback)**:
```
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
pip install -r requirements.txt --no-cache-dir

...

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/build/lib/python3.6/site-packages/pytzdata-2019.3.dist-info'
Consider using the `--user` option or check the permissions.
```

**Command or request that led to error**:
Locally: `docker-compose up`

On AWS Elastic Beanstalk: `eb deploy`

**Comment by nbeuchat** [comment]
Here is my docker-compose file:

```
version: '3.0'

services:
  chatbot:
    image: rasa/rasa:1.6.1-spacy-en
    ports:
      - 5005:5005
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh
    environment:
      - PYTHONPATH=$PYTHONPATH:/app
    command:
      - run
      - "--debug"
      - "--enable-api"
      - "--cors \"*\""
    entrypoint:
      - /bin/bash
      - /app/entrypoint.sh
  action_server:
    image: rasa/rasa-sdk:1.6.1
    volumes:
      - ./actions:/app/actions
      - ./action_server/requirements.txt:/app/requirements.txt
      - ./action_server/entrypoint.sh:/app/entrypoint.sh
      - ./endpoints.yml:/app/endpoints.yml
      - ./domain.yml:/app/domain.yml
      - ~/.ssh:/root/.ssh
    command:
      - start
      - "--actions"
      - "actions"
```
