### ISSUE TITLE
User input starting with a slash is interpreted as an intent

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#5075]
**Rasa version**: 1.6.1

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
When a user enters an input with a slash such as `/start`, Rasa NLU recognizes this input as the intent `start` with 100% confidence even though the intent does not exist in the domain file. 

I tried adding `/start` in the NLU training data for another intent (`greeting`) but it still recognizes it as `start`. 

Note that the same thing happens with inputs such as `/ start`, `/ get started` (recognized intent: `get started`), etc.

**Error (including full traceback)**:
Entering `/start` in the Rasa shell returns: 
```
{
  "text": "/start",
  "intent": {
    "name": "start",
    "confidence": 1.0
  },
  "intent_ranking": [
    {
      "name": "start",
      "confidence": 1.0
    }
  ],
  "entities": []
}
```
while entering `start` in the Rasa shell correctly returns: 
```
{
  "intent": {
    "name": "greeting",
    "confidence": 0.9929155111312866
  },
  "entities": [],
  },
  "intent_ranking": [
    {
      "name": "greeting",
      "confidence": 0.9929155111312866
    },
    ...
  ],
  "text": "start"
}
```

**Command or request that led to error**:
```
rasa shell nlu
/start
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "en"
pipeline:
  - name: "SpacyNLP"
    case_sensitive: true
  - name: "SpacyTokenizer"
  - name: "SpacyEntityExtractor"
    dimensions: [...]
  - name: "DucklingHTTPExtractor"
    url: ...
    dimensions: ["time", ...]
    timezone: "America/New_York"
  - name: "RegexFeaturizer"
  - name: "SpacyFeaturizer"
  - name: "CRFEntityExtractor"
    features: [...]
  - name: "EntitySynonymMapper"
  - name: "EmbeddingIntentClassifier"
```

**Content of domain file (domain.yml)** (if relevant):
`start` is *not* present in the domain file
