### ISSUE TITLE
Setting config flags in domain is ignored

### ISSUE THREAD

**Issue by IgNoRaNt23** [RasaHQ/rasa#5182]
There's the option to set flags in the domain via
`config:
  store_entities_as_slots: true`

where `store_entites_as_slots = True` is the default value used, when no option is entered.  See https://github.com/RasaHQ/rasa/blob/80ab6e894f1240813fa082adbb2cb18ef38224d1/rasa/core/domain.py#L344

Now, if a domain is created and the value is manually set to false. The setting will be ignored and be set to `true`. For example, if a model is trained with said domain, the domain-file that is saved in the model tar-file, will have the value set to true again.

This is a blocker for https://github.com/RasaHQ/rasa/issues/4884

**Rasa version**:
1.61

**Python version**:
3.6.9

**Operating system** (windows, osx, ...):
Ubuntu

**Issue**:
See above

**Content of domain file before model training (domain.yml)** (if relevant):
```yml
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - bot_challenge

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye
- utter_iamabot

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great, carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_iamabot:
  - text: "I am a bot, powered by Rasa."

config:
  store_entities_as_slots: false

```

**Content of domain file inside trained model tar-file (core/domain.yml)** (if relevant):
```yml
actions:
- utter_cheer_up
- utter_did_that_help
- utter_goodbye
- utter_greet
- utter_happy
- utter_iamabot
config:
  store_entities_as_slots: true
entities: []
forms: []
intents:
- greet:
    ignore_entities: []
    use_entities: true
- goodbye:
    ignore_entities: []
    use_entities: true
- affirm:
    ignore_entities: []
    use_entities: true
- deny:
    ignore_entities: []
    use_entities: true
- mood_great:
    ignore_entities: []
    use_entities: true
- mood_unhappy:
    ignore_entities: []
    use_entities: true
- bot_challenge:
    ignore_entities: []
    use_entities: true
slots: {}
templates:
  utter_cheer_up:
  - image: https://i.imgur.com/nGF1K8f.jpg
    text: 'Here is something to cheer you up:'
  utter_did_that_help:
  - text: Did that help you?
  utter_goodbye:
  - text: Bye
  utter_greet:
  - text: Hey! How are you?
  utter_happy:
  - text: Great, carry on!
  utter_iamabot:
  - text: I am a bot, powered by Rasa.
```
