### ISSUE TITLE
Rasa1.7.1 segmentation fault(core dumped)

### ISSUE THREAD

**Issue by gitpranjal** [RasaHQ/rasa#5228]
**Rasa version**:

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):
1.7.1

**Python version**:
3.6.8

**Operating system** (windows, osx, ...):
Ubuntu18.04LTS

**Issue**:
Segmentation fault(core dumped) upon attempting to training the rasa core model

**Error (including full traceback)**:
```
Segmentation fault (core dumped)
```

**Command or request that led to error**:
```
rasa train -c config_bluekaktus_-_manufacturing.yml --out models

```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
- name: "SpacyNLP"
  case_sensitive: false
- name: "SpacyTokenizer"
- name: "CountVectorsFeaturizer"
  analyzer: 'word'
  min_ngram: 1
  max_ngram: 3
  lowercase: true
  OOV_token: oov
  return_sequence: true
- name: "SpacyFeaturizer"
  return_sequence: true
- name: "RegexFeaturizer"
  return_sequence: true
- name: "SpacyEntityExtractor"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "EmbeddingIntentClassifier"
  loss_type: "margin"
- name: "ResponseSelector"
- name: "retrieval_action_fallback.ResponseThreshold"


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: "MemoizationPolicy"
    max_history: 81
  - name: "KerasPolicy"
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 81
      state_featurizer:
        - name: BinarySingleStateFeaturizer
  - name: "MappingPolicy"
  - name: "FormPolicy"
  - name: "FallbackPolicy"
    nlu_threshold: 0.6
    core_threshold: 0.3
    fallback_action_name: "action_default_fallback"


importers:
- name: "RasaFileImporter"
- name: "my_training_data_importer.MyImporter"
  project_name: "bluekaktus_-_manufacturing"
```

**Content of domain file (domain.yml)** (if relevant):
```yml
