### ISSUE TITLE
RASA always tries to match a intent even if there is no match

### ISSUE THREAD

**Issue by code4passion** [RasaHQ/rasa#5260]
I trained rasa nlu against some examples. It works great when the query matches  one of the intent. But if the query doesnot match any intent than it still matches one of the intent with high score.

For example i tried rasa on this big data set https://github.com/nghuyong/rasa-nlu-benchmark/tree/master/data/Facebook%20Multilingual%20Task%20Oriented%20Dataset.

If i enter a rubbish query "kk" it still matched a intent with 0.7 confidence

```
"intent": {
    "name": "cancel_alarm",
    "confidence": 0.7932985443952425
  },
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
@code4passion this is likely not a bug, but what pipeline are you using?

**Comment by code4passion** [comment]
pretrained_embeddings_spacy

config.yml
```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: pretrained_embeddings_spacy
#supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

```
