### ISSUE TITLE
ResponseSelector training not working 

### ISSUE THREAD

**Issue by tpinju00** [RasaHQ/rasa#5344]
**Rasa version**: 1.8.0

**Python version**: 3.7

**Operating system** (windows, osx, ...): Linux (Docker)

**Issue**:

While training my model everything works properly and just fails when it comes to training the response selector, that component doesn't get trained and console just exits training in general.

**Error (including full traceback)**:
```
https://forum.rasa.com/uploads/default/optimized/2X/3/3703407eb64f849ce9c349d01619dd8fd6b59d04_2_1035x357.png
```

**Command or request that led to error**:
```
docker run -it -p 8080:5005 -v myPath:/app ImageBuiltFromOfficialRasaDockerfile train --domain domain.yml --data data --out models
```

**Content of configuration file (config.yml)** (if relevant):
```yml
pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
analyzer: "char_wb"
min_ngram: 1
max_ngram: 4
  - name: DIETClassifier
epochs: 1
  - name: EntitySynonymMapper
epochs: 1
  - name: ResponseSelector
epochs: 1


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```
