### ISSUE TITLE
response ending in 2 newlines leads to empty message

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#5361]
If you define your response using the `+|` format in YAML, 
```yaml
  utter_newline:
    - text: |+
          This is one part of my response:  
          
          Something 
          Something else

  utter_other:
...
```

the representation of this automatically ends in `\n\n`. However since we split based on those characters, you end up with an empty message, e.g. in the rest channel:
```
[
  {
    “recipient_id”: “test1",
    “text”: “This is one part of my response:  ”
  },
  {
    “recipient_id”: “test1",
    “text”: “Something  \n20910 Something else”
  },
  {
    “recipient_id”: “test1",
    “text”: “”
  }
]
```
