### ISSUE TITLE
CRFEntityExtractor splits one entity into two

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5377]
**Rasa version**: 1.8.0
**Python version**: 3.7
**Operating system** (windows, osx, ...): OSX

**Issue**:
If the `CRFEntityExtractor` is trained with `BILOU_flag` set to `False` entities consisting of two words are shown as individual entities and are not combined. 

In [this function](https://github.com/RasaHQ/rasa/blob/1c627fe2dbf92d41cfa3a685b0b66e5d1b4367dc/rasa/nlu/extractors/crf_entity_extractor.py#L323), we do not combine entities that have the same type and occur directly after each other. 

Forum thread: https://forum.rasa.com/t/lookup-table-not-working-for-entities-with-multiple-words/25305

**Command to reproduce bug**:
To reproduce the error, train the `restaurantbot` example with the config below.
```
rasa train nlu
```
If you execute afterwards `rasa shell nlu` and enter `north american food`, you will get something like:
```
  "entities": [
    {
      "start": 0,
      "end": 5,
      "value": "north",
      "entity": "cuisine",
      "confidence": 0.8311922393651153,
      "extractor": "CRFEntityExtractor"
    },
    {
      "start": 6,
      "end": 14,
      "value": "american",
      "entity": "cuisine",
      "confidence": 0.9248010334484645,
      "extractor": "CRFEntityExtractor"
    }
  ],
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
  BILOU_flag: False
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
```
