### ISSUE TITLE
OOV token and special tokenizers

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5383]
**Description of Problem**: The `CountVectorFeaturizer` checks if the given `OOV_token` is present in the data or not. If it is not present it logs a warning. When a special tokenizer is used, for example `ConveRTTokenizer`, tokens get split into sub-tokens. The OOV token might be also split into sub-tokens, for example, `ConveRTTokenizer` splits `oov` into `oo` and `v`. In that case the check if the OOV token is present in the training data would fail as the token `oov` is not in the list <span class="error">[`oo`, `v`]</span>.

**Overview of the Solution**: Two ideas:

*   Move the OOV token to the tokenizer itself. The tokenizer would tokenize the OOV token and add it to the message object.
*   Use the actual token object in the check in `CountVectorsFeaturizer` and take the start and end positions of tokens into account.

**Comment by Akhil-YS** [comment]
Hi @tabergma .
I am trying to extract any person's name from a sentence using `oov` and  `CountVectorFeaturizer` by following Sara bot.  I see that it's not working as expected i.e. some names are not getting extracted even if the sentence is given as it is in the training data and I'm getting the following logs. Is it because of what you have mentioned above?

![image](https://user-images.githubusercontent.com/67151916/91933346-4d425180-ed06-11ea-8a76-4e207564d6b4.png)




```
## intent:inform
- My name is [James](name)
- my name is [Leota](name)
- Ok, it is [Minna](name)
- Its [Donette](name)
- It is [Abel](name)
- My name is oov
- my name is oov
- Ok, it is oov
- Its oov
- It is oov
- oov
- [Louis](name)
- [Josephine](name)
- [Lenna](name)
- [Mitsue](name)
- [Sage](name)
- [Kris](name)
- [Kiley](name)
- [Graciela](name)
```
My config.yml

```
language: en
pipeline:
  - name: SpacyNLP
    case_sensitive: False
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    OOV_token: oov
    token_pattern: (?u)\b\w+\b
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: FormPolicy
```
![image](https://user-images.githubusercontent.com/67151916/91932456-d5732780-ed03-11ea-8d61-b67acc6dde47.png)

Please let me know if I am doing anything wrong here.
