### ISSUE TITLE
Separation of dense vs. sparse featurizers breaks backward compatibility for <= 1.5.3 builds

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#5403]
**Rasa version**: 1.4.6

**Rasa SDK version** (if used & relevant): 1.4.0

**Rasa X version** (if used & relevant): N/A

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): Docker

**Issue**: Attempting to train or run older versions (<=1.5.3) of Rasa fails with below traceback.

The issue appears to be attempting to access `rasa.nlu.featurizers.sparse_featurizer.regex_featurizer`, which does not exist in the `1.4.6` tagged repo's `rasa/nlu/featurizers` directory.  I'm guessing the issue came about when the sparse vs. dense featurizer split happened.

Is there a way to prevent this kind of thing from happening in the future?  It's not a good experience to pin a Rasa version only to have breaking changes in higher versions that aren't being used to impact my experience.  Docker images especially should be resistant to this sort of issue, but now I have to dedicate some time to upgrade my rasa deployments to match the current version's repo and retrain a model.

**Error (including full traceback)**:
```
rasa_1           | 2020-03-10 17:43:26 DEBUG    rasa.core.tracker_store  - Connected to MongoTrackerStore.
rasa_1           | 2020-03-10 17:43:26 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
rasa_1           | 2020-03-10 17:43:26 DEBUG    rasa.model  - Extracted model to '/tmp/tmpzh4p42qu'.
rasa_1           | 2020-03-10 17:43:26 ERROR    rasa.core.agent  - Could not load model due to Failed to find module 'rasa.nlu.featurizers.sparse_featurizer.regex_featurizer'. 
rasa_1           | No module named 'rasa.nlu.featurizers.sparse_featurizer'.
rasa_1           | [2020-03-10 17:43:26 +0000] [1] [ERROR] Experienced exception while trying to serve
rasa_1           | Traceback (most recent call last):
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/nlu/registry.py", line 146, in get_component_class
rasa_1           |     return class_from_module_path(component_name)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/utils/common.py", line 180, in class_from_module_path
rasa_1           |     m = importlib.import_module(module_name)
rasa_1           |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
rasa_1           |     return _bootstrap._gcd_import(name[level:], package, level)
rasa_1           |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
rasa_1           |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
rasa_1           |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
rasa_1           |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
rasa_1           |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
rasa_1           |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
rasa_1           |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
rasa_1           | ModuleNotFoundError: No module named 'rasa.nlu.featurizers.sparse_featurizer'
rasa_1           | 
rasa_1           | During handling of the above exception, another exception occurred:
rasa_1           | 
rasa_1           | Traceback (most recent call last):
rasa_1           |   File "/build/lib/python3.6/site-packages/sanic/app.py", line 1135, in run
rasa_1           |     serve(**server_settings)
rasa_1           |   File "/build/lib/python3.6/site-packages/sanic/server.py", line 775, in serve
rasa_1           |     trigger_events(before_start, loop)
rasa_1           |   File "/build/lib/python3.6/site-packages/sanic/server.py", line 633, in trigger_events
rasa_1           |     loop.run_until_complete(result)
rasa_1           |   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/run.py", line 249, in load_agent_on_start
rasa_1           |     action_endpoint=endpoints.action,
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/agent.py", line 262, in load_agent
rasa_1           |     remote_storage=remote_storage,
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/agent.py", line 914, in load_local_model
rasa_1           |     remote_storage=remote_storage,
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/agent.py", line 374, in load
rasa_1           |     interpreter = NaturalLanguageInterpreter.create(nlu_model)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/interpreter.py", line 57, in create
rasa_1           |     return RasaNLUInterpreter(model_directory=obj)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/interpreter.py", line 259, in __init__
rasa_1           |     self._load_interpreter()
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/interpreter.py", line 282, in _load_interpreter
rasa_1           |     self.interpreter = Interpreter.load(self.model_directory)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/nlu/model.py", line 305, in load
rasa_1           |     return Interpreter.create(model_metadata, component_builder, skip_validation)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/nlu/model.py", line 327, in create
rasa_1           |     components.validate_requirements(model_metadata.component_classes)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/nlu/components.py", line 38, in validate_requirements
rasa_1           |     component_class = registry.get_component_class(component_name)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/nlu/registry.py", line 175, in get_component_class
rasa_1           |     raise ModuleNotFoundError(exception_message)
rasa_1           | ModuleNotFoundError: Failed to find module 'rasa.nlu.featurizers.sparse_featurizer.regex_featurizer'. 
rasa_1           | No module named 'rasa.nlu.featurizers.sparse_featurizer'
rasa_1           | Traceback (most recent call last):
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/nlu/registry.py", line 146, in get_component_class
rasa_1           |     return class_from_module_path(component_name)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/utils/common.py", line 180, in class_from_module_path
rasa_1           |     m = importlib.import_module(module_name)
rasa_1           |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
rasa_1           |     return _bootstrap._gcd_import(name[level:], package, level)
rasa_1           |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
rasa_1           |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
rasa_1           |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
rasa_1           |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
rasa_1           |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
rasa_1           |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
rasa_1           |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
rasa_1           | ModuleNotFoundError: No module named 'rasa.nlu.featurizers.sparse_featurizer'
rasa_1           | 
rasa_1           | During handling of the above exception, another exception occurred:
rasa_1           | 
rasa_1           | Traceback (most recent call last):
rasa_1           |   File "/build/bin/rasa", line 11, in <module>
rasa_1           |     load_entry_point('rasa==1.4.6', 'console_scripts', 'rasa')()
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
rasa_1           |     cmdline_arguments.func(cmdline_arguments)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/cli/run.py", line 83, in run
rasa_1           |     rasa.run(**vars(args))
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/run.py", line 56, in run
rasa_1           |     **kwargs,
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/run.py", line 205, in serve_application
rasa_1           |     endpoints.lock_store if endpoints else None
rasa_1           |   File "/build/lib/python3.6/site-packages/sanic/app.py", line 1135, in run
rasa_1           |     serve(**server_settings)
rasa_1           |   File "/build/lib/python3.6/site-packages/sanic/server.py", line 775, in serve
rasa_1           |     trigger_events(before_start, loop)
rasa_1           |   File "/build/lib/python3.6/site-packages/sanic/server.py", line 633, in trigger_events
rasa_1           |     loop.run_until_complete(result)
rasa_1           |   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/run.py", line 249, in load_agent_on_start
rasa_1           |     action_endpoint=endpoints.action,
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/agent.py", line 262, in load_agent
rasa_1           |     remote_storage=remote_storage,
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/agent.py", line 914, in load_local_model
rasa_1           |     remote_storage=remote_storage,
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/agent.py", line 374, in load
rasa_1           |     interpreter = NaturalLanguageInterpreter.create(nlu_model)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/interpreter.py", line 57, in create
rasa_1           |     return RasaNLUInterpreter(model_directory=obj)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/interpreter.py", line 259, in __init__
rasa_1           |     self._load_interpreter()
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/core/interpreter.py", line 282, in _load_interpreter
rasa_1           |     self.interpreter = Interpreter.load(self.model_directory)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/nlu/model.py", line 305, in load
rasa_1           |     return Interpreter.create(model_metadata, component_builder, skip_validation)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/nlu/model.py", line 327, in create
rasa_1           |     components.validate_requirements(model_metadata.component_classes)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/nlu/components.py", line 38, in validate_requirements
rasa_1           |     component_class = registry.get_component_class(component_name)
rasa_1           |   File "/build/lib/python3.6/site-packages/rasa/nlu/registry.py", line 175, in get_component_class
rasa_1           |     raise ModuleNotFoundError(exception_message)
rasa_1           | ModuleNotFoundError: Failed to find module 'rasa.nlu.featurizers.sparse_featurizer.regex_featurizer'. 
rasa_1           | No module named 'rasa.nlu.featurizers.sparse_featurizer'
```

**Command or request that led to error**:
```
docker-compose run
```
`docker-compose.yml`:
```
version: "3.0"

services:
  rasa:
    image: rasa/rasa:1.4.6
    networks:
      - rasa-network
    ports:
      - 5005:5005
      - 5006:5006
    volumes:
      - ./:/app
    command:
      - run
      - -vv
      - -m
      - models
      - --endpoints
      - config/endpoints_dev.yml
      - --credentials
      - config/credentials.yml
      - --log-file
      - ./rasa.log
      - --enable-api
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
- name: WhitespaceTokenizer
  intent_split_symbol: _
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: EmbeddingIntentClassifier
  batch_size: 512
  loss_type: margin
- name: DucklingHTTPExtractor
  url: http://duckling:8000
  dimensions:
  - time
  - number
  - phone-number
  locale: en_US
  timezone: America/New_York
policies:
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.5
  ambiguity_threshold: 0.01
  core_threshold: 0.01
  fallback_core_action_name: action_default_fallback
  fallback_nlu_action_name: flag_conversation_for_review
  deny_suggestion_intent_name: incorrect_intent
- name: AugmentedMemoizationPolicy
  max_history: 10
- name: MappingPolicy
- name: KerasPolicy
  epochs: 250
  batch_size: 512
  featurizer:
  - name: MaxHistoryTrackerFeaturizer
    max_history: 10
    state_featurizer:
    - name: BinarySingleStateFeaturizer
```
