### ISSUE TITLE
Rasa X missing SQL Event Consumer

### ISSUE THREAD

**Issue by ncrmro** [RasaHQ/rasa#5491]
When trying to use Postgres as an event_broker I get the following error.

```
Could not configure valid event consumer. Exiting.
/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py:1397: UserWarning: Found event broker `EndpointConfig` of type 'sql', which is not supported.
```

```
event_broker:
  type: "sql"
  url: ${DB_HOST}
  port: 5432
  dialect: postgresql
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  db: event_broker
```
My Event Broker config looks like

```
Could not configure valid event consumer. Exiting.
/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py:1397: UserWarning: Found event broker `EndpointConfig` of type 'sql', which is not supported.
```

Can see the missing SQL portion here in rasa-x.

`rasax/community/services/event_consumers/utils.py`

But here here in rasa it does have SQL.
`rasa/core/brokers/broker.py`

This is in the docs so just wondering whats up?

https://rasa.com/docs/rasa/api/event-brokers/#sql-event-broker
