### ISSUE TITLE
Make NLU configuration more flexible

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#5510]
**Description of Problem**:
Currently, the NLU pipeline is interpreted as a flat pipeline where each component produces annotations, i.e. tokens, sparse features, dense features, etc. and then they are finally consumed by all the ML components present in the pipeline. This used to work well when we were dealing with a smaller number of ML tasks in the same pipeline, i.e. intent classification and entity recognition. As we keep adding more ML tasks as part of our NLU pipeline, like response selection, the idea doesn't scale well because the same set of featurizers are not useful for every ML task and may actually degrade the performance for some.
It would be better if each ML component can take as input which featurizers should be used for its modelling.

**Overview of the Solution**:
We add an extra parameter to each component which sets an alias for it in the configuration. That alias can be used in the downstream ML component.

For example - 

```
- pipeline:
   - name: WhitespaceTokenizer
   - name: CountVectorsFeaturizer
      alias: cvf_word
   - name: CountVectorsFeaturizer
      analyzer: char
      min_ngram: 1
      max_ngram: 4
      alias: cvf_char
   - name: DIETClassifier
      in: [cvf_word, cvf_char]
   - name: ResponseSelector
      in: [cvf_word]
```

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog
