### ISSUE TITLE
Parameter "share_hidden_layers" not compatible with RegexFeaturizer/LexicalSyntacticFeaturizer

### ISSUE THREAD

**Issue by hotzenklotz** [RasaHQ/rasa#5528]
**Rasa version**:
1.9.3

**Rasa SDK version** (if used & relevant):
1.9.0

**Rasa X version** (if used & relevant):
not used

**Python version**:
3.7

**Operating system** (windows, osx, ...):
OSX

**Issue**:
Training a response selector / DIET classifier with the parameter `share_hidden_layers: true` leads to the following error, even though the text+label dimension were configure to be of equal size in the config:

```
ValueError: If embeddings are shared text features and label features must coincide. Check the output dimensions of previous components.
```

Suggested fix by @Ghostvv : Removing the `RegexFeaturizer` and the `LexicalSyntacticFeaturizer` from my config solved the issue. Looks like Rasa is attaching some features to either the text or label vectors internally that breaks the `share_hidden_layers` parameter.

Breaking NLU config:
```yml
pipeline:
  - name: HFTransformersNLP
    model_name: "bert"
    model_weights: "bert-base-german-cased"
  - name: "LanguageModelTokenizer"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: LanguageModelFeaturizer
  - name: CountVectorsFeaturizer
    lowercase: false
    use_shared_vocab: true
  - name: DIETClassifier
    epochs: 50
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 500
    share_hidden_layers: true
    hidden_layers_sizes:
      text: [256, 128]
      label: [256, 128]
```

**Error (including full traceback)**:
```
ValueError: If embeddings are shared text features and label features must coincide. Check the output dimensions of previous components.
```
in `diet_classifier.py`, line ~400
see method `_check_input_dimension_consistency`

**Command or request that led to error**:
```
rasa train / rasa train with cross_validation
```
