### ISSUE TITLE
Rasa does not pick up all spaCy entities. 

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#5708]
This issue was discovered while writing a guide on how to link a custom spaCy model to Rasa. The git for that guide can be found [here](https://github.com/RasaHQ/spaCy-integration-demo). 

I have a custom spaCy model that matches patterns. In particular it matches `python` and `go` to be programming language entities.

Here's the `config.yml`.

```
language: en

pipeline:
- name: SpacyNLP
  model: "en_proglang"
- name: SpacyTokenizer
- name: SpacyEntityExtractor
  dimensions: ["PROGLANG"]
- name: SpacyFeaturizer
  pooling: mean
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 1

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

This pipeline is only supposed to detect entities, that's why `epochs=1`. Let's now run this to see what it does. 

```
> rasa train; rasa shell nlu
... 
NLU model loaded. Type a message and press enter to parse it.
Next message:
i program with python and go
{
   ...
  "entities": [
    {
      "entity": "PROGLANG",
      "value": "go",
      "start": 26,
      "confidence": null,
      "end": 28,
      "extractor": "SpacyEntityExtractor"
    }
  ],
...
```

That's odd. It only detected `go` here. Let's try another sentence. 

```
Next message:
i program with python       
...
  "entities": [
    {
      "entity": "PROGLANG",
      "value": "python",
      "start": 15,
      "confidence": null,
      "end": 21,
      "extractor": "SpacyEntityExtractor"
    }
...
```

That's really weird. So let's check what happens when I run this directly with `spaCy`. 

```
> python
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy 
>>> nlp = spacy.load("en_proglang")
>>> nlp("i program with python and go").ents
(python, go)
```

So spaCy locally can detect both, but Rasa only seems to pick up the most recent one. This feels like a bug. 

```
python3.7

rasa==1.9.6
spacy==2.2.4
```
