### ISSUE TITLE
conveRT dependency (tensorflow_text) not installed by default

### ISSUE THREAD

**Issue by visvamba** [RasaHQ/rasa#5733]
**Rasa version**: 1.8.1

**Python version**: 3.7.4

**Operating system** (windows, osx, ...): MacOS Catalina 10.15.3

**Issue**: `tensorflow_text` package necessary for `conveRT`, but is not installed by default.

**Error (including full traceback)**:
```
2020-04-28 15:37:39 WARNING  rasa.nlu.test  - Training model 'conveRT' failed. Error: Not all required importable packages are installed. To use this pipeline, you need to install the missing dependencies. Please install the package(s) that contain the module(s): tensorflow_text
```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "en"

pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: FormPolicy
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.5
    core_threshold: 0.5
    fallback_action_name: "action_default_fallback"
```
