### ISSUE TITLE
Case insensitive token with WhitespaceTokenizer

### ISSUE THREAD

**Issue by mrcsilverfox** [RasaHQ/rasa#5750]
**Rasa version**: 1.9.7

**Python version**: 3.6.10

**Operating system**: osx

**Issue**: When I'd updated the rasa image version from 1.4.6 to 1.9.7, the tokens are not case insensitive. Entities are recognise well, but the value is case sensitive. 

I train only the nlu model with both version and I tested in both case with a word: Chef

**Content of configuration file (config.yml)**: This is a config file of v.1.9.7.
```yml
language: it
pipeline:
- name: WhitespaceTokenizer
  # Text will be tokenized with case sensitive as default
  "case_sensitive": false # or False, and case_sensitive without quotes
- name: RegexFeaturizer
- name: DucklingHTTPExtractor
  # url: http://localhost:8000 # on localhost
  url: http://duckling:8000 # on docker container
  dimensions:
  - time
  - number
  locale: it_IT
  timezone: Europe/Rome
- name: LexicalSyntacticFeaturizer
  features: [
    ["low", "upper"],
    [
      "BOS",
      "EOS",
      "low",
      "prefix5",
      "prefix2",
      "suffix5",
      "suffix3",
      "suffix2",
      "upper",
      # "title",
      "digit",
    ],
    ["low", "upper"],
  ]
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  number_of_transformer_layers: 0
  epochs: 75 # 50
policies:
- name: MemoizationPolicy
# - name: KerasPolicy
- name: TEDPolicy
  max_history: 10
  epochs: 100
  batch_size: [32, 64]
- name: MappingPolicy
- name: FormPolicy
- name: "FallbackPolicy"
  nlu_threshold: 0.4 # intent recognition
  core_threshold: 0.3 # dialogue
  fallback_action_name: "action_default_fallback"
```

**Content of configuration file (config.yml)**: This is a config file of v.1.4.6
```yml
language: it
pipeline:
- name: WhitespaceTokenizer
  case_sensitive: false
- name: RegexFeaturizer
- name: DucklingHTTPExtractor
  # url: http://localhost:8000 # on localhost
  url: http://duckling:8000 # on docker container
  dimensions:
  - time
  - number
  locale: it_IT
  timezone: Europe/Rome
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: EmbeddingIntentClassifier
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: FormPolicy
- name: "FallbackPolicy"
  nlu_threshold: 0.4 # intent recognition
  core_threshold: 0.3 # dialogue policies
  fallback_action_name: "action_default_fallback"
```

**Command and results with rasa v 1.9.7**
```code
docker run -it -v $(pwd):/app rasa/rasa:1.9.7 shell -m models/nlu-model-with-ted-v.1.9.7.tar.gz

{
  "intent": {
    "name": "request",
    "confidence": 0.9788008332252502
  },
  "entities": [
    {
      "entity": "object_type",
      "start": 0,
      "end": 4,
      "extractor": "DIETClassifier",
      "value": "Chef"
    }
  ],
…
}
```

**Command and results with rasa v 1.4.6**
```
docker run -it -v $(pwd):/app rasa/rasa:1.4.6 shell

{
  "intent": {
    "name": "request",
    "confidence": 0.9743005633354187
  },
  "entities": [
    {
      "start": 0,
      "end": 4,
      "value": "chef",
      "entity": "object_type",
      "confidence": 0.9920963780816914,
      "extractor": "CRFEntityExtractor"
    }
  ],
…
}
```

The outcome of previous version is correct, while the upgraded version doesn't work well.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
Actually, this is not a bug. The `case_sensitive` flag in the `WhitespaceTokenizer` still works. If you set `case_sensitive: False` in the config, the tokens will be lower cased. As the tokens are used for further processing, all components will use the lower cased tokens. However, when we extract the entities, the entity extractor gives us the start and end value of the entity in the text. The value of the entity is then extracted from the original text again, which was not lower cased. So, internally we treat everything as lower cased, but externally you may not notice it.

**Comment by mrcsilverfox** [comment]
Thanks for your answer, @tabergma but so, what can I do to achieve the same result?

**Comment by tabergma** [comment]
You cannot. Why is it important for you to get the lower cased version in the entity value?

**Comment by mrcsilverfox** [comment]
Because in this case, I set `object_type` as a categorical slot, with values in lower case, so when I get it not in lower case, the dialogue fails. 

This is an example of story: 
```
## search chef
* greet
  - utter_greet
* request
  - action_check_entities
  - slot{"object_type": "chef"}
  - do something
```
and this is a domain.yml 
```
 object_type:
    type: categorical
    values:
    - menu
    - chef
    - "['menu', 'chef']"
    - "['chef', 'menu']"
    auto_fill: false
```

**Comment by tabergma** [comment]
As some users actually require the text to be in its original form, we will not update the current behaviour. However, you have a couple of options:

(1) You could just add the case sensitive version to the `object_type` values
```
 object_type:
    type: categorical
    values:
    - menu
    - Menu
    - chef
    - Chef
    - "['menu', 'chef']"
    - "['Menu', 'Chef']"
    - "['chef', 'menu']"
    - "['Chef', 'Menu']"
    auto_fill: false
```

(2) Another option would be to create a [custom component](https://rasa.com/docs/rasa/api/custom-nlu-components/#id1) that lower cases the incoming text. You could put this component before the tokenizer itself.

(3) The last option I see is to create a [custom slot](https://rasa.com/docs/rasa/core/slots/#custom-slot-types) that lower cases the text.

Hope, one of the options works for you. I'll close the issue . If you have any further questions, feel free to ask them in the [forum](https://forum.rasa.com/).
