### ISSUE TITLE
Duckling url with trailing slash leads to parsing failure 

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#5792]
Noticed during rasa workshop setup:

**Error (including full traceback)**:
```
rasa.nlu.extractors.duckling_http_extractor  - Failed to get a proper response from remote duckling. Status Code: 404. Response: <!DOCTYPE html>
<html>
<head>
<title>Not found</title>
</head>
<body>
<code>No handler accepted "//parse"</code>
</body></html>
```

**Content of configuration file (config.yml)** (if relevant):
```yml
...
- name: DucklingHTTPExtractor
  url: http://duckling.rasa.com:8000/
...
```
