### ISSUE TITLE
Can't recognize Chinese entity in rasa 1.10.1

### ISSUE THREAD

**Issue by scd10** [RasaHQ/rasa#5876]
**Rasa version**: 1.10.1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.6

**Operating system** (windows, osx, ...): CentOS 7

**Issue**:
I am using Chinese in creating assistant. Recently I was trying to switch from rasa 1.9.7 to 1.10.1 to try the "role" feature. The entity recognizer works fine in 1.9.7. But with the same nlu data, entity recognizer  always make mistakes in 1.10.1. It tends to include outside characters or won't recognize any entities  if the expression is long. 
Since Chinese don't have space character to separate words, maybe there are some new mechanisms  to prevent continues character to be separated during entity recognition?

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: zh
pipeline:
  - name: HFTransformersNLP
    model_name: "bert"
    model_weights: "./bert"
  - name: LanguageModelTokenizer
    intent_tokenization_flag: False
    intent_split_symbol: "_"
  - name: RegexFeaturizer
  - name: LanguageModelFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: FormPolicy

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
