### ISSUE TITLE
Response Selector Issue

### ISSUE THREAD

**Issue by kathirit87** [RasaHQ/rasa#5906]
Rasa version: 1.10.1

Python version: 3.6

Operating system: Linux 

Issue: Response selector (Retrieval Action ) gives wrong answer

i am trying to implement FAQ bot using response selector. There are more than 70 faq response text placed in response.md. 
Rasa responding Gitlab_CI when user request for Gitlab. 
Same issue exists for other intent also.
Please refer the attached screen shot.
kindly provide suggestions to improve the FAQ bot. 
response.md:
```
## ask impact
* faq/impact
  - Portal helps to ....
## ask/gitLab
* gitlab/ask_gitlab
  - GitLab is a web-based...
## ask GitLab_CI
* gitlab/ContinousIntegration
  - GitLab CI (Continuous Integration) ...
```
nlu.md:
```
## intent: faq/impact
- portal
- impact
- devsecops
## intent: gitlab/ask_gitlab
- Gitlab
## intent: gitlab/ContinousIntegration
- Continous Integration
- GitlabCI
```
Content of configuration file (config.yml):
```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: "KeywordIntentClassifier"
    case_sensitive: False
  - name: "WhitespaceTokenizer"
    intent_split_symbol: "_"
    case_sensitive: False
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 100
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    retrieval_intent: faq
    epochs: 100
  - name: "ResponseSelector"
    retrieval_intent: gitlab
    epochs: 100
  - name: "ResponseSelector"
    retrieval_intent: db
    epochs: 100
  - name: "ResponseSelector"
    retrieval_intent: mainframe
    epochs: 100
  - name: "ResponseSelector"
    retrieval_intent: dotools
    epochs: 100
  - name: "ResponseSelector"
    retrival_intent: awscloud
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 1
  - name: MappingPolicy

```

Content of domain file (domain.yml):
```
intents:
  - greet
  - bye
  - thank
  - lincoln
  - faq
  - mood_unhappy
  - bot_challenge
  - affirm
  - bot_age
  - bot_living
  - gitlab
  - db
  - jenkin
  - mainframe
  - dotools
  - awscloud

actions:
  - respond_faq
  - respond_gitlab
  - respond_db
  - respond_mainframe
  - respond_dotools
  - respond_awscloud

responses:
 utter_noworries:
  - text: "You are most welcome!"
 utter_greet:
  - text: "Hi! How can I help you today ?"
 utter_bye:
  - text: "Bye!"
  - text: "Goodbye!"
 utter_iamabot:
```
![Rasa_issue](https://user-images.githubusercontent.com/35557081/83017697-19aea780-9ff2-11ea-8e58-728273ad6bf9.PNG)
