### ISSUE TITLE
Unable to train my model

### ISSUE THREAD

**Issue by Akhil1278** [RasaHQ/rasa#5961]
**Rasa version**:1.10.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:3.6

**Operating system** (windows, osx, ...):Windows

**Issue**:rasa.core.policies.ensemble.InvalidPolicyConfig: Module for policy 'MemoizationPolicy' could not be loaded. Please make sure the name is a valid policy.

**Error (including full traceback)**:
  File "c:\users\akhil\venv\lib\site-packages\rasa\core\registry.py", line 21, in policy_from_module_path
    module_path, lookup_path="rasa.core.policies.registry"
  File "c:\users\akhil\venv\lib\site-packages\rasa\utils\common.py", line 208, in class_from_module_path
    m = importlib.import_module(lookup_path)
  File "C:\Users\akhil\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\akhil\venv\lib\site-packages\rasa\core\policies\registry.py", line 5, in <module>
    from rasa.core.policies.ted_policy import TEDPolicy
  File "c:\users\akhil\venv\lib\site-packages\rasa\core\policies\ted_policy.py", line 26, in <module>
    from rasa.utils.tensorflow.models import RasaModel
  File "c:\users\akhil\venv\lib\site-packages\rasa\utils\tensorflow\models.py", line 12, in <module>
    from rasa.utils.tensorflow.model_data import RasaModelData, FeatureSignature
  File "c:\users\akhil\venv\lib\site-packages\rasa\utils\tensorflow\model_data.py", line 7, in <module>
    from sklearn.model_selection import train_test_split
  File "c:\users\akhil\venv\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "c:\users\akhil\venv\lib\site-packages\sklearn\base.py", line 20, in <module>
    from .utils import _IS_32BIT
  File "c:\users\akhil\venv\lib\site-packages\sklearn\utils\__init__.py", line 27, in <module>
    from .fixes import np_version
  File "c:\users\akhil\venv\lib\site-packages\sklearn\utils\fixes.py", line 18, in <module>
    import scipy.stats
  File "c:\users\akhil\venv\lib\site-packages\scipy\stats\__init__.py", line 384, in <module>
    from .stats import *
  File "c:\users\akhil\venv\lib\site-packages\scipy\stats\stats.py", line 179, in <module>
    from scipy.spatial.distance import cdist
  File "c:\users\akhil\venv\lib\site-packages\scipy\spatial\__init__.py", line 102, in <module>
    from ._procrustes import procrustes
  File "c:\users\akhil\venv\lib\site-packages\scipy\spatial\_procrustes.py", line 11, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "c:\users\akhil\venv\lib\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "c:\users\akhil\venv\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "c:\users\akhil\venv\lib\site-packages\scipy\linalg\blas.py", line 215, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The file cannot be accessed by the system.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\akhil\venv\lib\site-packages\rasa\core\policies\ensemble.py", line 308, in from_dict
    constr_func = registry.policy_from_module_path(policy_name)
  File "c:\users\akhil\venv\lib\site-packages\rasa\core\registry.py", line 24, in policy_from_module_path
    raise ImportError(f"Cannot retrieve policy from path '{module_path}'")
ImportError: Cannot retrieve policy from path 'MemoizationPolicy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\akhil\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\akhil\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\akhil\venv\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\akhil\venv\lib\site-packages\rasa\__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\users\akhil\venv\lib\site-packages\rasa\cli\scaffold.py", line 206, in run
    init_project(args, path)
  File "c:\users\akhil\venv\lib\site-packages\rasa\cli\scaffold.py", line 118, in init_project
    print_train_or_instructions(args, path)
  File "c:\users\akhil\venv\lib\site-packages\rasa\cli\scaffold.py", line 58, in print_train_or_instructions
    args.model = rasa.train(domain, config, training_files, output)
  File "c:\users\akhil\venv\lib\site-packages\rasa\train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "C:\Users\akhil\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "c:\users\akhil\venv\lib\site-packages\rasa\train.py", line 101, in train_async
    additional_arguments,
  File "c:\users\akhil\venv\lib\site-packages\rasa\train.py", line 188, in _train_async_internal
    additional_arguments=additional_arguments,
  File "c:\users\akhil\venv\lib\site-packages\rasa\train.py", line 223, in _do_training
    additional_arguments=additional_arguments,
  File "c:\users\akhil\venv\lib\site-packages\rasa\train.py", line 361, in _train_core_with_validated_data
    additional_arguments=additional_arguments,
  File "c:\users\akhil\venv\lib\site-packages\rasa\core\train.py", line 43, in train
    policies = config.load(policy_config)
  File "c:\users\akhil\venv\lib\site-packages\rasa\core\config.py", line 28, in load
    return PolicyEnsemble.from_dict(config_data)
  File "c:\users\akhil\venv\lib\site-packages\rasa\core\policies\ensemble.py", line 319, in from_dict
    "".format(policy_name)
```

```

**Command or request that led to error**:rasa train
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: FormPolicy

  - name: "FallbackPolicy"
    nlu_threshold: 0.1
    core_threshold: 0.1
    fallback_action_name: "action_default_fallback"
![Screenshot (36)](https://user-images.githubusercontent.com/65960157/83773169-d1525200-a6a1-11ea-9a98-51512a80895c.png)

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
