### ISSUE TITLE
RulePolicy: SlotMappings in Domain are requested by alphabet

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6057]
With the RulePolicy (see `rules` branch) you can add SlotMappings in the domain. When the `FormAction` within Rasa Open Source runs, it should ask for the slots in the same order as it's given in the domain. Currently the slots are requested by alphabet. It's probably due to the `sort` in `Domain.merge`.

**Comment by wochinge** [comment]
@alwx One thought that I had: While we need to merge the forms I don't think it makes sense to actually try to merge the slotmappings within a form. Why? It makes sense to split up the form definitions on multiple files, but I don't see why you would split up the definition of one form and its mappings onto several files. What do you think?

**Comment by alwx** [comment]
Will check it out and update you later today or tomorrow!

**Comment by alwx** [comment]
@wochinge are you sure it's still the case? 

I wrote a simple test to check the order of requested slots:

```
async def test_request_slots_order_after_merge():
    test_yaml_1 = """
    forms:
    - my_form1:
        slot_e:
          type: from_text
        slot_b:
          type: from_text
        slot_d: 
          type: from_text
        slot_c:
          type: from_text
    """

    test_yaml_2 = """
    forms:
    - my_form1:
        slot_a:
          type: from_text
    """

    domain1 = Domain.from_yaml(test_yaml_1)
    domain2 = Domain.from_yaml(test_yaml_2)
    domain = domain1.merge(domain2)

    form_name = "my_form1"
    action = FormAction(form_name, None)

    assert action.required_slots(domain) == ["slot_e", "slot_b", "slot_d", "slot_c", "slot_a"]
```

However, what I got instead is `["slot_e", "slot_b", "slot_d", "slot_c"]` which means two things:
1) slots do not really get merged
2) the order remains the same

**Comment by wochinge** [comment]
@alwx 
Thanks for providing the test! 
The syntax is little bit different (we should probably also handle your syntax) (note that the slot mappings are lists)
```
    test_yaml_1 = """
    forms:
    - my_form1:
        slot_e:
        - type: from_text
        slot_b:
        - type: from_text
        slot_d: 
        - type: from_text
        slot_c:
        - type: from_text
    """

    test_yaml_2 = """
    forms:
    - my_form1:
        slot_a:
        - type: from_text
    """
```

> slots do not really get merged

Ok, I think we should not even try that to be honest 👍 (still it's somewhat of a bug because I thought it would work). Not sure if we need to fix anything in `Domain.merge(...)` then. Wdyt?

I guess the problem with order is happening somewhere else then? Maybe here https://github.com/RasaHQ/rasa/blob/bed6aebf1e534fb723138f4c8316100cf30370b2/rasa/core/actions/forms.py#L163 ? 


I didn't account to the fact, that order is important. I guess we should change the YML syntax then to accept a list of slots:

```yml
- restaurant_form:
      - cuisine:
         - type: from_entity
           entity: cuisine
           not_intent: chitchat
      - num_people:
         - type: from_entity
           entity: number
           intent: [inform, request_restaurant]
      - outdoor_seating:
         - type: from_entity
           entity: seating
         - type: from_intent
           intent: affirm
           value: true
         - type: from_intent
           intent: deny
           value: false
```
