### ISSUE TITLE
RasaX: No policy ensemble or domain set

### ISSUE THREAD

**Issue by cristianmtr** [RasaHQ/rasa#6076]
**Rasa version**: 1.9.5

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.27.4

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:

**Error (including full traceback)**:
```
/opt/venv/lib/python3.6/site-packages/rasa/utils/common.py:351: UserWarning: No policy ensemble or domain set. Skipping action prediction and execution.

```

**Command or request that led to error**:
```
eval $(egrep -v '^#' .env | xargs) eb local run
```

NOTES:

- We are using ElasticBeanstalk. I am currently testing it locally. It does produce a docker-compose intermediary file, if that's easier to debug.
- I have uploaded a model that works in combination with our chatbot image in our current production environment

`docker-compose.yml`

```
app:
  command:
  - start
  - --actions
  - actions
  environment:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    LOCK_STORE_DB: $LOCK_STORE_DB
    LOKI_PASSWORD: $LOKI_PASSWORD
    LOKI_USERNAME: $LOKI_USERNAME
    RASA_LOGGER_FILTERS: $RASA_LOGGER_FILTERS
    TRACKER_DB: $TRACKER_DB
    TRACKER_PASSWORD: $TRACKER_PASSWORD
    TRACKER_URL: $TRACKER_URL
    TRACKER_USERNAME: $TRACKER_USERNAME
  image: OURCUSTOMIMAGE
  ports:
  - 5055:5055
nginx:
  environment:
    RASA_PRODUCTION_HOST: $RASA_PRODUCTION_HOST_NGINX
    RASA_X_HOST: $RASA_X_HOST_NGINX
  image: rasa/nginx:0.27.4
  links:
  - app:app
  - rasaproduction:rasa-production
  - rasaworker:rasa-worker
  - rasax:rasa-x
  ports:
  - 80:8080
  - 443:8443
  volumes:
  - /home/cristian/code/rasax/certs:/opt/bitnami/certs
  - /home/cristian/code/rasax/terms:/opt/bitnami/nginx/conf/bitnami/terms
rasaproduction:
  command:
  - x
  - --no-prompt
  - --production
  - --config-endpoint
  - $RASA_X_HOST/api/config?token=$RASA_X_TOKEN
  - --port
  - '5005'
  - --jwt-method
  - HS256
  - --jwt-secret
  - $JWT_SECRET
  - --auth-token
  - $RASA_TOKEN
  - --debug
  - --enable-api
  - --cors
  - '*'
  environment:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    DB_DATABASE: tracker
    DB_HOST: $DB_HOST
    DB_LOGIN_DB: $DB_LOGIN_DB
    DB_PASSWORD: $DB_PASSWORD
    DB_PORT: '5432'
    DB_USER: $DB_USER
    ENVIRONMENT: chatbot-rasax-production
    JWT_SECRET: $JWT_SECRET
    LOCAL_MODE: 'false'
    LOCK_STORE_DB: $LOCK_STORE_DB
    LOKI_PASSWORD: $LOKI_PASSWORD
    LOKI_USERNAME: $LOKI_USERNAME
    PYTHONPATH: $PYTHONPATH:/app
    RABBITMQ_HOST: $RABBITMQ_HOST
    RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
    RABBITMQ_QUEUE: $RABBITMQ_QUEUE
    RABBITMQ_USERNAME: $RABBITMQ_USERNAME
    RASA_ENVIRONMENT: production
    RASA_LOGGER_FILTERS: $RASA_LOGGER_FILTERS
    RASA_MODEL_PULL_INTERVAL: '10'
    RASA_MODEL_SERVER: $RASA_X_HOST/api/projects/default/models/tags/production
    RASA_PRODUCTION_HOST: $RASA_PRODUCTION_HOST
    RASA_TOKEN: $RASA_TOKEN
    RASA_USER_APP: $RASA_USER_APP
    RASA_WORKER_HOST: $RASA_WORKER_HOST
    RASA_X_HOST: $RASA_X_HOST
    RASA_X_PASSWORD: $RASA_X_PASSWORD
    RASA_X_TOKEN: $RASA_X_TOKEN
    RASA_X_USERNAME: $RASA_X_USERNAME
    TRACKER_DB: $TRACKER_DB
    TRACKER_PASSWORD: $TRACKER_PASSWORD
    TRACKER_URL: $TRACKER_URL
    TRACKER_USERNAME: $TRACKER_USERNAME
  image: OURCUSTOMIMAGE
  ports:
  - 5005:5005
rasaworker:
  command:
  - x
  - --no-prompt
  - --production
  - --config-endpoint
  - $RASA_X_HOST/api/config?token=$RASA_X_TOKEN
  - --port
  - '5005'
  - --jwt-method
  - HS256
  - --jwt-secret
  - $JWT_SECRET
  - --auth-token
  - $RASA_TOKEN
  - --enable-api
  - --debug
  - --cors
  - '*'
  environment:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    DB_DATABASE: worker_tracker
    DB_HOST: $DB_HOST
    DB_LOGIN_DB: $DB_LOGIN_DB
    DB_PASSWORD: $DB_PASSWORD
    DB_PORT: '5432'
    DB_USER: $DB_USER
    ENVIRONMENT: chatbot-rasax-worker
    JWT_SECRET: $JWT_SECRET
    LOCAL_MODE: 'false'
    LOCK_STORE_DB: $LOCK_STORE_DB
    LOKI_PASSWORD: $LOKI_PASSWORD
    LOKI_USERNAME: $LOKI_USERNAME
    RABBITMQ_HOST: $RABBITMQ_HOST
    RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
    RABBITMQ_QUEUE: $RABBITMQ_QUEUE
    RABBITMQ_USERNAME: $RABBITMQ_USERNAME
    RASA_ENVIRONMENT: worker
    RASA_LOGGER_FILTERS: $RASA_LOGGER_FILTERS
    RASA_MODEL_PULL_INTERVAL: '10'
    RASA_MODEL_SERVER: $RASA_X_HOST/api/projects/default/models/tags/production
    RASA_PRODUCTION_HOST: $RASA_PRODUCTION_HOST
    RASA_TOKEN: $RASA_TOKEN
    RASA_USER_APP: $RASA_USER_APP
    RASA_WORKER_HOST: $RASA_WORKER_HOST
    RASA_X_HOST: $RASA_X_HOST
    RASA_X_PASSWORD: $RASA_X_PASSWORD
    RASA_X_TOKEN: $RASA_X_TOKEN
    RASA_X_USERNAME: $RASA_X_USERNAME
    TRACKER_DB: $TRACKER_DB
    TRACKER_PASSWORD: $TRACKER_PASSWORD
    TRACKER_URL: $TRACKER_URL
    TRACKER_USERNAME: $TRACKER_USERNAME
  image: OURCUSTOMIMAGE
  ports:
  - 5006:5005
rasax:
  environment:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    DB_DATABASE: $DB_DATABASE
    DB_HOST: $DB_HOST
    DB_LOGIN_DB: $DB_LOGIN_DB
    DB_PASSWORD: $DB_PASSWORD
    DB_PORT: '5432'
    DB_USER: $DB_USER
    JWT_SECRET: $JWT_SECRET
    LOCAL_MODE: 'false'
    LOCK_STORE_DB: $LOCK_STORE_DB
    LOKI_PASSWORD: $LOKI_PASSWORD
    LOKI_USERNAME: $LOKI_USERNAME
    PASSWORD_SALT: $PASSWORD_SALT
    RABBITMQ_HOST: $RABBITMQ_HOST
    RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
    RABBITMQ_QUEUE: $RABBITMQ_QUEUE
    RABBITMQ_USERNAME: $RABBITMQ_USERNAME
    RASA_LOGGER_FILTERS: $RASA_LOGGER_FILTERS
    RASA_MODEL_DIR: /app/models
    RASA_MODEL_PULL_INTERVAL: '10'
    RASA_MODEL_SERVER: $RASA_X_HOST/api/projects/default/models/tags/production
    RASA_PRODUCTION_HOST: $RASA_PRODUCTION_HOST
    RASA_TOKEN: $RASA_TOKEN
    RASA_USER_APP: $RASA_USER_APP
    RASA_WORKER_HOST: $RASA_WORKER_HOST
    RASA_X_HOST: $RASA_X_HOST
    RASA_X_PASSWORD: $RASA_X_PASSWORD
    RASA_X_TOKEN: $RASA_X_TOKEN
    RASA_X_USERNAME: $RASA_X_USERNAME
    RASA_X_USER_ANALYTICS: '0'
    SANIC_RESPONSE_TIMEOUT: '3600'
    SELF_PORT: '5002'
    TRACKER_DB: $TRACKER_DB
    TRACKER_PASSWORD: $TRACKER_PASSWORD
    TRACKER_URL: $TRACKER_URL
    TRACKER_USERNAME: $TRACKER_USERNAME
  image: rasa/rasa-x:0.27.4
  ports:
  - 5002:5002
  volumes:
  - /home/cristian/code/rasax/models:/app/models
  - /home/cristian/code/rasax/environments.yml:/app/environments.yml
  - /home/cristian/code/rasax/credentials.yml:/app/credentials.yml
  - /home/cristian/code/rasax/endpoints.yml:/app/endpoints.yml
  - /home/cristian/code/rasax/logs:/logs
  - /home/cristian/code/rasax/auth:/app/auth

```
`environments.yml`

```yml
rasa:
  production:
    url: ${RASA_PRODUCTION_HOST}
    token: ${RASA_TOKEN}
  worker:
    url: ${RASA_WORKER_HOST}
    token: ${RASA_TOKEN}

```

`endpoints.yml`

```yml
models:
  url: ${RASA_MODEL_SERVER}
  token: ${RASA_X_TOKEN}
  wait_time_between_pulls: ${RASA_MODEL_PULL_INTERVAL}
tracker_store:
  type: sql
  dialect: "postgresql"
  url: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  db: ${DB_DATABASE}
  login_db: ${DB_LOGIN_DB}
action_endpoint:
  url: ${RASA_USER_APP}/webhook
lock_store:
  type: redis
  url: XXXXXXXXXXXXXXXXXXXXX
  port: 6380
  password: XXXXXXXXXXXXXXXXXXXXX
  db: ${LOCK_STORE_DB}
  use_ssl: True
event_broker:
  type: pika
  url: amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}/${RABBITMQ_USERNAME}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  queues:
    - ${RABBITMQ_QUEUE}
```

`.env` file

```
AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DB_DATABASE=rasax
DB_HOST=XXXXXXXXXXXXXXXXXXXXXXXXXXX
DB_LOGIN_DB=postgres
DB_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXX
DB_USER=postgres
DOCKER_HOST_IP=172.17.0.1
ENDPOINTS_YML=endpoints.yml
JWT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXX
LOCK_STORE_DB=14
LOKI_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXX
LOKI_USERNAME=4014
PASSWORD_SALT=XXXXXXXXXXXXXXXXXXXXXXXXXXX
RABBITMQ_HOST=XXXXXXXXXXXXXXXXXXXXXXXXXXX
RABBITMQ_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXX
RABBITMQ_QUEUE=rasax
RABBITMQ_URL=XXXXXXXXXXXXXXXXXXXXXXXXXXX
RABBITMQ_USERNAME=XXXXXXXXXXXXXXXXXXXXXXXXXXX
RASA_PRODUCTION_HOST=http://172.17.0.1:5005
RASA_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXX
RASA_VERSION=1.9.5
RASA_WORKER_HOST=http://172.17.0.1:5006
RASA_X_HOST=http://172.17.0.1:5002
RASA_X_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXX
RASA_X_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXX
RASA_X_USERNAME=me
REDIS_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXX
REMINDER_TIMEOUT=900
TRACKER_DB=XXXXXXXXXXXXXXXXXXXXXXXXXXX
TRACKER_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXX
TRACKER_URL=XXXXXXXXXXXXXXXXXXXXXXXXXXX
TRACKER_USERNAME=XXXXXXXXXXXXXXXXXXXXXXXXXXX
RASA_USER_APP=http://172.17.0.1:5055
RASA_MODEL_PULL_INTERVAL=120
RASA_PRODUCTION_HOST_NGINX=172.17.0.1:5005
RASA_X_HOST_NGINX=172.17.0.1:5005

```

@federicotdn Any ideas? :)
