### ISSUE TITLE
the whole sentence is regarded as a entity

### ISSUE THREAD

**Issue by li-x-q** [RasaHQ/rasa#6082]
**Rasa version**: 1.10.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: Python 3.6.10 :: Anaconda, Inc.

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**: using MITIE，CRFEntityExtractor or DIEClassifier to identify entities in chinese, however, the whole sentence is regarded as a entity

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
the pipeline configuration
```yml
pipeline:
  - name: JiebaTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
