### ISSUE TITLE
Unable to start Rasa pointing to empty S3 model storage

### ISSUE THREAD

**Issue by avarabyeu** [RasaHQ/rasa#6092]
**Rasa version**:
1.10.3

**Operating system** (windows, osx, ...):
Official Docker Image

**Issue**:
Unable to start Rasa pointing to empty S3 model storage (Minio is used as s3-compatible storage)

**Error (including full traceback)**:
```
rasa_1      | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
rasa_1      | Traceback (most recent call last):
rasa_1      |   File "/opt/venv/bin/rasa", line 8, in <module>
rasa_1      |     sys.exit(main())
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/rasa/__main__.py", line 108, in main
rasa_1      |     cmdline_arguments.func(cmdline_arguments)
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/rasa/cli/run.py", line 83, in run
rasa_1      |     rasa.run(**vars(args))
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/rasa/run.py", line 56, in run
rasa_1      |     **kwargs,
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/run.py", line 216, in serve_application
rasa_1      |     endpoints.lock_store if endpoints else None
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
rasa_1      |     serve(**server_settings)
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/sanic/server.py", line 892, in serve
rasa_1      |     trigger_events(before_start, loop)
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/sanic/server.py", line 668, in trigger_events
rasa_1      |     loop.run_until_complete(result)
rasa_1      |   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/run.py", line 257, in load_agent_on_start
rasa_1      |     action_endpoint=endpoints.action,
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/agent.py", line 259, in load_agent
rasa_1      |     model_server=model_server,
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/rasa/core/agent.py", line 916, in load_from_remote_storage
rasa_1      |     persistor.retrieve(model_name, target_path)
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/rasa/nlu/persistor.py", line 55, in retrieve
rasa_1      |     self._retrieve_tar(tar_name)
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/rasa/nlu/persistor.py", line 170, in _retrieve_tar
rasa_1      |     self.bucket.download_fileobj(model_path, f)
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/boto3/s3/inject.py", line 720, in bucket_download_fileobj
rasa_1      |     Callback=Callback, Config=Config)
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/boto3/s3/inject.py", line 678, in download_fileobj
rasa_1      |     return future.result()
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
rasa_1      |     return self._coordinator.result()
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
rasa_1      |     raise self._exception
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/s3transfer/tasks.py", line 255, in _main
rasa_1      |     self._submit(transfer_future=transfer_future, **kwargs)
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/s3transfer/download.py", line 343, in _submit
rasa_1      |     **transfer_future.meta.call_args.extra_args
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
rasa_1      |     return self._make_api_call(operation_name, kwargs)
rasa_1      |   File "/opt/venv/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
rasa_1      |     raise error_class(parsed_response, operation_name)
rasa_1      | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

**Command or request that led to error**:
```
docker-compose up
```

**Content of docker-compose.yaml file**:
```yml
version: '3.0'

services:
  rasa:
    image: rasa/rasa:latest-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./rasa-app-data/:/app/"
    environment: 
    - AWS_SECRET_ACCESS_KEY=minioadmin
    - AWS_ACCESS_KEY_ID=minioadmin
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_ENDPOINT_URL=http://minio:9000
    - BUCKET_NAME=test
    command: ['run','--enable-api', '--remote-storage', 'aws']

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

  minio:
    image: minio/minio
    networks: ['rasa-network']
    ports:
    - "9000:9000"
    command: ['server', '/data']
    volumes:
    - "./rasa-model-data/:/data/"


networks: {rasa-network: {}}
```
