### ISSUE TITLE
Dialogflow import bug "No training examples found for the dialogflow file data\intents\<every intent>.json!"

### ISSUE THREAD

**Issue by A-A-R0N** [RasaHQ/rasa#6137]
**Rasa version**: Rasa 1.10.3

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: python 3.6.8

**Operating system** (windows, osx, ...): windows 10

**Issue**:

For every imported intent, a warning message is given saying it cannot find the example data even though the files are there. I have tried this will several exported chatbots including very simple sample ones.
```
c:\users\aaron\appdata\local\programs\python\python36\lib\site-packages\rasa\utils\common.py:363: UserWarning: No training examples found for dialogflow file data\intents\every_intent.json!
```

**Cause**:
This issue is caused when the language variable set to None in the /nlu/training_data/formats/dialogflow.py file. When generating the intent example filename in the _read_example_js function, it generates it as "intent_name_usersays_None.json" instead of "intent_name_usersays_en.json". I've already addressed the issue in my local code with a simple check against the language variable that corrects the value if it is None. I'm looking for the best place to update the code and will submit a pull request. I see calling request actually set a default value, but somewhere down the line a None value is passed for language.

**Error (including full traceback)**:
```
c:\users\aaron\appdata\local\programs\python\python36\lib\site-packages\rasa\utils\common.py:363: UserWarning: No training examples found for dialogflow file data\intents\intent_name.json!
  More info at https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/
```

**Command or request that led to error**:
```
rasa train nlu
```

**Content of configuration file (config.yml)** (if relevant):
It doesn't seem to be relevant, it is the default file.
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
This is the default file.
```yml
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - bot_challenge

responses:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great, carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_iamabot:
  - text: "I am a bot, powered by Rasa."

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
```
