### ISSUE TITLE
Role Entity modification not taken in account in interactive mode

### ISSUE THREAD

**Issue by julienbronner** [RasaHQ/rasa#6160]
**Rasa version**: 1.10.3

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): MacOS Catalina 10.15.5

**Issue**: 
I use the recent feature of Role and groups for entities (and I think it is very usefull) but when I want to train this with interactive mode, if the role is not good and I modify it, the modification is not taken in account.

In the example below, we can see the entity "Lyon" is a "city-site" but it has to be a role "source" but my modification doesn't appear in the chat history after.

Thank you by advance.

**Error (including full traceback)**:
```
------
? Your input -> bloque skype depuis lyon vers porto                                                            
? Is the intent 'reseau_action' correct for '[bloque]{"entity": "action", "value": "deny"} [skype](application)
 depuis [lyon]{"entity": "city-site", "role": "destination"} vers [porto]{"entity": "city-site", "role": "desti
nation"}' and are all entities labeled correctly?  No                                                          
? What intent is it?  1.00 reseau_action                                                                       
? Please mark the entities using [value](type) notation [bloque]{"entity": "action", "value": "deny"} [skype](a
pplication) depuis [lyon]{"entity": "city-site", "role": "source"} vers [porto]{"entity": "city-site", "role": 
"destination"}                                                                                                 
------
Chat History

 #    Bot                                                                                  You        
──────────────────────────────────────────────────────────────────────────────────────────────────────
 1    action_listen                                                                                   
──────────────────────────────────────────────────────────────────────────────────────────────────────
 2                          [bloque]{"entity": "action", "value": "deny"} [skype](application) depuis 
                          [lyon]{"entity": "city-site", "role": "destination"} vers [porto]{"entity": 
                                                                  "city-site", "role": "destination"} 
                                                                           intent: reseau_action 1.00 
──────────────────────────────────────────────────────────────────────────────────────────────────────
 3    slot{"action":                                                                                  
      "deny"}                                                                                         
```

**Command or request that led to error**:
```
rasa interactive
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

language: fr

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: "DucklingHTTPExtractor"
    url: "http://localhost:8000"
    dimensions: ["time"]
    timezone: "Europe/Paris"
    timeout : 3


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: "TEDPolicy"
    epochs: 250
    max_history: 5
  - name: "FallbackPolicy"
    fallback_action_name: 'action_default_fallback'
  - name: "MemoizationPolicy"
    max_history: 5
  - name: "FormPolicy"
  - name: "MappingPolicy"

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
