### ISSUE TITLE
No warning when EntitySynonymMapper is positioned incorrectly in config.yml

### ISSUE THREAD

**Issue by b-quachtran** [RasaHQ/rasa#6198]
**Rasa version**: 1.10.3

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.7

**Operating system** (windows, osx, ...): OS X

**Issue**:

When `EntitySynonymMapper` is placed above the entity extractor in config.yml, Rasa will train without throwing any warnings when the component doesn't work as expected. 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: EntitySynonymMapper
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy


```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
