### ISSUE TITLE
RulePolicy should predict Core fallback action if no rule was found

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6208]
With the RulePolicy you can now write rules to handle low NLU confidence.
However, as we deprecate the FallbackPolicies we now have no policy which predicts a fallback action in case the Core confidence is low.

**Proposed Steps**
- [ ] The `RulePolicy` should predict a fallback action `x` with a confidence `y` in case no matching rule was applied
- [ ] the name `x` of the fallback action can be configured in the policy config (`config.yml`)
- [ ] the confidence threshold `y` for the fallback can be configured in the policy config
- [ ] add a config value to enable / disable this behavior

```yaml
polices:
- name: RulePolicy
  core_threshold: 0.5
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: True/False
```
