### ISSUE TITLE
Lock Failure Not Reported

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#6226]
**Description of Problem**:
When hitting the REST endpoint with an utterance, we received no response. After that the REST endpoint stopped responding to requests. There were no messages related to the endpoint call - no indication that the user has sent an utterance.  This made for difficult troubleshooting.  Eventually figured out that there was an issue with a custom (clustered Redis) lock store.

**Overview of the Solution**:
The lock store code needs to add debug logging and report this type of error.

**Comment by wochinge** [comment]
more information in here: https://github.com/RasaHQ/rasa-x/issues/2079

**Comment by wochinge** [comment]
Debugging / Ideation

* in `get_lock` `redis.get(...)` blocks indefinitely
  - setting `socket_timeout` on the redis client helps

How to reproduce:
- run redis: `docker run -p 6379:6379 redis`
- use the following lock store config

```
lock_store:
    type: "redis"
    url: localhost
    port: 6379
    db: 0
    use_ssl: True. # using ssl if redis isn't configured so, will block. Set to `False` to make it working
```
