### ISSUE TITLE
 rasa x, NLU Inbox change my entities string to \u05d3\u05de\u05d9  on the nlu.md

### ISSUE THREAD

**Issue by DavidKohav** [RasaHQ/rasa#6228]
**Rasa version**: Rasa 1.10.7

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.8

**Operating system** (windows, osx, ...): ubuntu 18

**Issue**:
After I confirmed the checkbox in the rasa x, NLU Inbox. 
I see in the nlu.md file that the entities look very strange {"entity": "insurance_money", "value": "\u05d3\u05de\u05d9 \u05d0\u05d1\u05d8\u05dc\u05d4"}
I do not have this problem in the story.md file

my python encoding is UTF8 and the Pycharm as well 
I'm a developer for Hebrew users

**Content of configuration file (config.yml)** (if relevant):
```yml
language: he
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: FormPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_core_action_name: "custom_action_fallback"
    fallback_nlu_action_name: "custom_action_fallback"
    deny_suggestion_intent_name: "out_of_scope"
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
