### ISSUE TITLE
document RASA_DUCKLING_HTTP_URL env variable usage

### ISSUE THREAD

**Issue by N-Olbert** [RasaHQ/rasa#6240]
**Rasa version**: 1.10.7

**Python version**: 3.7

**Operating system** (windows, osx, ...): Windows 10 1909

**Issue**: It seems like the Duckling-URL becomes a hard-coded part of the NLU-Model. Changing the Duckling-URL after training seems to have no effect.

Repro:

1.  Train a model using f. e. [http://localhost:8000](http://localhost:8000) as Duckling-URL
2.  Change the URL to f. e. [http://localhost:55555](http://localhost:55555) (but DONT retrain the model)
3.  Start the Duckling-server on [http://localhost:55555](http://localhost:55555)
4.  Run `rasa run`
5.  See failure after parsing any message

See also: [https://forum.rasa.com/t/does-the-duckling-url-become-a-hard-coded-part-of-the-trained-model/31001](https://forum.rasa.com/t/does-the-duckling-url-become-a-hard-coded-part-of-the-trained-model/31001)

**Error (including full traceback)**:

 Failed to connect to duckling http server. Make sure the duckling server is running/healthy/not stale and the proper host and port are set in the configuration. More information on how to run the server can be found on github: [https://github.com/facebook/duckling#quickstart](https://github.com/facebook/duckling#quickstart) Error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /parse (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BE546C5D48>: Failed to establish a new connection: <span class="error">[WinError 10061]</span> Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))

**Note**: Port 8000 is still used.

**Content of configuration file (config.yml)** (if relevant): Before

<pre>language: de
 pipeline:

*   name: WhitespaceTokenizer
*   name: RegexFeaturizer
*   name: LexicalSyntacticFeaturizer
*   name: CountVectorsFeaturizer
*   name: CountVectorsFeaturizer
     analyzer: "char_wb"
     min_ngram: 1
     max_ngram: 4
*   name: DIETClassifier
     epochs: 100
*   name: EntitySynonymMapper
*   name: ResponseSelector
     epochs: 100
*   name: "DucklingHTTPExtractor"
     url: "http://localhost:8000"
     dimensions: <span class="error">["time"]</span>
     locale: "de_DE"
     timezone: "UTC"
     timeout : 3</pre>

After

<pre>language: de
 pipeline:

*   name: WhitespaceTokenizer
*   name: RegexFeaturizer
*   name: LexicalSyntacticFeaturizer
*   name: CountVectorsFeaturizer
*   name: CountVectorsFeaturizer
     analyzer: "char_wb"
     min_ngram: 1
     max_ngram: 4
*   name: DIETClassifier
     epochs: 100
*   name: EntitySynonymMapper
*   name: ResponseSelector
     epochs: 100
*   name: "DucklingHTTPExtractor"
     url: "http://localhost:55555" #This is the only change
     dimensions: <span class="error">["time"]</span>
     locale: "de_DE"
     timezone: "UTC"
     timeout : 3</pre>

**Comment by N-Olbert** [comment]
According to the forum, this is defined functionality (see https://forum.rasa.com/t/does-the-duckling-url-become-a-hard-coded-part-of-the-trained-model/31001), so please consider this as an enhancement request rather than a bug.

Not being able to change the port/uri after training is bad because if a customer has already used the Duckling-port which was  provided during training there is no way to change this port except to train a new model (which takes some time).

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
You could use an environment variable instead of a hardcoded URL in your configuration, e.g. 

```yaml
language: de
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: "DucklingHTTPExtractor"
    url: ${DUCKLING_URL} #This is the only change
    dimensions: ["time"]
    locale: "de_DE"
    timezone: "UTC"
    timeout : 3
```

I see that this isn't ideal in terms of usability, but otherwise we'd need some way to pass in the duckling url during loading the model. I think using an env variable still seems the best way to do this. Wdyt?
