### ISSUE TITLE
RulePolicy: Replace `...` in YAML training data

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6254]
**General information**
Related discussion: [Notion](https://www.notion.so/rasa/Feedback-on-2-0-4574eaacc0764967ac0b8b82fbc72904#1b3d29e0c00c4f92bf68162f78da0828)

Consider a rule like the following:

```yaml
- rule: Submit form
  steps:
  # Condition that form is active.
  - form: loop_q_form
  - ...
  - action: loop_q_form
  - form: null
  - slot: requested_slot
    value: null
  # The action we want to run when the form is submitted.
  - action: utter_stop
```

Everything before the `...` is the condition for the rule to apply. We want to make this explicit by moving the condition steps to a special key `condition`. The rule would then look like:

```yaml
- rule: Submit form
  condition:
  # Condition that form is active.
  - form: loop_q_form
  steps:
  - action: loop_q_form
  - form: null
  - slot: requested_slot
    value: null
  # The action we want to run when the form is submitted.
  - action: utter_stop
```

There a currently two other applications for `...` in rules besides conditions:
- the lack of `...` at the start of a rule indicates that the rule only applies at conversation start. As this is way less frequent than having a rule which can apply at all conversation parts, we need to replace this with a different construct
- `...` at the end of the rule `steps` indicate that the rule should not predict `action_listen` once the rule is finished, but that another action (e.g. from a different rule / story) should be predicted

**Steps to Solution**
- [x] enable YAML reader to parse steps from `condition` key. It's probably easier to keep the conversation events as they are, which means that the `condition` part should be insert as the initial conversation events, followed by a `ActionExecuted("...")` and then the remaining steps from `steps`. Phrased differently: No need to touch anything besides the yaml reader. We just translate the `condition` to what we currently have (unless this is a huge implementation pain)
- [x] these steps might make sense to do as part of the issue depending on the discussion state:
   - replace `...` at the end of a rule with another indicator to tell Rasa to not predict `action_listen` at the end of a rule
   - find a different indicator than the missing `...` at the start of `steps` to tell Rasa that a rule is only applicable at the beginning of a story

**Comment by akelad** [comment]
The current suggestion for the start of the conversation is something like:
```
- rule: Greet user (only relevant at start of conversation)
  condition:
    - action: action_session_start
  steps:
    - intent: greet
    - action: utter_greet
```
There's been some debate as to whether it should say `conversation_started` instead of `action: action_session_start` to make it clearer to the user.

The current suggestion for the end of the conversation is: 
```
- rule: FAQ detailed
  steps:
    - intent: faq
    - action: utter_faq
  wait_for_user_input: false
```
This key should only need to be added when the case is not the default option of waiting for user input after a predicted action.

Let me know if anyone has more questions on this topic

**Comment by wochinge** [comment]
> There's been some debate as to whether it should say conversation_started instead of action: action_session_start to make it clearer to the user.

Let's go for `action: action_session_start` for now and then get feedback on it?

**Comment by akelad** [comment]
sure!

**Comment by wochinge** [comment]
@akelad I think it should actually be like that, no? That's the same way we e.g. handle it for "form submit" rules

```
- rule: Greet user (only relevant at start of conversation)
  steps:
    - action: action_session_start
    - intent: greet
    - action: utter_greet
```
