### ISSUE TITLE
Rename `slot` event yaml training data to `slot_was_set`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6259]
A `slot` step in stories doesn't actually set a slot but it's  just an event that results from an action or user message setting a slot.

To clarify that we decided in [this discussion](https://www.notion.so/rasa/Feedback-on-2-0-4574eaacc0764967ac0b8b82fbc72904#1fa4a5bfe78b499d8a20acb605ce026b) to rename the `slot` key to `slot_was_set`.

This means that the following training data will change as follows:

Prior:
```yaml
stories:
- story: Slot set story
  steps:
  - intent: chitchat
  - slot: slot-name
    value: slot-value

- story: story_with_a_conditional_checkpoint
  steps:
  - checkpoint: greet_checkpoint
    # This checkpoint should only apply if slot is set to the specified value
    slots: 
    - context_scenario: holiday
    - holiday_name: thanksgiving
  - intent: greet
  - action: utter_greet
```

Now:
```yaml
stories:
- story: Slot set story
  steps:
  - intent: chitchat
  - slot_was_set: slot-name
    value: slot-value

- story: story_with_a_conditional_checkpoint
  steps:
  - checkpoint: greet_checkpoint
    # This checkpoint should only apply if slot is set to the specified value
    slot_was_set: 
    - context_scenario: holiday
    - holiday_name: thanksgiving
  - intent: greet
  - action: utter_greet
```
