### ISSUE TITLE
Improve the suggested pipelines

### ISSUE THREAD

**Issue by chkoss** [RasaHQ/rasa#6326]
See feedback [in Notion](https://www.notion.so/rasa/Feedback-on-2-0-4574eaacc0764967ac0b8b82fbc72904#75a5a5747ffa462ba0b9ead6d45b355f).

Currently, doing `pip install rasa==2.0.0a1` and then `rasa init` fails because the suggested pipeline includes spaCy, which is not installed by default. Also, the suggested pipeline doesn't match what we recommend in [our docs](https://rasa.com/docs/rasa/nlu/choosing-a-pipeline/#how-to-choose-a-pipeline).

A potential solution would be to include conveRT in the default installation, except on Windows (where tensorflow-text isn't supported yet), and then suggest the following pipelines:

If `language: en` and not on Windows, suggest
```yaml
pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
```

else suggest
```yaml
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
```
