### ISSUE TITLE
Error while training the bot as per instructions provided in the tutorial (https://rasa.com/docs/rasa/user-guide/rasa-tutorial/)

### ISSUE THREAD

**Issue by 123nishant** [RasaHQ/rasa#6342]
**Rasa version**: 1.10.9

**Rasa SDK version** (if used & relevant): 1.10.2

**Rasa X version** (if used & relevant): NA

**Python version**: 3.7.7

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:
While training the rasa bot initially, I am facing issue as mentioned below. As per the error it's an error in markdown files, but the markdown files are basic, that are loaded by default

**Error (including full traceback)**:
rasa train
/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/utils/common.py:363: UserWarning: No training examples found for dialogflow file data/examples/dialogflow/intents/Default Fallback Intent.json!
  More info at https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/
/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/nlu/training_data/formats/readerwriter.py:15: FutureWarning: You are using the deprecated training data format to declare synonyms. Please use the following format: 
[<entity-text>]{"entity": "<entity-type>", "value": "<entity-synonym>"}.
You can use the following command to update your training data file:
sed -i -E 's/\[([^)]+)\]\(([^)]+):([^)]+)\)/[\1]{"entity": "\2", "value": "\3"}/g' nlu.md
  return self.reads(rasa.utils.io.read_file(filename), **kwargs)
/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/nlu/training_data/formats/readerwriter.py:37: FutureWarning: Your rasa data contains 'intent_examples' or 'entity_examples' which will be removed in the future. Consider putting all your examples into the 'common_examples' section.
  return self.read_from_json(js, **kwargs)
Traceback (most recent call last):
  File "/home/nishant/miniconda3/envs/ml/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/cli/train.py", line 76, in train
    additional_arguments=extract_additional_arguments(args),
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/train.py", line 101, in train_async
    additional_arguments,
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/train.py", line 144, in _train_async_internal
    file_importer.get_stories(), file_importer.get_nlu_data()
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/importers/importer.py", line 269, in get_nlu_data
    nlu_data = await asyncio.gather(*nlu_data)
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/importers/rasa.py", line 61, in get_nlu_data
    return utils.training_data_from_paths(self._nlu_files, language)
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/importers/utils.py", line 9, in training_data_from_paths
    training_datas = [loading.load_data(nlu_file, language) for nlu_file in paths]
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/importers/utils.py", line 9, in <listcomp>
    training_datas = [loading.load_data(nlu_file, language) for nlu_file in paths]
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 67, in load_data
    data_sets = [_load(f, language) for f in files]
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 67, in <listcomp>
    data_sets = [_load(f, language) for f in files]
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 138, in _load
    return reader.read(filename, language=language, fformat=fformat)
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/nlu/training_data/formats/readerwriter.py", line 15, in read
    return self.reads(rasa.utils.io.read_file(filename), **kwargs)
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/nlu/training_data/formats/markdown.py", line 100, in reads
    self._set_current_section(header[0], header[1])
  File "/home/nishant/miniconda3/envs/ml/lib/python3.7/site-packages/rasa/nlu/training_data/formats/markdown.py", line 315, in _set_current_section
    "".format(section, "', '".join(available_sections))
ValueError: Found markdown section 'entity' which is not in the allowed sections 'intent', 'synonym', 'regex', 'lookup'.
```

```

**Command or request that led to error**:
rasa train

```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 1
    epochs: 100
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - bot_challenge

responses:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great, carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_iamabot:
  - text: "I am a bot, powered by Rasa."

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

```
