### ISSUE TITLE
rasa-x can't train a specific type of model with spacy fr large 

### ISSUE THREAD

**Issue by JosephCHS** [RasaHQ/rasa#6379]
**Rasa version**: 1.10.8

**Rasa SDK version**: 1.10.2

**Rasa X version**: 0.31.5

**Python version**: 3.7

**Operating system** (windows, osx, ...): ubuntu 18.07

**Issue**: 
Locally with rasa 1.10.8, I can train a model with `fr_core_news_lg` (from spacy).\
When I used Rasa-x through docker, I can't train a model with `fr_core_news_lg` (spacy) set in the config file.
The model can be generated only if I modify the config file with `model: fr_core_news_md`, knowing that I didn't mention `fr_core_news_md` anywhere in my docker file and the command `spacy validate` in the worker/production container confirm that only the large model is being used. 

Here is my docker file:
```
FROM rasa/rasa:1.10.8-spacy-en as base

USER root

RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends \
    # required by psycopg2 at build and runtime
    libpq-dev \
     # required for health check
    curl \
 && apt-get autoremove -y

FROM base as builder

RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends \
  build-essential \
  wget \
  openssh-client \
  graphviz-dev \
  pkg-config \
  git-core \
  openssl \
  libssl-dev \
  libffi6 \
  libffi-dev \
  libpng-dev

# install poetry
# keep this in sync with the version in pyproject.toml and Dockerfile
ENV POETRY_VERSION 1.0.5
ENV PATH "/root/.poetry/bin:/opt/venv/bin:${PATH}"

# copy files
COPY config.yml /build/config.yml

# change working directory
WORKDIR /build

# install dependencies
RUN python -m venv /opt/venv && \
  . /opt/venv/bin/activate && \
  pip install --no-cache-dir -U 'pip<20' && \
  pip uninstall spacy -y && \
  rm /opt/venv/lib/python3.7/site-packages/spacy-2.1.9.dist-info/ -rf && \
  pip install --no-cache-dir -U spacy==2.3.0 && \
  rm -rf dist *.egg-info

# make sure we use the virtualenv
ENV PATH="/opt/venv/bin:$PATH"

# spacy link
RUN python -m spacy download fr_core_news_lg && \
    python -m spacy link fr_core_news_lg fr_core_news_lg --force

# start a new build stage
FROM base as runner

# copy everything from /opt
COPY --from=builder /opt/venv /opt/venv

# make sure we use the virtualenv
ENV PATH="/opt/venv/bin:$PATH"

# update permissions & change user to not run as root
WORKDIR /app
RUN chgrp -R 0 /app && chmod -R g=u /app
USER 1001

# Create a volume for temporary data
VOLUME /tmp

# change shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# the entry point
EXPOSE 5005
ENTRYPOINT ["rasa"]
CMD ["--help"]
```

**Error (including full traceback)**:
```
nginx_1            | 172.18.0.1 - - [11/Aug/2020:08:46:37 +0000] "GET /api/environments HTTP/1.1" 200 202 "http://localhost/models" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
nginx_1            | 172.18.0.1 - - [11/Aug/2020:08:46:37 +0000] "GET /api/health HTTP/1.1" 200 167 "http://localhost/models" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
nginx_1            | 172.18.0.1 - - [11/Aug/2020:08:46:37 +0000] "GET /api/projects/default/models?limit=1&offset=0 HTTP/1.1" 200 223 "http://localhost/models" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
nginx_1            | 172.18.0.1 - - [11/Aug/2020:08:46:37 +0000] "GET /api/projects/default/models?limit=4&offset=1 HTTP/1.1" 200 889 "http://localhost/models" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
nginx_1            | 172.18.0.1 - - [11/Aug/2020:08:46:45 +0000] "GET /api/projects/default/git_repositories/2/status HTTP/1.1" 200 230 "http://localhost/models" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
nginx_1            | 172.18.0.1 - - [11/Aug/2020:08:47:45 +0000] "GET /api/projects/default/git_repositories/2/status HTTP/1.1" 200 230 "http://localhost/models" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
rasa-x_1           | ERROR:rasax.community.api.blueprints.models:500, message='Internal Server Error', url=URL('http://rasa-worker:5005/model/train?token=elUhAXFMFynGhdj88ciTaw%3D%3D')
rasa-x_1           | Encountered an exception while training. Please check the logs of the rasa worker container for more information.
nginx_1            | 172.18.0.1 - - [11/Aug/2020:08:48:01 +0000] "POST /api/projects/default/models/jobs HTTP/1.1" 500 271 "http://localhost/models" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
nginx_1            | 172.18.0.1 - - [11/Aug/2020:08:48:45 +0000] "GET /api/projects/default/git_repositories/2/status HTTP/1.1" 200 230 "http://localhost/models" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
nginx_1            | 172.18.0.1 - - [11/Aug/2020:08:49:45 +0000] "GET /api/projects/default/git_repositories/2/status HTTP/1.1" 200 230 "http://localhost/models" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
nginx_1            | 172.18.0.1 - - [11/Aug/2020:08:50:45 +0000] "GET /api/projects/default/git_repositories/2/status HTTP/1.1" 200 230 "http://localhost/models" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
```

**Command or request that led to error**:

Train button in the Rasa GUI

**Content of configuration file (config.yml)** (if relevant):
```yml
language: fr
pipeline:
- name: SpacyNLP
  model: fr_core_news_lg
  case_sensitive: false
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
policies:
- name: MemoizationPolicy
  max_history: 3
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: MappingPolicy
- name: FormPolicy
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.3
  ambiguity_threshold: 0.05
  core_threshold: 0.3
  deny_suggestion_intent_name: out_of_scope

```
