### ISSUE TITLE
E2E actions should result in `BotUtterance`s

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6410]
With Rasa Open Source 2.0 we introduce end-to-end actions. End-to-end actions don't have a label (like `utter_greet`) but contain the actual user utterance, e.g.:

```yaml
stories:
- story: My end-to-end story
  steps:
  - intent: greet
  - bot: Hey, how are you? 
```

Todos:
- [x] make sure that an executed `Action` which has an end-to-end bot utterance, creates a `BotUttered` event
- [x] think about how to distinguish "End-to-end actions" from regular actions in the domain
