### ISSUE TITLE
Add end-to-end conversation tests support to the 2.0 parser

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#6430]
**Description of Problem**:
The 2.0 YAML Parser should be able to parse the following block:

```yaml
# End to end testing format:
test_conversations:
- story: A basic end-to-end test
  steps:
  - user: |
     hello
    intent: greet
  - action: utter_ask_howcanhelp
  - user: |
     show me [chinese]{"entity": "cuisine"} restaurants
    intent: inform
  - action: utter_ask_location
  - user: |
     in [Paris]{"entity": "location"}
    intent: inform
  - action: utter_ask_price
```

On a first look only `user` key processing is missing from the Stories parser.

**Definition of Done**:
- [x] Tests are added
- [ ] Feature described the docs
- [x] Feature mentioned in the changlog
