### ISSUE TITLE
RulePolicy core fallback config not loaded from model

### ISSUE THREAD

**Issue by NetBKarine** [RasaHQ/rasa#6516]
**Rasa version**: 2.0.0a2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:
RulePolicy fallback configuration does not seem to be loaded from model. It predicts `action_default_fallback` even though I configured another action.
I added logging to check and when running `rasa train`, the RulePolicy is correctly instantiated with the parameters in the config file, but when running `rasa shell`, it is instantiated with the default parameters (at least the action name, I didn't check the other parameters). My custom policy is instantiated correctly with the same action and it works. I think I could submit a PR for this, the problem seems to be the inherited `load` method from the MemoizationPolicy in the RulePolicy.

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
    case_sensitive: false
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
    case_sensitive: false
  - name: CountVectorsFeaturizer
    case_sensitive: false
  - name: CountVectorsFeaturizer
    case_sensitive: false
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: RulePolicy
    core_fallback_threshold: 0.01
    core_fallback_action_name: "action_my_fallback"
    enable_fallback_prediction: true
  - name: core.policies.unsupported_intent_policy.UnsupportedIntentPolicy
    fallback_action_name: "action_my_fallback"
```

**Content of domain file (domain.yml)** (if relevant):
```yml
...
actions:
  ...
  - action_my_fallback
...
```
