### ISSUE TITLE
Server crashes when using pipeline with BERT and CRFEntityExtractor

### ISSUE THREAD

**Issue by MajaRolevski** [RasaHQ/rasa#6522]
**Rasa version**: 1.10.7

**Python version**: 3.7

**Operating system**: Ubuntu 18

**Issue**:  I am using the pipeline given below for training the model on the server. After the DIET component finishes with training, CRFEntityExtractor training starts, but it crashes after a while and the server gives the error shown below. To continue working with the server, it has to be rebooted. I have noticed that this situation happens only when using the combination of BERT and CRFEntityExtractor.

Is there somebody familiar with this issue? Any help would be appreciated. 

Server configuration: 
GPUs:1, vCPU:16, Memory (GiB): 122, GPU Memory (GiB): 8

**Error (including full traceback)**:
```
Network error: Connection timed out
```

**Command or request that led to error**:
```
rasa train nlu
```

**Content of configuration file (config.yml)**:
```
language: en
pipeline:
- name: "HFTransformersNLP"
  model_weights: "bert-base-cased-finetuned-mrpc"
  model_name: "bert"
- name: "LanguageModelTokenizer"
- name: "LanguageModelFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: 'word'
- name: "CountVectorsFeaturizer"
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: "DIETClassifier"
  random_seed: 42
  intent_classification: True
  entity_recognition: False
  epochs: 10
  learning_rate: 0.0002
  embedding_dimension: 60
  number_of_transformer_layers: 1
  batch_size: 64
  hidden_layer_sizes:
  text: [256, 128]
  evaluate_on_number_of_examples: 2300
  evaluate_every_number_of_epochs: 1
  tensorboard_log_directory: "/home/ubuntu/rasa-1.8/tensorboard"
  tensorboard_log_level: "epoch"
name: "CRFEntityExtractor"
```
