### ISSUE TITLE
Dynamo Tracker Store Documentation Error

### ISSUE THREAD

**Issue by kearnsw** [RasaHQ/rasa#6545]
The documentation at docs/docs/tracker-stores.mdx contains a typo. 

```
tracker_store:
    type: dynamo
    tablename: <name of the table to create, e.g. rasa>
    region: <name of the region associated with the client>
```

Should be 

```
tracker_store:
    type: dynamo
    table_name: <name of the table to create, e.g. rasa>
    region: <name of the region associated with the client>
```

The `table_name` argument to the DynamoTrackerStore is snake case.
