### ISSUE TITLE
Make metadata available in NLU components

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#6602]
Part of #6475 

`2.0` Training data format introduced a new `metadata` field for the NLU training examples:

```yaml
nlu:
- intent: estimate_emissions
  # Arbitrary metadata
  metadata:
    author: Some example metadata!
    key: value
  # Multiline examples, each line is a separate training example.
  examples: |
     - how much CO2 will that use?
```

The content of metadata is not fixed and is up to the users to decide on. However, we should parse it and make it available from the custom NLU components user might have. One example - sentiments analyzer described [here](https://blog.rasa.com/enhancing-rasa-nlu-with-custom-components/). It uses a separate text file with sentiments, but now users should be able to store sentiments next to the training examples using the `metadata` field.
