### ISSUE TITLE
Merging categorical slots across multiple domains overrides values

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#6651]
**Rasa version**: 1.10.7

**Rasa SDK version** (if used & relevant): 1.10.2 (not relevant)

**Rasa X version** (if used & relevant): N/A

**Python version**: 3.7

**Operating system** (windows, osx, ...): Linux (Ubunutu)

**Issue**:
This may not 100% be an issue, but something I noticed in using the `MultiProjectImporter`.  What I would like to do is have a categorical slot such as `topic` shared across several imported projects and have those merged at training time.  The problem, i think is [this function](https://github.com/RasaHQ/rasa/blob/84db4cd5267c20ae755affa4ce2deaa3dc5b0185/rasa/shared/core/domain.py#L222) that's called when merging slots.  What happens is that for categorical slots, the lists of values are not merged, they're overridden regardless if `override_existing_values` is set.  This is because of typical `dict.update()` behavior:
```log
>>> d1 = {"a": [1, 2]}
>>> d2 = {"a": [3, 4]}
>>> d1.update(d2)
>>> d1
{'a': [3, 4]}
```

```log
>>> d1 = {"a": [1, 2]}
>>> d2 = {"a": [3, 4]}
>>> d2.update(d1)
>>> d2
{'a': [1, 2]}
```

What would be nice is to check if the values in the dict contain a list in which case merge the two lists.

I think this might be something others might run into when using `MultiProjectImporter` since while the bots are meant to be worked on independently, you'd expect any duplicative/repeated slots to result in a single merged slot during training.

However, I acknowledge that [categorical slots are the only case which contain a list of values](https://rasa.com/docs/rasa/core/slots/#categorical-slot), so unless you use the same categorical slot across multiple projects, you won't encounter this issue.  I'd argue that this is still something you'd want to account for, however, since it's unexpected behavior when merging training data.

**Error (including full traceback)**: N/A

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en

importers:
  - name: MultiProjectImporter

imports:
  - projects/test_1
  - projects/test_2

pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
```

**Content of domain file (domain.yml)** (if relevant):
Just tested this on a new project from `rasa init` and confirm this is happening:

Imported Domain 1 (`projects/test_1/domain.yml`):
```yml
# ...
slots:
  topic:
    type: categorical
    values:
      - A
      - B
      - C
# ...
```

Imported Domain 2 (`projects/test_2/domain.yml`):
```yml
# ...
slots:
  topic:
    type: categorical
    values:
      - D
      - E
      - F
# ...
```
Resulting domain.yml in model artifact:

```yml
  topic:
    type: rasa.core.slots.CategoricalSlot
    initial_value: null
    auto_fill: true
    values:
    - a
    - b
    - c
    - __other__
```
