### ISSUE TITLE
Tracker database query statement problems

### ISSUE THREAD

**Issue by genius0182** [RasaHQ/rasa#6673]
**Rasa version**:
Rasa 1.10.9

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
python 3.7.7

**Operating system** (windows, osx, ...):
windows,centos
**Issue**:
When tracker is stored in the database, the same command is repeatedly asked 50-60 times, which will cause problems. The reason is that the timestamp field has problems after being stored in the database. See the screenshot below for details.
![error](https://user-images.githubusercontent.com/24863486/93188661-d3817d80-f773-11ea-8ba3-087af7cd4e85.JPG)

suggestion: Line 735 of Rasa /core/ process.py.
e.timestamp = time.time()
Modified into
e.timestamp = int(time.time() * 1000000)
The timestamp field in the events table in the database becomes an int type.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Can you provide more information about your tracker store setup? The processor clearly tracks the timestamp correctly, the issue seems to be (as you've mentioned) upon saving that data to the tracker store, which would be specific to the type of tracker store you are using.

**Comment by genius0182** [comment]
The problem is not always appeared, in some extreme cases, the request is failed to reply, the reason is that the mysql timestamp column sorted, because the timestamp of the content is the same, so there is no effect of sorting, just like in the picture above shows the sort of, in fact with ID 66816668 17, according to the record right should be the last but is actually is displayed in the upper part.This is the cause of the problem.
The tracker used is DialogueStateTracker.SQLTrackerStore is used.
The normal situation is as shown below
![1600216893572](https://user-images.githubusercontent.com/24863486/93285357-3a9c4200-f807-11ea-966a-0e6012180a2f.png)
The abnormal situation is shown in the figure below
![1600218158348](https://user-images.githubusercontent.com/24863486/93285387-4be54e80-f807-11ea-905e-78c3b2d12e13.png)
query sql result:
![1600218272546](https://user-images.githubusercontent.com/24863486/93285421-5ef81e80-f807-11ea-88cc-9db9557061e6.png)
![1600218330609](https://user-images.githubusercontent.com/24863486/93285432-65869600-f807-11ea-93df-d3f3079f5fa1.png)
![1600218404959](https://user-images.githubusercontent.com/24863486/93285450-6f0ffe00-f807-11ea-923e-b2b74884d3e9.png)
sql result data:
[rasa_data.zip](https://github.com/RasaHQ/rasa/files/5229252/rasa_data.zip)

**Comment by erohmensing** [comment]
Can you please add the `endpoints.yml` with your tracker store configuration? This has important data such as the dialect used.

**Comment by genius0182** [comment]
``` yml
# Server which runs your custom actions.
# https://rasa.com/docs/rasa/core/actions/#custom-actions/

action_endpoint:
 url: "http://localhost:5055/webhook"

# Tracker store which is used to store the conversations.
# By default the conversations are stored in memory.
# https://rasa.com/docs/rasa/api/tracker-stores/

tracker_store:
    type: SQL
    dialect: "mysql+pymysql"  # the dialect used to interact with the db
    url: "127.0.0.1"  # (optional) host of the sql db, e.g. "localhost"
    db: "db"  # path to your db
    username:  "aa" # username used for authentication
    password:  "123456" # password used for authentication
```
