### ISSUE TITLE
`rasa data validate` shows wrong conflicting action name

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#6691]
**Rasa version**:
Rasa Version     : 2.0.0a5 (commit 30d2af7847dd97b02fdad4a4abf7ddb64d8115aa)
Rasa SDK Version : 2.0.0a5
Rasa X Version   : 0.32.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
Python Version   : 3.7.0 (default, Oct  9 2018, 10:31:47) 

**Operating system** (windows, osx, ...):
Operating System : Linux-4.15.0-117-generic-x86_64-with-debian-buster-sid

**Issue**:
`rasa data validate` shows wrong conflicting action name. Specifically, if a conflict is present (regardless whether in a story or in a rule), it prints `Story structure conflict after action 'action'`, where the last `action` should be the name of the action instead of the word "action".

**Error**:
With stories
```
- story: happy path
  steps:
  - intent: greet
  - action: utter_greet
  - intent: mood_great
  - action: utter_happy

- story: sad path 1
  steps:
  - intent: greet
  - action: utter_greet
  - intent: mood_unhappy
  - action: utter_cheer_up
  - action: utter_did_that_help
  - intent: affirm
  - action: utter_happy

- story: sad path 2
  steps:
  - intent: greet
  - action: utter_goodbye
  - intent: mood_unhappy
  - action: utter_cheer_up
  - action: utter_did_that_help
  - intent: deny
  - action: utter_goodbye
```
the wrong output is
```
rasa.validator  - Story structure conflict after action 'action':
  utter_greet predicted in 'sad path 1' and 'happy path'
  utter_goodbye predicted in 'sad path 2'
```

**Command or request that led to error**:
```
rasa init
# now add a conflicting story, e.g. by replacing a utter_goodbye by a utter_greet
rasa data validate
```
