### ISSUE TITLE
Converter tool not working for E2E stories

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#6716]
Part of #6638 

### The Issue:

The converter script converts this markdown e2e story:

```markdown
* faq: what is [Rasa X](product)?
    - slot{"product": "x"}
    - respond_faq
    - action_set_faq_slot
```

into this yaml:

```yaml
- story: faqs
  steps:
  - checkpoint: STORY_START
  - intent: 'faq: what is [Rasa X](product)?'
  - slot_was_set:
    - product: x
  - action: respond_faq
  - action: action_set_faq_slot
```

... which doesn't match the E2E format in the docs ([https://rasa.com/docs/rasa/next/testing-your-assistant#end-to-end-testing](https://rasa.com/docs/rasa/next/testing-your-assistant#end-to-end-testing))

The `intent` section should look different:
```yaml
...
- user: |
      what is [Rasa X](product)?
  intent: faq
...
```

### How to reproduce:

 - create a text file `test_faq.md` with markdown snippet from above
 - run `rasa data convert core -f yaml --data {path_to_the_test_faq.md} --out {any_folder}` 
 - this will create a file called `test_faq_converted.yaml` in the output directory

Files to take a look to: 
- `rasa/cli/data.py`
- `rasa/core/training/converters/story_markdown_to_yaml_converter.py`
- `rasa/shared/core/training_data/story_writer/yaml_story_writer.py`

Test to take a look to:
- `tests/cli/test_rasa_data.py`
- `tests/shared/core/training_data/story_writer/test_yaml_story_writer.py`
