### ISSUE TITLE
Test stories don't work if they aren't in the end-to-end format

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#6732]
Part of #6638 

**Rasa version**: 2.0.0rc1

Test stories don't work if they aren't in the end-to-end format, even if they are still valid story files e.g.

```yaml
version: "2.0"
stories:
- story: prompt for getting started + confirm
  steps:
  - intent: get_started_step1
  - action: action_greet_user
  - intent: affirm
  - action: utter_getstarted
  - action: utter_first_bot_with_rasa
```

This story will fail because the intent `get_started_step1` gets interpreted as a message instead of an intent. The output file `failed_test_stories.yml` shows this:

```yaml
version: "2.0"
stories:
- story: prompt for getting started + confirm (/var/folders/wc/lzjxcb8j28b2cvrwl9jv9k_h0000gn/T/tmpebavhe42/c8b65dd1df414dc4ae9ec0824829f728_test_stories_converted.yml)
  steps:
  - action: action_listen
  - intent: get_started_step1  # predicted: enter_data: get_started_step[1](number)
    user: |-
      get_started_step1
  - action: action_greet_user
  - action: action_listen
  - intent: affirm
    user: |-
      affirm
  - action: utter_getstarted
  - action: utter_first_bot_with_rasa
  - action: action_listen
```

**Comment by kalkbrennerei** [comment]
i think this is already fixed?
trying to reproduce it i got this:

```yaml
version: "2.0"
stories:
- story: prompt for getting started + confirm (/var/folders/7y/mgv9hfvs45l75j9mn_5gxv2h0000gr/T/tmpd67pel0n/a9262482620c4001b02c35fe029cfa51_test_getting_started.yml)
  steps:
  - action: action_listen
  - intent: get_started_step1
  - action: action_greet_user  # predicted: action_default_fallback
  - action: action_listen
  - intent: affirm
  - action: utter_getstarted  # predicted: utter_happy
  - action: utter_first_bot_with_rasa  # predicted: action_listen
  - action: action_listen
```
