### ISSUE TITLE
Bug of Chinese tokenization in 2.0.0rc1

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa#6752]
**Rasa version**: 2.0.0rc1

**Python version**: 3.8.2

**Operating system** (windows, osx, ...): ubuntu 20.04

**Command or request that led to error**: rasa train

**Issue**:
Every Chinese train example is split as one and only one token by mistake, all Chinese character without whitespace inside will treated as one token with each character as subtoken. when the example comes with entities, it will cause `UserWarning: Misaligned entity annotation`. A hidden and terrible result is that since the tokenization is incorrected, the training component (such like a DIET component) is not correct too although there is no error shows up.

I will submit a PR to fix it.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by xkungfu** [comment]
@howl-anderson 
你好，借楼请教一个问题，我在试用rc1时也遇到了问题，但是因为我是新手，我不能确定是源码的问题，还是我自己使用不当造成的。网上查到的资料都是关于旧版的rasa的，2.0版还没有见到中文方面的资料，rasa执行时又没有报错，所以对于我来说我无法确定问题。正好您在使用中文的配置，可否帮助我看一下我的配置是不是有问题？谢谢！

Rasa version: 2.0.0rc1
Python version: 3.6.9
OS: ubuntu 18.04

config.yml
```

language: "zh"
pipeline:
- name: "JiebaTokenizer"
  dictionary_path: "jiebatemp"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4

policies:
  - name: MemoizationPolicy
    max_history: 5
```

the dict.txt format like below:

 
> RSS订阅 3 n
> 江南Style 3 n
> 1号店 3 n
> 中国 129470 ns
> 中国下载 3 b


rasa train successfully. but parse intent by rasa shell nlu, the result is null.
