### ISSUE TITLE
Add `unfeaturized` flag to slots

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6809]
# Motivation

Slots themselves cause confusion in another way -- users may define the type based on what they hold (e.g. “text”) but not include them in their stories because they shouldn’t affect the flow -- it’s common that users don’t understand that setting the type to text will actually featurize the slot, leading to unpredictable behavior.

# Suggested Solution

1. Add a flag `unfeaturized: true / false` to the configuration of each slot in the domain. Return the slots features in `as_feature` depending on the value of the `unfeaturized` flag
   
   ```yaml
   slots:
     os:
       type: categorical
       values:
       - Windows
       - MacOS
       - Linux
       unfeaturized: true
    # this would previously been
    # os2:
      # type: unfeaturized
    ````
    Open questions:
    - [ ] What should be the default value for `unfeaturized`? I'd vote for `false` because we will otherwise breaking existing bots. 
2. Deprecate `UnfeaturizedSlot`
    Open questions:
    - [ ] Should we introduce a slot type `Any` instead which can hold arbitrary values? I'd vote for `yes`. We can introduce a slot type `Any` which explicitly throws an error when used with `unfeaturized: false`. If users want to use an `Any` slot with `unfeaturized: false`, they need to implement their own slot type
3. Check whether / how this affects Rasa X / Rasa SDK
