### ISSUE TITLE
Make entity extraction for entities separated by comma configurable 

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#6852]
With PR https://github.com/RasaHQ/rasa/pull/6191, entities separated by comma now get extracted separately. This makes sense for something like: 

please add buffalo, ranch, mustard, barbeque sauces results in {'entity': 'sauces', 'start': 11, 'end': 43, 'value': 'buffalo, ranch, mustard, barbeque', 'extractor': 'DIETClassifier'}

But maybe shouldn't work this way for address entities like `5306 Walnut Ave., Building A, Sacramento, CA 95841`. See also issue https://github.com/RasaHQ/rasa/issues/6795.

We should make this behaviour configurable in the entity extractors, and maybe even on an entity level, given you might have both types of entities in one bot.

**Comment by tttthomasssss** [comment]
@tabergma @akelad just to be clear - is the idea to make this configurable per entity type (on the basis of the entity types that are annotated in the NLU training data)? For example, supposing that `address` and `ingredients` are two entity types in the data, users simply need to specify sth like the following in the config (with default behaviour of True?):

```
language: en
pipeline:
  ...
  - name: DIETClassifier
    epochs: 100
    entity_recognition: True
    split_entities_by_comma: 
      address: False
      ingredients: True
  ...
```

**Comment by tabergma** [comment]
Something like this sounds good I would say. I guess it would be even better if we support both variants:
```
language: en
pipeline:
  ...
  - name: DIETClassifier
    epochs: 100
    entity_recognition: True
    split_entities_by_comma: False/True
  ...
```
and 
```
language: en
pipeline:
  ...
  - name: DIETClassifier
    epochs: 100
    entity_recognition: True
    split_entities_by_comma: 
      address: False
      ingredients: True
  ...
```
We also should be able to handle the cases where not all entities are listed in the second configuration. And this should also be available for the `CRFEntityExtractor`.
