### ISSUE TITLE
Rules: One user message limit breaks handling of unhappy paths

### ISSUE THREAD

**Issue by N-Olbert** [RasaHQ/rasa#6861]
**Rasa version**: 2.0rc3

Currently (changed in rc3 by #6607 because of #6557) a rule is not allowed to contain more than one user message/utterance action.

Anyways in practice there are cases where more user messages are useful, as also stated in the official [documentation](https://rasa.com/docs/rasa/forms#writing-stories--rules-for-unhappy-form-paths):
```
rules:
- rule: Example of an unhappy path
  condition:
  # Condition that form is active.
  - active_loop: restaurant_form
  steps:
  - intent: stop
  - action: utter_ask_continue
  - intent: stop
  - action: action_deactivate_loop
  - active_loop: null
```

Current error for this offical example: 

> Found rules 'Example of an unhappy path' that contain more than 1 user message. Rules are not meant to hardcode a state machine. Please use stories for these cases.

Suggestion: Increase the number of allowed user utterances to 2. This still prevents building (highly) complex state machines with rules, but allows common unhappy path handling with confirmation. 
Forcing the user to set *restrict_rules* to false does not seem to be a valid option, because according to the documentation it seems to be dangerous (I doubt so :D) and requires manual effort.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Ghostvv** [comment]
thank you for spotting that, we'll update the docs.
You can convert unhappy path into 2 rules:
```
rules:
- rule: ask continue
  condition:
  # Condition that form is active.
  - active_loop: restaurant_form
  steps:
  - intent: stop
  - action: utter_ask_continue

- rule: stop form
  condition:
  # Condition that form is active.
  - active_loop: restaurant_form
  steps:
  - action: utter_ask_continue
  - intent: stop
  - action: action_deactivate_loop
  - active_loop: null
```
