### ISSUE TITLE
Slack : Bot doesnt respond at all : "TypeError: 'NoneType' object is not iterable". trace =>line 203, in _sanitize_user_message , for uid_to_remove in uids_to_remove:

### ISSUE THREAD

**Issue by SindhuMohana** [RasaHQ/rasa#6895]
**Rasa version**: Rasa: 1.10.14

**Rasa SDK version** (if used & relevant): NA

**Rasa X version** (if used & relevant): NA

**Python version**: Python 3.7.9

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
I am testing a bot on slack after deploying it successfully in slack - I get : "TypeError: 'NoneType' object is not iterable"
**Please note that the same Bot works well with "rasa shell"**
**The problem is ONLY seen when trying to test the bot in Slack.**

**Error (including full traceback)**:

Traceback (most recent call last):
  File "c:\users\smohana\anaconda3\envs\rasa_new\lib\site-packages\sanic\app.py", line 976, in handle_request
    response = await response
  File "c:\users\smohana\anaconda3\envs\rasa_new\lib\site-packages\rasa\core\channels\slack.py", line 384, in webhook
    user_message, metadata["users"]
  File "c:\users\smohana\anaconda3\envs\rasa_new\lib\site-packages\rasa\core\channels\slack.py", line 203, in _sanitize_user_message
    for uid_to_remove in uids_to_remove:
TypeError: 'NoneType' object is not iterable`

**Command or request that led to error**:
Just trying to interact with utter_greet in Slack

```

**Content of configuration file (config.yml)** (if relevant):
``
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 150
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 150


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
``
NA
```
