### ISSUE TITLE
Warn for invalid keys for classifiers

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#6966]
**Rasa version**: 2.0.0

**Issue**:

If you pass an invalid key to a classifier no warning or error is thrown during training

**Command or request that led to lack of error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
pipeline
- name: FallbackClassifier
   confidence_threshold: 0.7
```

(should be `threshold`)

**Comment by rgstephens** [comment]
Here's a similar issue with responses. `button_type` is not valid at this location, but `validate` and `train` don't throw an error.

```
  utter_ask_feedback:
  - buttons:
    - button_type: inline
    - payload: /feedback{"feedback_value":"positive"}
      title: 👍
    - payload: /feedback{"feedback_value":"negative"}
      title: 👎
    text: How is this conversation going?
```
