### ISSUE TITLE
`rasa data validate stories` misses some conflicts with rules

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#6973]
**Rasa version**:
Rasa Version     : 2.0.0
Rasa SDK Version : 2.0.0a5
Rasa X Version   : 0.32.0
Python Version   : 3.7.0 (default, Oct  9 2018, 10:31:47) 
Operating System : Linux-4.15.0-118-generic-x86_64-with-debian-buster-sid

**Issue**:
The `rasa data validate stories` command misses some conflicts between rules and stories that appear at the beginning of the story. Specifically, if you create a `rasa init` project and replace `rules.yml` with
```
version: "2.0"
rules:
- rule: the rule
  steps:
  - intent: goodbye
  - action: utter_iamabot
```
and `stories.yml` with
```
version: "2.0"
stories:
- story: the story
  steps:
  - intent: goodbye
  - action: utter_goodbye
```
and then run `rasa data validate stories`, the output will be `No story structure conflicts found`, which is wrong.
The conflict is found correctly if you add `conversation_start: true` to the rule. This is caused by the `...` action that comes from the rule and throws off the validation code.

Related [discussion on Slack](https://rasa-hq.slack.com/archives/C36SS4N8M/p1602088753114200).

**Error (including full traceback)**:
```
No story structure conflicts found
```

**Command or request that led to error**:
```
rasa data validate stories
```
