### ISSUE TITLE
Steep increase in memory consumption while training using rasa nlu

### ISSUE THREAD

**Issue by Scsourav18** [RasaHQ/rasa#6998]
**Rasa version**: 1.10.2

**Python version**: 3.6.10

**Operating system** : RHEL 7.6

**Issue**:
I have created a project using Rasa NLU along with Flask for intent recognition. Below is the part of code used for training
```
from rasa.nlu.model import Interpreter
from rasa.nlu.training_data import load_data
from rasa.nlu import config
from rasa.nlu.model import Trainer

model_name = "app-" + 101
model_path = os.path.join(model_storage_path, model_name)
training_data = load_data(training_data.json)
trainer = Trainer(config.load(en_config.yml))
trainer.train(training_data)
trainer.persist(model_storage_path, fixed_model_name=model_name)
model = Interpreter.load(model_path)
```
And the contents of config file used is
```yml
language: "en"

pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    entity_recognition: False
  - name: ResponseSelector
    epochs: 100
```
The APIs are hosted using a docker container. Initially when the service is hosted  the memory consumption of the container using docker stats is : -
```
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
0197375c3ec3        0.21%               135.6MiB / 15.5GiB   0.85%               51.6kB / 72.2kB     10.6MB / 0B         15
```
And after training for the first time the memory consumption increased to 2.4GB
```
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
0197375c3ec3        0.22%               2.507GiB / 15.5GiB   16.17%              179kB / 232kB       58MB / 12.3kB       52
```
And after training second time using the same training data the memory consumption by increased by 1.6GB
```
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
0197375c3ec3        0.20%               4.16GiB / 15.5GiB    26.83%              276kB / 352kB       58MB / 61.4kB       52
```
And after third time the consumption increased by 1.4 GB
```
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
0197375c3ec3        0.23%               5.581GiB / 15.5GiB   35.99%              385kB / 487kB       58MB / 106kB        52
```
After a few training the server becomes unresponsive and i need to restart the container.
Is this a expected behavior or am i missing something?
PS :- the training data json is around 20KB and models which are persisted in filesystem is around 51MB
