### ISSUE TITLE
Converter works unpredictibly with retrieval intents

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#7032]
**Rasa version**: 2.0.0

**Issue**:
If you have an md e2e story that contains full retrieval intents or responses, the converter sometimes strips out yaml with only the base intent

This:
```
## id
* out_of_scope/other: hahaha
    - utter_out_of_scope/other
```

is converted to:
```
version: "2.0"
stories:
- story: id
  steps:
  - intent: 'out_of_scope/other: hahaha'
  - action: utter_out_of_scope/other
```

BUT this
```
## id

* out_of_scope/other: hahaha
    - utter_out_of_scope/other
```

gets converted into something completely different, with the retrieval intent removed:
```
version: "2.0"
stories:
- story: id
  steps:
  - intent: out_of_scope
    user: |-
      hahaha
  - action: utter_out_of_scope/other
```
