### ISSUE TITLE
Allow forms without default slot mappings / only custom slots mappings

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7068]
Currently, you need to add at least one slot mapping to your form in the domain. Otherwise, it will choose the Rasa Open Source 1.x `FormAction` for execution (see [here](https://github.com/RasaHQ/rasa/blob/ae8eee310a9cb00573d5d44650d2654436475cc4/rasa/core/actions/action.py#L127))

We need to detect the deprecated usage of old forms differently and allow that users can define a form like the following:

```yaml
forms:
   my_form:
     # no slot mappings
     # all slots are extracted in the custom validation action
```
