### ISSUE TITLE
Loading a model is a taking a long time in DIET classifier

### ISSUE THREAD

**Issue by Sharma-Saravanan** [RasaHQ/rasa#7096]
**Rasa version**: 2.0.2

**Rasa SDK version** (if used & relevant): 2.0.0

**Rasa X version** (if used & relevant):

**Python version**:3.6.8

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: Loading the rasa nlu trained model  is takin long time and thus return a response after 2 mins

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```
train RASA NLU using any data with the attached config and load the model using "from rasa.nlu.model import Interpreter"` will take 2 mins to return the result

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "en"

pipeline:
  - name: "SpacyNLP"
    model: "en"
    case_sensitive: False
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    alias: "spacy"
  - name: RegexFeaturizer
    alias: "regex"
  - name: LexicalSyntacticFeaturizer
    alias: "lexical-syntactic"
  - name: CountVectorsFeaturizer
    alias: "cvf-word"
  - name: CountVectorsFeaturizer
    alias: "cvf-char"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    featurizers: ["convert", "cvf-word"]
    epochs: 100

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @melindaloubser1 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
@ Sharma-Saravanan am I understanding the issue right that training an NLU model which includes DIETClassifier is taking >2 min?
If so, that is very normal, in fact usually training times are much longer than that, depending on how much data you have.

**Comment by Sharma-Saravanan** [comment]
NO, you have misunderstood it... the training process seems to be normal.
loading the trained model is takin more than 2 mins which will further increase the prediction time

**Comment by melindaloubser1** [comment]
How long did the model take to train? Is the 2 min just at initial loading time? what are subsequent prediction times after the model has been loaded?

**Comment by Sharma-Saravanan** [comment]
training time took 1.4 mins and model size was 32MB for 10 intents...
initial loading time of the model was around 2 mins.
subsequent prediction times after the model has been loaded is 3 seconds. But the problem is we are using different models for different categories such as dental model, roofing model, etc.. so we need to load the model dynamically

**Comment by melindaloubser1** [comment]
Gotcha. I'm wondering about this part of your pipeline:
```
  - name: ResponseSelector
    featurizers: ["convert", "cvf-word"]
    epochs: 100
```
I don't see `convert` as an alias to any featurizer - are you seeing any errors when training/loading this model? 

If I can get clarification on that I'll try reproduce it with your pipeline. I definitely don't see this long a load time using the following pipeline, even with training taking upwards of half an hour:

```
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  ranking_length: 5
- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions:
  - email
  - number
  - amount-of-money
- name: EntitySynonymMapper
- name: ResponseSelector
  retrieval_intent: out_of_scope
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  retrieval_intent: faq
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  retrieval_intent: chitchat
  scale_loss: false
  epochs: 100
- name: FallbackClassifier
  threshold: 0.7
```
