### ISSUE TITLE
Including None or null explicitly as featurized Slot Value leads to failing Rule Policy

### ISSUE THREAD

**Issue by LuzianHahn** [RasaHQ/rasa#7166]
**Rasa version**: 2.0.3

**Rasa SDK version** (if used & relevant): -

**Rasa X version** (if used & relevant): - 

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): Linux Ubuntu16.04

**Issue**: 
When adding the value "None"(str) or null explicitly into the value configuration of a possible slot inside the domain.yml, the RulePolicy cannot handle the content "None"(NullObject) as condition to match rules.

See the following setup:

**General:**

- ***Rules:***

```yml
version: '2.0'
rules:
- rule: set_A
  steps:
  - intent: intent_A
  - action: action_set_A
- rule: set_None
  steps:
  - intent: intent_None
  - action: action_set_None
- rule: utter_A
  condition:
  - slot_was_set:
    - X: A
  steps:
  - intent: trigger_utter
  - action: utter_A
- rule: utter_None
  condition:
  - slot_was_set:
    - X:
  steps:
  - intent: trigger_utter
  - action: utter_None
```

- ***Test Story:***

```yml
stories:
- story: utter A and None
  steps:
  - intent: intent_A
  - action: action_set_A
  - slot_was_set:
    - X: A
  - intent: trigger_utter
  - action: utter_A
  - intent: intent_None
  - action: action_set_None
  - slot_was_set:
    - X: 
  - intent: trigger_utter
  - action: utter_None
```

**Example 1** (without setting explicitly None as value):
- ***Domain:*** (name of the file: "domain_wout.yml")
```yml
version: '2.0'
intents:
- intent_A
- intent_None
- trigger_utter
responses:
  utter_A:
  - text: "A"
  utter_None:
  - text: "None"
forms: []
slots:
  X:
    type: categorical
    values:
    - "A"
actions:
- action_set_A
- action_set_None
```

**Example 2** (with setting explicitly null as value):
- ***Domain:*** (name of the file: "domain_w_null.yml")
```yml
version: '2.0'
intents:
- intent_A
- intent_None
- trigger_utter
responses:
  utter_A:
  - text: "A"
  utter_None:
  - text: "None"
forms: []
slots:
  X:
    type: categorical
    values:
    - "A"
    - null
actions:
- action_set_A
- action_set_None
```

**Example 3** (with setting explicitly "None" as value):
- ***Domain:*** (name of the file: "domain_w_None.yml")
```yml
version: '2.0'
intents:
- intent_A
- intent_None
- trigger_utter
responses:
  utter_A:
  - text: "A"
  utter_None:
  - text: "None"
forms: []
slots:
  X:
    type: categorical
    values:
    - "A"
    - "None"
actions:
- action_set_A
- action_set_None
```
**Example 3** (with setting explicitly an additional random string as value):
- ***Domain:*** (name of the file: "domain_w_random.yml")
```yml
version: '2.0'
intents:
- intent_A
- intent_None
- trigger_utter
responses:
  utter_A:
  - text: "A"
  utter_None:
  - text: "None"
forms: []
slots:
  X:
    type: categorical
    values:
    - "A"
    - something_else
actions:
- action_set_A
- action_set_None
```
**Error (including full traceback)**:
```
>>> Start Setup: wout
Training Core model...
Core model training completed.
Your Rasa model is trained and saved at '/tmp/rasa_featurized_slot_w_none/models/wout.tar.gz'.
No NLU model found. Using default 'RegexInterpreter' for end-to-end evaluation. If you added actual user messages to your test stories this will likely lead to the tests failing. In that case, you need to train a NLU model first, e.g. using `rasa train`.
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 353.44it/s]
<<< End Setup: wout
>>> Start Setup: w_null
Training Core model...
Core model training completed.
Your Rasa model is trained and saved at '/tmp/rasa_featurized_slot_w_none/models/w_null.tar.gz'.
No NLU model found. Using default 'RegexInterpreter' for end-to-end evaluation. If you added actual user messages to your test stories this will likely lead to the tests failing. In that case, you need to train a NLU model first, e.g. using `rasa train`.
  0%|                                                                                                        | 0/1 [00:00<?, ?it/s]
WrongPredictionException: Model predicted a wrong action. Failed Story: 

version: "2.0"
stories:
- story: utter A and None
  steps:
  - intent: intent_A
  - action: action_set_A
  - slot_was_set:
    - X: A
  - intent: trigger_utter
  - action: utter_A
  - intent: intent_None
  - action: action_set_None  # predicted: action_listen

<<< End Setup: w_null
>>> Start Setup: w_None
Training Core model...
Core model training completed.
Your Rasa model is trained and saved at '/tmp/rasa_featurized_slot_w_none/models/w_None.tar.gz'.
No NLU model found. Using default 'RegexInterpreter' for end-to-end evaluation. If you added actual user messages to your test stories this will likely lead to the tests failing. In that case, you need to train a NLU model first, e.g. using `rasa train`.
  0%|                                                                                                                                                                       | 0/1 [00:00<?, ?it/s]
WrongPredictionException: Model predicted a wrong action. Failed Story: 

version: "2.0"
stories:
- story: utter A and None
  steps:
  - intent: intent_A
  - action: action_set_A
  - slot_was_set:
    - X: A
  - intent: trigger_utter
  - action: utter_A
  - intent: intent_None
  - action: action_set_None  # predicted: action_listen

<<< End Setup: w_None
>>> Start Setup: w_random
Training Core model...
Core model training completed.
Your Rasa model is trained and saved at '/tmp/rasa_featurized_slot_w_none/models/w_random.tar.gz'.
No NLU model found. Using default 'RegexInterpreter' for end-to-end evaluation. If you added actual user messages to your test stories this will likely lead to the tests failing. In that case, you need to train a NLU model first, e.g. using `rasa train`.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 364.22it/s]
<<< End Setup: w_random
```

**Command or request that led to error**:
```bash
for setup in wout w_null w_None w_random;do
	echo ">>> Start Setup: $setup"
	rasa train core -s data.yml -d domain_${setup}.yml --fixed-model-name $setup --quiet
	rasa test core -s test_story.yml -m models/${setup}.tar.gz --out results/${setup} --fail-on-prediction-errors --quiet
	echo "<<< End Setup: $setup"
done
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: DucklingHTTPExtractor
    url: http://localhost:8000
  - name: DIETClassifier
    epochs: 1
  - name: FallbackClassifier
    ## If the highest ranked intent has a confidence lower than the threshold than
    ## the NLU pipeline predicts an intent `nlu_fallback` which you can then use in
    ## stories / rules to implement an appropriate fallback.
    threshold: 0.2

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: action_listen
    enable_fallback_prediction: true
```
