### ISSUE TITLE
Ambiguity in Two-Stage-Fallback implementation documents for version 2.0.x

### ISSUE THREAD

**Issue by akshayrkg** [RasaHQ/rasa#7168]
The `rules.yml` file depicting the implementation of Two-Stage-Fallback has a small ambiguity in the below two links.
The value for `active_loop` is different in the two links.

**https://rasa.com/docs/rasa/fallback-handoff#fallbacks**

```
rules:
- rule: Implementation of the Two-Stage-Fallback
  steps:
  - intent: nlu_fallback
  - action: action_two_stage_fallback
  - active_loop: two_stage_fallback
```

**https://rasa.com/docs/rasa/migration-guide**
```
rules:
  - rule: Implementation of the TwoStageFallbackPolicy
    steps:
    - intent: nlu_fallback
    - action: action_two_stage_fallback
    - active_loop: action_two_stage_fallback
```
