### ISSUE TITLE
Corrupted GZIP file when save model

### ISSUE THREAD

**Issue by alexlana** [RasaHQ/rasa#7175]
**Rasa version**: 2.0.3 in Docker 2.4.0.0 (engine 19.03.13)

**Rasa SDK version** (if used & relevant): --

**Rasa X version** (if used & relevant): --

**Python version**: 3.7-slim

**Operating system** (windows, osx, ...): MacOS 10.15.7

**Issue**:
Model saved in a corrupted GZIP file. When I tryed to expand using the MacOS I received a message about incompatible format. 

When I tryed `rasa run` I had the messages bellow.

I am using this pipeline:
```
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1
```

I test it commenting all lines and than uncomment line by line. Before DIETClassifier the result gzipped file have about 2MB and I have no trouble to expand it. When I use DIETClassifier the file size increases to about 25MB and was corrupted, always.

**Error (including full traceback)**:
```
rbot       | 2020-11-03 21:09:08 INFO     rasa.model  - Loading model models/20201103-210828.tar.gz...
rbot       | 2020-11-03 21:09:08 ERROR    rasa.model  - Failed to extract model at models/20201103-210828.tar.gz. Error: not a gzip file
rbot       | Traceback (most recent call last):
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1646, in gzopen
rbot       |     t = cls.taropen(name, mode, fileobj, **kwargs)
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1623, in taropen
rbot       |     return cls(name, mode, fileobj, **kwargs)
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1486, in __init__
rbot       |     self.firstmember = self.next()
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 2289, in next
rbot       |     tarinfo = self.tarinfo.fromtarfile(self)
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1094, in fromtarfile
rbot       |     buf = tarfile.fileobj.read(BLOCKSIZE)
rbot       |   File "/usr/local/lib/python3.7/gzip.py", line 287, in read
rbot       |     return self._buffer.read(size)
rbot       |   File "/usr/local/lib/python3.7/_compression.py", line 68, in readinto
rbot       |     data = self.read(len(byte_view))
rbot       |   File "/usr/local/lib/python3.7/gzip.py", line 474, in read
rbot       |     if not self._read_gzip_header():
rbot       |   File "/usr/local/lib/python3.7/gzip.py", line 422, in _read_gzip_header
rbot       |     raise OSError('Not a gzipped file (%r)' % magic)
rbot       | OSError: Not a gzipped file (b'\x00\x00')
rbot       | 
rbot       | During handling of the above exception, another exception occurred:
rbot       | 
rbot       | Traceback (most recent call last):
rbot       |   File "/opt/venv/bin/rasa", line 8, in <module>
rbot       |     sys.exit(main())
rbot       |   File "/opt/venv/lib/python3.7/site-packages/rasa/__main__.py", line 116, in main
rbot       |     cmdline_arguments.func(cmdline_arguments)
rbot       |   File "/opt/venv/lib/python3.7/site-packages/rasa/cli/run.py", line 116, in run
rbot       |     get_model(args.model)
rbot       |   File "/opt/venv/lib/python3.7/site-packages/rasa/model.py", line 159, in get_model
rbot       |     return unpack_model(model_path)
rbot       |   File "/opt/venv/lib/python3.7/site-packages/rasa/model.py", line 204, in unpack_model
rbot       |     with tarfile.open(model_file, mode="r:gz") as tar:
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1593, in open
rbot       |     return func(name, filemode, fileobj, **kwargs)
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1650, in gzopen
rbot       |     raise ReadError("not a gzip file")
rbot       | tarfile.ReadError: not a gzip file
rbot exited with code 1
```

**Command or request that led to error**:
```
rasa train
```
When save GZIP.

**Content of configuration file (config.yml)** (if relevant):
```yml
language: pt

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100

policies:
  - name: TEDPolicy
    epochs: 10
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 5
      state_featurizer:
        - name: BinarySingleStateFeaturizer
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "utter_fallback"
```

I guess this is related with Docker volume and the file size... but I couldn't found anything about it in the Docker community. In Rasa community I found some content that seems related, like this: https://github.com/RasaHQ/rasa/issues/5134
