### ISSUE TITLE
ML policies with missing models causing ensemble not to load

### ISSUE THREAD

**Issue by pheel** [RasaHQ/rasa#7303]
```yaml
rules:
  - rule: Thank you
    steps:
      - intent: thankyou
      - action: utter_noworries
stories: []
```

```yaml
policies:
  - name: TEDPolicy
  - name: RulePolicy
```

Since no stories are used, training results in log entry **Can not train 'TEDPolicy'. No data was provided. Skipping training of the policy**.

However, trying to load Core model after training is prevented by exception: **Failed to load TED policy model. Path '/var/folders/80/5x0m20sn0bb_r7bg28b6lvt40000gn/T/tmp96oslq6_/core/policy_0_TEDPolicy' doesn't exist**.

Ensemble could be allowed to load, minus any ML policies whose training was skipped.

**Rasa version**: 2.0.x
