### ISSUE TITLE
missing lookup data in NLU after migration from 1.X to 2.0

### ISSUE THREAD

**Issue by kiranbeethoju** [RasaHQ/rasa#7311]
**Rasa version**: 
rasa==1.10.8
rasa-core==0.14.5
rasa-nlu==0.15.1

**Rasa SDK version** (if used & relevant):
rasa-core-sdk==0.14.0
rasa-sdk==1.10.3

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):
Linux Ubuntu 16.04 LTS 
**Issue**:

Lookup data missing after migration !! 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
`language: en
pipeline:
- name: WhitespaceTokenizer
  intent_tokenization_flag: true
  intent_split_symbol: _
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 10
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.25
  ambiguity_threshold: 0.1
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 200
- name: FormPolicy
- name: KerasPolicy
  epochs: 100
- name: RulePolicy
  core_fallback_threshold: 0.25
  core_fallback_action_name: utter_fallback`
```

**Content of domain file (domain.yml)** (if relevant):
```yml
Content of NLU which was missing after migration
`## lookup:deaddcition.txt
  data/deaddcition.txt

## lookup:relation.txt
  data/relation.txt

## lookup:products.txt
  data/products.txt

## lookup:medicine.txt
  data/medicine/medicine.txt

## lookup:locations.txt
  data/locations.txt

## lookup:family.txt
  data/family.txt
`
```
