### ISSUE TITLE
Checking rules validity ignores the conversation_start flag

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7355]
**Rasa version**: 2.1.0

**Python version**: 3.7.9

**Operating system**: Ubuntu

**Issue**:
I have two rules that deal with the same intent but one at the start of a conversation and one at any time in the conversation except at the start. When training, I receive a contradiction error. 

Is the `conversation_start` flag checked when checking rules contradictions? Am I misunderstanding the `conversation_start` flag?

Here is the rule at the start of the conversation: 
```
- rule: Ask a question when starting a conversation
  conversation_start: true
  steps:
    - intent: faq_apartment
    - action: action_greet
    - action: action_faq_apartment
```

And the other rule when the conversation is already ongoing:
```
rules:
- rule: Ask a question within a conversation
  conversation_start: false
  steps:
  - intent: faq_apartment
  - action: action_faq_apartment
```

**Error (including full traceback)**:
```
- the prediction of the action 'action_faq_apartment' in rule 'Ask a question within a conversation' is contradicting with rule(s) 'Ask a question when starting a conversation' which predicted action 'action_greet'.
Please update your stories and rules so that they don't contradict each other.
```

**Command or request that led to error**:
```
rasa train core
```

**Content of configuration file (config.yml)** (if relevant):
```yml
policies:
  - name: RulePolicy
    check_for_contradictions: true
```
