### ISSUE TITLE
Rule applicability depends on slot values when initial_value is used

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#7450]
**Rasa version**: 2.1.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): Mac

**Issue**:
When using `initial_value` for some slot `s` whose value influences the conversation, rules that aren't written as depending on a specific value of `s` are still constructed such that they are conditioned on the exact value used for `initial_value`. Then, these rules can't be applied in situations where `s` has a different value.

Example:
```yml
intents:
- i1

slots:
  s_cat1:
    type: categorical
    values:
      - v1
      - v2
    initial_value: v1

actions:
- action_1

rules:
- rule: rule not conditioned on slot value
  steps:
  - intent: i1
  - action: action_1
  - slot_was_set:
    - s_cat1: v2

policies:
  - name: RulePolicy 
```

where `action_1` simply sets the slot to a different value:
```python
class Action1(Action):
    def name(self) -> Text:
        return "action_1"

    async def run(self, dispatcher, tracker, domain):
        return [SlotSet("s_cat1", "v2")]
```

after training and testing like this:
```bash
rasa train core
rasa test core -s tests/test_story.yml
```

leads to failed predictions in a test story because the rule couldn't be applied where the slot had a value different from the initial one:
```yml
  steps:
  - intent: i1
  - action: action_1
  - slot_was_set:
    - s_cat1: v2
  - intent: i1
  - action: action_1  # predicted: action_default_fallback
  - action: action_listen  # predicted: action_default_fallback
```
