### ISSUE TITLE
Rasa X changes the order of the form slots mapping

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7460]
**Rasa version**: 2.1.1

**Rasa SDK version**: 2.1.1

**Rasa X version**: 0.34.0

**Python version**: 3.7.9

**Operating system**: Ubuntu

**Issue**:
When starting Rasa X, the order of the slot mappings defined for forms in the domain file is automatically changed so that they are sorted alphabetically. Given that the order of the mapping changes the order in which the questions are asked by the bot within a form, this should not happen. 

**Command or request that led to error**:
```
rasa x
```

**Content of domain file (domain.yml)** (if relevant):
Before starting Rasa X
```yml
forms:
  form_preferences:
    preferences_target_price:
    - intent: ...
    has_pet:
    - intent: ...
    ...
```

After starting Rasa X
```yml
forms:
  form_preferences:
    has_pet:
    - intent: ...
    preferences_target_price:
    - intent: ...
    ...
```
