### ISSUE TITLE
Rasa train fails when slot of type `any` contains a dictionary 

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7470]
**Rasa version**: 2.1.3

**Rasa SDK version**: 2.1.2

**Rasa X version**: 0.34.0

**Python version**: 3.7.9

**Operating system**: Ubuntu

**Issue**:
I created stories using interactive learning with Rasa X. Some actions fill a few slots of type `any` with a dictionary. 

In the story steps, I have something like:
```
  - slot_was_set:
    - preferences_move_in_date:
        min: '2020-12-07'
        max: null
```

When training, I get a validation error for this story although the slot is of type `any` (and anyway it does not influence conversations) so I would expect the validation to go through. 

I can manually remove these slots from these interactive learning stories but that is very time-consuming. 

**Error (including full traceback)**:
```
YamlValidationException: Failed to validate 'data/stories/interactive/0001_interactive.yml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
  in data/stories/interactive/0001_interactive.yml:298:
      Cannot find required key 'intent'. Path: '/stories/0/steps/150'
  in data/stories/interactive/0001_interactive.yml:298:
      Key 'slot_was_set' was not defined. Path: '/stories/0/steps/150'
  in data/stories/interactive/0001_interactive.yml:300:
      Value 'ordereddict([('min', '2020-12-07'), ('max', None)])' is not of type 'text'. Path: '/stories/0/steps/150/slot_was_set/0/preferences_move_in_date'
  in data/stories/interactive/0001_interactive.yml:300:
      Value 'ordereddict([('min', '2020-12-07'), ('max', None)])' is not of type 'bool'. Path: '/stories/0/steps/150/slot_was_set/0/preferences_move_in_date'
  in data/stories/interactive/0001_interactive.yml:300:
      Value 'ordereddict([('min', '2020-12-07'), ('max', None)])' is not a list. Value path: '/stories/0/steps/150/slot_was_set/0/preferences_move_in_date'
  in data/stories/interactive/0001_interactive.yml:299:
      Value 'ordereddict([('preferences_move_in_date', ordereddict([('min', '2020-12-07'), ('max', None)]))])' is not of type 'str'. Path: '/stories/0/steps/150/slot_was_set/0'
```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
policies:
  - name: TEDPolicy
    max_history: 7
    epochs: 200
  - name: RulePolicy
    check_for_contradictions: true
    core_fallback_threshold: 0.3
    core_fallback_action_name: action_default_fallback  # customized in action server
    enable_fallback_prediction: true
```

**Content of domain file (domain.yml)** (if relevant):
```yml
slots:
  preferences_move_in_date:
    type: any
    influence_conversation: false
```
