### ISSUE TITLE
Rule contradicts with story although slots infulencing conversations should disambiguate them

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7472]
**Rasa version**: 2.1.3

**Rasa SDK version**: 2.1.2

**Python version**: 3.7.9

**Operating system**: Ubuntu

**Issue**:
I have a rule with a condition that a text slot (which influence conversation) is set. I have a story which has this slot set to `null` very early in the conversation. The validation fails stating that the story and rule contradicts each other but this slot makes them different. 

**rule.yml**
```
version: "2.0"
rules:
- rule: respond to apartment FAQs
  conversation_start: false
  condition:
    - slot_was_set:
      - slug: ABCDE
  steps:
  - intent: faq_apartment
  - action: action_faq_apartment
```

**story.yml**
```
version: "2.0"
stories:
- story: Story from Conversation ID 633c1ae1e2694de1ac4ad254346fd2ce
  steps:
  ...
  - slot_was_set:
    - slug: null
  ... many intents, actions and slot_was_set events, none of which setting slug...
  - intent: faq_apartment
    entities:
    - time: '2021-01-03T00:00:00.000-05:00'
    - number: 1
    - mention: the third one
  - action: action_set_apt_selected
  - slot_was_set:
    - slug: ABCDE
```

**Error (including full traceback)**:
```
InvalidRule: 
Contradicting rules or stories found 🚨

- the prediction of the action 'action_set_apt_selected' in story 'Story from Conversation ID 633c1ae1e2694de1ac4ad254346fd2ce' is contradicting with rule(s) 'respond to apartment FAQs' which predicted action 'action_faq_apartment'.
Please update your stories and rules so that they don't contradict each other.
You can find more information about the usage of rules at https://rasa.com/docs/rasa/rules. 
```

**Command or request that led to error**:
```
rasa train core
```

**Content of configuration file (config.yml)** (if relevant):
```yml
policies:
  - name: TEDPolicy
    max_history: 7
    epochs: 200
  - name: RulePolicy
    check_for_contradictions: true
```

**Content of domain file (domain.yml)** (if relevant):
```yml
slots:
  slug:
    type: text
    influence_conversation: true
```
