### ISSUE TITLE
interactive mode makes repetitions with form and slots

### ISSUE THREAD

**Issue by metal3d** [RasaHQ/rasa#7476]
**Rasa version**: 2.1.4

**Rasa SDK version** (if used & relevant): 2.1.2

**Python version**: 3.8

**Operating system** (windows, osx, ...): Fedora Linux 33

**Issue**:
When starting interactive mode, using forms, there are a lot of repeted `slot_was_set` in the stories.

**Error (including full traceback)**:
```yaml
- story: interactive_story_1
  steps:
  - intent: greet
  - action: utter_greet
  - intent: want_receipe
    entities:
    - food_type: plat
  - slot_was_set:
    - food_type: plat
  - action: food_form
  - active_loop: food_form
  - slot_was_set:
    - food_type: plat
  - slot_was_set:
    - food_type: plat
  - slot_was_set:
    - requested_slot: ingredients
  - slot_was_set:
    - ingredients:
      - oignons
      - carottes
      - patates
  - slot_was_set:
    - ingredients:
      - oignons
      - carottes
      - patates
  - slot_was_set:
    - requested_slot: null
  - active_loop: null
  - action: utter_give_receipe
```
Look at the last ones to see what I mean.

In this one, you can see `food_type` that is repeated, and 2 shape of "ingredients" near the end of the story:
```yaml
- story: interactive_story_1
  steps:
  - intent: greet
  - action: utter_greet
  - intent: want_receipe
    entities:
    - food_type: gratin
  - slot_was_set:
    - food_type: gratin
  - action: food_form
  - active_loop: food_form
  - slot_was_set:
    - food_type: gratin
  - slot_was_set:
    - food_type: gratin
  - slot_was_set:
    - requested_slot: ingredients
  - slot_was_set:
    - ingredients:
      - pommes de terre
  - slot_was_set:
    - ingredients: pommes de terre
  - slot_was_set:
    - requested_slot: null
  - active_loop: null
  - action: utter_give_receipe
```

I don't know if that breaks something, but the bot is not answering correctly at this time.

**Command or request that led to error**:
```
rasa interactive
```
