### ISSUE TITLE
Double entity extraction

### ISSUE THREAD

**Issue by desmarchris** [RasaHQ/rasa#7490]
**Rasa version**: 2.1.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.8.6

**Operating system** (windows, osx, ...): ubuntu

**Issue**: After adding `RegexEntityExtractor` to my pipeline and using a regex to collect email, a detected email is returned twice (once from DIET, once from regex?). In this case, I think the DIET entity detection should be ignored if it's matching a return from regex, or if a regex is returned at all.

**Error (including full traceback)**:
```
I can help you find the status of your order. What's your email address so I can find the order?
Your input ->  it's example@gmail.com
Based on the latest order from ['example@gmail.com', 'example@gmail.com'], it looks like your order should arrive in a few days.
```

Response: 
```
utter_order_status:
  - text: Based on the latest order from {email}, it looks like your order should arrive in a few days.
```

Rules: 
```
- rule: Activate email form for order status
  steps:
  - intent: order_status
  - action: order_status_form
  - active_loop: order_status_form
- rule: Submit order status form
  condition:
  - active_loop: order_status_form
  steps:
  - action: order_status_form
  - active_loop: null
  - slot_was_set:
    - email
  - action: utter_order_status
```

**Content of configuration file (config.yml)** (if relevant):
```yml
pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: RegexEntityExtractor
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
