### ISSUE TITLE
Inconsistent prediction of next action 

### ISSUE THREAD

**Issue by humcasma** [RasaHQ/rasa#7514]
**Rasa version**: 2.1.3

**Rasa SDK version** (if used & relevant): 2.1.2

**Rasa X version** (if used & relevant): None

**Python version**:3.6.9

**Operating system** (windows, osx, ...): Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic

**Issue**:
I have created a form to fill in two slots (one of the slots is extracted with help of a custom FormValidationAction). Once the form action is over, a custom action should be executed to show some items. To achieve this behavior I have created the following rule:
```
version: "2.0"
rules:
- rule: Activate form to show items with given characteristics
  steps:
  - intent: show_me_X.     
  - action: show_X_form  
  - slot_was_set:       
    - gender
    - item_type
  - active_loop: show_X_form
  - active_loop: null
  - action: action_show_items   # Custom action
  - action: action_deactivate_loop
```
Training fails if no stories are found, so I also created a greetings intent and corresponding story:
```
  - story: respond to chitchat
     steps:
    - intent: greetings.hello
    - action: utter_greetings.hello
```
Using the following _config.yml_ file, the bot trains without any issue:
```
version: "2.0"

language: es

policies:
   - name: MemoizationPolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
   - name: RulePolicy

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: ResponseSelector
    epochs: 100  
```

When testing the bot, the form action is correctly executed, but once the form is deactivated, the _action_show_items_ custom action is not executed. In the logs I can read: 
```
There is no memorised next action. 
There is no applicable rule.
Predicted next action using policy_0_TEDPolicy.
Predicted next action 'action_listen' with confidence 0.95.
```
Why Rasa says that there is no applicable rule and checks the TED policy?

Trying to solve the issue, and being in experimentation mood, I deleted the greeting story and created another story 100% similar to the original rule (i.e., I defined the exact same behavior with a story and a rule). Still no luck. This time _action_default_fallback_ was predicted with _policy_2_RulePolicy_.
I then added the greetings handshake as a rule (i.e., stories.yml contains now 1 story describing the form behavior and rules.yml contains a rule describing the same behvior, plus another rule describing the response to a greetings.hello intent) and still no luck. I then modified the story and rule describing the form behavior to utter a message upon form completion, instead of the _action_show_items_ custom action. This time a message was printed upon form completion (from the logs: _Predicted next action using policy_1_TEDPolicy. Predicted next action 'utter_test' with confidence 0.79._)

Why does it work with a simple utterance and not with a custom action? Why is the executed action the one chosen by the TED policy and why the Memoisation and Rule policies are not able to "predict" the next action?
