### ISSUE TITLE
Rasa always falling back

### ISSUE THREAD

**Issue by LEAGUEDORA** [RasaHQ/rasa#7531]
**Rasa version**: 2.1.3

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): WIN 10

**Issue**:
I didn't why my rasa bot always fall back. Intent classification is good but the replying ones is not correct

**Error (including full traceback)**:
```
This is what I am getting
![Screenshot (19)](https://user-images.githubusercontent.com/61022690/101970110-7e5be780-3c4e-11eb-8ecd-b43b3d8799a5.png)

This was earlier screenshot when it is working fine
![Screenshot (20)](https://user-images.githubusercontent.com/61022690/101970112-8025ab00-3c4e-11eb-9ef5-f3c94ee725db.png)

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1



# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
  - name: RulePolicy

```

**Content of domain file (domain.yml)** (if relevant):
```yml

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
intents:
- greet
- what_is_supported
- eligibility_criteria
- goodbye
- bot_challenge
- how_to_apply_supported
- fetch_can
entities:
- supported
- can_number
- email
- mobile
- name
slots:
  can_number:
    type: text
    influence_conversation: false
  email:
    type: text
    influence_conversation: false
  mobile:
    type: text
    influence_conversation: false
  name:
    type: text
    influence_conversation: false
  supported:
    type: text
    influence_conversation: false
responses:
  utter_greet:
  - text: Hey! How are you?
  utter_ask_can_number:
  - text: Enter can bro
  utter_default:
  - text: Falled back
actions:
- action_what_is_supported
- action_eligibility
- action_ask_can_number
- action_ask_name
- action_ask_mobile
- action_ask_email
- action_apply_supported
- action_fetch_can
- form_fetch_can
forms:
  form_fetch_can:
    can_number:
    - type: from_text
    email:
    - type: from_text
    mobile:
    - type: from_text
    name:
    - type: from_text


```

```stories

version: "2.0"

stories:

- story: stories for what is supported
  steps:
  - intent: what_is_supported
  - action: action_what_is_supported

- story: story for eligibility criteria
  steps:
  - intent: eligibility_criteria
  - action: action_eligibility

- story: story for applying
  steps:
  - intent: how_to_apply_supported
  - action: action_apply_supported


  
- story: fetching can
  steps:
  - intent: fetch_can
  - action: utter_ask_can_number
  - action: form_fetch_can
  - active_loop: form_fetch_can
```

debug message:
Your input ->  what is income certificate
2020-12-12 09:21:56 DEBUG    rasa.core.lock_store  - Issuing ticket for conversation 'fd95b907d632406e860e44b1d917e1dd'.
2020-12-12 09:21:56 DEBUG    rasa.core.lock_store  - Acquiring lock for conversation 'fd95b907d632406e860e44b1d917e1dd'.
2020-12-12 09:21:56 DEBUG    rasa.core.lock_store  - Acquired lock for conversation 'fd95b907d632406e860e44b1d917e1dd'.
2020-12-12 09:21:56 DEBUG    rasa.core.tracker_store  - Could not find tracker for conversation ID 'fd95b907d632406e860e44b1d917e1dd'.
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Starting a new session for conversation ID 'fd95b907d632406e860e44b1d917e1dd'.
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Policy prediction ended with events '[]'.
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Action 'action_session_start' ended with events '[<rasa.shared.core.events.SessionStarted object at 0x000001B49DBF6DC8>, <rasa.shared.core.events.ActionExecuted object at 0x000001B359AEB608>]'.
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Current slot values:
        can_number: None
        email: None
        mobile: None
        name: None
        supported: None
        requested_slot: None
2020-12-12 09:21:56 DEBUG    rasa.nlu.classifiers.diet_classifier  - There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-12-12 09:21:56 DEBUG    rasa.nlu.selectors.response_selector  - Adding following selector key to message property: default
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Received user message 'what is income certificate' with intent '{'id': -7096267651852178878, 'name': 'what_is_supported', 'confidence': 0.9999905824661255}' and entities '[{'entity': 'supported', 'start': 8, 'end': 14, 'confidence_entity': 0.9511626958847046, 'value': 'income', 'extractor': 'DIETClassifier'}]'
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Current slot values:
        can_number: None
        email: None
        mobile: None
        name: None
        supported: income
        requested_slot: None
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 5 events.
2020-12-12 09:21:56 DEBUG    rasa.core.policies.memoization  - Current tracker state:
[state 1] user intent: what_is_supported | user entities: ('supported',) | previous action name: action_listen
2020-12-12 09:21:56 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-12-12 09:21:56 DEBUG    rasa.core.policies.rule_policy  - Current tracker state:
[state 1] user intent: what_is_supported | user entities: ('supported',) | previous action name: action_listen
2020-12-12 09:21:56 DEBUG    rasa.core.policies.rule_policy  - There is no applicable rule.
2020-12-12 09:21:56 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_1_RulePolicy.
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Predicted next action 'action_default_fallback' with confidence 0.30.
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Policy prediction ended with events '[]'.
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Action 'action_default_fallback' ended with events '[BotUttered('Falled back', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {"template_name": "utter_default"}, 1607745116.4180608), <rasa.shared.core.events.UserUtteranceReverted object at 0x000001B345C6EB48>]'.
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Current slot values:
        can_number: None
        email: None
        mobile: None
        name: None
        supported: None
        requested_slot: None
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 1.00.
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Policy prediction ended with events '[]'.
2020-12-12 09:21:56 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'.
2020-12-12 09:21:56 DEBUG    rasa.core.lock_store  - Deleted lock for conversation 'fd95b907d632406e860e44b1d917e1dd'.

Please help me asap I'm in a hurry

**Comment by vanshkapil** [comment]
You should either add more stories or in Rasa V2 you can add it as a rule.

**Comment by sara-tagger** [comment]
Thanks for the issue, @melindaloubser1 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
Hi @LEAGUEDORA I don't think this is a bug, I'd recommend posting your question on the [forum](https://forum.rasa.com/) with the screenshots that aren't displaying here.

**Comment by nbeuchat** [comment]
Hey @LEAGUEDORA, I'm not 100% sure about the details of the `MemoizationPolicy` but I think that the story you have in your training data does not exactly match the story you have in Rasa X because of the entity `supported`

If you look at the log:

2020-12-12 09:21:56 DEBUG rasa.core.policies.memoization - Current tracker state:
[state 1] user intent: what_is_supported | **user entities: ('supported',)** | previous action name: action_listen
2020-12-12 09:21:56 DEBUG rasa.core.policies.memoization - There is no memorised next action

You can see that the `supported` entity is in the tracker state. 

So, you have a few options:

- Use the `TED Policy`, it should be able to handle that
- Add a story like this for the Memoization Policy to work: 
```
- story: stories for what is supported
  steps:
  - intent: what_is_supported
    entities: 
    - supported: xyz
  - action: action_what_is_supported
```
- Set `use_entities` to `[]` in your domain file for the `what_is_supported` intent (you may or may not want that depending if the behavior should be different if the entity is not there): 
```
intents:
- ...
- what_is_supported:
  use_entities: []
```
- Use rules

I would recommend using the TED Policy because the Memoization Policy and Rule Policy won't generalize.
