### ISSUE TITLE
Provide an option to ignore rules with conversation_start: true when checking conflicting stories

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7552]
**Description of Problem**:
When training Rasa Core, we can check rules and stories for conflicts. In addition, the recommended way of writing stories is writing short conversational blocks.

> consider separating your longer stories into smaller conversational blocks that handle sub-tasks.

For our bot, responding to any intent at the start of a conversation is always slightly different than responding during an on-going conversation as we want to greet the user and send some information on how the bot works (let's call it `action_greet`). We can define these easily using rules with the `conversation_start` flag. 

**Example**:
We should have a way of allowing the story/rule checker to allow for such contradictions if the `conversation_start` flag is present for that rule. 
```
- rule: Has question at the start of conversation
  conversation_start: true
  steps:
    - intent: has_question
    - action: action_greet
    - action: utter_what_want_to_know
```

```
- story: Has question conversation block
  steps:
    - intent: has_question
    - action: utter_what_want_to_know
```

**Overview of the Solution**:
My proposal would be to add a flag in the `RulePolicy` configuration  

Something:
```
policies:
  - name: RulePolicy
    check_for_contradictions: true
    allow_for_conversation_start_contradictions: true
```

The only contradictions that should then be checked for rules with `conversation_start: true` would be between rules with `conversation_start: true`. 

Any thoughts?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rgstephens will get back to you about it soon! ✨

**Comment by Ghostvv** [comment]
> In addition, the recommended way of writing stories is writing short conversational blocks.

it was a recommended way before the rules were introduced. I wouldn't recommend that anymore. If you can provide a short story block, why not use a rule?

**Comment by Ghostvv** [comment]
the problem is that recently we found out that `TEDPolicy` actually get quite confused with stories without conversation histories, so I don't think it is a good approach to remove this contradiction check, because it does what it is intended to do - write the stories that resemble the stories during prediction

**Comment by Ghostvv** [comment]
I don't see how this is different from removing all the checks

**Comment by nbeuchat** [comment]
> it was a recommended way before the rules were introduced. I wouldn't recommend that anymore. If you can provide a short story block, why not use a rule?

For the small story shown above, the `has_question` should _in general_ triggers the action `utter_what_want_to_know` but not in every instance so I cannot use a rule. 

> the problem is that recently we found out that TEDPolicy actually get quite confused with stories without conversation histories, so I don't think it is a good approach to remove this contradiction check, because it does what it is intended to do - write the stories that resemble the stories during prediction

Interesting, I was aware of that! I haven't used enough the `TEDPolicy` yet to judge but from my early tests, I found that it worked quite okay.

> I don't see how this is different from removing all the checks

The difference is that the rules with `conversation_start: true` have a very short "life span" and hence I may be fine to ignore a contradiction between something in the middle of a conversation and something at the onset. 

Another use-case I could see is to change how a conversation starts in response to a greeting without having to update all the training data, especially if that update is short-lived (to change the flow for a Christmas promotion for example).

Overall, my feeling is that we want to have very tight control over how a conversation starts, and rules are fantastic for that but they make writing stories (manually) very tedious as we need to repeat over and over again the same conversation start. Our workaround now is to run the training with the checks on, ignore the conflicts with rules that have the `conversation_start: true`, and retrain without the check. Maybe a better way would be to allow some rules not to be checked? That would be more explicit I suppose.

**Comment by Ghostvv** [comment]
> For the small story shown above, the has_question should in general triggers the action utter_what_want_to_know but not in every instance so I cannot use a rule.

but your story actually says otherwise, you rely ML policy to figure this `in general but not always` on its own, which is not very scalable way, because the successful "learning" depends on many factors including random initial conditions

> they make writing stories (manually) very tedious
> I found that it worked quite okay.

in our experience with developing Sara, writing correct stories is crucial in long run because this little inconsistencies pile up, and at some point you might have a broken bot.
I suggest to rethink your stories. We added this check specifically, it is meant to point out which stories/rules need to be updated

**Comment by Ghostvv** [comment]
> they make writing stories (manually) very tedious

do you already have real stories? I'd recommend manually fixing conversations that your users had with your bot and adding them to your stories, instead of writing them manually

**Comment by nbeuchat** [comment]
I did a few more experiments and you're right, these short story blocks tend to confuse the bot. I like having them as it gives a good understanding of how the bot should behave by simply looking at the manually crafted stories. 

> do you already have real stories? I'd recommend manually fixing conversations that your users had with your bot and adding them to your stories, instead of writing them manually
Yes, I do :-) As mentioned just above, I liked having both for clarity (and I thought for generalization too) but I see it can hurt performance.

**Comment by Ghostvv** [comment]
>  I like having them as it gives a good understanding of how the bot should behave by simply looking at the manually crafted stories.

this is the intention of rules, I'd recommend figuring out the conditions (e.g. in terms of slots) when this short snippets should happen and add them to the rules

**Comment by nbeuchat** [comment]
> this is the intention of rules, I'd recommend figuring out the conditions (e.g. in terms of slots) when this short snippets should happen and add them to the rules

That makes sense (although I feel it's removing a bit of flexibility). 

However, I still have issues with the `conversation_start: true` check even across rules:

*Rule 1: start*
```
- rule: Search at the start of conversation
  conversation_start: true
  steps:
    - intent: ask_search
    - action: action_greet
    - action: action_introduce_form_preferences
  wait_for_user_input: false
```

*Rule 2: anywhere else*
```
- rule: Activate preferences form when searching
  condition:
  - slot_was_set:
    - preferences_filled: null
  steps:
  - intent: ask_search
  - action: action_introduce_form_preferences
  wait_for_user_input: false
```
I also tried to optimistically add `conversation_start: false` but that doesn't help. 

I see that they are conflicting at the start of the conversation but I'd like the first rule to take precedence as it's more "specific" given that it has the `converation_start: true` flag. 

What do you think?
