### ISSUE TITLE
Rules example bot broken

### ISSUE THREAD

**Issue by ripperdoc** [RasaHQ/rasa#7559]
**Rasa version**: master

**Issue**:

When I download and attempt to train the bot in [https://github.com/RasaHQ/rasa/tree/master/examples/rules](https://github.com/RasaHQ/rasa/tree/master/examples/rules) it looks faulty/incomplete to me. Most of the intents used in the `rules.yml` are not present in the `nlu.yml`. Is the correct nlu file somewhere else?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @m-vdb will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
Thanks a lot @ripperdoc for raising this issue. From a first look at the file, it seems that you're right and we're missing NLU examples for at least the following intents `activate_q_form`, `ask_possibilities`, `explain`, `faq`. I'll notify the team in charge.

In the mean time, you can add NLU examples for all of those intent in the `nlu.yml` file. For instance:
```yaml
...
- intent: activate_q_form
  examples: |
  - I'd like to do an activity
  - I'd like to do something
  
- intent: explain
  examples: |
  - I don't understand
  - I'm not sure
  - Can you explain?
  
- intent: ask_possibilities
  examples: |
  - What are the possibilities?
  - What is possible?
```
I realise it's not ideal, I'm sure we can make these examples more user-friendly. I hope that helps, LMK
