### ISSUE TITLE
button_type not working with 2.0 yaml response schema validation

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#7605]
**Issue**:

The Telegram channel `button_type` option is not working with Rasa 2.x because the new [schema validation](https://github.com/RasaHQ/rasa/blob/6dcf34ea185d6feca5b09a49dccaafc568705add/rasa/shared/nlu/training_data/schemas/responses.yml#L22) for responses is missing the definition.

**Rasa version**: 2.2.0

**Error (including full traceback)**:
```
YamlValidationException: Failed to validate '/Users/greg/Dev/rasa/testbot/domain.yml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
  in /Users/greg/Dev/rasa/testbot/domain.yml:135:
      Key 'button_type' was not defined. Path: '/responses/utter_buttons_vertical/1'
```

**Command or request that led to error**:
```
rasa train
```

**Content of domain file (domain.yml)** (if relevant):
```yml
  utter_buttons_vertical:
  - buttons:
    - payload: /buttons_default
      title: Default
    - payload: /buttons_inline
      title: Inline
    - payload: /buttons_reply
      title: Reply
    text: These are vertical buttons?
  - channel: telegram
    text: These are vertical telegram buttons?
    button_type: vertical
    buttons:
    - payload: /buttons_default
      title: Default
    - payload: /buttons_inline
      title: Inline
    - payload: /buttons_reply
      title: Reply
```
