### ISSUE TITLE
tokenization failed in rasa 2.0

### ISSUE THREAD

**Issue by XiaoLiuAI** [RasaHQ/rasa#7623]
**Rasa version**:
2.2.6

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
3.7

**Operating system** (windows, osx, ...):
osx, ubuntu

**Issue**:
Currently, rasa hf_transformer implementation use whitespace tokenizer to make tokenization then use transformers tokenizer to make subtokens. This will lead to the failure of languages like Chinese, which does not have whitespace. For intent classification, it does not matter. However, for NER, entities are based on tokens, which are split by whitespace, instead of subtokens. It means none of entities will be extracted since nearly all the entities are not aligned. 

I think it is a quite serious fundamental algorithm design problem. 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: zh
pipeline:
  - name: HFTransformersNLP
    # Name of the language model to use
    model_name: "bert"
    # Pre-Trained weights to be loaded
    # model_weights: "hfl/chinese-roberta-wwm-ext"
    model_weights: "bert-base-chinese"

    # An optional path to a specific directory to download and cache the pre-trained model weights.
    # The `default` cache_dir is the same as https://huggingface.co/transformers/serialization.html#cache-directory .
    cache_dir: null
  - name: LanguageModelTokenizer
    intent_tokenization_flag: true
    intent_split_symboll: "-"
  - name: LanguageModelFeaturizer

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
