### ISSUE TITLE
Prefillings slots doesn't work correctly in forms with multiple from_entity types and form validation

### ISSUE THREAD

**Issue by Dobatymo** [RasaHQ/rasa#7628]
**Rasa version**: 2.2.2
**Rasa SDK version** (if used & relevant): 2.2.0
**Rasa X version** (if used & relevant): None
**Python version**: 3.7.4
**Operating system** (windows, osx, ...): Windows-10-10.0.18362-SP0

**Issue**:

When a form is activated, it tries to prefill the slots using existing information. However if there are multiple `from_entity` types in the domain file (see below), bad entities can overwrite good ones. It tries to validate both entities using the validation action on the actions server, but it doesn't stop when it finds a good one.
For example if `another_entity=bad` and `the_entity=good` it will receive something like `[SlotSet(key: the_entity, value: good)', 'SlotSet(key: the_entity, value: None)']` from the validation action. Which leads to setting the slot to None and asking the user again.

I think that situation also occurs during normal form operation and not only during prefilling, but I have not tested this situation as much.

**Content of domain file (domain.yml)** (if relevant):
```yml
forms:
  the_form:
    the_entity:
    - type: from_entity
      entity: another_entity
    - type: from_entity
      entity: the_entity
```

The result is 100% identical if I use this domain file:
```yml
forms:
  the_form:
    the_entity:
    - type: from_entity
      entity: another_entity
```
It's calling the action two times, where the first is correctly verified from `the_entity` and the second one uses the value from `another_entity` which overwrites the previously correct value.
