### ISSUE TITLE
Action server failure handling

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#7630]
**Description of Problem**:
Would like a way for the bot to handle action server failures. Could be the action server isn’t running or the response is exceeding a timeout period. Could there be an action fallback policy or custom policy around this so that rules/stories could take this into account. 

**Overview of the Solution**:
Possibly define an action_fallback_intent and threshold. If there is a failure calling the action server, the configured intent would be predicted.

```yml
policies:
- name: RulePolicy
  action_fallback_intent: "action_failure_intent"
  action_fallback_threshold_secs: 1.5
```
