### ISSUE TITLE
During rasa test, YamlValidationException shows temp path

### ISSUE THREAD

**Issue by shubhvachher** [RasaHQ/rasa#7640]
**Rasa version**: 2.0.0

**Rasa SDK version** (if used & relevant): Not Used

**Rasa X version** (if used & relevant): Not Used

**Python version**: 3.6.8 (anaconda)

**Operating system** (windows, osx, ...): windows

**Issue**:

During `rasa test` if there is a `YamlValidationException` then the path for the file shown points to the temp directory. 

**Error (including full traceback)**:
```
YamlValidationException: Failed to validate 'C:\Users\USER\AppData\Local\Temp\tmpjvcoar7v\3c3f65c658cd4a41b3fb1703892fa328_test_happypaths_basic.yml'. Please make sure 
the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
...
```

**Command or request that led to error**:
```
rasa test
```

You could test using this `retrieval intent` example from my `test_happypaths_basic.yml`:
```
stories:
- story: faq/restaurant_available_testing
  steps:
  - user: "Does the hotel have a restaurant?"
  - intent: faq/restaurant_available
  - action: utter_faq/restaurant_available
```

**Definition of Done**
- [ ] evalute if copying to `/temp` is needed and drop it if not
- [ ] correctly report path to actual test file
