### ISSUE TITLE
Rasa 2.2.2 core model predictions off

### ISSUE THREAD

**Issue by iszainab** [RasaHQ/rasa#7658]
**Rasa version**: 2.2.2

**Rasa SDK version** (if used & relevant): 2.2.0

**Rasa X version** (if used & relevant): None

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:
1. Rasa core model predictions seem off. Everything was fine with RASA 1.10 however I migrated to RASA 2.2.2 following the docs and everything and I made sure not to change any hyper parameters when switching from depreciated policies. I tried debugging and my stories seem to match the tracker states and yet the predicted action is off.

2. Why does it seem like the nlu components are being processed during the core model's evaluation? Is this expected behavior? I can see in the docs that it says that the state featurizer uses the nlu pipeline to featurize states but it doesn't seem right that my custom components that have nothing to do with featurization are being processed. Can there be a better solution for this please?

NOTE: For all practical aspects, my training parameters have not changed at all.

**Content of old configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: "mycustomcomponent1.CustomComponent1"
  - name: "mycustomcomponent2.CustomComponent2"
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "CRFEntityExtractor"
    BILOU_flag: True
  - name: "EntitySynonymMapper"
  - name: "DIETClassifier"
    intent_classification: True
    entity_recognition: False
    use_masked_language_model: False
    batch_strategy: 'sequence'
    epochs: 300
  - name: "ResponseSelector"
    retrieval_intent: chitchat
    epochs: 100

policies:
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.3
    ambiguity_threshold: 0.1
    core_threshold: 0.05
    fallback_action_name: 'entity_driven_fallback'
  - name: MappingPolicy
  - name: AugmentedMemoizationPolicy
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 11
        state_featurizer:
          - name: BinarySingleStateFeaturizer
  - name: TEDPolicy
    batch_strategy: 'sequence'
    epochs: 300
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 5
        state_featurizer:
          - name: BinarySingleStateFeaturizer

```

**Content of new config file (domain.yml)** (if relevant):
```yml
language: en
pipeline:
  - name: xxx.CustomComponent1
  - name: yyy.CustomComponent2
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    intent_classification: true
    entity_recognition: true
    use_masked_language_model: false
    batch_strategy: sequence
    epochs: 300
    BILOU_flag: true
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
policies:
  - name: AugmentedMemoizationPolicy
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 11
        state_featurizer:
          - name: SingleStateFeaturizer
  - name: TEDPolicy
    batch_strategy: sequence
    epochs: 300
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 5
        state_featurizer:
          - name: SingleStateFeaturizer
  - name: RulePolicy
    core_fallback_threshold: 0.05
    core_fallback_action_name: entity_driven_fallback

```
