### ISSUE TITLE
Python: ImportError: cannot import name 'Interpreter' from 'rasa.nlu'

### ISSUE THREAD

**Issue by stefanvantchev** [RasaHQ/rasa#7681]
**Rasa version**:
2.0.6

**Rasa SDK version** (if used & relevant):
2.0

**Rasa X version** (if used & relevant):
N/A

**Python version**:
3.8

**Operating system** (windows, osx, ...):
Debian 

**Issue**:
Basic python file simply cannot be run on a brand new Rasa installation on a brand new server... 

YET... 

calling RASA RUN works

Here is the python code:
------------------------------------
from rasa.nlu import Interpreter

def load_model():
	interpreter = Interpreter.load('models')
	print(interpreter.parse("Hello"))
	
if __name__ == '__main__':
	load_model()

------------------------------------

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "u.py", line 3, in <module>
    from rasa.nlu import Interpreter
ImportError: cannot import name 'Interpreter' from 'rasa.nlu' (/home/stefan_vantchev/venv/lib/python3.7/site-packages/rasa/nlu/__init__.py)
```

**Command or request that led to error**:
```
python3 u.py
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
  - name: HFTransformersNLP
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer    
    model_name: "bert"
    model_weights: "rasa/LaBSE"
  - name: DIETClassifier
    epochs: 50
```

**Content of domain file (domain.yml)** (if relevant):
```yml
N/A
```
