### ISSUE TITLE
UnsupportedLanguageError: component 'LanguageModelTokenizer' does not support language 'zh'.

### ISSUE THREAD

**Issue by Slyne** [RasaHQ/rasa#7689]
**Rasa version**: 2.2.2

**Rasa SDK version** (if used & relevant):
no
**Rasa X version** (if used & relevant):
no
**Python version**:
3.6.8
**Operating system** (windows, osx, ...):
ubuntu
**Issue**:
I'm trying to use the transformer based featurizer on Chinese.
It's ok to use jiebaTokenizer. However I think the pretrained language model uses a character based tokenizer so I want to use the language model specific tokenizer. But I encounter this error: 
UnsupportedLanguageError: component 'LanguageModelTokenizer' does not support language 'zh'.

**Error (including full traceback)**:
```
UnsupportedLanguageError: component 'LanguageModelTokenizer' does not support language 'zh'.
```
When using JiebaTokenizer, there are a lot of warnings like :
```
"Make sure the start and end values of entities ([(5, 7, '三十'), (10, 12, '流量')]) in the training data match the token boundaries ([(0, 1, '给'), (1, 2, '我'), (2, 3, '办'), (3, 7, '一个三十'), (7, 8, '的'), (8, 10, '新流'), (10, 12, '流量'), (12, 13, '务')])"
```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: zh

pipeline:
  - name: RegexEntityExtractor
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
    model_name: bert
    model_weights: bert-base-chinese
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
```

Is there a character tokenizer ?
