### ISSUE TITLE
Make it possible to `OR` slot values 

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#7715]
**Description of Problem**:
Currently only one slot **value** can be given  per `slot_was_set` step or condition. It would be useful to be able to "OR" slot values, i.e. list multiple options that all qualify for that step, especially with many-valued categorical slots. 

Currently the only way around is either to create "meta slots" which reflect a certain grouping of slot values, or to create individual stories for each slot value, even when the steps in each one are identical otherwise. This can lead to an explosion in the number of stories with a many-valued categorical slot.

(Bigger scope: it would also be useful to be able to OR slot  **names** e.g. either the `first_name` or the `logged_in` slot have a value, although I have seen less clear examples where this would be the best way to solve a problem. )

**Overview of the Solution**:
Allow listing multiple allowable values per slot in a story or rule `slot_was_set` step (see examples). If in a conversation the slot is set to any one of those values, the dialogue state should be considered to match the story/rule at that point.

**Examples** (if relevant):

For example, given this slot:
```
slots:
  account_type:
    type: categorical
    values:
       - free
       - standard
       - gold
       - premium
```

There could be cases where you want to group the values into `free`, and `standard, gold, premium`, 
 and other cases where each individual value gets its own variant on a story, or the values are grouped differently:

```
stories:
   story: greet a customer on a free plan
   steps: 
      - intent: greet
      - slot_was_set:
         - account_type: free
      - action: utter_greet_free_customer

   story: greet a customer on any paid plan
   steps: 
      - intent: greet
      - slot_was_set:
         - account_type: 
               - standard
               - gold
               - premium
      - action: utter_greet_paying_customer

   story: list options standard and free
   steps: 
      - intent: what_can_do
      - slot_was_set:
         - account_type: 
               - standard 
               - free
      - action: utter_standard_options

   story: list options gold and premium
   steps: 
      - intent: what_can_do
      - slot_was_set:
         - account_type: 
               - gold 
               - premium
      - action: utter_advanced_options
  ````

**Blockers** (if relevant):
None known 

**Definition of Done**:

- [x] determine if this is the best way to address the problem.
- [x] verify solution with Research and CSE.
- [ ] Open implementation issue with solution detailed.
