### ISSUE TITLE
RasaYAMLWriter renders multiline NLU examples incorrectly

### ISSUE THREAD

**Issue by chdorner** [RasaHQ/rasa#7753]
**Rasa version**: 2.2.5 (`master` at 5549b07d70a39819bf793017de3badd7ea903bc6)

**Rasa SDK version** (if used & relevant): –

**Rasa X version** (if used & relevant): –

**Python version**: 3.8.6

**Operating system** (windows, osx, ...): Mac OS 11

**Issue**: 
YAML output of `RasaYAMLWriter` for multiline examples is not identical to the original YAML input.

**Error (including full traceback)**:
–

**Command or request that led to error**:
```python
from rasa.shared.nlu.training_data.formats.rasa_yaml import RasaYAMLReader, RasaYAMLWriter
yaml_string = f"""version: "2.0"
nlu:
- intent: greet
  examples:
  - text: |
      Hello,
      My name is Christof
  - text: |
      Hello,
      You can call me Christof
"""
training_data = RasaYAMLReader().reads(yaml_string)
print(RasaYAMLWriter().dumps(training_data))
```

Outputs:
```yaml
version: "2.0"
nlu:
- intent: greet
  examples: |
    - Hello,\nMy name is Christof
    - Hello,\nYou can call me Christof
```

**Content of configuration file (config.yml)** (if relevant):
–

**Content of domain file (domain.yml)** (if relevant):
–
