### ISSUE TITLE
Unable to update config.yml in Rasa X

### ISSUE THREAD

**Issue by kearnsw** [RasaHQ/rasa#7832]
**Rasa version**:
2.2.7-full

**Rasa SDK version** (if used & relevant):
2.2.0

**Rasa X version** (if used & relevant):
0.35.0

**Python version**:
3.8

**Operating system** (windows, osx, ...):
Amazon Linux

**Issue**:
I am not able to update the configuration file. Each time I attempt to do so, I receive a 422 error. In addition, syncing with Github also does not appear to modify the config file. This error still occurs after disconnecting from Github. It is present on this version and also the 0.33.0 version used before. 

**Error (including full traceback)**:
```
[2021-01-28 04:20:44 +0000] - (sanic.access)[INFO][192.168.41.156:56032]: PUT http://<redacted>.us-east-1.elb.amazonaws.com/api/projects/default/settings  422 237
DEBUG:rasax.community.services.model_service:Model discovery completed.
```

**Command or request that led to error**:
Manually updating the configuration file by adding the following line:
```
- name: aws.ComprehendMedical
```

Also occurs by just removing anything or any other changes. 

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: aws.ComprehendMedical
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
policies: null
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @samsucik will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
Thanks for reporting @kearnsw. What do you see in the Rasa X logs when you try to change the config file?

**Comment by kearnsw** [comment]
@melindaloubser1, I believe the error traceback I posted above is the log from the RasaX pod. It just shows the error code of 422, preceded and followed by 200 messages pinging for new models.

**Comment by melindaloubser1** [comment]
Looking at  the API spec, 422 indicates [missing mandatory keys](https://rasa.com/docs/rasa-x/pages/http-api#operation/saveModelConfig), but your config is valid - as long as there is a module `aws` installed and `ComprehendMedical` is available at that module path. 

Can you use the API directly to fetch your config? 
If so, what is the config that it returns? 
Can you use the API directly to change your config?

**Comment by kearnsw** [comment]
When I call the `/api/projects/default/settings` endpoint, I get the pre-change configuration file that is nearly equivalent to that above. 

```yaml
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: components.aws.ComprehendMedical
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
policies:
```

Looks like the issue is that the policies are not set, so you cannot use the default pipeline if you modify the configuration through RasaX directly. 

```json
{
    "version": "0.35.1",
    "status": "failure",
    "message": "Error: The config file is missing mandatory parameters: 'policies'. Add missing parameters to config file and try again.",
    "reason": "ConfigMissingKeys",
    "details": {},
    "help": null,
    "code": 422
}
```
