### ISSUE TITLE
Mislabeling of "sentence features" as "dense features" in documentation

### ISSUE THREAD

**Issue by alexyuwen** [RasaHQ/rasa#7845]
You can see in the `_get_sentence_features` method in the `rasa/nlu/classifiers/sklearn_intent_classifier.py` file that the error message reads "No sentence features present. Not able to train sklearn policy."  This is misleading because sentence features are referred to as "dense features" in the documentation.

I have attached a zip folder containing test component code as well as my `config.yml` file. I used the test component code to test that the features were not present from the spacy_featurizer.  When outputting the features I found that they were empty, as you can see in these screenshots:
<img width="1345" alt="features" src="https://user-images.githubusercontent.com/68449128/106346519-020c7a80-6275-11eb-8fc4-8a62ebcd20a0.png">
<img width="1345" alt="features2" src="https://user-images.githubusercontent.com/68449128/106346520-03d63e00-6275-11eb-9fa5-e7baab200019.png">

[code.zip](https://github.com/RasaHQ/rasa/files/5897330/code.zip)

@kearnsw

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alopez will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
@koaning Are you working on this? If not, can you remove your assignment?

**Comment by dakshvar22** [comment]
@alexyuwen I wasn't able to reproduce this on the latest rasa version `2.5.1` and also on `main`. I was able to successfully train a model with this config: 

```
pipeline:
 # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
 # If you'd like to customize it, uncomment and adjust the pipeline.
 # See https://rasa.com/docs/rasa/tuning-your-model for more information.

    - name: SpacyNLP
    - name: SpacyTokenizer
    - name: SpacyFeaturizer
    - name: SpacyEntityExtractor
    - name: SklearnIntentClassifier
    - name: EntitySynonymMapper
    - name: FallbackClassifier
      threshold: 0.3
      ambiguity_threshold: 0.1
```

I also tried with 

```
pipeline:
 # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
 # If you'd like to customize it, uncomment and adjust the pipeline.
 # See https://rasa.com/docs/rasa/tuning-your-model for more information.

    - name: SpacyNLP
    - name: SpacyTokenizer
    - name: SpacyFeaturizer
    - name: SpacyEntityExtractor
    - name: DIETClassifier
    - name: EntitySynonymMapper
    - name: FallbackClassifier
      threshold: 0.3
      ambiguity_threshold: 0.1
      
 ```

Command used: `rasa train nlu`

Let us know if the issue persists for you on the above mentioned versions . I am closing the issue until then.
Thanks!
