### ISSUE TITLE
Ability to configure exchange name in RabbitMQ event broker

### ISSUE THREAD

**Issue by kaustuk** [RasaHQ/rasa#7848]
**Description of Problem**:

A case where people want to deploy couple of bots with RabbitMQ as event broker. Rather then maintain different different RabbitMQ(pods or as an external service) user decided to have 1 RabbitMQ infra structure and each bot will have different queue name and exchange, to publish and consumer event. As of now, there is no way to configure exchange name because of this even though the queue name is different, exchange name would be same across bots. And message would be publish to all the queue because it's bind to same exchange that is `rasa-exchange`  as per code. [Here](https://github.com/RasaHQ/rasa/blob/97d6c6e88ede20d4f01761c655131c4007bb061f/rasa/core/brokers/pika.py#L203) is the code link

**Overview of the Solution**:

Added extra parameter of exchange name to be read from endpoints.yml file

Existing event config schema in endpoints.yaml
```yaml
event_broker:
  type: pika
  url: localhost
  username: username
  password: password
  queues:
    - queue-1
```

New proposed schema in endpoints.yaml
```yaml
event_broker:
  type: pika
  url: localhost
  username: username
  password: password
  queues:
    - queue-1
  exchange_name: rasa-exchanges
```

**Examples** (if relevant):

**Blockers** (if relevant):

This might be the blocker when user what to have multi-tenant bot deployment.

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changelog
