### ISSUE TITLE
Add a docker image that supports GPU out of the box

### ISSUE THREAD

**Issue by desmarchris** [RasaHQ/rasa#7950]
**Description of Problem**:
Setting up Rasa to train with a GPU takes a decent amount of time and is error prone.

**Overview of the Solution**:
A Rasa Docker image based off of `nvidia/cuda`

**Definition of Done**:

**Comment by ortsaCniveK** [comment]
Agreed, would be a nice win. As a stopgap, we could also just use the `tensorflow` image provided by [this great tutorial](https://pub.towardsai.net/how-i-use-docker-to-train-rasa-2-1-x-bots-on-a-gpu-442cd9d31d67?gi=93935062c4f4) works great, with the below files:

`Dockerfile`:
```Dockerfile
FROM tensorflow/tensorflow:2.1.2-gpu

RUN pip install rasa==2.4.0
```

`docker-compose.yml`:
```yaml
version: "3.8"

services:
  rasa:
    build:
      context: .
    runtime: nvidia
    volumes:
      - ./:/app
    entrypoint: sh
    tty: true
```

However this still requires [installation and setup of the `nvidia` Docker runtime locally](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker).
