### ISSUE TITLE
Slots not resetting with action_deactivation_loop

### ISSUE THREAD

**Issue by travelmail26** [RasaHQ/rasa#8079]
**Rasa version**:
Rasa Version     : 2.2.9
Rasa SDK Version : 2.2.0
Rasa X Version   : None
Python Version   : 3.8.1
Operating System : macOS-10.14.6-x86_64-i386-64bit

**Issue**:
Slots are not resetting after form de-activation is called. I was told to create a ticket in this [forum](https://forum.rasa.com/t/slots-not-resetting/40502) thread

**Stories solution**:
- story: User stops health_form
  steps:
  - active_loop: health_form
  - intent: flush_slots
  - action: action_flush_slots
  - action: utter_start_over
  - action: utter_greet
  - action: action_deactivate_loop
  - active_loop: null

**description**
Because action_deactivation_loop dosen't reset the slots, I added a custom action with the trigger

```
class ActionFlushSlots(Action):
    
    def name(self) -> Text:
        return "action_flush_slots"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:

        slots = []
        for key, value in tracker.current_slot_values().items():
            if value is not None:
                slots.append(SlotSet(key=key, value=None))

        return slots
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @ArjaanBuijk will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@travelmail26 What's the complete stack trace?
And what are you trying to do when?

**Comment by ancalita** [comment]
Hi @travelmail26 In absence of the complete stack trace, I've replicated the `InvalidRule` behaviour you described in the forum post - this I gathered is owed to the fact that `action_deactivate_loop` was placed outside of an active form because the health form was already deactivated via `active_loop: null` in the example you provided in the forum post:
```
- rule: Submit form
  condition:
    # Condition that form is active.
    - active_loop: health_form
  steps:
  - action: health_form
  - active_loop: null
    # The action we want to run when the form is submitted.
  - action: action_submit_results
  - action: utter_slots_values
  - action: action_deactivate_loop
  - active_loop: null
``` 

I also agree with @wochinge that the correct way currently to reset the slots is via custom action because `action_deactivate_loop` has the same function as `active_loop: null` to inactivate/ exit the form and is best used to [handle unhappy form paths,](https://rasa.com/docs/rasa/forms#writing-stories--rules-for-unhappy-form-paths).
 
The solution I see here is for us to update docs so that it's clear what's the recommended route for resetting slots using [`AllSlotsReset`event ](https://rasa.com/docs/rasa/reference/rasa/shared/core/events#allslotsreset-objects) returned by a custom action after form submission. Would that work?
