### ISSUE TITLE
trigger_intent with entities does not autofill slot with these entities

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#8107]
**Rasa version**: 2.2.9

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
When using the [trigger intent endpoint](https://rasa.com/docs/rasa/pages/http-api#operation/triggerConversationIntent), the entities that I pass with the request are not auto-filling their corresponding slots as expected. 

We used to have a custom endpoint that basically did the exact same thing as `trigger_intent` but I'm trying to move to the standard Rasa endpoint. This is blocking our migration as entities are useless if they do not behave as entities from a normal message. 

Given the following paragraph from the documentation, I would expect the slots to be filled as usual:

> The trigger_intent endpoint injects a user intent (possibly with entities) into your conversation. For Rasa, it is **as if you entered a message that got classified with that specific intent and entities**. The assistant will then predict and execute the next action as usual.

**Command or request that led to error**:
```
POST {{url}}/conversations/{{sender_id}}/trigger_intent?token={{token}}&output_channel=latest

{
	"name": "greeting",
	"entities": {"matches_found": 20}
}
```

I get the following response so the entities were correctly passed to the bot but the slots were not set:
```
{
    "tracker": {
        "sender_id": "...",
        "slots": {
...
            "matches_found": null,
...
        },
        "latest_message": {
            "intent": {
                "name": "greeting"
            },
            "entities": [
                {
                    "entity": "matches_found",
                    "value": 20
                }
            ],
            "text": "EXTERNAL: greeting",
            "message_id": null,
            "metadata": {
                "is_external": true
            }
        },
...
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
- greeting
    use_entities: []  # note that I tried with other intents that do not have this
...
entities:
- matches_found  
...
slots:
  matches_found:
    type: float
    influence_conversation: true
    max_value: 1.0
    min_value: 0.0
```
