### ISSUE TITLE
Can not use custom tracker store: “Custom tracker store not found. Using InMemoryTrackerStore instead”

### ISSUE THREAD

**Issue by baphuc1998** [RasaHQ/rasa#8148]
**Rasa version**: 2.3.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.5 (Anaconda)

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
I'm having trouble using the custom tracker store. I have also referenced some workarounds on forums. Even I set my rasa project directory to PYTHONPATH but I still got this warning:
```
UserWarning: Tracker store with type 'tracker.CustomMongoTrackerStore' not found. Using `InMemoryTrackerStore` instead.
```

**Content of configuration file (endpoints.yml)** (if relevant):
```yml
action_endpoint:
  url: "http://127.0.0.1:5055/webhook"
  
core_endpoint:
  url: "http://127.0.0.1:5005"

tracker_store:
  # type: mongod
  type: tracker.CustomMongoTrackerStore
  url: localhost
  db: Conversation

```

**Content of tracker.py** :
```python
from rasa.core.tracker_store import TrackerStore, MongoTrackerStore
from rasa_sdk.events import SlotSet
import json
from rasa.core.slots import TextSlot

class CustomMongoTrackerStore(MongoTrackerStore):

    def save(self, tracker, timeout=None):
        """Saves the current conversation state."""
        session_id = tracker.get('session_id')
        print("***SESSION***",session_id)
        print(self._current_tracker_state_without_events(tracker))

        if self.event_broker:
            self.stream_events(tracker)

        additional_events = self._additional_events(tracker)

        self.conversations.update_one(
            {"sender_id": tracker.sender_id},
            {
                "$set": self._current_tracker_state_without_events(tracker),
                "$push": {
                    "events": {"$each": [e.as_dict() for e in additional_events]}
                },
            },
            upsert=True,
        )
```
