### ISSUE TITLE
Clarify how ResponseSelector uses response text for training

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#8150]
**Description of Problem**: When `use_text_as_label: true` is set, `ResponseSelector` uses actual text of responses as a label in training. But if multiple response variations are defined for a single response, then only the first variation is actually used. This goes back to `Message` objects in NLU `training_data` that only contain one variation (see the `response` key):

<pre> 

 {'text': 'hey', 'intent': 'greet', 'intent_response_key': 'greet/hi', 'response': 'heyia', 'text_tokens': [ ], 'intent_tokens': [ ], 'response_tokens': [ ], 'intent_response_key_tokens': [ , ]} 

 </pre>

See also [relevant Slack thread](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1615287873378700).

**Overview of the Solution**: While using only the first response variation as a label should work, it also means that additional info (from further response variations) is ignored even though it could improve training. At the very least, we should communicate to users.

We also need to check if only the first response variation is used in NLG when `use_text_as_label: true` and decide if that should be changed.

**Definition of Done**:

*   [ ] we know exactly what the current behaviour is (and have made changes if we think any are needed)
*   [ ] it's all explained in the docs
*   [ ] if needed, we raise an appropriate warning when `ResponseSelector` is used with `use_text_as_label: true` and multiple response variations are present
*   [ ] feature mentioned in the changelog if something actually changes

**Comment by dakshvar22** [comment]
@samsucik 

> We also need to check if only the first response variation is used in NLG when use_text_as_label: true and decide if that should be changed.

Even with `use_text_as_label=True`, the NLG picks a response randomly from the given set of candidates. The idea here is that all candidates are very similar to each other and hence using just one of them during training is fine.

**Comment by samsucik** [comment]
Thanks, @dakshvar22, good to know that all variations are still used.

I understand that **ideally** all variations would be very similar and similarly useful in training. But I think that, in reality, there can be a lot of variation. What if, accidentally, the first variation ends up being quite different from the rest, or just too short/vague/uninformative? I think that will impact ResponseSelector's training a fair bit and users should know they need to pay extra attention to the first variation for each response key.

As an example, let's take Sara's `chitchat/ask_howdoing` and `chitchat/ask_weather`. Just by very unluckily choosing which variation goes first for each of these response keys, I end up with:
```yml
utter_chitchat/ask_howdoing:
- text: "A little bit cold, otherwise fine."
- text: "I'm great! Thanks for asking."
- text: "I'm good, thanks!"
- text: "A little bit too warm, otherwise fine."
utter_chitchat/ask_weather:
- text: "It's getting pretty chilly!"
- text: "I don't know about where you live, but in my world it's always sunny 🔆"
- text: "Where I'm from, it's almost never-leaving-the-house weather."
- text: "Winter is coming ⚔️"
```
Now the first variations are quite close to each other, and they're also not the "typical" ones with respect to the remaining variations. So, I'd expect ResponseSelector to struggle with differentiating between `howdoing` and `askweather` in this particular case. Just because I ordered my variations in an unfortunate way.
