### ISSUE TITLE
Graph generated upon comparing multiple NLU pipelines is not rendered correctly

### ISSUE THREAD

**Issue by ganeshviyer** [RasaHQ/rasa#8200]
**Rasa version**: 2.3.4

**Rasa SDK version** (if used & relevant): (not relevant;  using an NLU-only pipeline)

**Rasa X version** (if used & relevant): (not relevant for this issue)

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): mac OS Big Sur 11.1

**Issue**:
See this forum topic for more info - https://forum.rasa.com/t/is-there-a-doc-on-how-to-interpret-pipeline-comparison-results/41165/2

I was looking to find a resource that would help me interpret the results of the pipeline comparison, but it appears that there are multiple graphs plotted over each other (as noted by @samsucik).

In addition, he notes that the graph also has lost information about the scale of its axes.  I'm not sure what the expected result should be.

Also tagging @dakshvar22.

**Error (including full traceback)**:
See attached file in the forum - https://forum.rasa.com/uploads/short-url/koZaCVIBB4ozHLZdbBMbnJUt9IK.pdf

**Command or request that led to error**:
```
rasa test nlu --nlu data/nlu.yml --config available_config/spacy.yml available_config/mitie.yml
```

**Content of configuration file (config.yml)** (if relevant):
spacy.yml
```
language: "en"  # your two-letter language code

pipeline:
  - name: SpacyNLP
    model: "en_core_web_md"
    case_sensitive: False
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
```
mitie.yml
```
language: "en"  # your two-letter language code

pipeline:
  - name: MitieNLP
    model: "data/total_word_feature_extractor.dat"
  - name: MitieTokenizer
  - name: MitieFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
```

**Content of domain file (domain.yml)** (if relevant): (not relevant here)
```yml

```

**Definition of done**
- [ ] Cause of this bug determined
- [ ] Fix, if straightforward. Otherwise, create an issue detailing the cause and potential solutions
