### ISSUE TITLE
False `constrain_similarities` warnings

### ISSUE THREAD

**Issue by staticdev** [RasaHQ/rasa#8216]
NOTE: this does not seems to be related to https://github.com/RasaHQ/rasa/issues/8144

**Rasa version**: 2.4.0

**Rasa SDK version** (if used & relevant): 2.4.0

**Rasa X version** (if used & relevant): N/A

**Python version**: 3.8.6

**Operating system** (windows, osx, ...): Ubuntu 20.10

**Issue**: 

With `constrain_similarities` configured I still get warnings about it on `rasa train`.

**Error (including full traceback)**:
```
/home/user/pyenv/versions/3.8.6/lib/python3.8/site-packages/rasa/utils/train_utils.py:558: UserWarning: constrain_similarities is set to `False`. It is recommended to set it to `True` when using cross-entropy loss. It will be set to `True` by default, Rasa Open Source 3.0.0 onwards.
  rasa.shared.utils.io.raise_warning(
/home/user/pyenv/versions/3.8.6/lib/python3.8/site-packages/rasa/utils/train_utils.py:531: UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds.
  rasa.shared.utils.io.raise_warning(
```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
version: "2.0"
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    model_confidence: linear_norm
    constrain_similarities: True
  - name: FallbackClassifier
    threshold: 0.7
  - name: DucklingEntityExtractor
    url: http://duckling.rasa.com:8000
    dimensions:
    - time
    - number
  - name: SpacyNLP
    model: "en_core_web_md"
    case_sensitive: false
  - name: "SpacyEntityExtractor"
    dimensions: []
  - name: EntitySynonymMapper
policies:
- name: AugmentedMemoizationPolicy
- name: TEDPolicy
  epochs: 40
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True

```

**Content of domain file (domain.yml)** (if relevant):
```yml
NOT RELEVANT.
```
