### ISSUE TITLE
Invalid key `model_confidence`

### ISSUE THREAD

**Issue by adamfeher64** [RasaHQ/rasa#8220]
**Docker image**: https://hub.docker.com/r/rasa/rasa
**Image version**: 2.4.0-full

**Warning**:
```
UserWarning: You have provided an invalid key model_confidence for component ResponseSelector in your pipeline. Valid options for ResponseSelector are:
...
```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)**:
```yml
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    model_confidence: linear_norm
    constrain_similarities: True
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    model_confidence: linear_norm
    constrain_similarities: True
  - name: FallbackClassifier
    threshold: 0.1
    ambiguity_threshold: 0.03

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    model_confidence: linear_norm
    constrain_similarities: True
  - name: RulePolicy

```
