### ISSUE TITLE
Events in tracker increase exponentially after each restarted event when `retrieve_events_from_previous_conversation_sessions: true` for SQL/MongoTrackerStore

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#8238]
**Rasa version**: 2.3.4

**Python version**: 3.7

**Operating system** (windows, osx, ...): MacOS

**Issue**:

When using either the `MongoTrackerStore` or `SQLTrackerStore` with `retrieve_events_from_previous_conversation_sessions: true`, the events in the tracker are double-saved after each `restarted` event, leading to an exponential increase in the number of events in the tracker.

The `/tracker` endpoint however does not return the number of events reported in the log.

**Error (including full traceback)**:

After sending the message `/goodbye`, which triggers `action_restart` 6 times:
```
$ cat rasarun.log | grep "tracker now has"
2021-03-18 10:16:02 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 4 events.
2021-03-18 10:16:02 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 11 events.
2021-03-18 10:16:02 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 26 events.
2021-03-18 10:16:03 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 56 events.
2021-03-18 10:16:03 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 116 events.
2021-03-18 10:16:03 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 236 events.
```

Tracker returned by  `curl 'http://localhost:5005/conversations/multiplies/tracker'`:
```json
{
  "sender_id": "multiplies",
  "slots": {
    "session_started_metadata": null
  },
  "latest_message": {
    "intent": {},
    "entities": [],
    "text": null,
    "message_id": null,
    "metadata": {}
  },
  "latest_event_time": 1616080178.2097110748,
  "followup_action": null,
  "paused": false,
  "events": [
    {
      "event": "action",
      "timestamp": 1616080178.2096371651,
      "name": "action_session_start",
      "policy": null,
      "confidence": 1.0,
      "action_text": null
    },
    {
      "event": "session_started",
      "timestamp": 1616080178.2096960545
    },
    {
      "event": "action",
      "timestamp": 1616080178.2097110748,
      "name": "action_listen",
      "policy": null,
      "confidence": null,
      "action_text": null
    }
  ],
  "latest_input_channel": null,
  "active_loop": {},
  "latest_action": {
    "action_name": "action_listen"
  },
  "latest_action_name": "action_listen"
}
```

**Command or request that led to error**:
```
rasa run --enable-api
```
```
for i in 1 2 3 4 5 6; do    curl --request POST \
    --url http://localhost:5005/webhooks/rest/webhook \
    --header 'Content-Type: application/json' \
    --data '{
        "sender": "multiplies",
        "message":"/goodbye"
    }'
done
```
```
 curl 'http://localhost:5005/conversations/multiplies/tracker'
```

**Content of configuration file (config.yml)** (if relevant):
```yml
policies:
  - name: RulePolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml
version: "2.0"

intents:
  - greet
  - goodbye

responses:
  utter_greet:
  - text: hi

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
```

**Content of rules.yml**:
```
version: "2.0"

rules:

- rule: Say goodbye anytime the user says goodbye
  steps:
  - intent: goodbye
  - action: action_restart

- rule: Say goodbye anytime the user says goodbye
  steps:
  - intent: greet
  - action: utter_greet
```

**Content of endpoints.yml**:
```
tracker_store:
   type: mongod
   url: mongodb://localhost:27017
   db: rasa
   retrieve_events_from_previous_conversation_sessions: true
```

Or 
```
tracker_store:
   type: sql
   url: postgresql://localhost:5432
   db: tracker
   retrieve_events_from_previous_conversation_sessions: true
```
Identical behaviour for postgres & mongo.

## Enable definition of done:
The tracker store does not re-save events from previous session.
