### ISSUE TITLE
Stories generated by Rasa X are different than interactive mode and not working

### ISSUE THREAD

**Issue by AlperKaan35** [RasaHQ/rasa#8281]
**Rasa version**: 2.4

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.37.1

**Python version**: 3.7.7

**Operating system** (windows, osx, ...): fedora

**Issue**:

Rasa interactive mode and rasa x generates stories differently. When I use rasa x to generate story, it does not work when I try it from terminal. Rasa x also add intent names and reactivation of forms after filling a slot in forms, rasa interactive mode does not do this.

Interactive mode of rasa x:
```

- intent: order
  - action: order_form
  - active_loop: order_form
  - slot_was_set:
    - requested_slot: a_pizza
  - intent: inform
    entities:
    - a_pizza: pepperoni
  - slot_was_set:
    - a_pizza: pepperoni
  - action: order_form
  - slot_was_set:
    - a_pizza: pepperoni
  - slot_was_set:
    - requested_slot: b_size
  - intent: inform
    entities:
    - b_size: large
  - slot_was_set:
    - b_size: large
  - action: order_form
  - slot_was_set:
    - b_size: large
  - slot_was_set:
    - requested_slot: c_drink
  - intent: inform
    entities:
    - c_drink: cola
  - slot_was_set:
    - c_drink: cola
  - action: order_form
  - slot_was_set:
    - c_drink: cola
  - slot_was_set:
    - requested_slot: null
  - active_loop: null
  - action: payment_form
  - active_loop: payment_form
```

Interactive mode of rasa:
```

- intent: order
  - action: order_form
  - active_loop: order_form
  - slot_was_set:
    - requested_slot: a_pizza
  - slot_was_set:
    - a_pizza: pepperoni
  - slot_was_set:
    - a_pizza: pepperoni
  - slot_was_set:
    - requested_slot: b_size
  - slot_was_set:
    - b_size: large
  - slot_was_set:
    - b_size: large
  - slot_was_set:
    - requested_slot: c_drink
  - slot_was_set:
    - c_drink: cola
  - slot_was_set:
    - c_drink: cola
  - slot_was_set:
    - requested_slot: null
  - active_loop: null
  - action: payment_form
  - active_loop: payment_form
```
