### ISSUE TITLE
Rasa x event-service (consumer) is too slow and make rabbitmq queue is growing.

### ISSUE THREAD

**Issue by Cobaramin** [RasaHQ/rasa#8312]
**Rasa version**: 2.3.4

**Rasa SDK version** (if used & relevant): 2.3.1

**Rasa X version** (if used & relevant): 0.37.1

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): Linux-4.19.112+-x86_64-with-glibc2.29

**Issue**:
I'm deploying rasa, rasa-x, rabbitmq cluster to k8s cluster.
I setting up an environment for rasa experiment, and I found out that rasa-x event service is too slow to consume messages from queue. 

Other than that rasa-x event-service can not be scale out. I guess it because of fanout exchange implementation. (https://stackoverflow.com/questions/23198144/multiple-workers-consume-same-message-from-rabbitmq-queue, https://github.com/RasaHQ/rasa/blob/2ef804000087197f070e1e6a6bd0b6f7a3925551/rasa/core/brokers/pika.py#L210 )

Here is a result when I send requests with locust 
(concurrent users = 1)
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/17552517/112609677-65b6bc80-8e4e-11eb-96c1-97509a0ceea8.png">

(concurrent users = 2) *event-service cannot utilize the queue here*
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/17552517/112611625-a7e0fd80-8e50-11eb-8690-761b13747840.png">

**Content of configuration file (endpoint.yml)** (if relevant):
```yml
tracker_store:
  type: sql
  dialect: "postgresql"
  url: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  db: ${DB_DATABASE}
  
event_broker:
  type: "pika"
  url: rabbit-rabbitmq.rabbitmq.svc.cluster.local
  username: "rasa-user"
  password: ${RABBITMQ_PASSWORD}
  port: 5672
  queues: 
  - rasa_production_events
```

**Content of configuration file (rabbitmq.yml) (if relevant)**:
```yaml
...
 chart:
    repository: https://charts.bitnami.com/bitnami
    name: rabbitmq
    version: 8.9.2
...
 ```
