### ISSUE TITLE
Assert release includes all changelog entries

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8450]
**Description of Problem**:
There are two problems
* [changelog files can have wrong names](https://rasa-hq.slack.com/archives/C36SS4N8M/p1618248847468200?thread_ts=1617893280.381500&cid=C36SS4N8M) which excludes them from `towncrier`
* somebody merged before the release PR is merged (should be fixed by our mini code freeze) which adds a new changelog before the release was tagged

**Overview of the Solution**:
We have some check at `make release` or in the CI which checks that the `changelog/` folder doesn't contain any items except
- `README.md`
- `.gitignore`
- `_template.md.jinja2`

**Definition of Done**:
- [ ] The CI fails for `prepare release` PRs if not all changelogs were included

**Comment by HotThoughts** [comment]
The easiest way that I can think of would be to add a job in the CI. Something like this:
```yaml
  changelog:
    name: Check Changelog
    runs-on: ubuntu-20.04

    steps:
      - name: Assert release includes all changelog entries
        if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'prepare-release')
        working-directory: changelog
        run: |
          # List all unexpected files in changelog/
          UNEXPECTED_FILES=$(ls -A --ignore={"README.md",".gitignore","_template.md.jinja2"})

          # Exit 1 if found any unexpected files
          [[ "$UNEXPECTED_FILES" ]] && \
          echo "Found the following unexpected files in changelogs/" && \
          echo "$UNEXPECTED_FILES" && \
          exit 1 || \
          echo "Release includes all changelog entries."
```

This should run only if the event name is `pull_request` and the head branch is a `prepare-release` branch. What do you think?
