### ISSUE TITLE
Rasa is not extracting Entity value with hyphen and space

### ISSUE THREAD

**Issue by HariTeneti** [RasaHQ/rasa#8468]
**Rasa version**: Rasa:2.4.3-full

**Rasa SDK version** (if used & relevant): Rasa-sdk:2.4.1

**Rasa X version** (if used & relevant): 0.38.1

**Python version**: Python 3.6

**Operating system** (windows, osx, ...): CentOS

**Issue**:
Rasa is not extracting Entity value if it contains a hyphen and space.

NLU Data:-

intent: getcurrencyweight examples: |
What is the weight of AAL in GDS - Equity
Ex:- [{‘entity’: ‘account’, ‘start’: 29, ‘end’: 32, ‘confidence_entity’: 0.9999918937683105, ‘value’: ‘GDS’, ‘extractor’: ‘DIETClassifier’}, {‘entity’: ‘account’, ‘start’: 35, ‘end’: 41, ‘confidence_entity’: 0.9999841451644897, ‘value’: ‘Equity’, ‘extractor’: ‘DIETClassifier’}],

The model is trained with “GDS - Equity” (please note the space before/after the hyphen) entity but it is extracting as “GDS” and “Equity” instead of “GDS - Equity”. It doesn’t seem to be a problem with multiple words or hyphen in entity value as I can get the entity “AVIVA CAD1” / "GDS-Equity (no space before/after hyphen). The problem is clearly with the combination of Hyphen and Space.

Here is the version that we are using for Rasa/RasaX/RasaSDK. RasaX:- 0.38.1 Rasa:2.4.3-full
Rasa-sdk:2.4.1

Config.yml:-

language: en pipeline:

name: WhitespaceTokenizer
name: RegexFeaturizer
name: LexicalSyntacticFeaturizer
name: CountVectorsFeaturizer OOV_token: oov token_pattern: (?u)\b\w+\b
name: CountVectorsFeaturizer analyzer: char_wb min_ngram: 1 max_ngram: 4
name: DIETClassifier epochs: 200 ranking_length: 5
name: EntitySynonymMapper
name: ResponseSelector epochs: 100
name: FallbackClassifier threshold: 0.3 policies:
name: TEDPolicy max_history: 10 epochs: 20 batch_size:
32
64
max_history: 6 name: AugmentedMemoizationPolicy
name: RulePolicy core_fallback_threshold: 0.3 core_fallback_action_name: “action_default_fallback” enable_fallback_prediction: True

Please see the following thread for more details:-
https://forum.rasa.com/t/rasa-is-not-extracting-entity-value-with-hyphen-and-space/42401

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  ranking_length: 5
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
policies:
- name: TEDPolicy
  max_history: 10
  epochs: 20
  batch_size:
  - 32
  - 64
- max_history: 6
  name: AugmentedMemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Definition of done**
- [ ] Determine if we are able to reproduce this bug
- [ ] If so, investigate the problem and create an issue for the fix
