### ISSUE TITLE
Key 'quick_replies' was not defined. Path

### ISSUE THREAD

**Issue by sumanentc** [RasaHQ/rasa#8487]
**Rasa version**:
2.0.2

**Python version**:
3.8

**Operating system** (windows, osx, ...):
MacOS Big Sur

**Issue**:
I am getting the below error while executing rasa train
YamlValidationException: Failed to validate '/Users/abc/Public/workspace/nlp/rasa/rasabot/domain.yml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
  in /Users/abc/Public/workspace/nlp/rasa/rasabot/domain.yml:40:
      Key 'quick_replies' was not defined. Path: '/responses/utter_fallback/1'

**Content of domain file (domain.yml)** (if relevant):
```yml
- text: "Sorry! I coudn't get you. Please ask any of the following questions."
    channel: facebook
    quick_replies:
    - title: Active in India 
      content_type: text
      payload: '/status{{"stage":"active"}}'
```
