### ISSUE TITLE
rasa-x github connect gets value error ${{ secrets.DOCKER_HUB_LOGIN}}

### ISSUE THREAD

**Issue by randywreed** [RasaHQ/rasa#8542]
**Rasa version**: 2.5.0

**Rasa SDK version** (if used & relevant): 2.5.0

**Rasa X version** (if used & relevant): 0.39

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): Linux

**Issue**: in rasa-x connect to git hub fails. The debug generates error :ValueError: Error when trying to expand the environment variables in '${{ secrets.DOCKER_HUB_LOGIN }}'. Please make sure to also set these environment variables: '['${{']'.

**Error (including full traceback)**:
```
rasa-x_1           | Job "run_background_synchronization (trigger: cron[minute='*'], next run at: 2021-04-26 01:43:00 UTC)" raised an exception
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/base.py", line 125, in run_job
rasa-x_1           |     retval = job.func(*job.args, **job.kwargs)
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/integrated_version_control/git_service.py", line 140, in run_background_synchronization
rasa-x_1           |     common_utils.run_in_loop(
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasax/community/utils/common.py", line 900, in run_in_loop
rasa-x_1           |     return loop.run_until_complete(coro)
rasa-x_1           |   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/integrated_version_control/git_service.py", line 1159, in synchronize_project
rasa-x_1           |     return await self._force_inject_latest_remote_changes()
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/integrated_version_control/git_service.py", line 1219, in _force_inject_latest_remote_changes
rasa-x_1           |     await self._inject_data()
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/integrated_version_control/git_service.py", line 1191, in _inject_data
rasa-x_1           |     await rasax.community.initialise.inject_files_from_disk(
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasax/community/initialise.py", line 352, in inject_files_from_disk
rasa-x_1           |     inject_domain(
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasax/community/initialise.py", line 187, in inject_domain
rasa-x_1           |     if not rasa.shared.core.domain.Domain.is_domain_file(
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasa/shared/core/domain.py", line 1790, in is_domain_file
rasa-x_1           |     content = rasa.shared.utils.io.read_yaml_file(filename)
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasa/shared/utils/io.py", line 373, in read_yaml_file
rasa-x_1           |     return read_yaml(read_file(filename, DEFAULT_ENCODING))
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasa/shared/utils/io.py", line 354, in read_yaml
rasa-x_1           |     return yaml_parser.load(content) or {}
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/main.py", line 343, in load
rasa-x_1           |     return constructor.get_single_data()
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
rasa-x_1           |     return self.construct_document(node)
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 123, in construct_document
rasa-x_1           |     for _dummy in generator:
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 723, in construct_yaml_map
rasa-x_1           |     value = self.construct_mapping(node)
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 440, in construct_mapping
rasa-x_1           |     return BaseConstructor.construct_mapping(self, node, deep=deep)
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 255, in construct_mapping
rasa-x_1           |     value = self.construct_object(value_node, deep=deep)
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 146, in construct_object
rasa-x_1           |     data = self.construct_non_recursive_object(node)
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/constructor.py", line 181, in construct_non_recursive_object
rasa-x_1           |     data = constructor(self, node)
rasa-x_1           |   File "/usr/local/lib/python3.8/dist-packages/rasax/community/utils/yaml.py", line 39, in env_var_constructor
rasa-x_1           |     raise ValueError(
rasa-x_1           | ValueError: Error when trying to expand the environment variables in '${{ secrets.DOCKER_HUB_LOGIN }}'. Please make sure to also set these environment variables: '['${{']'.

```

**Command or request that led to error**:
```
Rasa x, verify connection to github.
```

**Content of configuration file (config.yml)** (if relevant):
```language: en
pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "LexicalSyntacticFeaturizer"
- name: "CountVectorsFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "DIETClassifier"
  epochs: 100
- name: SpacyNLP
  model: "en_core_web_md"
- name: SpacyEntityExtractor
  dimensions: ["PERSON"]
- name: "EntitySynonymMapper"

policies:
- name: RulePolicy

```

**Content of domain file (domain.yml)** (if relevant):
```
ersion: '2.0'
config:
  store_entities_as_slots: true
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
intents:
- greet:
    use_entities: true
- ask_remind_call:
    use_entities: true
- ask_forget_reminders:
    use_entities: true
- bye:
    use_entities: true
- ask_id:
    use_entities: true
- EXTERNAL_dry_plant:
    use_entities: true
- EXTERNAL_reminder:
    use_entities: true
- EXT_reminder:
    use_entities: true
- check_flower:
    use_entities: true
entities:
- PERSON
- plant
slots:
  PERSON:
    type: rasa.shared.core.slots.TextSlot
    initial_value: null
    auto_fill: true
    influence_conversation: false
  plant:
    type: rasa.shared.core.slots.TextSlot
    initial_value: null
    auto_fill: true
    influence_conversation: false
responses:
  utter_what_can_do:
  - text: What can I do for you?
  utter_goodbye:
  - text: Bye
  utter_plant_warn:
  - text: your plant needs water
  utter_please_wait:
  - text: This may take some time. Please wait.
actions:
- action_set_reminder
- action_forget_reminders
- action_react_to_reminder
- action_tell_id
- action_warn_dry
- action_send_msg
- action_dummy
forms: {}
e2e_actions: []


```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @kalkbrennerei will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by randywreed** [comment]
so the variable ${{ secrets.DOCKER_HUB_LOGIN }} only exists in the github workflow action_server.yml  Included it here in cae it is of use for debugging the issue. 
```
on:
  push:
    branches:
      - main
      - nonasync
    paths:
    - 'actions/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Action Server image and upgrade Rasa X deployment
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: get current date
      id: date
      run: echo "::set-output name=date::$(date +'%b-%d-%Y-%H-%M')"    
    - id: action_server
      name: Build Action Server image
      uses: RasaHQ/rasa-action-server-gha@v1.0.3

      # Full list of parameters: https://github.com/RasaHQ/action-server-gha/tree/master#input-arguments
      with:
        docker_image_name: 'randywreed/reminderbot'
        docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        # More details about github context:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        #
        # github.sha - The commit SHA that triggered the workflow run
        docker_image_tag: '${{ steps.date.outputs.date }}'
```
