### ISSUE TITLE
Explore the heavily changed Rasa NLU training progress

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#8576]
**Rasa version**: 2.5.1 (current `main` branch)

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): MacOS

**Issue**: 
After the recent DIET & TED refactoring PR (#7589) got merged, DIET's training characteristic (how the training loss and accuracy evolves) changed drastically -- at least for one small dataset we've got (see [this Slack thread](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1619685661333200)).

This matters because convergence properties shouldn't change (degrade) this much, and the changes introduced in the PR were not meant to change this at all.

What needs to be done:
- [x] check if a similar effect can be observed on other NLU datasets
- [x] check what the impact is on the test-set results (because training accuracy/loss and generalisation performance are different things)
- [x] explore the different versions (commits) of Rasa OSS to pinpoint the changes that impacted this
- [ ] identify what (if anything) needs to change in the code if we want to "bring things back to normal"

**Error**:
![plot](https://user-images.githubusercontent.com/7470182/116589631-be2d1e00-a914-11eb-8400-7f4bbe36e004.png)

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    random_seed: 47
```
