### ISSUE TITLE
InvalidRule warning raised despite slots that should resolve conflict

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#8581]
**Rasa version**:
2.5.1 (not observed in 2.5.0)

**Python version**:
3.8.7

**Operating system** (windows, osx, ...):
OSX

**Issue**:
See slack thread [here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1619633986316800). It seems rule validation isn't considering slots when resolving potential conflicts.

**Error (including full traceback)**:
```
InvalidRule: 
Contradicting rules or stories found 🚨
- the prediction of the action 'utter_switch_luis' in story 'why rasa 3' is contradicting with rule(s) 'why rasa 2, why rasa 4' which predicted action 'utter_ask_more'.
```

The story:
```
- story: why rasa 3
  steps:
  - intent: why_rasa
    entities:
    - current_api: luis
  - slot_was_set:
    - current_api: luis
  - action: utter_why_rasa
  - action: utter_switch_luis
  ...
  ```
The rules:
```
- rule: why rasa 2
  steps:
  - intent: why_rasa
    entities:
    - current_api: tensorflow
  - slot_was_set:
    - current_api: __other__
  - action: utter_why_rasa
  - action: utter_ask_more
- rule: why rasa 4
  steps:
  - intent: why_rasa
    entities:
    - current_api: dialogflow
  - slot_was_set:
    - current_api: dialogflow
  - action: utter_why_rasa
  - action: utter_switch_dialogflow
  - action: utter_ask_more_migrate
  ```
The domain.yml
```
slots:
  current_api:
    type: categorical
    values:
    - dialogflow
    - luis
    ```
