### ISSUE TITLE
Form action `required_slots` receives nonsense values in `slots_mapped_in_domain`

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#8632]
**Rasa version**:

```
Rasa Version      :         2.5.1
Minimum Compatible Version: 2.2.0a1
Rasa SDK Version  :         2.5.0
Rasa X Version    :         None
Python Version    :         3.8.0
Operating System  :         Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.10
Python Path       :         /home/jem-mosig/miniconda3/envs/rasa-master/bin/python
```

**Issue**:

The `slots_mapped_in_domain` argument of the `required_slots` function contains the nonsense label `"required_slots"`, which breaks forms. This did *not* happen in

```
Rasa Version     : 2.4.3
Rasa SDK Version : 2.5.0
Rasa X Version   : None
Python Version   : 3.8.0
Operating System : Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.10
Python Path      : /home/jem-mosig/miniconda3/envs/rasa-master/bin/python
```

**Error (including full traceback)**:
No error message or traceback. But the contents of `slots_mapped_in_domain` for a regular form are
```
["required_slots"]
```

**Command or request that led to error**:
Talk to the bot and trigger a form. Print out the contents of `slots_mapped_in_domain` in the action server code. (Minimal breaking example is attached to this issue.)

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper

policies:
  - name: RulePolicy
    enable_fallback_prediction: False

```

**Content of domain file (domain.yml)** (if relevant):
```yml
version: "2.0"

intents:
  - greet
  - goodbye

responses:
  utter_goodbye:
  - text: "Bye"

  utter_ask_trivia_answer:
  - text: "Who am I?"

actions:
- validate_trivia_form

slots:
  trivia_answer:
    type: any
    auto_fill: false
    influence_conversation: false

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

forms:
  trivia_form:
    trivia_answer:
      - type: from_text

```
