### ISSUE TITLE
Warn user if they have RulePolicy in their ensemble and haven't defined `utter_default` or other fallback behaviour

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#8740]
**Description of Problem**: By default, `RulePolicy` comes with the settings

core_fallback_threshold: 0.4 core_fallback_action_name: "action_default_fallback" enable_fallback_prediction: True

This is not intuitive, but may be necessary for rules-only bots. If the user has not defined `utter_default`, they will get odd-looking behaviour (the user utterance is reverted, but nothing happens on the bot's side).

**Overview of the Solution**: We should output a warning if the user has not changed the fallback behaviour of RulePolicy and not defined `utter_default`.

This case may be difficult to distinguish from the case where the user has overwritten `action_default_fallback` s.t. it doesn't rely on `utter_default`. The warning could reflect this.

We may choose not to output the warning if the user has `enable_fallback_prediction: True` and explicitly changed the default settings (the assumption being that they then know that they need to define fallback behaviour/utterances).

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog
*   [ ] User is warned if `enable_fallback_prediction: True` **and** they haven't defined `utter_default`

**Comment by jonra1993** [comment]
Hello, @koernerfelicia I am facing a weird behavior utter_default is not triggered after action_default_fallback despite the fact that it is defined on the domain.yml file. I am using Rasa 3.0.4 maybe do you know what I am doing wrong. I followed this According to this documentation [Fallback and Human Handoff](https://rasa.com/docs/rasa/fallback-handoff#summary)

config.yml
```
pipeline:
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
```

domain.yml
```
responses:
  utter_default:
  - text: ¨No entendí tu mensaje¨
  
actions:
- utter_default
```
