### ISSUE TITLE
`slot_was_set` doesn't work as expected for categorical slots 

### ISSUE THREAD

**Issue by behnam354** [RasaHQ/rasa#8743]
**Rasa version**: 2.6.0

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**:

When defining a rule with `slot_was_set` conditioned on a categorical slot .. the rule is applied when slot is not null and don't really care about the category values. For example if we create a categorical slot say session_complete .. then Rasa 2.6.0 complains about the two following rules conflicting with one another:

```yml
## in rule.yml
# submit form if success
  - rule: submit my form
    condition:
    - active_loop: my_form
    steps:
    - action: my_form
    - active_loop: null
    - slot_was_set:
      - requested_slot: null
    - slot_was_set:
      - session_complete: success
    - action: action_submit_my_form


  - rule: deactivate my form and restart session if failure
    condition:
    - active_loop: my_form
    steps:
    - action: my_form
    - active_loop: null
    - slot_was_set:
      - requested_slot: null
    - slot_was_set:
      - session_complete: failure ## changing this to null resolves the conflict
    - action: action_restart
   ```

**Content of domain file (domain.yml)** (if relevant):
```yml
slots:
  session_complete:
    type: categorical
    initial_value: null
    auto_fill: true
    influence_conversation: true
    values:
      - null
      - success
      - failure
```
