### ISSUE TITLE
rasa bert cannot perform intent recognition on short text, especially a word

### ISSUE THREAD

**Issue by gongshaojie12** [RasaHQ/rasa#8778]
**Rasa version**:2.2.3

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:3.6.12

**Operating system** (windows, osx, ...):windows

**Issue**:
"Pieces" and "Pieces?" were put into nlu.yml as two NLU training samples, and then used bert+DIETClassifier for intent classification model training. After the model training is completed, I use the two samples "Pieces" and "Pieces?" to test the model, the model cannot predict the correct category.

I debugged the source code and couldn't find out the problem. I want to solve this problem and hope to provide me with some suggestions, thank you very much!

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: LanguageModelFeaturizer
     model_name: "bert"
     model_weights: "bert-base-uncased"
     cache_dir: null
   - name: DIETClassifier
     epochs: 100
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
   - name: FallbackClassifier
     threshold: 0.8
     ambiguity_threshold: 0.1


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: AugmentedMemoizationPolicy
   - name: TEDPolicy
     max_history: 8
     epochs: 200
     hidden_layers_sizes:
       dialogue: [256, 128]
   - name: RulePolicy
     core_fallback_threshold: 0.3
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
