### ISSUE TITLE
Contradicting rules or stories found with list slots

### ISSUE THREAD

**Issue by annthehuman** [RasaHQ/rasa#8784]
**Rasa version**: 2.6.2

**Python version**: 3.6.8

**Operating system**: Windows-10-10.0.17763-SP0

**Issue**: Rules contradicting with each other, but slot buttons set to influence_conversation: true in domain.

version: "2.0" rules:

*   rule: predictive_dynamic_set steps:

*   intent: buttons

*   action: action_get_buttons

*   slot_was_set:

*   buttons: <span class="error">[1, 2, 3]</span>

*   action: utter_predictive_buttons

*   rule: predictive_static_set steps:

*   intent: buttons

*   action: action_get_buttons

*   slot_was_set:

*   buttons: null

*   action: utter_static_buttons

**Error (including full traceback)**:

Contradicting rules or stories found

*   the prediction of the action 'utter_static_buttons' in rule 'predictive_static_set' is contradicting with rule(s) 'predictive_dyn amic_set'.
*   the prediction of the action 'utter_predictive_buttons' in rule 'predictive_dynamic_set' is contradicting with rule(s) 'predictiv e_static_set'. Please update your stories and rules so that they don't contradict each other.

**Command or request that led to error**: `rasa train`

**Content of configuration file (config.yml)** (if relevant):

language: ru

pipeline:

*   name: WhitespaceTokenizer
*   name: LexicalSyntacticFeaturizer
*   name: CountVectorsFeaturizer
*   name: CountVectorsFeaturizer analyzer: char_wb min_ngram: 1 max_ngram: 4
*   name: DIETClassifier epochs: 200
*   name: EntitySynonymMapper

policies:

*   name: RulePolicy core_fallback_threshold: 0.4 core_fallback_action_name: "action_default_fallback" enable_fallback_prediction: True
*   name: TEDPolicy epochs: 20 random_seed: 0 max_history: 5 batch_size:
*   32
*   64
*   name: MemoizationPolicy max_history: 1

**Content of domain file (domain.yml)** (if relevant):

predictive-buttons: type: list influence_conversation: true

**Definition of done**

*   <span class="error">[x]</span> Determine if we are able to reproduce this bug / if warning is incorrect
*   [ ] If so, investigate this problem and create an issue for the bug / warning fix
*   <span class="error">[x]</span> Reply to the user and help them figure out a path forward

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @ArjaanBuijk will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koernerfelicia** [comment]
Thanks @annthehuman! Just adding the [forum thread](https://forum.rasa.com/t/contradicting-rules-or-stories-found-with-categorical-slots/43391/10) for reference

I think this is possibly related to:  https://github.com/RasaHQ/rasa/pull/8646 and https://github.com/RasaHQ/rasa/pull/8689

**Comment by samsucik** [comment]
@annthehuman I can see that the slot is called `predictive-buttons` in the domain vs `buttons` in the rules. I wonder if this could be the issue...

**Comment by annthehuman** [comment]
> @annthehuman I can see that the slot is called `predictive-buttons` in the domain vs `buttons` in the rules. I wonder if this could be the issue...

Hi! I renamed slot in domain, now it's:
```
version: "2.0"

intents:
  - buttons

actions:
  - action_get_buttons

slots:
  buttons:
    type: list
    influence_conversation: true
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
```

And error stayed:
```
InvalidRule:
Contradicting rules or stories found �

- the prediction of the action 'utter_static_buttons' in rule 'predictive_static_set' is contradicting with rule(s) 'predictive_dyn
amic_set'.
- the prediction of the action 'utter_predictive_buttons' in rule 'predictive_dynamic_set' is contradicting with rule(s) 'predictiv
e_static_set'.
Please update your stories and rules so that they don't contradict each other.
You can find more information about the usage of rules at https://rasa.com/docs/rasa/rules.
```

**Comment by tttthomasssss** [comment]
### Reproduction

**Rasa version**: 2.7.0
**Rasa SDK version**: 2.7.0
**Python version**: 3.7.6
**Operating system**: Darwin-19.2.0-x86_64-i386-64bit

The reported problem can be reproduced with the information in the issue. I have used `rasa train core` with the given `domain` spec, `config` and `rules` file.

**Comment by tttthomasssss** [comment]
@annthehuman Hey, could you try to following to see whether it solves your problem. I think you are using the `slot_was_set` condition "story style" in a rules config, which doesn't seem to work. Check out the [Rules with Conditions](https://rasa.com/docs/rasa/rules#rules-with-conditions) docs as well as the docs on [Slot Types](https://rasa.com/docs/rasa/domain/#slot-types).

So either you could try using stories instead of rules by putting the following in a `stories.yml` file:
```yaml
version: "2.0"
stories:
  - story: predictive_dynamic_set
    steps:
      - intent: buttons
      - action: action_get_buttons
      - slot_was_set:
        - buttons: [1, 2, 3]
      - action: utter_predictive_buttons

  - story: predictive_static_set
    steps:
      - intent: buttons
      - action: action_get_buttons
      - slot_was_set:
        - buttons: null
      - action: utter_static_buttons
```

Or you could adapt the rules to use the `slot_was_set` as a condition like: 
```yaml
version: "2.0"
rules:
  - rule: predictive_dynamic_set
    condition:
      - slot_was_set:
        - buttons: [1, 2, 3]
    steps:
      - action: utter_predictive_buttons

  - rule: predictive_static_set
    condition:
      - slot_was_set:
        - buttons: null
    steps:
      - action: utter_static_buttons
```

**Comment by tttthomasssss** [comment]
Hey @annthehuman 👋  - did you get the chance to try out my suggestion above or does the issue still persist?

**Comment by annthehuman** [comment]
Hi, @tttthomasssss! I changed slot type to text, and error gone. So, seems like "story stile" slots in rules work, and issue is in list slot type.

**Comment by tttthomasssss** [comment]
Hi @annthehuman - thanks very much for the feedback! Could you please post the version of the config that worked for you? I'd like to do a quick analysis to figure out whether this is anything that requires us fix some functionality or update the documentation.

**Comment by tttthomasssss** [comment]
Hi @annthehuman, I wasn't able to run your suggestion of changing the slot type to text. Could you post your working config, rules and domain files, so I can take a look?

**Comment by annthehuman** [comment]
Hi @tttthomasssss sorry for a long answer here is config:

```
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
  - name: EntitySynonymMapper
language: ru

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.1
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: TEDPolicy
    epochs: 300
    random_seed: 0
  - name: MemoizationPolicy
```
Rule with text slot:
```
version: "2.0"
rules:
  - rule: predictive_dynamic_set
    steps:
    - intent: buttons
    - action: action_get_buttons
    - slot_was_set:
      - buttons: set
    - action: utter_predictive_buttons
    - action: action_cleaning_slots
    - slot_was_set:
      - buttons: null

  - rule: predictive_static_set
    steps:
    - intent: buttons
    - action: action_get_buttons
    - slot_was_set:
      - buttons: null
    - action: utter_static_buttons
```
domain:
```
version: "2.0"
actions:
- utter_predictive_buttons
- action_cleaning_slots
- action_get_buttons
- utter_static_buttons
intents:
- buttons:
    use_entities: []
slots:
  buttons:
    type: text
    influence_conversation: true
session_config:
  session_expiration_time: 1
  carry_over_slots_to_new_session: false
```
