### ISSUE TITLE
Rasa requests required slot when FormAction is invoked, but custom slot mapping is not called for requested slot

### ISSUE THREAD

**Issue by kimberlykf** [RasaHQ/rasa#8797]
**Rasa version**: 2.4.0 (but also confirmed this issue persisted with version 2.6.3)

**Rasa SDK version** (if used & relevant): 2.4.0 (but also confirmed this issue persisted with version 2.6.3)

**Rasa X version** (if used & relevant): not relevant

**Python version**: 3.8.8

**Operating system** (windows, osx, ...): macOS

**Issue**:

I am using a Rasa form to collect all of the necessary information in order to execute a specific type of query. I define slot mappings for each slot I want to fill in the domain file. I also have a few required slots where none of the predefined slot mappings fit my use case, so I use a custom action to extract and slot those values from the users message. When the user sends a message to the bot that includes all of the required entities right off the bat, the custom mapping functions are called, no problem. However, when the user does not provide all of the required entities and a slot is requested, say domain, when the user follows up with a domain, the custom mapping function is not called. Instead, Rasa attempts to auto-fill the slot based on the extracted entities (more specifically, using the from_entity mapping).

**In short, the custom mapping function is not called after a slot is requested**

**Error (including full traceback)**:
```

see description above

```

**Command or request that led to error**:
```
see description above. 
```

**Content of configuration file (config.yml)** (if relevant): not relevant
```

not relevant

```

**Content of domain file (domain.yml)** (if relevant):
```
forms:
      object_query_form:
        info_need_obj:
          - type: from_entity
           entity: info_need_obj

...

slots:
     info_need_obj:
       type: any
       influence_conversation: false
       auto_fill: true
     domain:
       type: any
       influence_conversation: false
       auto_fill: false
     identifier:
       type: any
       influence_conversation: false
       auto_fill: false

```

**Content of rule file (rules.yml)** (if relevant):
```

 #### Object Query ####
 - rule: Activate ObjectQuery Form
   steps:
   - intent: object_query
   - action: object_query_form
   - active_loop: object_query_form
 
 - rule: Submit ObjectQuery Form
   condition:
     - active_loop: object_query_form
   steps:
     - action: object_query_form
     - active_loop: null
     - action: action_execute_query

```

**Content of action file (actions.py)**:
```
class ValidateObjectQueryForm(FormValidationAction):
     def name(self) -> Text:
        return "validate_object_query_form"
 
     async def required_slots(
         self,
         slots_mapped_in_domain: List[Text],
         dispatcher: "CollectingDispatcher",
         tracker: "Tracker",
         domain: "DomainDict",
     ) -> Optional[List[Text]]:
 
         return slots_mapped_in_domain + ["identifier", "domain"] 
 
     async def extract_domain(
         self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict
     ) -> Dict[Text, Any]:
        
        val = code to extract slot
         return {"domain": val}
 
     async def extract_identifier(
         self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict
     ) -> Dict[Text, Any]:
 
         val = code to extract slot
         return {"identifier": val}

```

**Definition of done**
- [ ] Determine if we are able to reproduce this bug
- [ ] If so, investigate the problem and create an issue for the fix

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @aeshky will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by samsucik** [comment]
Fyi this originated from a [forum thread](https://forum.rasa.com/t/rasa-requests-required-slot-when-formaction-is-invoked-but-custom-slot-mapping-is-not-called-for-requested-slot/44189/4) and needs to be reproduced first.

**Comment by samsucik** [comment]
Hey @kimberlykf, I tried to reproduce this but couldn't. What do you mean when you say:
> Rasa attempts to auto-fill the slot based on the extracted entities (more specifically, using the `from_entity` mapping).

The only slot with `from_entity` mapping is the `info_need_obj`. Do you mean that you observe some of the remaining slots (`domain` or `identifier`) using the `from_entity` mapping even though they shouldn't?

As for reproducing the error, I'd need more details from you because in order to get to a complete example, I had to fill some gaps and make guesses/choices along the way. Take a look at my setup and let me know what changes I should make (and also whether or not you can observe any incorrect behaviour when using my setup).

With my setup (details further down), I see all extractors triggered when they should. This is the chat history I get in `rasa interactive` when all slots are extracted from the first utterance:
<img width="649" alt="Screenshot 2021-06-11 at 16 31 39" src="https://user-images.githubusercontent.com/7470182/121711531-9c59b600-cad2-11eb-91ce-d3e8b9e1f9a2.png">
And this is what I get when not all slots are extracted from the 1st message, and the remaining ones get extracted from the 2nd message:
<img width="653" alt="Screenshot 2021-06-11 at 16 34 27" src="https://user-images.githubusercontent.com/7470182/121711811-e80c5f80-cad2-11eb-8f11-20d9b87867ba.png">

This is the setup I used:

Domain:
```yml
version: "2.0"
intents:
  - object_query
forms:
  object_query_form:
    info_need_obj:
      - type: from_entity
        entity: info_need_obj
entities:
  - info_need_obj
slots:
  info_need_obj:
   type: any
   influence_conversation: false
   auto_fill: true
  domain:
   type: any
   influence_conversation: false
   auto_fill: false
  identifier:
   type: any
   influence_conversation: false
   auto_fill: false
actions:
  - validate_object_query_form
  - action_execute_query
responses:
  utter_ask_domain:
  - text: Give me domain
  utter_ask_identifier:
  - text: Give me identifier
```

Config:
```yml
language: en
pipeline:
policies:
  - name: RulePolicy
```

NLU data:
```yml
version: "2.0"
nlu:
- intent: object_query
  examples: |
    - i want [obj](info_need_obj)
    - i need [obj](info_need_obj)
    - give me [obj](info_need_obj)
- intent: some_other_random_intent
  examples: |
    - are you a bot?
    - are you a human?
```

`actions.py`:
```python
from typing import Any, Text, Dict, List, Optional
from rasa_sdk.executor import CollectingDispatcher
from rasa_sdk import Tracker, FormValidationAction, Action
from rasa_sdk.types import DomainDict


class ValidateObjectQueryForm(FormValidationAction):
    def name(self) -> Text:
        return "validate_object_query_form"

    async def required_slots(
            self,
            slots_mapped_in_domain: List[Text],
            dispatcher: "CollectingDispatcher",
            tracker: Tracker,
            domain: DomainDict,
    ) -> Optional[List[Text]]:
        return slots_mapped_in_domain + ["identifier", "domain"]

    async def extract_domain(
     self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict
    ) -> Dict[Text, Any]:

        dispatcher.utter_message(text="EXTRACTING DOMAIN")
        text_of_last_user_message = tracker.latest_message.get("text")
        if "want" in text_of_last_user_message:
            val = "domain_slot_val"
        else:
            val = None
        return {"domain": val}

    async def extract_identifier(
     self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict
    ) -> Dict[Text, Any]:
        dispatcher.utter_message(text="EXTRACTING IDENTIFIER")
        val = "identifier_slot_val"
        return {"identifier": val}


class ActionExecuteQuery(Action):
    def name(self) -> Text:
        return "action_execute_query"

    async def run(
        self, dispatcher, tracker: Tracker, domain: Dict[Text, Any],
    ) -> List[Dict[Text, Any]]:
        dispatcher.utter_message(text="EXECUTING!")
        return []
```

`endpoints.yml`:
```yml
action_endpoint:
  url: "http://localhost:5055/webhook"
```

Rule data:
```yml
version: "2.0"
rules:
 - rule: Activate ObjectQuery Form
   steps:
   - intent: object_query
   - action: object_query_form
   - active_loop: object_query_form
 - rule: Submit ObjectQuery Form
   condition:
     - active_loop: object_query_form
   steps:
     - action: object_query_form
     - active_loop: null
     - action: action_execute_query
```
