### ISSUE TITLE
E2E large dataset featurization memory and cpu improvements

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa#8803]
subissue for #8595 

**Description of Problem**:
Currently, e2e featurization of large datasets, such as multiwoz, takes considerable memory and cpu (time) resources.

For example, training on 25% of multiwoz using language model featurizer bert with rasa/LABse featurization took almost 4 hours:
![multiwoz-25p-ted-batch-spacy-label-batch-128-big](https://user-images.githubusercontent.com/1107341/120614667-c28ab080-c457-11eb-9c20-bd871f92e9bc.png)

More benchmarking/comparison of main and solution 1:  #8593 

**Overview of the Solution**:
Afaik, there are a two existing solution proposals:
1. @wochinge and @joejuzl have implemented an improvement in the architecture prototype that addresses the issue that messages are featurized redundantly when trackers overlap. They do this by featurizing all message once, creating a look up table, and then using that lookup table to featurize the messages in the trackers. I have benchmarked it in #8593. It improved featurization speed and also memory consumption during featurization. However, just before training on gpu started, there was a spike in memory consumption comparable to levels of the main branch without this change. So there might be some other part needed.

2. @dakshvar22 has created [an early implementation proposal](https://github.com/RasaHQ/rasa/compare/ted_featurize_inside_train) for pulling the featurization into the data generator for the model. This would mean that featurization is done in parallel during training. The benefits are: 1) the featurized dataset is never completely in memory, 2) featurization can easily be parallelized among the data workers, 3) featurization is done lazily only as the model training starts. The downside is that it would in total use up more cpu power as the featurization is done multiple times throughout the training procedure. This might be addressed using caching.

The two solutions have some overlap, but also parts that mutually exclude one another.

**Definition of Done**:
- [x] assess solution 2 in more detail and run some preliminary tests and benchmarks
- [x] implement a combined prototype to the problem
- [x] benchmark the resulting solution
- [x] create implementation proposal

**Comment by wochinge** [comment]
> just before training on gpu started, there was a spike in memory consumption comparable to levels of the main branch without this change

Any idea why?

**Comment by twerkmeister** [comment]
I am not quite sure - one part definitely is that still all trackers are featurized and then those features are duplicated for the rasa training data. Maybe the spike isn't really representative and in actuality is is still a bit lower, but you'll definitely have two full featurized datasets in memory at least.

**Comment by twerkmeister** [comment]
Hey @dakshvar22 running into a number of problems in the pure e2e test with your prototype - maybe you can give me some inspiration?
1. First problem was that there are no custom actions in pure e2e and so I picked the features of the first default action: see this commit here https://github.com/RasaHQ/rasa/commit/ef827843eb1427daf3de93c82c5b48e116c00f4b
2. Now I am getting an error like the one at the bottom (A)
    1. I was thinking this might be related to slots and entities so I removed all slot_was_set: and entities: events in the stories yml so that it now looks like (B).  Would I have to remove the in line annotations as well?
    2. Also set  entity_recognition to false in ted policy config


##### (A)
```
 Invalid argument:  TypeError: `generator` yielded an element that did not match the expected structure. The expected 
structure was (tf.float32, tf.int64, tf.float32, tf.int64, tf.float32, tf.int64, tf.float32, tf.int64, tf.float32, tf.int64, tf.float32, 
tf.int64, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.int64, tf.float32, tf.int64, tf.float32, tf.int64, tf.float32, tf.int64, 
tf.float32, tf.float32), but the yielded element was (array([[[0.], ....
 ```
##### (B)
```
- story: SNG01856.json
  steps:
  - user: am looking for a place to to stay that has [cheap](price) price range it should be in a type of [hotel](type)
  - bot: Okay, do you have a specific area you want to stay in?
  - user: no, i just need to make sure it's cheap. oh, and i need parking
  - bot: I found <choice> <price> hotel for you that includes parking. Do you like me to book it?
  - user: Yes, please. [6](people) people [3](stay) nights starting on [tuesday](day).
  - bot: I am sorry but I wasn't able to book that for you for <day>. Is there another day you would like to stay or perhaps a shorter stay?
  - user: how about only [2](stay) nights.
  - bot: "Booking was successful.\nReference number is : <ref>. Anything else I can do for you?"
  - user: No, that will be all. Good bye.
  - bot: Thank you for using our services.
  ```

**Comment by dakshvar22** [comment]
It's indeed because of the lack of support for slots and entities. Removing `entities` and `slot_was_set` events is needed. Removing inline annotations of entities can be painful and not sure if needed. Alternatively, you can remove the `slots` section from the domain file and run training. I just copied the story to my training data and tried locally after removing `slots` from domain and it worked. It's needed right now so that any inline annotations of entities do not set any slots with the same name automatically.

**Comment by twerkmeister** [comment]
So here's my initial benchmarking result:

I tested on a 9% subset of multiwoz with around 750 stories and 10000 user+bot utterances in total with a pretty normal pipeline, potentially even a bit on the smaller end:

```
language: en

pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 3
    max_ngram: 3

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 20
    batch_strategy: sequence
    label_batch_size: 64
    entity_recognition: false
    batch_size:
      - 64
      - 64
```

#### Watching GPU utilization
* For the prototype, GPU utilization would flip flop between 100% and 0% roughly 50/50 each
* for main: mostly 100% sometimes 90 or 80

#### epoch time
* For the prototype, ~414 seconds per epoch
* For main, ~240 seconds per epoch + ~420 seconds preprocessing time once upfront

#### Conclusions
For this particular case, single worker preprocessing is the bottle neck. Seems preprocessing takes around 160 seconds longer than the model training for the data. However with 2 or maybe 3 workers that problem would be resolved. If we'd be using a bigger pipeline, especially language model featurizer, higher parallelization factor might be needed.
