### ISSUE TITLE
IntentTEDPolicy: Adapt `rasa test` to sort errors and warnings by severity.

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#8970]
`IntentTEDPolicy` attaches a severity key to the metadata of `action_unlikely_intent` prediction. This severity value can be used to sort all the errors and warnings (in descending order) that are output by `rasa test`. This will be helpful for users to focus on "top" warnings when there are a lot of warnings but not a lot of time.

For example, if there were two stories where `action_unlikely_intent` could be predicted:

```
version: "2.0"
stories:
- story: path 1
  steps:
  - user: |
      hello there!
    intent: greet
  - action: utter_greet
  - user: |
      amazing
    intent: mood_great
  - action: utter_happy # action_unlikely_intent predicted with severity 1.2
  
- story: path 2
  steps:
  - user: |
      hello there!
    intent: greet
  - action: utter_greet
  - user: |
      very sad
    intent: mood_unhappy
  - action: utter_cheer_up  # action_unlikely_intent predicted with severity 2.0
  - action: utter_did_that_help
  - user: |
      yes
    intent: affirm    # action_unlikely_intent predicted with severity 4.2
  - action: utter_happy
```

Then the above stories should be sorted and output in this way in the warnings / error file.

```
version: "2.0"
stories:

- story: path 2
  steps:
  - user: |
      hello there!
    intent: greet
  - action: utter_greet
  - user: |
      very sad
    intent: mood_unhappy
  - action: utter_cheer_up  # action_unlikely_intent predicted with severity 2.0
  - action: utter_did_that_help
  - user: |
      yes
    intent: affirm    # action_unlikely_intent predicted with severity 4.2
  - action: utter_happy

- story: path 1
  steps:
  - user: |
      hello there!
    intent: greet
  - action: utter_greet
  - user: |
      amazing
    intent: mood_great
  - action: utter_happy # action_unlikely_intent predicted with severity 1.2
```

The feasibility of this (and a proposed implementation) is already tested on the branch of this [PR](https://github.com/RasaHQ/rasa/pull/8969). The branch is incomplete because more tests can be written for this.

**Definition of Done**:
What needs to be there to consider this feature as done?
- [ ] Tests are added
- [ ] `rasa test` sorts the output as expected above.
