### ISSUE TITLE
EmbeddingIntentClassifier behaviour not reproducable with DIETClassifier 

### ISSUE THREAD

**Issue by aeshky** [RasaHQ/rasa#9007]
## Problem
The [migration docs](https://rasa.com/docs/rasa/migration-guide/#rasa-17-to-rasa-18) imply that the following configuration in Rasa 2.x:
```
- name: "DIETClassifier"
  epochs: 300 
  hidden_layers_sizes: 
    text: [256, 128]
  number_of_transformer_layers: 0
  weight_sparsity: 0
  intent_classification: True
  entity_recognition: False
  use_masked_language_model: False
  BILOU_flag: False
  random_seed: 1
```
should give you the same results as the following configurations in Rasa 1.x:
```
- name: "EmbeddingIntentClassifier"
  epochs: 300
  random_seed: 1
```
However, we have created a [minimum example](https://github.com/RasaHQ/moodbot_config.git) with moodbot that gives different results with the two configurations.

**This is a high priority issue that impacts a customer who has experienced a performance drop after migrating from rasa version 1.5.1 to 2.5.0 using the above settings**

## Definition of Done

- [x] Confirm whether or not the results should be identical: they shouldn't if the Rasa version is different. See [this comment](https://github.com/RasaHQ/rasa/issues/9007#issuecomment-874226078). 

If not:
- [x] Make this explicit in the migration docs, ~~explaining why~~. 
- [x] Communicate this the customer and create another issue to address the drop in their performance.

If the results should be identical:
- [x] Identify the source of the discrepancy. ~~If it's a bug, create an issue for the fix~~.
- [x] Decide whether to create a regression test to ensure identical behaviour. ~~If yes, create an issue for the test.~~: no regression test needed.
