### ISSUE TITLE
syntax notes  page missing on https://rasa.com/docs/

### ISSUE THREAD

**Issue by solyarisoftware** [RasaHQ/rasa#9188]
Hi all

RASA 2 is great, but many small things are confusing especially for beginners. Syntax is often tricky.

Even if all information are in facts already contained in the documentation pages, I feel a that a dedicated page would be best. My proposal is to make a dedicated page on https://rasa.com/docs/ just to collect syntax tips/notes. Some possible subtopics:

---

**1. `/`COMMANDS**
Please insert  the complete list of **/commands** with at least one example of usage for each command. Even if many 
  commands are already listed in https://rasa.com/docs/rasa/default-actions
  
Also, please clarify the /intent command containing entities, e.g. `/intent_name{{"entity_type_1":"entity_value_1", "entity_type_2": "entity_value_2"}}` even if already specified here: https://rasa.com/docs/rasa/responses#buttons
  
In facts just in this case: /intent  is not just related to buttons, but it's about writing pseudocode stories:
  ```
  intent: /intent_name{"entity_type_1":"entity_value_1"}
  action: action_blablabla
  ```
---

**2. ENTITIES FULL SYNTAX**

The full syntax is: `[<entity-text>]{"entity": "<entity name>", "role": "<role name>", "group": "<group name>", "value": "<entity synonym>"}` and it has documented here: https://rasa.com/docs/rasa/training-data-format#entities and that's ok! But i'd foresee a dedicated section on a possible syntax page. Maybe just repeating the syntax with few practical examples of all cases.

---
 
**3. NAMING CONVENTIONS GUIDELINES** 
It could be great to have a section dedicated to naming conventions, concerning intent/actions names in yaml files and also in python code. E.g.

  ```yaml
  #  good 
  - intent: bye
  - action: action_bye
  - action: utter_bye
  ```  

  ```yaml
  #  bad 
  - intent: auRevoir
  - action: auRevoir_action
  - action: response_au_revoir
  ```    

It could be a minor point, but in my opinion naming conventions help a lot beginners and allow reuse of code!

---

**4. SLOTS SETTING (ON YAML)** 

A bit off.topics, but I'd add on documentation a specific page all dedicate to slots programming on yaml code. Again, currently docs do provide examples, but sometime the info is sparse in many pages. I'd collect all info about programming with slots in a unified/single page!

---

If you like this proposal/change request, please put a thumb up icon.
Please other possible common requests in comments.

Thanks!
Giorgio

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @amn41 will get back to you about it soon! ✨

**Comment by solyarisoftware** [comment]
BTW, in addition to points above I add a minor BUG in RASA doc documentation at page:

https://rasa.com/docs/rasa/training-data-format#entities

and paragraph **Entities**. In the code chunk I copy here, the first example is wrong: 
```yaml
nlu:
- intent: check_balance
  examples: |
    - how much do I have on my [savings]("account") account
    - how much money is in my [checking]{"entity": "account"} account
    - What's the balance on my [credit card account]{"entity":"account","value":"credit"}
```

Referring to an entity with name `account`:

QUOTATION MARKS ARE WRONG: 
```yaml
    - how much do I have on my [savings]("account") account
```

TO BE CORRECTED IN: 
```yaml
    - how much do I have on my [savings](account) account
```

the entity name (account) must not be enclosed in quotation marks. Otherwise the RASA runtime rise an error... something like not found entity `''account''`

Minor stuff, but I' became crazy for a while, debugging :)
I hope this helps others

Thanks
