### ISSUE TITLE
Allow using dictionary for button payload for custom widgets

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#9190]
**Description of Problem**:
In a custom channel, it's possible to make a button do something other than just send Rasa the text of the button payload.  That behaviour is entirely dependent on the connector code. 

However, `rasa data validate` rejects the format of any payload that is not a text string. Although `rasa shell` won't be able to use the complex payload, other channels could. Therefore it should be  allowed to specify it that way.

**Overview of the Solution**:
1. Allow dictionary format for button payloads
2. Warn if such a payload is used for a standard channel that can't handle it 

**Examples** (if relevant):

e.g. this response:
```
  utter_complex_button:
    - text: "text"
      buttons:
        - payload: "/greet"
          title: "hi"
        - payload:
            intent: /bot_challenge
            external_link: www.google.com
            reply_text: "some text to display back to the user"
          title: "challenge bot"
        - payload: "/stop"
          title: "exit convo"
  ```
  Will generate this error in `rasa data validate` at the moment:
  ```
YamlValidationException: Failed to validate '/Users/melinda/rasa_bots/moodbot2.x/domain.yml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
  in /Users/melinda/rasa_bots/moodbot2.x/domain.yml:55:
      Value 'ordereddict([('intent', '/bot_challenge'), ('external_link', 'www.google.com'), ('reply_text', 'some text to display back to the user')])' is not of type 'str'. Path: '/responses/utter_complex_button/0/buttons/1/payload'
  ```
  
**Blockers** (if relevant):
none known

**Definition of Done**:
- [ ] Implementation
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changelog
