### ISSUE TITLE
Condition response with buttons generates "ERROR: Couldn't create message for response..."

### ISSUE THREAD

**Issue by randywreed** [RasaHQ/rasa#9191]
**Rasa version**:2.7.1

**Rasa SDK version** (if used & relevant): 2.7.0

**Rasa X version** (if used & relevant): 0.41

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): ubuntu 20.04

**Issue**:
set up conditional response with buttons. The model trains without error, but
 when executed it generates an error

**Error (including full traceback)**:
```
2021-07-23 08:56:02 ERROR    rasa.core.actions.action  - Couldn't create message for response 'utter_reflection_continue
```

**Command or request that led to error**:
```
 utter_reflection_continue:
  - buttons:
    - payload: /reflection_retry
      title: Add More
    - payload: /submit_as_is
      title: Submit As Is
    condition:
    - name: reflection_len_ok
      type: slot
      value: true
    text: Reflections should be 250 words and your reflection is {reflection_len} words. Reflections less than 150 words will not be accepted. Would you like to add more?
  - buttons:
    - payload: /reflection_retry
      title: Add More
    condition:
    - name: reflection_len_ok
      type: slot
      value: false
    text: Reflections should be 250 words and your relection is {reflection_len} You need to add more.

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
