### ISSUE TITLE
failed_test_stories.yml is not printing the correct message

### ISSUE THREAD

**Issue by ArjaanBuijk** [RasaHQ/rasa#9279]
**Rasa version**: 2.8.0

**Rasa SDK version** (if used & relevant): N/A

**Rasa X version** (if used & relevant): N/A

**Python version**: 3.8

**Operating system** (windows, osx, ...): Linux

**Issue**: failed_test_stories.yml includes a test story that is actually correct

The bot is attached.

When running `rasa test` , you will see that this test story is marked as a failed test story, but it does not say why.

**file: test_stories.yml**
```yaml
- story: play ping pong
  steps:
  - user: |
      hello there!
    intent: greet
  - action: utter_greet
  - user: |
      play ping pong
    intent: play_game
  - action: utter_lets_play

```

**file: failed_test_stories.yml**
```yaml
version: "2.0"
stories:
- story: play ping pong (./tests/test_stories.yml)
  steps:
  - intent: greet
  - action: utter_greet
  - intent: play_game
  - action: utter_lets_play
```

In previous versions of Rasa, it would print the reason why it failed:

**file: failed_test_stories.yml**
```yaml
version: "2.0"
stories:
- story: play ping pong 
  steps:
  - intent: greet
  - action: utter_greet
  - intent: play_game  # predicted: play_game: play [ping pong](game)
  - action: utter_lets_play
```

It all works when updating the test story to include the entity extraction, like this:

**file: test_stories.yml  (with corrected version)**
```yaml
- story: play ping pong
  steps:
  - user: |
      hello there!
    intent: greet
  - action: utter_greet
  - user: |
      play [ping pong](game)
    intent: play_game
  - action: utter_lets_play
```

[the_model.zip](https://github.com/RasaHQ/rasa/files/6941250/the_model.zip)
