### ISSUE TITLE
Rule policies will not fire if unrelated featurized slots are set

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#9302]
_Product feedback submission from @rgstephens_

**Who is the feedback from?**

Multiple customers

**What is the feedback?**

Rule policies will not fire if unrelated featurized slots are set. This behavior is counterintuitive and not documented.

**What problem are they trying to solve?**

A simple rule like this should work if a featurized slot is set:

```yml
- rule: greet
 steps:
 - intent: greet
 - action: utter_greet
```

[Repo with more details](https://github.com/rgstephens/rasa-rule-slot-issue)

[Slack thread](https://rasa-hq.slack.com/archives/C0148JNFXLG/p1628271530006800)

**Recommendation**
- Assign two researcher to this issue

**Possible Inelegant Workaround**
- Add a rule for every possible slot state

**Possible Solutions**
- Make the state of slot featurization explicit in the rules (e.g. none or any)

**Definition of Done**
In order of urgency:
- [ ] See whether suggested workaround will resolve immediate customer problem
- [ ] Understand customer context: who does this affect? 
- [ ] Identify consequences: what would change if this suggested behavior change were implemented?
- [ ] Identify possible alternative next steps to be refined and scoped later, likely to include more explicit definition of rule behavior

Instead of the above steps, @samsucik carried out an investigation to pin-point the bug and, while doing so, proposed a simple fix (implemented in #9475), which has been verified to fix the issue on all examples provided by @rgstephens. The discussion inspired [related improvements to our docs](https://github.com/RasaHQ/rasa/issues/9521) and [another bug report](https://github.com/RasaHQ/rasa/issues/9483).

@samsucik to coordinate who is doing what on this issue
@kedz assigned reviewer

**Comment by rgstephens** [comment]
Example repo of this issue is [here](https://github.com/rgstephens/rasa-rule-slot-issue)

**Comment by rgstephens** [comment]
I'm trying to understand how this issue might affect another bot and created a [more-help](https://github.com/rgstephens/rasa-rule-slot-issue/tree/more-help) branch which adds two more featurized slots and [test stories](https://github.com/rgstephens/rasa-rule-slot-issue/blob/more-help/tests/test_stories.yml) that demonstrate the problem.

The main branch has a single featurized categorical slot called `num_appts` where the value is set in a custom action and the response to the goodbye intent is always incorrect if `num_appts` is set to any value.

In this branch, I've added another featurized categorical slot called `acct_type` but I can't get the problem to exhibit itself with this slot. With the test cases below, the `num_appts` test consistently fails but not `acct_type`.

```yml
- story: goodbye no slots
  steps:
  - user: |
      bye-bye!
    intent: goodbye
  - action: utter_goodbye

- story: goodbye - num_appts slot
  steps:
  - slot_was_set:
    - num_appts: multiple
  - user: |
      bye-bye!
    intent: goodbye
  - action: utter_goodbye

- story: goodbye  acct_type slot
  steps:
  - slot_was_set:
    - acct_type: basic
  - user: |
      bye-bye!
    intent: goodbye
  - action: utter_goodbye
```

**Comment by samsucik** [comment]
@rgstephens before someone from Research picks this up properly as a sprint task, I quickly looked into it and noticed one difference in the way the two slots are handled -- which explains the behaviour you're observing, though the question now becomes why the 2 slots are handled differently. The difference is that in the trained RulePolicy, the rules explicitly condition only on the `num_appts` slot's initial value, but not on `acct_type`. I.e. if you unzip the trained model and look into the `model_name/core/policy_1_RulePolicy/rule_policy.json` file, you'll see rules like this:
```json
"[{\"prev_action\": {\"action_name\": \"action_listen\"}, \"slots\": {\"num_appts\": [1.0, 0.0, 0.0, 0.0]}, \"user\": {\"intent\": \"bot_challenge\"}}]": "utter_iamabot",
```
So, the question for whoever investigates this further is: Why would one featurised slot appear in the rules, and another one wouldn't?

In terms of how can a slot even get ignored (i.e. not included in a rule), one example is [the already mentioned fix](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1628271461148900?thread_ts=1628256290.141100&cid=C8LEHMTAM) which excludes explicitly defined `initial_value`s of slots from rules. Here, however, we're talking about implicit initial values -- even an initially unset slot will have some default (initial) featurisation.

**Comment by akelad** [comment]
for the research teams backlog meeting on friday: this seems like relatively high priority to be addressed

**Comment by melindaloubser1** [comment]
Here is another aspect of this issue - this rule and story are found to conflict:

```
rules:
- rule: Say 'I am a bot' anytime the user challenges
  steps:
  - intent: bot_challenge
  - action: utter_iamabot

stories:
- story: bot challenge with slot
  steps:
  - intent: bot_challenge
    entities:
    - name: "amy"
  - slot_was_set:
    - name: 'amy'
  - action: utter_iamabot_name
```

This is a true conflict **iff** RulePolicy ignores featurized slots that aren't specified in a rule. If it does consider them (which it seems to, at least sometimes), then there should be no conflict, since the rule is equivalent to the following rule with which no conflict is found:
```
rules:
- rule: Say 'I am a bot' anytime the user challenges
  condition:
  - slot_was_set:
     - name: null
  steps:
  - intent: bot_challenge
  - action: utter_iamabot
```

A user pointed out that the reason this conflict is found is that this line: 
https://github.com/RasaHQ/rasa/blob/93d9983e465f7a426930a746fef1252cbb2f8f35/rasa/core/policies/rule_policy.py#L810
Only uses keys that actually appear in the rule to check equality of a rule and story state - since there are no slots in the rule above, the slots are not even included in consideration for conflict checking.

**Comment by provwilliamnagy** [comment]
I'm one of the customers experiencing the issue and I think the core issue (or at least the part that's causing me problems) is actually caused by the fact that the featurized categorical slot has an allowable value of `none` (in my case, the allowed values are `none`, `single`, `multiple`).  I thought those were being treated as strings but perhaps something in the Python code is confusing it and treating it as `None` even though it was specified in the YAML.  If I rename that value in the category to something like `nada`, it doesn’t appear in the compiled rules…

**Comment by samsucik** [comment]
@melindaloubser1 I think we're on the same page. The outstanding issue is featurised slots sometimes getting embedded in rules even if they're not present in the rule as it is written. Once that's fixed, we can make things clear in the docs. As for that code snippet, I believe it is correct and does what we want (though it makes some of the very core logic rather implicit and deserves to be at least documented much better).

**Comment by samsucik** [comment]
@provwilliamnagy thanks for the very helpful pointer, indeed a possible slot value of `none` is being treated the same as the initial value of the slot (the Pythonic `None`) during slot featurisation (code [here](https://github.com/RasaHQ/rasa/blob/0d97d427fd342b3f0fab4eaabc3d5169249dbf61/rasa/shared/core/slots.py#L372)). However, fixing this might actually happen elsewhere, not this far down the line in the code. Because, if a slot is unset (i.e. its value is the Pythonic `None`), we might want to not featurise it at all. I'm looking into it now.

**Comment by samsucik** [comment]
I investigated our options because it wasn't immediately clear to me where and how the bug should be fixed. As I was thinking it through (which was taking quite some time), I also wrote a fix (which was very quick).

My thoughts are now captured in this PR: #9475. It fixes the specific issue pointed out by @provwilliamnagy (feel free to check it out, everything should work for you if you install Rasa Open Source from that branch) and takes us to the state where all the examples provided by @rgstephens work nicely. The PR also proposes more clarity around unset slots and the use of `None`/`null` as categorical slot values.

**Comment by kedz** [comment]
@samsucik are you also planning on addressing this in PR [#9475](https://github.com/RasaHQ/rasa/pull/9475): 

> The outstanding issue is featurised slots sometimes getting embedded in rules even if they're not present in the rule as it is written. 

I just pulled your branch and ran it on @rgstephens `more-help` branch but added an initial value to domain like so:
```yaml
slots:
  num_appts:
    type: categorical
    auto_fill: true
    initial_value: single
    influence_conversation: true
    values:
      - none
      - single
      - multiple
```
which causes rule definitions to pick up this initial value implicitly and therefore fail to ignore the `num_appts` value at test time.

Is this the case you are referring to of slots getting implicitly embedded in rules? Are there other cases?
