### ISSUE TITLE
Make behaviour of rules w.r.t. unmentioned featurized slots explicit and configurable

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#9815]
### What problem are you trying to solve?

The behaviour of a rule when slots which are not mentioned in the rule are set is ambiguous and not configurable.
For example, given this rule for the response selector:
```
- rule: faq
  steps:
    - intent: faq
    - action: utter_faq
```
The intuitive assumption by the user is that this rule applies **whenever** `faq` is the intent, regardless of what else has happened in the conversation. This is however not true; if an unmentioned featurized slot is set, this rule is ignored.
This behaviour has caused confusion in the past; see the discussion on https://github.com/RasaHQ/rasa/issues/9302. [Documenting the current behaviour](https://github.com/RasaHQ/rasa/issues/9521) would be a good first step, but it would be better to make the agnosticism of a rule with regard to unmentioned featurized slots configurable in the rule itself.

The [implementation allowing `OR`ing for slot values in stories](https://github.com/RasaHQ/rasa/pull/9317) does not extend to rule conditions, so it's not possible to get around this by doing massive ORs (not a good idea in any case).

### What's your suggested solution?

There could be a condition key like `allow_unmentioned_slots` that controls whether a rule insists on an exact match of slot featurization, or just a minimal match on the values specified.

```
- rule: faq
  conditions:
  - allow_unmentioned_slots: true 
  steps:
    - intent: faq
    - action: utter_faq
```

This should also work in the presence of one or more specific slot conditions, for example the following rule would match whenever `returning_user` was `true`, regardless of what other featurized slots were set. 
```
- rule: faq
  conditions:
  - allow_unmentioned_slots: true 
  - slot_was_set:
      - returning_user: true
  steps:
    - intent: faq
    - action: utter_faq
```

### Examples (if relevant)

The example above is a real user's case of confusion and desire for the rule to work regardless of slots.  [This](https://github.com/RasaHQ/rasa/issues/9302#issuecomment-900873505)  is another example of real-world confusion.

A configurable constraint would help in cases of unintentional conflicts between stories and rules like that one, e.g. these two would no longer be in conflict:

```
rules:
- rule: Say 'I am a bot' anytime the user challenges
  conditions:
  - allow_unmentioned_slots: false 
  steps:
  - intent: bot_challenge
  - action: utter_iamabot

stories:
- story: bot challenge with slot
  steps:
  - intent: greet
  - action: action_greet
  - intent: bot_challenge
    entities:
    - name: "amy"
  - slot_was_set:
    - name: 'amy'
  - action: utter_iamabot_name
```

### Is anything blocking this from being implemented? (if relevant)

None known

### Definition of Done

[ ] Implementation of a key to control agnosticism of a rule w.r.t unmentioned featurized slots
