### ISSUE TITLE
Success Markers: adapt YAML syntax

### ISSUE THREAD

**Issue by aeshky** [RasaHQ/rasa#9997]
### Remove default operator:
Currently, when no operator is specified, `and` is used by default. Remove this option, making specifying an operator compulsory. 
For example, this is no longer valid:
```
- my_marker1: 
	- intent_detected: intent1
	- slot_is_set: slot1
```
and has to be written as:
```
- my_marker1: 
    - and:
        - intent_detected: intent1
        - slot_is_set: slot1
```

### Remove ability to distribute operator:
Currently, it is possible to distribute the operator onto atomic conditions. Remove this option.
For example, this: 
```
- seq:
    - intent_detected: intent1
    - intent_detected: intent2
```
becomes:
```
- seq:
    - intent_detected: 
        - intent1
        - intent2
```

### Definition of done:

- [ ] default operator removed
- [ ] ability to distribute operator removed
- [ ] functionality unit tested
